// ============================================================================
// CLUSTER-KONFIG · WUPPERTAL (Bergisches Land)
// ============================================================================
// Re-Skin auf den Koeln-Endstand (08o-08q): Schema + Komponenten aus der
// Koeln-Vorlage, Inhalt/Farbe/Assets bleiben Wuppertal. Einzige Datei mit der
// Cluster-Identitaet (Staedte, Region, Brennpunkte, SEO).
// Theme-Farben: app/globals.css :root (Graphit + Signalrot). themeColor: layout.tsx.
// Bilder: public/assets/img/wuppertal/.
// ============================================================================

export interface City {
  slug: string
  name: string
  plz: string
  /** H1-Untertitel (SEO-Variation pro Stadt). */
  h1Sub: string
  /** Einwohner-Bezeichnung ("Wuppertaler") fuer Reviews-Headline. */
  residents: string
  /** Stadt-Zentrum-Koordinaten (LocalBusiness-geo + Map-Pin). */
  lat: number
  lng: number
  /** Hauptstadt des Clusters (Hub). */
  main?: boolean
}

export interface Brennpunkt {
  name: string
  /** Pfad relativ zu CLUSTER.imgPath */
  img: string
  desc: string
}

export interface ClusterConfig {
  key: string
  region: string
  /** Region im Dativ ("im Bergischen Land") fuer Ueber-uns-Copy. */
  regionDative: string
  /** Quellen-Anker fuer Brennpunkt-Statistik (Einsatzgebiet-Disclaimer). */
  quellenAnker: string
  /** Hauptachsen (FAQ-Q2, cluster-spezifisch). */
  achsen: string[]
  /** Stadtteile der Hauptstadt (FAQ-Lokal-Card). */
  stadtteile: string[]
  domain: string
  /** data-theme-Key (dokumentarisch — :root in globals.css traegt die Vars). */
  theme: string
  themeColor: string
  /** Basis-Pfad fuer cluster-spezifische Bilder. */
  imgPath: string
  /** Dateiendung der Logo-Varianten logo-{key}-dark/-white. */
  logoExt: 'png' | 'svg'
  /** 08m A6 · Cache-Busting: bei INHALTS-Tausch eines Assets (gleicher Dateiname) hochzaehlen. */
  assetVersion: string
  /** H1-Sub-Span im Hero (NUR Desktop lg:+). */
  h1SubSpan: string
  /** Team-Foto (Netzwerk-Mobile Team-Hero-Card). */
  teamImg: string
  /** Vorname des lokalen SV (CTA-Rolle + Ueber-uns). */
  svName: string
  /** Nachname des lokalen SV (Person-Schema / formale Nennung). */
  svSurname: string
  phone: {
    display: string
    /** National formatiertes CTA-Label — href/tel bleibt international. */
    displayNational: string
    tel: string
    wa: string
  }
  /** Wahrzeichen-Hero (Einsatzgebiet). */
  landmark: { label: string; img: string }
  /** Verkehrs-Hauptachsen + Vor-Ort-Zeit (Facts-Grid). */
  facts: { value: string; label: string; accent?: boolean }[]
  /** Verkehrsschwerpunkte (Hauptstadt-Level). */
  brennpunkte: Brennpunkt[]
  cities: City[]
}

export const CLUSTER: ClusterConfig = {
  key: 'wuppertal',
  region: 'Bergisches Land',
  regionDative: 'Bergischen Land',
  quellenAnker: 'Polizei-Jahresverkehrsbericht 2025',
  achsen: ['A46', 'A1', 'B7'],
  stadtteile: ['Elberfeld', 'Barmen', 'Heckinghausen', 'Vohwinkel', 'Cronenberg', 'Ronsdorf'],
  domain: 'kfz-unfallgutachter-wuppertal.de',
  theme: 'graphit', // Wuppertal: Graphit/Eisengrau + Signalrot — globals.css :root traegt die Vars
  themeColor: '#2A2E33',
  imgPath: '/assets/img/wuppertal/',
  logoExt: 'svg', // Wuppertal: logo-wuppertal-dark.svg vorhanden — TODO Aaron: logo-wuppertal-white.svg fehlt noch
  assetVersion: '1',
  h1SubSpan: 'Unabhängige Sachverständige. Gerichtsfeste Gutachten nach BVSK-Standard.',
  teamImg: '/assets/img/wuppertal/team-wuppertal.webp?v=1',
  svName: 'Amet',
  svSurname: 'Egetürk', // Persona-Nachname (Amet Egetürk)
  phone: { display: '+49 1515 3608515', displayNational: '0151 5360 8515', tel: '+4915153608515', wa: '4915153608515' },
  landmark: { label: 'Schwebebahn', img: 'stadt-wuppertal.png' },
  facts: [
    { value: 'A46', label: 'Hauptachse' },
    { value: 'A1', label: 'Hauptachse' },
    { value: 'B7', label: 'Hauptachse' },
    { value: '60 Min', label: 'vor Ort', accent: true },
  ],
  brennpunkte: [
    { name: 'Widukindstraße', img: 'wuppertal_widukindstrasse.webp', desc: 'Dichter Verkehr, unübersichtliche Kreuzungen — häufig Auffahrunfälle.' },
    { name: 'Hofkamp', img: 'wuppertal_hofkamp.webp', desc: 'Viel Durchgangsverkehr auf enger Talachse — regelmäßig Kollisionen.' },
    { name: 'Döppersberg', img: 'wuppertal_doeppersberg.webp', desc: 'Knotenpunkt mit hoher Frequenz — Abbiege-Unfälle und Radverkehr.' },
  ],
  cities: [
    { slug: 'wuppertal',    name: 'Wuppertal',    plz: '42103', main: true, h1Sub: 'unabhängiger Sachverständiger',          residents: 'Wuppertaler',     lat: 51.2562, lng: 7.1508 },
    { slug: 'solingen',     name: 'Solingen',     plz: '42651',             h1Sub: 'Kfz-Sachverständiger Bergisches Land',     residents: 'Solinger',        lat: 51.1652, lng: 7.0671 },
    { slug: 'velbert',      name: 'Velbert',      plz: '42549',             h1Sub: 'Kfz-Sachverständiger Niederberg',          residents: 'Velberter',       lat: 51.3404, lng: 7.0436 },
    { slug: 'heiligenhaus', name: 'Heiligenhaus', plz: '42579',             h1Sub: 'unabhängiger Unfallgutachter',             residents: 'Heiligenhauser',  lat: 51.3258, lng: 6.9706 },
    { slug: 'wuelfrath',    name: 'Wülfrath',     plz: '42489',             h1Sub: 'Kfz-Sachverständiger Kreis Mettmann',      residents: 'Wülfrather',      lat: 51.2820, lng: 7.0386 },
    { slug: 'mettmann',     name: 'Mettmann',     plz: '40822',             h1Sub: 'Kfz-Sachverständiger Kreis Mettmann',      residents: 'Mettmanner',      lat: 51.2510, lng: 6.9750 },
    { slug: 'haan',         name: 'Haan',         plz: '42781',             h1Sub: 'unabhängiger Schadengutachter',            residents: 'Haaner',          lat: 51.1931, lng: 7.0125 },
    { slug: 'schwelm',      name: 'Schwelm',      plz: '58332',             h1Sub: 'Kfz-Sachverständiger Ennepe-Ruhr',         residents: 'Schwelmer',       lat: 51.2870, lng: 7.2940 },
    { slug: 'sprockhoevel', name: 'Sprockhövel',  plz: '45549',             h1Sub: 'Kfz-Sachverständiger Ennepe-Ruhr',         residents: 'Sprockhöveler',   lat: 51.3680, lng: 7.2440 },
    { slug: 'remscheid',    name: 'Remscheid',    plz: '42853',             h1Sub: 'unabhängiger Unfallgutachter',             residents: 'Remscheider',     lat: 51.1787, lng: 7.1897 },
    { slug: 'ennepetal',    name: 'Ennepetal',    plz: '58256',             h1Sub: 'Kfz-Sachverständiger Ennepe-Ruhr',         residents: 'Ennepetaler',     lat: 51.3000, lng: 7.3620 },
    { slug: 'hattingen',    name: 'Hattingen',    plz: '45525',             h1Sub: 'Kfz-Sachverständiger Ennepe-Ruhr',         residents: 'Hattinger',       lat: 51.3990, lng: 7.1860 },
  ],
}

/** Hauptstadt (Hub-Page /). */
export const MAIN_CITY: City = CLUSTER.cities.find((c) => c.main) ?? CLUSTER.cities[0]

/** Alle Slugs. */
export const CITY_SLUGS: string[] = CLUSTER.cities.map((c) => c.slug)

/** Spoke-Slugs (alle ausser Hauptstadt) — generateStaticParams. */
export const SPOKE_SLUGS: string[] = CLUSTER.cities.filter((c) => !c.main).map((c) => c.slug)

/** Routing-Pfad einer Stadt (Hauptstadt → "/"). */
export function cityHref(city: City): string {
  return city.main ? '/' : `/lp/${city.slug}`
}

/** Stadt per Slug (oder undefined → 404). */
export function getCity(slug: string): City | undefined {
  return CLUSTER.cities.find((c) => c.slug === slug)
}

/** Vorausgefuellter WhatsApp-Text pro Stadt. */
export function waText(city: City): string {
  return `Hallo, ich hatte einen Unfall in ${city.name} und brauche einen Gutachter.`
}

/** Vollstaendiger wa.me-Link mit vorausgefuelltem Text. */
export function waHref(city: City): string {
  return `https://wa.me/${CLUSTER.phone.wa}?text=${encodeURIComponent(waText(city))}`
}

/** Komma-Liste aller Staedte (Servicegebiet-Text / areaServed). */
export function cityNamesList(): string {
  const names = CLUSTER.cities.map((c) => c.name)
  return names.slice(0, -1).join(', ') + ' und ' + names[names.length - 1]
}

// ── SEO-Body (08o O6: strukturierte Absaetze statt Fliesstext) ───────────────
// `vorort: true` markiert den Absatz, der in der Einsatzgebiet-Lokalstrecke
// rendert (lib/seoVorOrt).
//
// AUSBAU 24.08.2026 (Near-Duplicate-Fix): Die LP-Seiten dieser Domain glichen
// einander zu 65,4 % (4-Gramm-Jaccard, Ortsnamen entfernt) — die Programm-Spec
// setzt die Grenze bei 40 %.
//
// ⚠ Die Ursache ist NICHT, dass diese Texte einander aehneln. Untereinander
// lagen sie bei Ø 0,6 % / max 7,2 % Ueberlappung, dem besten Wert im Cluster.
// Es ist ihr ANTEIL an der Seite: ~3.300 Woerter Seitenumfang, davon ~2.800
// Template (auf allen 12 LPs identisch) + ~400 Ortstiefe aus der DB + 79 Woerter
// SEO_BODY. Das Template verduennt alles — deshalb misst die Seite 65 %, obwohl
// der Ortstext fuer sich bei 7 % liegt. Wer hier kuerzt, kuerzt am einzigen
// Hebel. Rechnung fuer <40 %: ~1.200 Woerter Einzigartiges je Seite, minus 400
// Ortstiefe -> ~800 Woerter SEO_BODY je Ort (nicht 350; von 79 aus Faktor 10).
//
// Struktur nach der Koeln-Vorlage, aber tiefer: Intro + vorort-Absatz
// (Stadtteil-Dynamik) + FUENF h3-Fragen a 100–150 Woerter + Abbinder. Mehr
// Fragen, nicht laengere Saetze — und jede Antwort endet bei der
// Schadenmechanik: was am Fahrzeug kaputtgeht und was das fuer die
// Begutachtung heisst. Die `liste` ist bewusst PRO ORT verschieden (nicht wie
// in Koeln ein geteiltes LEISTUNGS_LISTE-Const): sie spiegelt das jeweilige
// Schadensprofil und traegt so selbst Ortsinhalt statt geteiltem Template.
//
// ⚠ INHALTLICHE ABGRENZUNG: Unterhalb dieses Texts rendert die Seite die
// freigegebene Ortstiefe aus `stadt_lokalinhalte` (Stadtbezirke, Verkehrsachsen,
// Unfallschwerpunkte, lokale FAQs — s. lib/lokalinhalt.ts). Die h3-Fragen hier
// sind bewusst GEGEN die dort hinterlegten FAQs abgeglichen (prod gelesen
// 24.08.2026): keine Frage wiederholt eine DB-FAQ, sonst steht dieselbe Antwort
// zweimal auf einer Seite und der Zugewinn ist null. Wer eine h3 aendert, prueft
// vorher `select lokale_faqs from stadt_lokalinhalte where stadt_slug = '<ort>'`.
//
// ⚠ WAHRHAFTIGKEIT: keine erfundenen Zahlen, Strassen, Knoten oder Ortsteile.
// Jeder genannte Ortsteil / Knoten / Anschlussstelle stammt aus der freigegebenen
// Ortstiefe oder ist einzeln belegt (Heiligenhaus hat KEINE DB-Zeile — dort sind
// B227/Kreuz Breitscheid, A44-Anschluss Hofermuehle, die Kammlage zwischen
// Vogelsangbachtal und Angertal sowie der PanoramaRadweg niederbergbahn extern
// recherchiert). Rechtsnorm nur als `§ 249 BGB`.
export interface SeoAbsatz {
  /** Editorial gebundene Zwischenueberschrift. */
  h3?: string
  text: string
  /** Kompakte Leistungs-Liste nach dem Text. */
  liste?: string[]
  /** Rendert in der Einsatzgebiet-Lokalstrecke ("Vor Ort"), nicht im SeoBody. */
  vorort?: boolean
}

export const SEO_BODY: Record<string, SeoAbsatz[]> = {
  wuppertal: [
    { text: `Wuppertal (42103) fährt sich anders als jede andere Großstadt in Nordrhein-Westfalen. Die Stadt liegt in ganzer Länge im Tal der Wupper: unten die B7 als durchgehende Talachse, darüber das Stahlgerüst der Schwebebahn, und erst oberhalb der Hänge nimmt die A46 den Durchgangsverkehr auf. Wer hier einen Unfall hat, steht selten auf einer breiten, übersichtlichen Straße — sondern zwischen Bordstein, Stützpfeiler und Gegenverkehr, oft im Gefälle. Nach einem unverschuldeten Zusammenstoß haben Sie das Recht auf einen eigenen, neutralen Kfz-Gutachter; das Honorar trägt die Haftpflicht des Unfallverursachers als Teil des Schadensersatzes nach § 249 BGB. Für Sie bleiben 0 €. Wir kommen zur Besichtigung dorthin, wo das Fahrzeug steht — an den Unfallort, in die Werkstatt oder vor die Haustür.` },
    { vorort: true, text: `Die Wuppertaler Stadtteile bringen jeweils ihr eigenes Schadensbild mit. Auf der Talachse durch Elberfeld und Barmen dominieren Auffahr- und Rangierschäden aus zähem Lieferverkehr und Parksuche — viel Stop-and-Go, wenig Platz zum Ausweichen. Vohwinkel im Westen trägt den Berufsverkehr Richtung Düsseldorf und Solingen. Cronenberg und Ronsdorf liegen mehrere hundert Meter über dem Talgrund; dorthin kommt man nur über Steilstrecken und Serpentinen, und Anfahrschäden am Unterboden sind dort Alltag. In Langerfeld-Beyenburg zieht der Verkehr Richtung Schwelm und Hagen durch, in Heckinghausen und Uellendahl-Katernberg sind es enge Hangstraßen mit quer geparkten Fahrzeugen und schlechter Sicht über die Kuppe. Wir besichtigen in jedem dieser Stadtteile.` },
    { h3: 'Warum ist ein Streifschaden im Talgrund teurer, als er aussieht?', text: `Weil Fahrzeuge hier selten frontal aufeinandertreffen, sondern seitlich und schräg. Der enge Straßenraum entlang der B7 zwingt zu knappen Ausweichbewegungen; was dabei entsteht, ist ein flacher Streifer über Tür, Schweller und Radlauf. Sichtbar bleibt oft nur ein Kratzer im Klarlack. Darunter liegen aber häufig verschobene Türblech-Falze, ein eingedrückter Schwellerhohlraum und ein gestauchter Radlauf — und genau dort sitzt bei modernen Fahrzeugen die Seitenaufprallstruktur. Kommt der Anstoß vom hohen Bordstein, geht die Kraft zusätzlich in Felgenhorn, Reifenflanke und Spurstange. Deshalb prüfen wir bei jedem Streifschaden im Tal die Achsgeometrie mit und messen die Lackschichtdicke über die gesamte Flanke, nicht nur an der Kontaktstelle:`, liste: ['Lackschichtdickenmessung über die komplette Fahrzeugseite', 'Prüfung von Schweller, Radlauf und Türfalz auf Verzug', 'Achsvermessung nach Bordsteinanstoß', 'Reifenflanke und Felgenhorn auf verdeckte Schäden', 'Foto- und Maßdokumentation des Anstoßwinkels', 'Gutachten binnen 48 Stunden'] },
    { h3: 'Was ist bei Anstößen rund um die Schwebebahnstützen zu beachten?', text: `Die Stützen der Schwebebahn stehen zwischen Fahrbahn und Flussbett und verengen den Verkehrsraum spürbar — beim Abbiegen, beim Ausweichen und vor allem beim Einparken. Kommt es zum Anstoß an einem Pfeiler, einer Absperrung oder einem Geländer, ist neben Ihrem Fahrzeug ein Dritter als Eigentümer der Anlage betroffen. Das ändert die Beweislage: Es geht dann nicht nur um Ihren Schaden, sondern auch um einen Fremdschaden, den jemand beziffern wird. Am Fahrzeug betrifft so ein Anstoß meist Stoßfängerecke, Scheinwerferhalter und Kotflügel — bei niedriger Geschwindigkeit sieht das harmlos aus, doch schon geringe Kräfte verschieben Radar- und Kamerasensorik hinter dem Stoßfänger. Wir halten Position, Anstoßwinkel und Fremdschaden so fest, dass sich die Haftung später nicht verschieben lässt, und weisen den Kalibrierbedarf der Assistenzsysteme gesondert aus.` },
    { h3: 'Was macht die tägliche Fahrt nach Cronenberg oder Ronsdorf mit einem Fahrzeug?', text: `Zwischen Talgrund und den Höhen liegen Steigungen, die man in dieser Länge sonst kaum im Alltagsverkehr findet. Wer dort jeden Tag hoch- und runterfährt, belastet Antriebsstrang und Bremsen dauerhaft stärker als im Flachland — und das ist nach einem Unfall relevant, weil die Versicherung gern zwischen Unfallfolge und Verschleiß trennt. Genau an dieser Grenze entstehen die Kürzungen. Ein Auffahrunfall im Gefälle drückt zudem anders: Das auffahrende Fahrzeug ist geneigt, der Anstoß liegt tiefer als üblich und trifft eher Querträger und Kofferraumboden als den Stoßfänger allein. Wir dokumentieren die Anstoßhöhe deshalb ausdrücklich mit — sie ist das Argument dafür, dass ein verzogener Längsträger Unfallfolge ist und kein Altschaden.` },
    { h3: 'Wer bezahlt Gutachter, Mietwagen und Anwalt?', text: `Bei einem unverschuldeten Unfall die Haftpflichtversicherung des Verursachers. Gutachterhonorar, Mietwagen oder Nutzungsausfallentschädigung und die Kosten eines Verkehrsrechtsanwalts gehören zum Schadensersatz nach § 249 BGB — Sie strecken nichts vor. Entscheidend ist, dass Sie den Sachverständigen selbst beauftragen und nicht den Prüfer der Gegenseite akzeptieren: Der arbeitet im Auftrag der Versicherung, die zahlen soll, nicht in Ihrem. Auf Wunsch übernimmt ein Verkehrsrechtsanwalt aus dem Claimondo-Netzwerk die Abwicklung von der Schadensmeldung bis zur Auszahlung, und wir organisieren parallel den Ersatzwagen für die Reparaturzeit.` },
    { h3: 'Dürfen Sie die Werkstatt selbst aussuchen?', text: `Ja. Ob freier Karosseriefachbetrieb oder Markenwerkstatt, entscheiden Sie — eine Verweisung auf eine günstigere Partnerwerkstatt der gegnerischen Versicherung müssen Sie nicht hinnehmen. Das Gutachten ist die Abrechnungsgrundlage, und es ist genau deshalb so geschrieben, dass die Werkstatt jede Position begründen kann. Auf Wunsch vermitteln wir über das Claimondo-Netzwerk einen Betrieb in Wuppertal, der auf dieser Basis abrechnet. Wollen Sie stattdessen fiktiv abrechnen, also den Betrag auszahlen lassen und selbst entscheiden, was repariert wird, bleibt auch diese Möglichkeit offen — das Gutachten muss dafür nur sauber zwischen Reparaturkosten, Wertminderung und Restwert trennen.` },
    { text: `Kfz-Gutachter Wuppertal — unabhängig, gerichtsfest, schnell im Tal wie auf den Höhen. Ein Anruf oder eine WhatsApp genügt, und wir klären in wenigen Minuten, ob sich ein Gutachten lohnt und wie es weitergeht.` },
  ],
  solingen: [
    { text: `Die Klingenstadt Solingen (42651) liegt auf den Höhen über der Wupper, zwischen Wuppertal und Remscheid. Verkehrlich ist sie ein Sonderfall: Solingen hat kein einziges Zentrum, sondern mehrere gewachsene Kerne, die erst 1929 zu einer Stadt zusammengefügt wurden. Wer von Ohligs nach Gräfrath oder von Wald nach Höhscheid will, fährt deshalb nicht durch eine Innenstadt, sondern über Verbindungsstraßen zwischen Ortsteilen — mit häufigem Wechsel aus Tempo-30-Zone, Hauptstraße und Waldstrecke. Die A3 führt westlich vorbei, die A46 verbindet die Stadt mit Wuppertal und Düsseldorf. Nach einem unverschuldeten Unfall haben Sie Anspruch auf einen eigenen Sachverständigen — bezahlt von der Haftpflicht des Verursachers nach § 249 BGB, nicht von Ihnen.` },
    { vorort: true, text: `Jeder Solinger Stadtteil hat sein eigenes Unfallmuster. In Ohligs bündelt sich rund um den Hauptbahnhof der Pendler- und Bringverkehr, mit entsprechend vielen Rangier- und Türöffnerschäden auf beengten Flächen. Mitte und Wald tragen den Einkaufs- und Lieferverkehr. Gräfrath mit seinem historischen Ortskern zwingt Auswärtige in Manöver, für die die Gassen nie gebaut wurden. Höhscheid und Burg liegen bereits an den Wupperhängen — dort geht es in Serpentinen bergab Richtung Fluss, und am Wochenende mischt sich Ausflugsverkehr unter die Ortskundigen. Wir kommen in alle Stadtteile zur Besichtigung, auch nach Burg an der Wupper.` },
    { h3: 'Was bedeutet die polyzentrische Lage Solingens für einen Unfall?', text: `Vor allem eines: Die Unfallstelle liegt oft nicht dort, wo man sie vermuten würde. Weil sich der Verkehr auf viele Verbindungsstraßen zwischen den Ortsteilen verteilt statt auf eine große Achse, passieren die meisten Kollisionen auf zweispurigen Straßen mit Gegenverkehr, parkenden Fahrzeugen am Rand und wechselnden Tempolimits. Das erzeugt ein charakteristisches Schadensbild: seitliche Anstöße im Begegnungsverkehr und Auffahrunfälle an Stellen, an denen ein Vorausfahrender unerwartet für einen Abbieger bremst. Am Fahrzeug trifft das Außenspiegel, vordere Kotflügelkante und Stoßfängerecke — Teile, die einzeln günstig wirken, deren Austausch bei aktueller Sensorik aber Kalibrierarbeiten nach sich zieht, die in Kostenvoranschlägen regelmäßig fehlen.` },
    { h3: 'Ausflugsverkehr nach Müngsten, Schloss Burg und zur Sengbachtalsperre: Was passiert dort?', text: `An schönen Wochenenden füllen sich die Straßen zum Brückenpark Müngsten, zur Sengbachtalsperre und nach Schloss Burg mit Fahrzeugen, deren Fahrer die Strecke nicht kennen. Die Zufahrten sind schmal, teils einspurig, die Parkflächen begrenzt — und genau dort entstehen die typischen Schäden: Anstöße beim Wenden auf zu engem Raum, Streifer an Böschungskanten und Leitplanken, Rempler auf improvisierten Stellflächen. Solche Schäden liegen fast immer tief am Fahrzeug, an Frontschürze, Unterfahrschutz und Radhausschale. Wer nur von oben fotografiert, sieht sie nicht. Wir besichtigen deshalb grundsätzlich auch von unten und halten fest, ob die Verkleidung nur verkratzt oder ihre Befestigungspunkte ausgerissen sind — das ist der Unterschied zwischen Polieren und Neuteil.` },
    { h3: 'Woran erkennt man, ob ein Auffahrunfall die Hinterachse getroffen hat?', text: `Nicht am Stoßfänger. Der ist bei modernen Fahrzeugen eine Schaumstoff- und Kunststoffhülle, die genau dafür da ist, den Aufprall zu verbergen — sie federt zurück und sieht danach fast unbeschädigt aus. Die Kraft läuft aber weiter in den Querträger, von dort in die hinteren Längsträger und in den Kofferraumboden. Erste Hinweise sind ungleiche Spaltmaße an der Heckklappe, eine Klappe, die nicht mehr sauber einrastet, und Falten im Reserveradmulden-Blech. Wir bauen bei Verdacht die Verkleidung ab, vermessen die Aufnahmepunkte der Hinterachse und prüfen die Spur. Bleibt das ungeprüft, zahlt die Versicherung den Stoßfänger und Sie fahren mit einem verzogenen Heck weiter — mit sichtbarem Reifenverschleiß nach wenigen tausend Kilometern:`, liste: ['Spaltmaßprüfung an Heckklappe und Seitenteilen', 'Sichtprüfung Querträger und Längsträger nach Demontage', 'Achsvermessung hinten mit Protokoll', 'Kofferraumboden und Reserveradmulde auf Stauchfalten', 'Wertminderung (merkantiler Minderwert) bei jungen Fahrzeugen', 'Gutachten binnen 48 Stunden'] },
    { h3: 'Was tun, wenn die Versicherung die Reparaturkosten kürzt?', text: `Kürzungen kommen selten pauschal, sondern positionsweise: Der Prüfbericht der Gegenseite streicht Verbringungskosten, setzt niedrigere Stundenverrechnungssätze an oder ersetzt Neuteile durch Gebrauchtteile. Sie müssen das nicht hinnehmen. Nach einem unverschuldeten Unfall haben Sie Anspruch auf ein Gegengutachten, dessen Kosten ebenfalls die Gegenseite trägt. Wir prüfen den Erstbericht Position für Position und belegen die strittigen Punkte mit Messwerten statt mit Einschätzungen — das ist der Unterschied, an dem sich eine Kürzung entweder halten lässt oder nicht. Besonders häufig geht es um die Wertminderung bei Fahrzeugen unter fünf Jahren und um Achs- und Karosseriearbeiten, die im ersten Bericht schlicht nicht auftauchen.` },
    { h3: 'Wie schnell ist ein Sachverständiger in Solingen vor Ort?', text: `In der Regel am selben Tag. Wichtiger als die Minutenzahl ist aber, dass das Fahrzeug bis zur Besichtigung möglichst unverändert bleibt: nicht waschen, nichts abbauen, keine Teile entsorgen — auch nicht die abgebrochene Spiegelkappe. Jede Veränderung nimmt Beweismaterial weg, das später fehlt, wenn die Gegenseite den Hergang bestreitet. Ist das Fahrzeug nicht mehr fahrbereit, besichtigen wir es dort, wo es steht, oder beim Abschleppbetrieb. Melden Sie sich telefonisch oder über WhatsApp; wir sagen Ihnen sofort, welche Unterlagen wir brauchen und was Sie bis zum Termin am besten unterlassen.` },
    { text: `Kfz-Gutachter Solingen — neutral, gerichtsfest, in allen Stadtteilen vor Ort. Rufen Sie an oder schreiben Sie kurz über WhatsApp, dann ist in fünf Minuten geklärt, wie es weitergeht.` },
  ],
  velbert: [
    { text: `Velbert (42549) liegt auf den Höhen zwischen Ruhrgebiet und Bergischem Land und ist seit dem 18. Jahrhundert das Zentrum der deutschen Schloss- und Beschlägeindustrie — die Schlüsselregion Velbert/Heiligenhaus gilt bis heute als weltweit führender Standort für Schließ- und Sicherheitstechnik. Für den Verkehr heißt das: viel Werks-, Zuliefer- und Pendlerverkehr auf Straßen, die durch hügeliges Gelände führen. Die A44 verläuft nördlich vorbei, die A535 verbindet die Stadt mit Wuppertal, dazu kommen die B224 und die B227. Nach einem unverschuldeten Unfall beauftragen Sie den Sachverständigen selbst; die Haftpflicht des Verursachers zahlt das Honorar nach § 249 BGB.` },
    { vorort: true, text: `Velbert ist verkehrlich drei Städte auf einmal: Mitte, Langenberg und Neviges waren bis 1975 eigenständig und liegen bis heute räumlich getrennt, verbunden über Höhen- und Talstraßen statt über ein gemeinsames Zentrum. Velbert-Mitte trägt Einkaufs-, Werks- und Berufsverkehr; hier passieren die klassischen Auffahr- und Abbiegeunfälle. Langenberg liegt eng im Tal, mit schmaler Ortsdurchfahrt, in der sich Lieferfahrzeuge und Gegenverkehr gegenseitig ausbremsen. Neviges zieht als Wallfahrtsort mit dem Mariendom auswärtige Besucher an, die die Zufahrten nicht kennen. Zwischen den drei Teilen liegen kurvige Verbindungsstrecken mit Kuppen und wechselnder Fahrbahnbreite. Zur Besichtigung kommen wir in alle drei.` },
    { h3: 'Was macht die A535 als kurze Stichautobahn besonders?', text: `Sie ist keine Fernstrecke, sondern eine Zubringerachse zwischen Velbert und Wuppertal — mit entsprechend hohem Anteil an Fahrern, die täglich dieselbe Strecke fahren und sie deshalb routiniert nehmen. Genau daraus entsteht das typische Schadensbild: dichtes Auffahren, spätes Bremsen an den Anschlussstellen, Spurwechsel ohne Schulterblick. Auffahrunfälle bei mittlerer Geschwindigkeit sind die häufigste Folge, und sie sind die Unfallart, bei der am meisten übersehen wird. Der Stoßfänger federt zurück, der Querträger dahinter bleibt verzogen; bei Fahrzeugen mit Anhängerkupplung läuft die Kraft zusätzlich in deren Aufnahme und von dort in den Längsträger. Wir prüfen deshalb bei jedem Heckschaden die Kupplungsaufnahme mit — ein verzogener Kugelhals ist ein sicherheitsrelevanter Befund, der nachträglich schwer zu belegen ist.` },
    { h3: 'Werks- und Flottenfahrzeuge aus der Schlüsselregion: Was ist anders?', text: `Bei einem Firmenfahrzeug hängt an dem Schaden mehr als eine Reparatur. Die Halterfirma braucht eine Dokumentation, die gegenüber der eigenen Flottenversicherung und der gegnerischen Haftpflicht gleichermaßen standhält, und sie braucht sie schnell, weil das Fahrzeug im Einsatz eingeplant ist. Bei Transportern und Kastenwagen kommt hinzu, dass der Ausbau — Regalsysteme, Trennwand, Dachträger — bei der Kalkulation regelmäßig unter den Tisch fällt, obwohl seine Demontage und Wiedermontage echte Arbeitszeit ist. Ebenso der Ausfallschaden: Bei gewerblich genutzten Fahrzeugen tritt an die Stelle des Nutzungsausfalls oft ein konkret zu belegender Verdienstausfall. Wir weisen beides getrennt aus, damit es nicht in einer Sammelposition verschwindet, die sich leicht streichen lässt.` },
    { h3: 'Wallfahrts- und Veranstaltungsverkehr in Neviges: Was passiert auf den Parkflächen?', text: `Wenn viele auswärtige Fahrzeuge gleichzeitig auf begrenzte Stellflächen treffen, verschiebt sich das Schadensbild weg von der Fahrbahn hin zum Stand. Typisch sind Anstöße beim Ein- und Ausparken, aufgerissene Seitenwände durch geöffnete Türen und Rempler beim Rückwärtsfahren aus einer Reihe, in der niemand Sicht hat. Diese Schäden sind niedrig, breit und flach — und der Verursacher ist häufig schon weg, wenn Sie zurückkommen. Dann entscheidet die Dokumentation: Lackantragungen in Fremdfarbe, Höhe der Kontaktstelle über der Fahrbahn und die Form des Abdrucks lassen sich auswerten, solange nichts verändert wurde. Waschen Sie das Fahrzeug in diesem Fall auf keinen Fall vor der Besichtigung.` },
    { h3: 'Was steht am Ende im Gutachten?', text: `Ein Gutachten nach BVSK-Standard ist kein Kostenvoranschlag, sondern eine Beweisurkunde: Es hält den Zustand vor der Reparatur so fest, dass er später niemand mehr bestreiten kann, und es beziffert jede Position nachvollziehbar. Es geht auf Wunsch direkt an Sie, an Ihre Kanzlei oder an die gegnerische Versicherung. Zum Standardumfang gehören:`, liste: ['Foto- und Maßdokumentation des gesamten Fahrzeugs', 'Lackschichtdickenmessung und Prüfung auf Vorschäden', 'Reparaturkosten nach marktüblicher Kalkulation', 'Prüfung von Anhängerkupplung und Trägerstruktur bei Heckschäden', 'Wertminderung, Restwert und Wiederbeschaffungswert', 'Gutachten binnen 48 Stunden'] },
    { h3: 'Warum nicht einfach den Gutachter der gegnerischen Versicherung nehmen?', text: `Weil der im Auftrag derjenigen Seite arbeitet, die am Ende zahlen soll. Das muss keine böse Absicht sein — es ist schlicht ein anderer Auftrag. Sein Prüfbericht bewertet, ob die geforderte Summe angemessen ist; er sucht nicht danach, was zusätzlich beschädigt sein könnte. Genau diese Lücke kostet Geld, weil Achsschäden, Sensorkalibrierung und Wertminderung typischerweise nur dann in der Abrechnung landen, wenn sie jemand aktiv erhoben hat. Sie haben das Recht auf einen eigenen Sachverständigen, und dieses Recht ist bei unverschuldetem Unfall auch finanziell folgenlos für Sie.` },
    { h3: 'Was gilt bei einem Schaden auf einem Werks- oder Firmenparkplatz?', text: `Ein Betriebsgelände ist kein öffentlicher Verkehrsraum, und das ändert einiges. Die Polizei nimmt einen reinen Parkplatzunfall dort in der Regel nicht auf, es gibt oft keine Zeugen, und die Beweislage ruht damit vollständig auf dem Fahrzeug. Umso wichtiger ist, dass nichts verändert wird, bevor jemand den Zustand festgehalten hat. Häufig kommt hinzu, dass Rangierschäden auf Werksflächen von Staplern, Anhängern oder Lieferfahrzeugen verursacht werden — dann liegt der Anstoß in ungewöhnlicher Höhe und mit ungewöhnlich harter Kontaktfläche, was am Fahrzeug zu punktueller Verformung statt flächiger Delle führt. Diese Form ist charakteristisch und lässt sich einem Verursacher zuordnen, solange sie dokumentiert ist. Wir kommen dafür auch auf das Betriebsgelände.` },
    { text: `Kfz-Gutachter Velbert — unabhängig, gerichtsfest, in Mitte, Langenberg und Neviges vor Ort. Ein Anruf oder eine kurze Nachricht per WhatsApp reicht für den ersten Schritt.` },
  ],
  heiligenhaus: [
    { text: `Heiligenhaus (42579) liegt im Niederbergischen Land auf einem Höhenrücken, der von West nach Ost verläuft und nach beiden Seiten steil abfällt: im Norden ins Vogelsangbachtal, im Süden ins Angertal. Diese Kammlage prägt den Verkehr mehr als jede Straßenplanung — wer die Stadt verlässt, fährt in aller Regel bergab, und wer hineinfährt, bergauf. Die B227 zieht als Hauptdurchfahrt mitten durch das Stadtgebiet und stellt im Westen die Verbindung zum Autobahnkreuz Breitscheid mit A3, A52 und A524 her; nördlich liegt die A44, an die Heiligenhaus über eine Anschlussstelle bei Hofermühle angebunden ist. Zusammen mit Velbert bildet die Stadt die Schlüsselregion, den führenden Standort der Schloss- und Beschlägeindustrie. Nach einem unverschuldeten Unfall zahlt die Haftpflicht des Verursachers Ihren eigenen Sachverständigen — nach § 249 BGB, ohne Eigenanteil für Sie.` },
    { vorort: true, text: `Heiligenhaus ist kleiner als seine Nachbarn, aber verkehrlich nicht einfacher. Innenstadt, Ober- und Unterstadt liegen dicht beieinander auf dem Kamm, mit der B227 als durchgehender Achse und entsprechend viel Durchgangsverkehr, der eigentlich gar nicht in die Stadt will. Oberilp und Unterilp sind Wohnquartiere mit ruhigen, aber engen Erschließungsstraßen und viel Parkdruck am Fahrbahnrand. Isenbügel und Hetterscheidt im Osten gehen in offenes Gelände über, Abtsküche und Hofermühle liegen bereits an den Hängen zum Angertal hin. Zwischen alldem verlaufen kurze, steile Verbindungsstücke, auf denen bei Nässe und Laub im Herbst regelmäßig etwas passiert. Zur Besichtigung kommen wir in jeden dieser Ortsteile.` },
    { h3: 'Was macht die B227 mitten durch die Stadt so schadensträchtig?', text: `Eine Bundesstraße, die als Ortsdurchfahrt dient, bringt zwei unvereinbare Verkehrsarten zusammen: Durchgangsverkehr, der zügig durchwill, und örtlichen Verkehr, der abbiegt, hält, ein- und ausparkt. Das Ergebnis sind Auffahrunfälle hinter Linksabbiegern und seitliche Anstöße beim Ausfahren aus Grundstückszufahrten. Weil die Geschwindigkeitsdifferenz dabei oft groß ist, sind diese Schäden schwerer, als die Innerortslage vermuten lässt. Am Fahrzeug trifft es bei einem Auffahrunfall Heckabschlussblech, Querträger und Kofferraumboden, beim seitlichen Anstoß die B-Säule und die Türverstärkung. Beides sind Bereiche, in denen moderne Fahrzeuge hochfeste Stähle verbauen, die sich nicht richten lassen, sondern nur austauschen — ein Unterschied, der die Reparaturkosten in einer Größenordnung verschiebt, die jeder Kostenvoranschlag ohne Demontage übersieht.` },
    { h3: 'Wie wirkt sich die Kammlage zwischen zwei Tälern aus?', text: `Sie sorgt dafür, dass fast jede Fahrt in Heiligenhaus mit Gefälle oder Steigung zu tun hat. Für die Schadensbewertung ist das aus zwei Gründen wichtig. Erstens verlängert Gefälle den Bremsweg spürbar, weshalb Auffahrunfälle hier häufiger mit höherer Restgeschwindigkeit stattfinden als auf ebener Strecke — der Schaden fällt schwerer aus, als die Beteiligten ihn einschätzen. Zweitens verändert die Neigung die Anstoßhöhe: Ein bergab rollendes Fahrzeug trifft tiefer, ein bergauf stehendes wird höher getroffen. Diese Höhe ist am Fahrzeug ablesbar und einer der belastbarsten Anhaltspunkte dafür, wie sich ein bestrittener Hergang tatsächlich zugetragen hat. Wir vermessen sie deshalb und halten sie im Gutachten fest.` },
    { h3: 'Was ist an der Anbindung Richtung A44 und Kreuz Breitscheid zu beachten?', text: `Auf den Zubringern zur A44 im Norden und auf der B227 Richtung Breitscheid im Westen wechselt der Verkehr von Ortsgeschwindigkeit auf Autobahntempo und zurück. Solche Übergangsstrecken erzeugen ein eigenes Unfallmuster: zu spätes Erkennen eines Rückstaus am Ende der Ausfahrt, Auffahren auf stehende Fahrzeuge, gelegentlich mit mehreren Beteiligten. Bei einer Kettenkollision entscheidet die Reihenfolge der Anstöße über die Haftungsverteilung, und die lässt sich nur aus den Schadensbildern rekonstruieren — welche Deformation zuerst entstand, ist an Überlagerungen und Lackantragungen erkennbar. Wir dokumentieren bei mehreren Beteiligten deshalb nicht nur Ihren Schaden, sondern auch die Spuren, die eine spätere Zuordnung tragen:`, liste: ['Foto- und Maßdokumentation mit Anstoßhöhe über Fahrbahn', 'Lackantragungen und Fremdfarben sichern', 'Prüfung auf Überlagerung mehrerer Anstöße', 'Heckstruktur nach Demontage der Verkleidung', 'Wertminderung und Reparaturkosten getrennt ausgewiesen', 'Gutachten binnen 48 Stunden'] },
    { h3: 'Radverkehr auf dem PanoramaRadweg: Warum ist das ein eigenes Thema?', text: `Der PanoramaRadweg niederbergbahn führt auf der Trasse der stillgelegten Niederbergbahn von Heiligenhaus über Velbert und Wülfrath bis nach Haan und bringt an schönen Tagen viele Radfahrende in die Stadt, auch solche mit Pedelecs, die deutlich schneller unterwegs sind, als Autofahrer erwarten. An den Stellen, wo die Trasse Straßen quert oder Radverkehr auf die Fahrbahn wechselt, entstehen Kollisionen mit einem besonderen Problem: Der Sachschaden am Auto ist meist klein, die Haftungsfrage aber groß. Ein verkratzter Kotflügel und eine eingedellte Tür lassen sich beziffern; wer wo Vorrang hatte, entscheidet sich an Anstoßstelle, Anstoßwinkel und Aufprallhöhe. Wir nehmen genau diese Merkmale auf, weil sie die einzigen objektiven Zeugen sind.` },
    { h3: 'Leasing- oder finanziertes Fahrzeug: Was ist nach einem Unfall anders?', text: `Einiges, und es wird regelmäßig zu spät bemerkt. Bei einem Leasingfahrzeug sind Sie Halter, aber nicht Eigentümer — das ist der Leasinggeber. Ansprüche auf Reparaturkosten und Wertminderung stehen deshalb zunächst ihm zu; üblicherweise ermächtigt der Vertrag Sie, sie im eigenen Namen geltend zu machen, doch die Auszahlung fließt je nach Vereinbarung an ihn. Wichtiger noch: Die meisten Leasingverträge schreiben eine Instandsetzung nach Herstellervorgaben in einer entsprechend ausgestatteten Fachwerkstatt vor. Eine fiktive Abrechnung, bei der Sie sich den Betrag auszahlen lassen und günstiger reparieren, ist dann praktisch ausgeschlossen — wer es trotzdem tut, bekommt das bei der Rückgabe zurückgespielt. Genau dort entscheidet sich, wozu das Gutachten gut war: Bei der Rückgabe wird über den Zustand gestritten, und ein vor der Reparatur erstelltes, neutrales Gutachten ist der einzige Beleg dafür, was tatsächlich beschädigt und wie es instand gesetzt wurde. Bei finanzierten Fahrzeugen mit Sicherungsübereignung gilt sinngemäß dasselbe.` },
    { h3: 'Elektrofahrzeug nach einem Anstoß: Warum die Batterie gesondert geprüft gehört', text: `Weil man ihr von außen nichts ansieht und die Folgen eines übersehenen Schadens nicht linear sind. Das Hochvoltsystem liegt bei den meisten Elektrofahrzeugen als flacher Block im Boden zwischen den Achsen — geschützt, aber eben auch in der Zone, die bei einem seitlichen Anstoß oder einer Kollision mit Bordstein und Leitplanke Kräfte aufnimmt. Die Hersteller geben für solche Fälle eigene Prüfschritte vor, typischerweise das Auslesen des Batteriemanagementsystems und eine Isolationsmessung. Fällt der Befund unklar aus, wird das Fahrzeug häufig mit Sicherheitsabstand auf einer separaten Fläche abgestellt, bis geklärt ist, ob eine Reaktion der Zellen zu befürchten ist — was Standkosten verursacht, die ebenfalls zum Schaden gehören. Für die Bewertung ist zusätzlich entscheidend: Ein Elektrofahrzeug mit ungeklärtem Batteriezustand hat praktisch keinen belastbaren Restwert. Wir weisen die Herstellerprüfung deshalb als eigene Position aus und bewerten das Fahrzeug erst, wenn ihr Ergebnis vorliegt.` },
    { h3: 'Beide Seiten tragen Schuld: Was bedeutet eine Haftungsquote für Ihre Auszahlung?', text: `Dass jede einzelne Position anteilig ersetzt wird — Reparaturkosten, Wertminderung, Mietwagen und auch das Sachverständigenhonorar. Bei einer Quote von siebzig zu dreißig bekommen Sie also siebzig Prozent von allem, und die restlichen dreißig Prozent des Gutachterhonorars tragen Sie selbst. Daraus wird oft der falsche Schluss gezogen, ein eigenes Gutachten lohne sich bei geteilter Schuld nicht. Das Gegenteil stimmt: Wenn die Quote strittig ist, wird nicht nur über die Höhe des Schadens gestritten, sondern über den Hergang — und der lässt sich nur aus dem Schadensbild rekonstruieren. Anstoßstelle, Anstoßwinkel, Kontakthöhe und Überlagerungen sagen, wer sich wie bewegt hat. Fehlt diese Aufnahme, bleibt es bei Aussage gegen Aussage, und dann setzt sich in der Regel die Version durch, hinter der eine Versicherung mit eigenem Prüfbericht steht. Wir klären die Quotenfrage offen mit Ihnen, bevor Sie beauftragen.` },
    { h3: 'Wer bezahlt Gutachter, Anwalt und Ersatzwagen?', text: `Bei unverschuldetem Unfall die Haftpflichtversicherung der Gegenseite. Das gilt für das Gutachterhonorar ebenso wie für einen Verkehrsrechtsanwalt und für Mietwagen oder Nutzungsausfallentschädigung während der Reparaturzeit — alles Teil des Schadensersatzes nach § 249 BGB. Sie müssen dafür nichts vorstrecken und sich auch nicht auf den Prüfer der Gegenseite einlassen. Über das Claimondo-Netzwerk vermitteln wir auf Wunsch Anwalt, Werkstatt und Ersatzfahrzeug, sodass die Abwicklung parallel zur Reparatur läuft statt hintereinander.` },
    { text: `Kfz-Gutachter Heiligenhaus — unabhängig, gerichtsfest, kurzfristig vor Ort in der Innenstadt, auf der Ilp und in Isenbügel. Melden Sie sich telefonisch oder per WhatsApp, dann klären wir das Weitere in wenigen Minuten.` },
  ],
  wuelfrath: [
    { text: `Wülfrath (42489) im Kreis Mettmann ist die kleinste Stadt in diesem Einsatzgebiet und zugleich die mit dem ungewöhnlichsten Verkehrsprofil. Der alte Ortskern liegt eng in einem Tal, das der Anger durchfließt; die neueren Stadtteile ziehen sich die Hänge hinauf. Geprägt ist die Stadt vom Kalksteinabbau — das Werk Flandersbach gilt als größter Kalksteinbruch Europas. Verkehrlich heißt das: kein Durchgangsverkehr auf einer großen Achse, dafür Werksverkehr, der sich auf wenige Straßen konzentriert. Im Osten verläuft die A535 mit einer eigenen Anschlussstelle, im Norden streift die A44 auf einem kurzen Teilstück das Stadtgebiet. Nach einem unverschuldeten Unfall haben Sie Anspruch auf einen eigenen Sachverständigen, bezahlt von der Haftpflicht des Verursachers nach § 249 BGB.` },
    { vorort: true, text: `Die Wülfrather Ortsteile unterscheiden sich stärker, als die Größe der Stadt vermuten lässt. Die Innenstadt mit ihrem historischen Kern hat schmale Straßen und wenig Rangierraum — hier passiert das meiste im Stand oder bei Schrittgeschwindigkeit. Flandersbach und Rohdenhaus liegen im Bereich des Kalkabbaus und sind vom Werksbetrieb geprägt. Kocherscheidt und Schlupkothen sind wohngeprägt, mit Erschließungsstraßen, die an den Hang gebaut wurden. Düssel im Süden liegt ländlich, mit Landstraßencharakter und entsprechend höheren Geschwindigkeiten. Zwischen den Ortsteilen führen kurvige Strecken über wechselnde Höhen. Wir kommen zur Besichtigung in jeden Teil des Stadtgebiets, auch zu Betriebshöfen und Abstellflächen.` },
    { h3: 'Was macht den engen Ortskern im Angertal für Fahrzeuge riskant?', text: `Alte Ortskerne sind für Fuhrwerke gebaut, nicht für heutige Fahrzeugbreiten. In Wülfrath kommt hinzu, dass der Kern im Tal liegt und die Straßen deshalb nicht nur schmal, sondern auch geneigt sind. Die typischen Schäden entstehen dort im Stand und bei sehr niedriger Geschwindigkeit: Anstöße beim Rangieren, Streifer an Hauswänden, Pollern und Bordsteinkanten, aufgesetzte Frontschürzen an Zufahrten mit steilem Übergang. Gerade dieser letzte Fall wird regelmäßig unterschätzt. Wenn ein Fahrzeug mit tiefer Front an einer Kante aufsetzt, reißt selten das Sichtbare — es reißen die Clip- und Schraubpunkte hinter der Schürze, und die Verkleidung sitzt danach nur noch scheinbar. Das fällt bei der ersten Wäsche auf, wenn sie sich löst. Wir prüfen deshalb die Befestigungspunkte, nicht nur die Oberfläche.` },
    { h3: 'Steinstaub, Splitt und Lack: Warum ist die saubere Abgrenzung so wichtig?', text: `Wo Kalkstein abgebaut und transportiert wird, liegt feiner Abrieb auf der Fahrbahn und in der Luft. Auf Lack und Glas hinterlässt das über die Zeit ein feines, flächiges Muster, das sich von einem frischen Unfallschaden deutlich unterscheidet — für das ungeübte Auge aber ähnlich aussieht. Genau an dieser Stelle setzen Kürzungen an: Die Gegenseite bewertet eine Schadensfläche als vorbestehend, und plötzlich zahlt sie nur einen Teil. Die Abgrenzung gelingt über die Lackschichtdickenmessung und über die Struktur der Beschädigung: Ein frischer Anstoß verformt gerichtet, Umgebungsabrieb wirkt ungerichtet und gleichmäßig. Wir messen deshalb flächig und nicht nur an der Kontaktstelle und dokumentieren den Vorzustand ausdrücklich mit — das schützt Ihre Forderung und ist zugleich ehrlich gegenüber der Versicherung:`, liste: ['Flächige Lackschichtdickenmessung statt Stichprobe', 'Abgrenzung Unfallschaden gegen Vorschaden und Umgebungsabrieb', 'Prüfung von Glas und Scheinwerferstreuscheiben', 'Befestigungspunkte hinter Schürzen und Verkleidungen', 'Reparaturkosten und Wertminderung getrennt beziffert', 'Gutachten binnen 48 Stunden'] },
    { h3: 'Warum sind Achse, Reifen und Felgen in Wülfrath besonders zu prüfen?', text: `Weil die Kombination aus Hanglagen, engen Kurven und Bordsteinen mit hoher Kante genau die Bauteile belastet, die man von außen nicht beurteilen kann. Ein Bordsteinanstoß beim Ausweichen wirkt oberflächlich wie ein Felgenkratzer. Tatsächlich läuft die Kraft über das Rad in Spurstange, Querlenker und Radlager. Die Folgen zeigen sich nicht sofort, sondern nach einigen hundert Kilometern als schiefstehendes Lenkrad, einseitiger Reifenverschleiß oder ein Geräusch, das langsam lauter wird. Wird das nicht im Gutachten erfasst, ist es später kaum noch durchsetzbar, weil sich der Zusammenhang zum Unfall nicht mehr belegen lässt. Wir lassen die Achse deshalb bei jedem Anstoß gegen ein Rad vermessen und legen das Protokoll bei.` },
    { h3: 'Was gilt, wenn kein Verursacher greifbar ist?', text: `Bei einem Parkschaden ohne Zeugen oder bei Fahrerflucht bleibt zunächst offen, wer zahlt — in Betracht kommen die eigene Vollkasko oder, unter bestimmten Voraussetzungen, die Verkehrsopferhilfe. Beide Wege setzen voraus, dass der Schaden nachvollziehbar dokumentiert ist, bevor irgendetwas verändert wurde. Erstatten Sie Anzeige, lassen Sie das Fahrzeug ungewaschen und bauen Sie nichts ab. Wir sichern anschließend Fremdlack, Abdruckform und Kontakthöhe. Aus diesen drei Angaben lässt sich in vielen Fällen die Fahrzeugklasse des Verursachers eingrenzen, und selbst wenn nicht, belegen sie gegenüber der eigenen Versicherung, dass es sich um Fremdeinwirkung handelte und nicht um einen selbst verursachten Schaden.` },
    { h3: 'Lohnt sich ein eigener Sachverständiger auch bei kleineren Schäden?', text: `Bei sehr geringen Schäden reicht mitunter ein Kostenvoranschlag; die Grenze verläuft aber niedriger, als die meisten annehmen. Sobald eine Wertminderung im Raum steht — bei Fahrzeugen bis etwa fünf Jahre praktisch immer, sobald geschweißt oder ein tragendes Teil ersetzt wird —, ist der Kostenvoranschlag der falsche Weg, weil er diese Position gar nicht kennt. Dasselbe gilt, wenn Assistenzsysteme kalibriert werden müssen oder der Hergang bestritten wird. Wir sagen Ihnen am Telefon ehrlich, wenn sich ein Gutachten in Ihrem Fall nicht lohnt — das kostet Sie nichts und erspart beiden Seiten Arbeit.` },
    { text: `Kfz-Gutachter Wülfrath — unabhängig, gerichtsfest, kurzfristig vor Ort im Angertal und in den Höhenlagen. Ein Anruf oder eine WhatsApp genügt für die erste Einschätzung.` },
  ],
  mettmann: [
    { text: `Mettmann (40822) ist Kreisstadt des Kreises Mettmann und liegt auf den Mettmanner Lößterrassen am Westrand des Rheinischen Schiefergebirges — dort, wo das Bergische Land ins Rheinland übergeht. Die Düssel durchfließt das Stadtgebiet im Bereich des Neandertals; zwischen dem tiefsten Punkt dort und der Höhe an der Wülfrather Stadtgrenze liegen rund 128 Höhenmeter. Verkehrlich hängt die Stadt an der A3 mit eigener Anschlussstelle und an der B7, die den Verkehr Richtung Düsseldorf und Wuppertal führt. Lößböden, Hanglagen und eine enge, gewachsene Kernstadt prägen das örtliche Unfallgeschehen. Nach einem unverschuldeten Unfall beauftragen Sie den Sachverständigen selbst — die Gegenseite zahlt ihn nach § 249 BGB.` },
    { vorort: true, text: `Mettmann besteht aus wenigen, aber sehr unterschiedlichen Teilen. Die Kernstadt ist der Kreisverwaltungs- und Einkaufsschwerpunkt: dichter Parksuchverkehr, viele Fußgänger, kurze Sichtachsen — hier passiert das meiste bei niedriger Geschwindigkeit und trotzdem mit erheblichen Kosten. Metzkausen im Norden ist wohngeprägt und liegt spürbar höher, verbunden über Hangstraßen. Obschwarzbach im Süden geht in offenes Gelände über, mit Landstraßenprofil und deutlich höheren Geschwindigkeiten. Dazu kommt der Ausflugsverkehr ins Neandertal, der an Wochenenden auswärtige Fahrer auf Strecken bringt, die sie nicht kennen. Zur Besichtigung kommen wir in alle Ortsteile — auch zu Werkstätten und Abstellplätzen außerhalb.` },
    { h3: 'Auffahrunfall an der Anschlussstelle Mettmann: Was wird dabei am häufigsten übersehen?', text: `Der Übergang zwischen A3 und nachgeordnetem Netz ist die klassische Rückstaustelle: Am Ende der Ausfahrt steht eine Schlange, die von oben nicht einsehbar ist. Wer dort auffährt, tut das mit deutlich mehr Restgeschwindigkeit als im Stadtverkehr. Am Fahrzeug sieht man danach oft erstaunlich wenig, weil der Stoßfänger zurückfedert — und genau das ist die Falle. Die Kraft läuft in den Querträger, von dort in die Längsträger und in den Kofferraumboden. Hinweise sind ungleiche Spaltmaße an der Heckklappe, eine Klappe, die anders schließt als vorher, und Falten im Blech der Reserveradmulde. Wir bauen bei Verdacht die Verkleidung ab und vermessen die Hinterachsaufnahme; bleibt das ungeprüft, wird der Stoßfänger bezahlt und der Verzug fährt mit.` },
    { h3: 'Was macht die Kernstadt für Rangierschäden so anfällig?', text: `Enge Straßen, schräge Stellplätze und viele Ein- und Ausfahrten auf kurzer Strecke: Das erzeugt Schäden, die langsam entstehen und trotzdem teuer sind. Ein Anstoß bei Schrittgeschwindigkeit verformt nicht, er schiebt — und dabei verschieben sich Anbauteile in ihren Aufnahmen, ohne dass außen etwas bricht. Typisch sind Stoßfängerecken, die sich später von der Kotflügelkante lösen, verschobene Scheinwerferhalter mit anschließend falsch stehendem Lichtkegel und Türen, die nicht mehr bündig sitzen. Bei Fahrzeugen mit Parksensorik oder Rückfahrkamera kommt hinzu, dass schon geringe Verschiebung die Kalibrierung unbrauchbar macht. Diese Position taucht in Kostenvoranschlägen fast nie auf und ist einer der häufigsten Gründe, warum eine Reparatur am Ende teurer wird als kalkuliert:`, liste: ['Prüfung aller Anbauteile auf Verschiebung in der Aufnahme', 'Spaltmaße rundum im Vergleich zur Gegenseite', 'Scheinwerfereinstellung und Kalibrierbedarf der Sensorik', 'Lackschichtdickenmessung zur Abgrenzung von Vorschäden', 'Wertminderung bei Fahrzeugen unter fünf Jahren', 'Gutachten binnen 48 Stunden'] },
    { h3: 'Ausflugsverkehr ins Neandertal: Wann wird es eng?', text: `An schönen Wochenenden treffen ortskundige Fahrer auf Besucher, die die Strecke zum ersten Mal fahren, langsamer unterwegs sind und unvermittelt abbiegen oder anhalten. Auf schmalen Talstraßen mit Böschung auf der einen und Gegenverkehr auf der anderen Seite bleibt dann wenig Spielraum. Die häufigste Folge sind Streifkollisionen im Begegnungsverkehr und Ausweichmanöver gegen die Böschungskante. Bei einem Ausweichschaden ohne Berührung mit dem anderen Fahrzeug wird es haftungsrechtlich anspruchsvoll: Sie müssen belegen, dass das Ausweichen erforderlich war. Dafür zählen Spurenlage, Schadensbild und Fahrzeugstellung. Wir nehmen diese Merkmale auf, solange sie noch da sind — nach dem Abschleppen sind sie es meist nicht mehr.` },
    { h3: 'Reparatur, fiktive Abrechnung oder Totalschaden — was ist sinnvoll?', text: `Das hängt an drei Zahlen, die im Gutachten sauber getrennt stehen müssen: Reparaturkosten, Wiederbeschaffungswert und Restwert. Liegen die Reparaturkosten darunter, wird repariert oder auf Gutachtenbasis fiktiv abgerechnet. Liegen sie darüber, aber nicht mehr als dreißig Prozent, kommt unter bestimmten Voraussetzungen die sogenannte 130-Prozent-Regelung in Betracht, die eine Reparatur trotz rechnerischem Totalschaden ermöglicht. Darüber hinaus wird auf Wiederbeschaffungsbasis abgerechnet. Entscheidend ist, dass der Restwert auf belastbaren Marktdaten beruht und nicht auf einem einzelnen Angebot eines Aufkäufers — an dieser Stelle entstehen die größten Differenzen. Wir beziffern alle drei Werte nachvollziehbar, damit Ihnen die Wahl offenbleibt statt vorgegeben zu werden.` },
    { h3: 'Wer trägt die Kosten für Gutachten, Anwalt und Ersatzwagen?', text: `Bei unverschuldetem Unfall die Haftpflicht des Verursachers, und zwar für alle drei. Das Gutachterhonorar, die Kosten eines Verkehrsrechtsanwalts sowie Mietwagen oder Nutzungsausfallentschädigung sind Teil des Schadensersatzes nach § 249 BGB. Sie sind auch nicht verpflichtet, die von der Versicherung vorgeschlagene Werkstatt zu nutzen — die Wahl liegt bei Ihnen, und das Gutachten ist die Grundlage, auf der der Betrieb Ihrer Wahl abrechnet. Auf Wunsch vermitteln wir Anwalt, Werkstatt und Ersatzfahrzeug über das Claimondo-Netzwerk, damit die Abwicklung nicht an Ihnen hängenbleibt.` },
    { text: `Kfz-Gutachter Mettmann — unabhängig, gerichtsfest, in Kernstadt, Metzkausen und Obschwarzbach vor Ort. Rufen Sie an oder schreiben Sie per WhatsApp; die erste Einschätzung dauert wenige Minuten.` },
  ],
  haan: [
    { text: `Haan (42781) liegt auf der Bergischen Heideterrasse zwischen Düsseldorf, Solingen und Wuppertal — verkehrlich einer der am dichtesten erschlossenen Orte in diesem Einsatzgebiet. Die A46 durchquert das Stadtgebiet von West nach Ost mit den Anschlussstellen Haan-Ost und Haan-West, die A3 verläuft in unmittelbarer Nähe, dazu kommt die B228. Der Ortsteil Gruiten grenzt an das Neandertal, wo die Düssel sich tief in den Kalkstein eingeschnitten hat. Das Ergebnis ist eine Stadt, durch die täglich sehr viel Verkehr fährt, der gar nicht hier hinwill. Nach einem unverschuldeten Unfall haben Sie das Recht auf einen eigenen Sachverständigen; sein Honorar trägt die Haftpflichtversicherung des Verursachers nach § 249 BGB.` },
    { vorort: true, text: `Haan besteht im Kern aus zwei sehr unterschiedlichen Teilen. Haan-Mitte ist städtisch geprägt, mit Einkaufs- und Berufsverkehr, engen Nebenstraßen und hohem Parkdruck; hier dominieren Rangier-, Abbiege- und Türöffnerschäden. Gruiten liegt getrennt davon im Westen, mit historischem Ortskern und direktem Übergang ins Neandertal — schmale Straßen, alte Bebauung, wenig Ausweichraum. Zwischen beiden und rund um die Anschlussstellen liegen die Gewerbeflächen, die den Lieferverkehr bündeln: Sattelzüge, Transporter und Pkw auf denselben Straßen, oft im Rückwärtsmanöver. Wir besichtigen in Haan-Mitte, in Gruiten und auf den Betriebshöfen an den Autobahnanschlüssen.` },
    { h3: 'Was passiert im Haaner Pendlerverkehr am häufigsten?', text: `Auffahrunfälle, und zwar in ihrer unangenehmsten Variante: auf Zubringern mit zügigem Verkehrsfluss, der unvermittelt zum Stehen kommt. Das Tempo ist dort hoch genug für strukturelle Schäden und niedrig genug, dass die Beteiligten sie unterschätzen. Am getroffenen Fahrzeug arbeitet sich die Kraft von hinten nach vorn: Querträger, Längsträger, Kofferraumboden, bei stärkerem Anstoß bis in die C-Säule. Beim auffahrenden Fahrzeug trifft es Kühler, Kondensator und Lüfter — Bauteile, deren Beschädigung sich erst nach einigen Kilometern durch steigende Kühlmitteltemperatur zeigt. Wir prüfen deshalb bei jedem Frontschaden den Kühlerverbund auf Undichtigkeit, auch wenn außen nur der Stoßfänger fehlt. Ein übersehener Kühlerschaden endet regelmäßig mit einem Motorschaden, der dann niemandem mehr zuzuordnen ist.` },
    { h3: 'Lieferverkehr an den Gewerbeflächen: Wer haftet beim Streifschaden?', text: `Wo Sattelzüge auf engen Betriebsstraßen rangieren, entstehen Streifschäden mit einem charakteristischen Bild: ein langer, in der Höhe konstanter Kontakt über mehrere Fahrzeugteile hinweg, oft mit Fremdlack oder Gummiabrieb. Die Haftungsfrage ist dabei selten trivial, weil häufig unklar bleibt, ob Fahrer, Spedition oder der Betreiber der Fläche einzustehen hat. Entscheidend ist die Kontakthöhe: Sie sagt, welches Fahrzeug welche Bewegung machte. Am Pkw geht ein solcher Streifer über Türen und Seitenwand, und weil Seitenwände heute meist verschweißt statt verschraubt sind, ist die Instandsetzung aufwendiger, als der Kratzer vermuten lässt. Wir halten Kontakthöhe, Verlaufsrichtung und Fremdantragungen fest, damit sich die Zuordnung später nicht drehen lässt:`, liste: ['Kontakthöhe über Fahrbahn exakt vermessen', 'Fremdlack und Gummiabrieb sichern und dokumentieren', 'Prüfung, ob Seitenwand geschweißt oder verschraubt ist', 'Türfalze und Scharniere auf Verzug', 'Reparaturweg mit Begründung statt Pauschalansatz', 'Gutachten binnen 48 Stunden'] },
    { h3: 'Was ist bei Schäden auf der Heideterrasse an Fahrwerk und Reifen zu prüfen?', text: `Die Heideterrasse ist kein Hochgebirge, aber sie ist auch nicht eben: Es gibt Kuppen, Senken und Übergänge, an denen ein Fahrzeug bei zügiger Fahrt kurz entlastet wird. Trifft ein Anstoß in genau diesem Moment, wirkt er anders als auf ebener Strecke, weil die Federung ausgefahren ist und die Kraft ungebremst in die Radaufhängung geht. Sichtbar ist davon nichts. Prüfbar ist es über die Achsvermessung und über die Sichtprüfung von Querlenker, Federbeinstützlager und Radlager. Ein weiterer Punkt: Nach einem Anstoß gegen ein Rad kann die Reifenflanke innen eingerissen sein, ohne außen beschädigt zu wirken — ein Befund, der später bei Autobahntempo gefährlich wird. Wir demontieren im Zweifel und sehen von innen nach.` },
    { h3: 'Mietwagen oder Nutzungsausfall — was steht Ihnen zu?', text: `Beides ist möglich, aber nicht gleichzeitig. Nehmen Sie für die Reparaturzeit einen Mietwagen, zahlt die gegnerische Haftpflicht ihn in einer Klasse, die Ihrem Fahrzeug entspricht. Verzichten Sie darauf und nutzen für ein paar Tage kein Auto, steht Ihnen stattdessen eine Nutzungsausfallentschädigung pro Tag zu, gestaffelt nach Fahrzeugklasse und Alter. Für Pendler ist die Rechnung meist eindeutig, für Zweitwagen oft nicht. Wichtig ist, dass das Gutachten die notwendige Reparaturdauer benennt — sie bestimmt den Zeitraum, für den überhaupt etwas gezahlt wird. Fehlt diese Angabe, kürzt die Gegenseite regelmäßig auf einen Erfahrungswert nach unten.` },
    { h3: 'Was sollten Sie unmittelbar nach dem Unfall tun?', text: `Sichern Sie die Unfallstelle und fotografieren Sie, bevor die Fahrzeuge bewegt werden — die Endstellung ist die wichtigste Information überhaupt und lässt sich später durch nichts ersetzen. Notieren Sie Kennzeichen, Versicherung und Zeugen. Danach gilt: nicht waschen, nichts reparieren, nichts abbauen und keine abgefallenen Teile entsorgen. Melden Sie den Schaden Ihrer eigenen Versicherung, aber lassen Sie sich nicht auf eine Besichtigung durch den Prüfer der Gegenseite drängen, bevor Sie einen eigenen Sachverständigen beauftragt haben. Rufen Sie uns an, dann sagen wir Ihnen, was in Ihrem konkreten Fall noch zu sichern ist.` },
    { text: `Kfz-Gutachter Haan — unabhängig, gerichtsfest, in Haan-Mitte, Gruiten und an den Gewerbeflächen vor Ort. Ein Anruf oder eine kurze WhatsApp genügt für den ersten Schritt.` },
  ],
  schwelm: [
    { text: `Schwelm (58332) ist Kreisstadt des Ennepe-Ruhr-Kreises und liegt am Westrand des Bergischen Landes zwischen Wuppertal und Hagen. Das Schwelmetal trennt die Innenstadt von den deutlich höher gelegenen Ortslagen Linderhausen und Winterberg — eine kleine Stadt mit großem Höhenunterschied auf kurzer Strecke. Verkehrlich ist Schwelm stark eingebunden: Die A1 verläuft östlich am Stadtgebiet vorbei und hat hier eine eigene Anschlussstelle, die A46 bindet Richtung Wuppertal an, und mit der B7 und der B483 kreuzen sich zwei Bundesstraßen im Stadtgebiet. Nach einem unverschuldeten Unfall beauftragen Sie den Sachverständigen selbst; die gegnerische Haftpflicht trägt das Honorar nach § 249 BGB, für Sie bleiben 0 €.` },
    { vorort: true, text: `Schwelm gliedert sich in Mitte, Nord und Süd, doch die eigentliche Trennlinie verläuft nicht zwischen diesen Bezirken, sondern zwischen Tal und Höhe. Die Innenstadt im Schwelmetal ist dicht bebaut, mit schmalen Straßen und ausgeprägtem Parkdruck — hier passieren Rangier- und Abbiegeschäden bei niedriger Geschwindigkeit. Die höher gelegenen Ortslagen Linderhausen und Winterberg erreicht man über kurze, steile Verbindungsstraßen mit engen Kurven. An den Rändern des Stadtgebiets kommt der Verkehr von A1 und A46 hinzu, der auf einmal von Autobahn- auf Ortsgeschwindigkeit heruntergebremst wird. Wir kommen zur Besichtigung ins Tal wie auf die Höhen.` },
    { h3: 'Was passiert typischerweise im Bereich der Anschlussstelle Schwelm?', text: `Anschlussstellen sind Tempowechselzonen, und der Tempowechsel ist die eigentliche Unfallursache. Wer die A1 verlässt, unterschätzt regelmäßig, wie kurz die Ausfahrt ist und wie schnell dahinter ein Rückstau steht. Wer auffährt, sucht eine Lücke und schaut nach hinten statt nach vorn. Beides endet in Auffahr- und Spurwechselkollisionen bei mittlerer Geschwindigkeit — der Bereich, in dem Fahrzeuge strukturell Schaden nehmen, ohne dass es dramatisch aussieht. Bei einem Anstoß von schräg hinten läuft die Kraft über die Seitenwand in die Radhausschale und den hinteren Längsträger; die Heckklappe schließt danach oft noch, sitzt aber nicht mehr mittig. Genau dieses Spaltmaß ist der erste verlässliche Hinweis, und wir vermessen es immer im Vergleich zur unbeschädigten Fahrzeugseite.` },
    { h3: 'Zwischen Innenstadt und Linderhausen: Was macht die Höhenstraßen kritisch?', text: `Kurze, steile Strecken mit engen Kurven verlangen ständige Lastwechsel — bergauf Zug, bergab Schub, dazwischen Bremsen in der Kurve. Für die Schadensbewertung ist vor allem die Bergabfahrt relevant: Ein Fahrzeug im Gefälle hat eine verlagerte Achslast, die Vorderachse ist stärker belastet, die Hinterachse entlastet. Kommt es dabei zur Kollision, fällt der Anstoß am Heck höher und an der Front tiefer aus als auf ebener Strecke. Diese Höhen sind messbar und rekonstruierbar — sie sind das, worauf sich ein Sachverständigengutachten stützt, wenn zwei Beteiligte den Hergang unterschiedlich schildern. Am Fahrzeug betrifft ein solcher Anstoß typischerweise Frontschürze, Unterfahrschutz und die Aufnahmepunkte des Motorträgers:`, liste: ['Anstoßhöhe an Front und Heck exakt vermessen', 'Unterfahrschutz und Motorträgeraufnahme prüfen', 'Spaltmaße im Seitenvergleich', 'Achsvermessung vorn und hinten', 'Abgrenzung Unfallschaden gegen Vorschaden per Lackmessung', 'Gutachten binnen 48 Stunden'] },
    { h3: 'Wildunfall am Schwelmer Stadtrand: Welche Spuren zählen?', text: `Wo Bebauung in Wald und Feld übergeht, kommt es in der Dämmerung zu Wildwechsel. Die Abwicklung läuft dann nicht über eine gegnerische Haftpflicht, sondern über Ihre Teilkasko — und die verlangt einen Nachweis, dass es tatsächlich ein Wildunfall war. Entscheidend sind Wildhaare, Blutspuren und Gewebereste am Fahrzeug sowie die Bescheinigung des Jagdausübungsberechtigten oder der Polizei. Waschen Sie das Fahrzeug deshalb keinesfalls vor der Besichtigung. Am Fahrzeug ist ein Wildunfall an einer breiten, flächigen Eindellung mit Aufwärtskomponente erkennbar; häufig sind Kühlergrill, Motorhaubenvorderkante und Scheinwerferhalter betroffen. Wir sichern die biologischen Spuren fotografisch, bevor sie verwittern, und weisen die Reparaturkosten teilkaskotauglich aus.` },
    { h3: 'Warum ist die Wertminderung bei jungen Fahrzeugen ein Streitpunkt?', text: `Weil sie kein Reparaturposten ist, sondern ein Marktwert: Ein Fahrzeug mit dokumentiertem Unfallschaden bringt beim Verkauf weniger, auch wenn es fachgerecht instand gesetzt wurde. Diesen merkantilen Minderwert schuldet die gegnerische Versicherung — sie zieht ihn aber gern in Zweifel, weil er sich nicht an einer Rechnung ablesen lässt. Relevant wird er vor allem bei Fahrzeugen unter etwa fünf Jahren und immer dann, wenn geschweißt oder ein tragendes Teil ersetzt wurde. Wir berechnen ihn nach einer anerkannten Methode und legen die Rechengrundlagen offen, statt eine Zahl zu behaupten. Das ist der Unterschied zwischen einer Position, die gekürzt wird, und einer, die hält.` },
    { h3: 'Wie schnell liegt das Gutachten vor, und wer bekommt es?', text: `In der Regel innerhalb von 48 Stunden nach der Besichtigung. Sie entscheiden, wer es erhält: Sie selbst, Ihre Kanzlei oder direkt die gegnerische Versicherung — häufig alle drei gleichzeitig, weil das die Regulierung beschleunigt. Wichtig ist die Reihenfolge: erst das Gutachten, dann die Reparatur. Wird vorher repariert, ist der Zustand nicht mehr feststellbar, und Sie müssen mit dem auskommen, was die Werkstattrechnung hergibt — Wertminderung und strittige Positionen sind dann kaum noch durchsetzbar. Ist das Fahrzeug nicht fahrbereit, besichtigen wir dort, wo es steht.` },
    { text: `Kfz-Gutachter Schwelm — unabhängig, gerichtsfest, im Schwelmetal wie in den Höhenlagen kurzfristig vor Ort. Rufen Sie an oder schreiben Sie per WhatsApp.` },
  ],
  sprockhoevel: [
    { text: `Sprockhövel (45549) liegt im Ennepe-Ruhr-Kreis auf dem hügeligen Übergang vom Ruhrgebiet ins Bergische, zwischen Hattingen und Schwelm. Die Stadt hat kein geschlossenes Zentrum, sondern verteilt sich auf Ortsteile in sehr unterschiedlicher Höhenlage: Haßlinghausen und Herzkamp oben auf den Höhen, Niedersprockhövel und Hiddinghausen deutlich tiefer. Die A43 quert das Gebiet mit einer eigenen Anschlussstelle und trifft südlich davon auf die A1. Dazwischen verlaufen schmale, kurvige Straßen mit Kuppen und alten Hohlwegen aus der Bergbauzeit — Sprockhövel gilt als eine der Wiegen des Ruhrbergbaus, und man sieht es dem Straßennetz bis heute an. Nach einem unverschuldeten Unfall zahlt die Haftpflicht des Verursachers Ihren eigenen Sachverständigen nach § 249 BGB.` },
    { vorort: true, text: `Die Sprockhöveler Ortsteile fahren sich jeweils anders. Haßlinghausen ist der Verwaltungs- und Versorgungsschwerpunkt mit dem meisten Alltagsverkehr und entsprechend vielen Rangier- und Abbiegeschäden. Niedersprockhövel und Obersprockhövel liegen getrennt davon, verbunden über Strecken, die mehr Landstraße als Ortsverbindung sind. Gennebreck und Herzkamp sind ländlich geprägt, mit Höfen, landwirtschaftlichem Verkehr und Feldzufahrten, die unvermittelt auf die Fahrbahn münden. Zwischen allem liegen Waldstücke und Wildwechselstrecken. Weil die Wege lang und die Werkstätten wenige sind, besichtigen wir bewusst dort, wo das Fahrzeug steht — auf dem Hof, in der Scheune oder am Straßenrand.` },
    { h3: 'Kuppen und Hohlwege: Warum sind Unterbodenschäden hier so häufig?', text: `Alte Wegeführungen folgen dem Gelände statt es auszugleichen. Das bedeutet kurze, harte Kuppen und Senken, an denen ein Fahrzeug mit normaler Bodenfreiheit durchaus aufsetzt — besonders beladen oder mit Anhänger. Die Schäden liegen dann dort, wo niemand hinsieht: an Unterfahrschutz, Auspuffanlage, Tankschutzblech und, bei Elektrofahrzeugen, am Batteriegehäuse. Letzteres ist der kritischste Fall überhaupt, weil eine Verformung des Gehäuses sicherheitsrelevant ist und der Austausch die Wirtschaftlichkeitsgrenze eines Fahrzeugs schnell überschreitet. Selbst wenn nichts sichtbar leckt oder klappert, gehört ein Aufsetzer deshalb auf die Hebebühne. Wir besichtigen Unterbodenschäden grundsätzlich von unten und dokumentieren Kontaktpunkte und Kratzrichtung — daraus lässt sich rekonstruieren, ob das Fahrzeug aufsetzte oder etwas dagegen geschleudert wurde.` },
    { h3: 'Wildunfall in der Dämmerung: Was muss dokumentiert werden?', text: `Auf den Verbindungsstrecken zwischen den Ortsteilen und an den Waldrändern ist Wildwechsel Alltag, besonders in den Stunden um Sonnenauf- und -untergang. Die Regulierung läuft über die Teilkasko, und die verlangt einen belastbaren Nachweis. Sichern Sie deshalb: Wildhaare, Blut- und Gewebereste am Fahrzeug, die Bescheinigung der Polizei oder des Jagdausübungsberechtigten sowie Fotos der Unfallstelle. Nicht waschen — das ist der häufigste und teuerste Fehler. Am Fahrzeug erkennt man einen Wildunfall an einer breitflächigen Eindellung mit Aufwärtsrichtung, meist an Frontschürze, Motorhaubenkante und Kotflügel; bei größerem Wild kommen Windschutzscheibe und Dachvorderkante hinzu. Wir sichern die Spuren fotografisch und weisen die Kosten teilkaskotauglich aus:`, liste: ['Fotografische Sicherung von Haaren, Blut und Gewebe vor der Wäsche', 'Eindellungsrichtung und Aufprallhöhe dokumentieren', 'Prüfung von Kühlerverbund und Frontsensorik', 'Unterboden auf Folgeschäden durch Überrollen', 'Kalkulation teilkaskotauglich aufgebaut', 'Gutachten binnen 48 Stunden'] },
    { h3: 'Motorrad- und Ausflugsverkehr am Wochenende: Was ändert das?', text: `Kurvige Strecken durch hügeliges Gelände ziehen an schönen Wochenenden Motorradfahrer und Ausflügler an. Für das Unfallgeschehen heißt das zweierlei: höhere Geschwindigkeiten in Kurven und mehr Beteiligte, die die Strecke nicht kennen. Bei einer Kollision zwischen Pkw und Motorrad ist der Sachschaden am Auto oft gering und die Haftungsfrage umso wichtiger — hier entscheiden Anstoßstelle, Anstoßwinkel und Kontakthöhe darüber, wer sich wie bewegt hat. Beim Pkw sind meist Kotflügel, Tür und Außenspiegel betroffen, häufig mit deutlichem Fremdlack- oder Gummiabrieb, der die Bewegungsrichtung verrät. Wir nehmen diese Merkmale auf, bevor sie durch Transport oder Reinigung verlorengehen, und beschreiben sie so, dass sie auch ein Gericht nachvollziehen kann.` },
    { h3: 'Wer entscheidet, wo repariert wird?', text: `Sie. Die gegnerische Versicherung darf Ihnen eine Werkstatt vorschlagen, aber nicht vorschreiben — die Wahl zwischen freiem Karosseriefachbetrieb und Markenwerkstatt liegt bei Ihnen, und das Gutachten ist die Grundlage, auf der abgerechnet wird. Gerade im ländlichen Raum spielt zusätzlich eine Rolle, wie weit das Fahrzeug transportiert werden muss und wer die Abschleppkosten trägt: Auch die gehören bei unverschuldetem Unfall zum Schadensersatz. Wollen Sie stattdessen fiktiv abrechnen und den Betrag ausgezahlt bekommen, geht auch das — dafür muss das Gutachten Reparaturkosten, Wertminderung und Restwert nur sauber voneinander trennen.` },
    { h3: 'Was kostet Sie das Gutachten?', text: `Bei unverschuldetem Unfall nichts. Das Sachverständigenhonorar ist Teil des Schadensersatzes nach § 249 BGB und wird von der Haftpflicht des Verursachers getragen — Sie treten den Anspruch ab, wir rechnen direkt mit der Versicherung ab. Anders liegt es, wenn Sie den Unfall selbst verursacht haben oder über die eigene Kasko regulieren; dann prüfen wir vorab, ob sich ein Gutachten überhaupt lohnt, und sagen Ihnen das offen. Bei geteilter Schuld wird das Honorar entsprechend der Haftungsquote aufgeteilt. Diese Frage klären wir immer vor der Beauftragung, nicht danach.` },
    { h3: 'Landwirtschaftlicher Verkehr und Feldzufahrten: Was ist dabei besonders?', text: `In Gennebreck und Herzkamp teilen sich Pkw und landwirtschaftliche Fahrzeuge dieselben schmalen Straßen. Daraus entstehen zwei wiederkehrende Konstellationen. Die erste: ein Traktor oder Anhänger biegt aus einer Feldzufahrt ein, die von der Fahrbahn aus schlecht einsehbar ist — der nachfolgende Verkehr erkennt das zu spät. Die zweite: Beim Überholen eines langsamen Gespanns wird dessen Länge unterschätzt. In beiden Fällen sind die Kontaktflächen ungewöhnlich, weil Landmaschinen harte, hochliegende Anbauteile ohne Knautschzone haben. Am Pkw führt das zu punktueller, tiefer Verformung statt flächiger Delle, oft mit Durchdringung bis in die Struktur dahinter. Solche Schäden lassen sich nicht nach Fläche kalkulieren; sie brauchen eine Beurteilung des Kraftverlaufs, und die setzt Demontage voraus.` },
    { text: `Kfz-Gutachter Sprockhövel — unabhängig, gerichtsfest, in Haßlinghausen, Niedersprockhövel und den Höhenlagen vor Ort. Ein Anruf oder eine WhatsApp genügt.` },
  ],
  remscheid: [
    { text: `Remscheid (42853) liegt auf den Höhen des Bergischen Landes zwischen Wupper und Ruhr, oberhalb von Wuppertal und Solingen. Die A1 quert das Stadtgebiet über die Müngstener Höhen und erschließt es mit den Anschlussstellen Remscheid und Remscheid-Lennep; im Norden liegt das Kreuz Wuppertal-Nord. Dazu kommen mit der B51, der B229 und der B237 gleich drei Bundesstraßen. An der Stadtgrenze zu Solingen überspannt die Müngstener Brücke, die höchste Eisenbahnbrücke Deutschlands, das Wuppertal; in ihrer Nähe liegt der Brückenpark. Nach einem unverschuldeten Unfall haben Sie Anspruch auf einen eigenen, neutralen Sachverständigen, dessen Honorar die Haftpflicht des Verursachers nach § 249 BGB trägt.` },
    { vorort: true, text: `Die Remscheider Stadtteile liegen weit auseinander und fahren sich verschieden. Alt-Remscheid ist der dicht bebaute Kern mit Einkaufs- und Berufsverkehr, engen Straßen und hohem Parkdruck. Lennep im Osten hat eine geschlossene historische Altstadt, in der Fahrzeugbreiten von heute schlicht nicht vorgesehen waren — hier passiert fast alles im Rangieren. Lüttringhausen im Nordosten ist wohn- und gewerbegeprägt, der Bezirk Süd zieht sich zu den Wupperhängen hinunter. Zwischen den Stadtteilen führen kurvenreiche Höhenstraßen, an den Rändern kommen Talsperren und Waldgebiete mit Ausflugsverkehr hinzu. Zur Besichtigung kommen wir in jeden Stadtteil.` },
    { h3: 'Ausflugsverkehr an den Talsperren und am Brückenpark: Was passiert dort?', text: `Rund um die Eschbachtalsperre — die erste Trinkwassertalsperre Deutschlands — und am Brückenpark unterhalb der Müngstener Brücke füllen sich an schönen Tagen schmale Zufahrten und begrenzte Parkflächen mit auswärtigen Fahrzeugen. Das erzeugt ein Schadensbild abseits der Fahrbahn: Anstöße beim Wenden auf zu engem Raum, Streifer an Böschungskanten, Pollern und Baumstämmen, Rempler beim Ausparken aus improvisierten Reihen. Diese Schäden liegen fast immer tief und seitlich, an Frontschürze, Radhausschale und Schwellerverkleidung. Von oben fotografiert sieht man sie kaum. Entscheidend ist, ob eine Verkleidung nur verkratzt oder ihre Befestigungspunkte ausgerissen sind — im ersten Fall genügt Aufbereitung, im zweiten ist es ein Neuteil. Wir sehen dafür grundsätzlich von unten nach.` },
    { h3: 'Parkrempler in der Lenneper Altstadt: Warum wird es dort so eng?', text: `Eine geschlossene Altstadt hat Straßenbreiten aus einer Zeit ohne Automobile und Stellplätze, die nachträglich hineingezwängt wurden. Das Ergebnis sind Manöver mit wenigen Zentimetern Spielraum, oft im Gefälle und mit schlechter Sicht über Schulter und Kamera. Typisch sind Anstöße an Hausecken, Pollern und Bordsteinen sowie Türöffnerschäden, weil zwischen parkendem und vorbeifahrendem Fahrzeug kaum Platz bleibt. Bei niedriger Geschwindigkeit verformt sich nichts spektakulär — es verschiebt sich. Stoßfängerecken lösen sich später aus der Kotflügelaufnahme, Türen sitzen nicht mehr bündig, Scharniere haben Spiel. Und bei Fahrzeugen mit Parksensorik reicht schon eine kleine Verschiebung, um die Kalibrierung unbrauchbar zu machen — eine Position, die in Kostenvoranschlägen fast immer fehlt:`, liste: ['Anbauteile auf Verschiebung in der Aufnahme prüfen', 'Spaltmaße rundum im Seitenvergleich', 'Türscharniere und Schließbleche auf Spiel', 'Kalibrierbedarf von Parksensorik und Kamera ausweisen', 'Lackschichtdickenmessung zur Abgrenzung von Altschäden', 'Gutachten binnen 48 Stunden'] },
    { h3: 'Warum sind Bremsen und Antrieb bei Remscheider Fahrzeugen ein eigenes Thema?', text: `Wer hier wohnt, fährt täglich lange Gefällestrecken. Bremsanlage, Kupplung und bei Elektrofahrzeugen die Rekuperation arbeiten dadurch messbar mehr als im Flachland. Für die Schadensregulierung ist das deshalb wichtig, weil die Versicherung nach einem Unfall zwischen Unfallfolge und Verschleiß unterscheidet — und genau an dieser Grenze kürzt. Ein Beispiel: Nach einem Frontanstoß ist eine verzogene Bremsscheibe schnell als „vorbestehend" abgetan. Ob sie es ist, lässt sich aber prüfen, über Dickenmessung, Laufbild und den Zustand der Gegenseite. Wir dokumentieren solche Bauteile deshalb ausdrücklich mit Befund statt sie pauschal ein- oder auszuschließen. Das ist gegenüber beiden Seiten redlich und hält im Streitfall.` },
    { h3: 'Was passiert bei einem Totalschaden an einem älteren Fahrzeug?', text: `Übersteigen die Reparaturkosten den Wiederbeschaffungswert, wird nicht automatisch abgerechnet und verschrottet. Es kommen mehrere Wege in Betracht: die Abrechnung auf Wiederbeschaffungsbasis abzüglich Restwert, die fiktive Abrechnung auf Gutachtenbasis oder — bis zu dreißig Prozent über dem Wiederbeschaffungswert und unter weiteren Voraussetzungen — die Reparatur nach der 130-Prozent-Regelung. Welcher Weg für Sie günstiger ist, hängt davon ab, ob Sie das Fahrzeug behalten wollen. Der Knackpunkt ist fast immer der Restwert: Legt die Versicherung ein Höchstgebot einer Restwertbörse vor, sinkt Ihre Auszahlung. Wir ermitteln ihn aus belastbaren regionalen Marktdaten und legen die Herkunft offen, damit sich die Zahl überprüfen lässt.` },
    { h3: 'Wie läuft die Besichtigung vor Ort ab?', text: `Wir kommen dorthin, wo das Fahrzeug steht — an den Unfallort, in die Werkstatt, vor die Wohnung. Vor Ort werden das gesamte Fahrzeug fotografiert, die Schadensstellen vermessen, die Lackschichtdicke geprüft und, wo nötig, Verkleidungen abgenommen. Wenn eine Achsvermessung oder ein Blick von unten erforderlich ist, organisieren wir eine Hebebühne. Anschließend erhalten Sie das Gutachten in der Regel binnen 48 Stunden, auf Wunsch zugleich für Ihre Kanzlei und die gegnerische Versicherung. Wichtig ist nur die Reihenfolge: erst die Besichtigung, dann die Reparatur — umgekehrt ist der Zustand nicht mehr feststellbar.` },
    { text: `Kfz-Gutachter Remscheid — unabhängig, gerichtsfest, in Alt-Remscheid, Lennep und Lüttringhausen vor Ort. Rufen Sie an oder schreiben Sie kurz per WhatsApp.` },
  ],
  ennepetal: [
    { text: `Ennepetal (58256) im Ennepe-Ruhr-Kreis entstand 1949 aus den bis dahin eigenständigen Gemeinden Milspe und Voerde und trägt den Namen des Flusses, dem es folgt. Die Stadt zieht sich langgestreckt durch das enge Tal der Ennepe: Milspe und Voerde liegen unten am Fluss, Rüggeberg und Königsfeld weit darüber auf den Hochflächen. Der Untergrund ist Massenkalk — daher die Kluterthöhle und die Steinbrüche, deren Schwerverkehr die Talstraßen mitbenutzt. Und Ennepetal liegt im Halbkreis dreier Talsperren: Heilenbecke, Hasper und Ennepe, wobei die Heilenbecketalsperre als älteste Talsperre Westfalens gilt. Nach einem unverschuldeten Unfall zahlt die Haftpflicht des Verursachers Ihren eigenen Sachverständigen nach § 249 BGB.` },
    { vorort: true, text: `Ennepetal ist eine Stadt mit zwei Ebenen. Unten im Tal liegen Milspe und Voerde als Versorgungs- und Gewerbeschwerpunkte; hier bündelt sich praktisch der gesamte Alltagsverkehr auf einer Achse, zusammen mit dem Schwerverkehr aus den Steinbrüchen. Entsprechend prägen Auffahr-, Abbiege- und Rangierschäden das Bild. Oben liegen Rüggeberg und Königsfeld, ländlich und weit auseinandergezogen, erreichbar nur über lange Steigungsstrecken mit engen Kurven. An den Rändern kommen die Zufahrten zu den Talsperren hinzu, die an Wochenenden Ausflugsverkehr auf schmale Straßen bringen. Wir kommen zur Besichtigung ins Tal wie auf die Höhen.` },
    { h3: 'Stop-and-Go durch das Ennepetal: Welche Schäden entstehen dabei?', text: `Wenn sich der gesamte Verkehr einer langgezogenen Stadt auf eine Talachse legt und dort zusätzlich Lieferfahrzeuge halten, entsteht dauerhaftes Stop-and-Go. Die typische Folge sind Auffahrunfälle bei geringer Geschwindigkeit — die Unfallart, bei der am meisten unterschätzt wird. Der Stoßfänger ist konstruktiv darauf ausgelegt, solche Anstöße wegzufedern und danach unbeschädigt auszusehen. Die Energie geht trotzdem irgendwohin: in den Querträger, die Crashboxen und bei stärkerem Anstoß in die Längsträger. Crashboxen sind Verformungselemente, die genau einmal funktionieren; sind sie gestaucht, müssen sie getauscht werden, auch wenn außen nichts zu sehen ist. Wir nehmen bei jedem Heckanstoß den Stoßfänger ab und beurteilen die Struktur dahinter statt die Hülle davor.` },
    { h3: 'Ausflugsverkehr zu Kluterthöhle und Talsperren: Wann wird es eng?', text: `Die Zufahrten zu Heilenbecke-, Hasper- und Ennepetalsperre sowie zur Kluterthöhle sind schmale Straßen, die für Anlieger gebaut wurden, nicht für Ausflugsspitzen. An schönen Wochenenden treffen dort ortsunkundige Fahrer, Wanderer, Radfahrende und parkende Fahrzeuge am Fahrbahnrand aufeinander. Die häufigsten Schäden entstehen im Begegnungsverkehr und beim Wenden: seitliche Streifer über mehrere Fahrzeugteile, Anstöße an Böschungskanten, aufgesetzte Frontschürzen an unbefestigten Rändern. Weil sich solche Fahrzeuge oft gegenseitig nur berühren, ohne dass jemand anhält, bleibt die Zuordnung schwierig. Kontakthöhe, Verlaufsrichtung des Kratzers und übertragener Fremdlack sind dann die einzigen belastbaren Anhaltspunkte — wir sichern sie, bevor sie durch Reinigung verlorengehen.` },
    { h3: 'Was fordert die tägliche Fahrt nach Rüggeberg oder Königsfeld vom Fahrzeug?', text: `Lange, gleichmäßige Steigungen und ebenso lange Gefällestrecken. Nach oben belastet das Antriebsstrang und Kühlung, nach unten dauerhaft die Bremsanlage. Für die Schadensbewertung ist vor allem die Bergabfahrt relevant, weil sie die Achslast nach vorn verlagert: Die Vorderachse ist stärker belastet, die Hinterachse entlastet, der Bremsweg länger. Ein Auffahrunfall im Gefälle trifft deshalb tiefer und mit mehr Restgeschwindigkeit als auf ebener Strecke. Diese Anstoßhöhe ist am Fahrzeug messbar und einer der wenigen objektiven Belege, wenn zwei Beteiligte den Hergang unterschiedlich schildern. Wir vermessen sie und halten sie im Gutachten fest — zusammen mit allem, was die Struktur dahinter betrifft:`, liste: ['Anstoßhöhe über Fahrbahn messen und dokumentieren', 'Crashboxen und Querträger nach Demontage beurteilen', 'Kühlerverbund auf Undichtigkeit prüfen', 'Bremsscheiben mit Befund statt Pauschalurteil bewerten', 'Unterboden nach Aufsetzern von unten besichtigen', 'Gutachten binnen 48 Stunden'] },
    { h3: 'Warum ein eigener Sachverständiger statt des Prüfers der Gegenseite?', text: `Weil beide einen unterschiedlichen Auftrag haben. Der Prüfer der gegnerischen Versicherung bewertet, ob die geforderte Summe angemessen ist — er sucht nicht danach, was zusätzlich beschädigt sein könnte. Ihr eigener Sachverständiger erhebt den Schaden vollständig, also auch Positionen, die niemand fordert, weil sie noch niemand kennt: gestauchte Crashboxen, verzogene Achsgeometrie, Kalibrierbedarf der Assistenzsysteme, merkantile Wertminderung. Genau diese Positionen machen erfahrungsgemäß den Unterschied. Dass Sie diesen eigenen Sachverständigen frei wählen dürfen, ist Ihr Recht — und bei unverschuldetem Unfall kostet es Sie nichts, weil das Honorar zum Schadensersatz gehört.` },
    { h3: 'Was sollten Sie bis zur Besichtigung unterlassen?', text: `Drei Dinge: waschen, reparieren und wegwerfen. Eine Wäsche entfernt Fremdlack, Gummiabrieb und bei Wildunfällen die biologischen Spuren — alles Material, das die Zuordnung trägt. Eine begonnene Reparatur macht den Vorzustand unfeststellbar, und damit sind Wertminderung und strittige Positionen kaum noch durchsetzbar. Abgefallene Teile wie Spiegelkappen, Zierleisten oder Kennzeichenhalter gehören in den Kofferraum, nicht in den Müll; sie belegen Anstoßrichtung und Kraft. Fotografieren Sie außerdem die Endstellung der Fahrzeuge, bevor Sie räumen. Alles Weitere klären wir am Telefon, bevor wir kommen.` },
    { h3: 'Wie wird der Wiederbeschaffungswert eines Fahrzeugs ermittelt?', text: `Nicht über eine Tabelle, sondern über den regionalen Markt: Maßgeblich ist, was Sie zahlen müssten, um ein gleichwertiges Fahrzeug in vergleichbarem Zustand bei einem seriösen Händler zu bekommen. Dafür zählen Alter, Laufleistung, Ausstattung, Vorschäden und Zustand — und eben die Preise, die im Umkreis tatsächlich aufgerufen werden. Diese Zahl entscheidet, ob überhaupt ein Totalschaden vorliegt, und sie ist deshalb die am häufigsten bestrittene Position im ganzen Gutachten. Wir leiten sie aus belastbaren Marktdaten ab und legen offen, welche Vergleichsfahrzeuge zugrunde liegen. Eine Zahl, deren Herkunft nachprüfbar ist, hält der Prüfung durch die Gegenseite stand; eine behauptete nicht.` },
    { text: `Kfz-Gutachter Ennepetal — unabhängig, gerichtsfest, in Milspe, Voerde und auf den Höhen vor Ort. Ein Anruf oder eine kurze WhatsApp genügt für die erste Einschätzung.` },
  ],
  hattingen: [
    { text: `Hattingen (45525) liegt im Ruhrtal am Südrand des Ruhrgebiets, genau dort, wo das Bergische Land beginnt. Zwischen der Ruhraue bei Welper und den Höhen der Elfringhauser Schweiz im Süden liegen rund zweihundert Höhenmeter — eine Spannweite, die man dem Straßennetz anmerkt. Durch das Stadtgebiet selbst führt keine Autobahn: Wer über die A43 kommt, verlässt sie an den Anschlussstellen Sprockhövel oder Witten-Herbede und fährt über Landstraßen weiter. Der übrige Verkehr verteilt sich auf die B51, die Ruhrtalachse Richtung Bochum und Witten sowie auf schmale, kurvige Höhenstraßen. Nach einem unverschuldeten Unfall haben Sie Anspruch auf einen eigenen Sachverständigen, bezahlt von der Haftpflicht des Verursachers nach § 249 BGB.` },
    { vorort: true, text: `Die Hattinger Stadtteile könnten unterschiedlicher kaum sein. Die Mitte mit ihrer geschlossenen Fachwerkaltstadt hat Straßenbreiten aus einer Zeit vor dem Automobil — hier ist fast jeder Schaden ein Rangierschaden. Welper und Blankenstein liegen an der Ruhr, wo Wohn-, Freizeit- und Durchgangsverkehr aufeinandertreffen, mit der Burg Blankenstein und dem Industriemuseum Henrichshütte als Besuchermagneten. Niederwenigern im Westen orientiert sich Richtung Essen, Bredenscheid und Holthausen im Süden gehen in die Höhen über: kurvig, schmal, mit Kuppen ohne Sicht. Wir kommen zur Besichtigung in jeden Stadtteil, von der Ruhraue bis auf die Höhen.` },
    { h3: 'Ohne Autobahn im Stadtgebiet: Wo bündelt sich der Hattinger Verkehr?', text: `Genau darin liegt die Besonderheit. Weil es keine Autobahn gibt, die den Durchgangsverkehr aufnimmt, läuft er über Bundes- und Landstraßen mitten durch bewohntes Gebiet. Diese Straßen tragen damit zwei unvereinbare Verkehrsarten gleichzeitig: zügigen Durchgangsverkehr und örtlichen Verkehr, der abbiegt, hält und in Grundstücke einfährt. Die Folge sind Auffahrunfälle hinter Linksabbiegern und seitliche Kollisionen beim Ausfahren aus Zufahrten — bei Geschwindigkeitsdifferenzen, die für Innerortsverhältnisse hoch sind. Am Fahrzeug betrifft das bei seitlichem Anstoß die B-Säule und die Türverstärkung, also Bereiche mit hochfesten Stählen, die sich nicht richten, sondern nur ersetzen lassen. Ohne Demontage ist das nicht zu beurteilen, und genau deshalb liegen Kostenvoranschläge hier so oft daneben.` },
    { h3: 'Straßenbahn bis Hattingen-Mitte: Was heißt das für Schäden im Mischverkehr?', text: `Die Bochumer Straßenbahnlinie 308 endet in Hattingen-Mitte, das heißt: Auf dem letzten Abschnitt teilen sich Bahn und Autoverkehr den Straßenraum. Für Unfälle hat das eigene Konsequenzen. Eine Straßenbahn kann nicht ausweichen und hat einen erheblich längeren Bremsweg als ein Pkw — das prägt sowohl den Hergang als auch die Haftungsbeurteilung. Kommt es zur Kollision, sind die Kräfte selbst bei niedriger Geschwindigkeit hoch, weil die Massen so ungleich sind. Am Pkw trifft es meist die gesamte Fahrzeugseite mit Verzug bis in Dach- und Bodenblech. Hinzu kommt: Beteiligt ist ein Verkehrsunternehmen mit eigener Schadensabteilung und eigenem Gutachter. Umso wichtiger ist ein Sachverständiger, der ausschließlich für Sie dokumentiert.` },
    { h3: 'Industrie- und Schwerlastverkehr im Ruhrtal: Wer haftet beim Streifschaden?', text: `Das Ruhrtal ist industriell geprägt, und wo Lkw auf schmalen Talstraßen unterwegs sind, entstehen Streifschäden mit typischem Muster: ein langer Kontakt in konstanter Höhe über mehrere Fahrzeugteile hinweg, oft mit Fremdlack oder Gummiabrieb. Ob Fahrer, Spedition oder Halterfirma einzustehen hat, entscheidet sich nicht am Schadensbild, wohl aber die Frage, wer sich wie bewegte — und die ist meist die strittige. Die Kontakthöhe verrät die Fahrzeugklasse des Verursachers, die Verlaufsrichtung des Kratzers die Relativbewegung. Am Pkw geht so ein Streifer über Türen und Seitenwand; da Seitenwände heute meist verschweißt statt verschraubt sind, ist der Instandsetzungsaufwand deutlich höher, als der Kratzer vermuten lässt:`, liste: ['Kontakthöhe über Fahrbahn exakt vermessen', 'Verlaufsrichtung und Fremdantragungen sichern', 'Prüfung, ob Seitenwand geschweißt oder verschraubt ist', 'B-Säule und Türverstärkung nach Demontage beurteilen', 'Reparaturweg begründet statt pauschal angesetzt', 'Gutachten binnen 48 Stunden'] },
    { h3: 'Anhänger, Wohnmobil und Fahrradträger: Was ist im Ausflugsverkehr zu beachten?', text: `Das Ruhrtal ist Ausflugsziel, und entsprechend viele Fahrzeuge sind hier mit Anhänger, Heckträger oder als Wohnmobil unterwegs. Für die Schadensaufnahme ändert das einiges. Bei einem Heckanstoß mit montiertem Fahrradträger läuft die Kraft konzentriert über die Anhängerkupplung in deren Aufnahme und von dort in den Längsträger — ein verzogener Kugelhals ist sicherheitsrelevant und muss geprüft werden, auch wenn der Träger selbst heil aussieht. Bei Anhängern und Wohnmobilen kommt hinzu, dass sie eigenständige Fahrzeuge mit eigener Bewertung sind: Reparaturkosten, Wertminderung und Wiederbeschaffungswert werden getrennt ermittelt. Wir nehmen Zugfahrzeug und Anhänger deshalb getrennt auf und weisen beides einzeln aus.` },
    { h3: 'Was hält der Sachverständige bei der Besichtigung fest?', text: `Den Zustand des Fahrzeugs, bevor ihn jemand verändert — das ist der Kern. Dazu gehören eine vollständige Fotodokumentation, die Vermessung der Schadensstellen mit Angabe der Anstoßhöhe, die Lackschichtdickenmessung zur Abgrenzung gegen Vorschäden und, wo nötig, die Demontage von Verkleidungen, um die Struktur dahinter beurteilen zu können. Erst darauf setzt die Kalkulation auf. Wichtig ist die Reihenfolge: erst besichtigen, dann reparieren. Wer vorher in die Werkstatt fährt, hat den Beweis verloren und muss mit dem auskommen, was auf der Rechnung steht — Wertminderung und strittige Positionen sind dann praktisch nicht mehr durchsetzbar.` },
    { text: `Kfz-Gutachter Hattingen — unabhängig, gerichtsfest, von der Ruhraue bis in die Höhenlagen vor Ort. Rufen Sie an oder schreiben Sie kurz per WhatsApp, dann klären wir das Weitere in wenigen Minuten.` },
  ],
}

export function seoBodyFor(slug: string): SeoAbsatz[] {
  return SEO_BODY[slug] ?? []
}

// Per-Stadt-metaHook (Lever 2): kurzer, unique lokaler Aufhaenger fuer die Meta-
// Description (seo.ts) statt des recycelten h1Sub -> killt near-duplicate-Snippets.
// Distilliert aus SEO_BODY, <=40 Z. Fehlt ein Slug -> Fallback auf city.h1Sub.
export const META_HOOKS: Record<string, string> = {
  wuppertal: 'Tallagen & dichter A46-Verkehr',
  solingen: 'Klingenstadt im Bergischen Land',
  velbert: 'Schloss-/Beschlägestadt an der A44',
  heiligenhaus: 'Niederberg-Lage bei Velbert',
  wuelfrath: 'Kalkstadt am Rand des Bergischen',
  mettmann: 'Kreisstadt im Neandertal, A3 & A44',
  haan: 'Pendlerort Mettmann/Solingen, A46',
  schwelm: 'Am Autobahnkreuz A1/A46',
  sprockhoevel: 'Landstraßen & Wildwechsel, Ennepe-Ruhr',
  remscheid: 'Werkzeugstadt, kurvenreiche Höhen',
  ennepetal: 'Kluterthöhle & enges Ennepetal',
  hattingen: 'Historische Altstadt im Ruhrtal',
}
