// ============================================================================
// CLUSTER-KONFIG · BONN (Rhein-Sieg)
// ============================================================================
// Re-Skin auf den Koeln-Endstand (08o-08q): Schema + Komponenten aus der
// Koeln-Vorlage, Inhalt/Farbe/Assets bleiben Bonn. Einzige Datei mit der
// Cluster-Identitaet. Theme-Farben: app/globals.css :root (Tinten-Schwarz +
// Antikgold). themeColor: layout.tsx. Bilder: public/assets/img/bonn/.
// ============================================================================

export interface City {
  slug: string
  name: string
  plz: string
  /** H1-Untertitel (SEO-Variation pro Stadt). */
  h1Sub: string
  /** Einwohner-Bezeichnung ("Bonner") fuer Reviews-Headline. */
  residents: string
  /** Stadt-Zentrum-Koordinaten (LocalBusiness-geo + Map-Pin). */
  lat: number
  lng: number
  /** Hauptstadt des Clusters (Hub). */
  main?: boolean
}

export interface Brennpunkt {
  name: string
  /** Pfad relativ zu CLUSTER.imgPath */
  img: string
  desc: string
}

export interface ClusterConfig {
  key: string
  region: string
  /** Region im Dativ ("im Rhein-Sieg-Kreis") fuer Ueber-uns-Copy. */
  regionDative: string
  /** Quellen-Anker fuer Brennpunkt-Statistik (Einsatzgebiet-Disclaimer). */
  quellenAnker: string
  /** Hauptachsen (FAQ-Q2, cluster-spezifisch). */
  achsen: string[]
  /** Stadtteile der Hauptstadt (FAQ-Lokal-Card). */
  stadtteile: string[]
  domain: string
  /** data-theme-Key (dokumentarisch — :root in globals.css traegt die Vars). */
  theme: string
  themeColor: string
  /** Basis-Pfad fuer cluster-spezifische Bilder. */
  imgPath: string
  /** Dateiendung der Logo-Varianten logo-{key}-dark/-white. */
  logoExt: 'png' | 'svg'
  /** 08m A6 · Cache-Busting: bei INHALTS-Tausch eines Assets (gleicher Dateiname) hochzaehlen. */
  assetVersion: string
  /** H1-Sub-Span im Hero (NUR Desktop lg:+). */
  h1SubSpan: string
  /** Team-Foto (Netzwerk-Mobile Team-Hero-Card). */
  teamImg: string
  /** Vorname des lokalen SV (CTA-Rolle + Ueber-uns). */
  svName: string
  /** Nachname des lokalen SV (Person-Schema / formale Nennung). */
  svSurname: string
  phone: {
    display: string
    /** National formatiertes CTA-Label — href/tel bleibt international. */
    displayNational: string
    tel: string
    wa: string
  }
  /** Wahrzeichen-Hero (Einsatzgebiet). */
  landmark: { label: string; img: string }
  /** Verkehrs-Hauptachsen + Vor-Ort-Zeit (Facts-Grid). */
  facts: { value: string; label: string; accent?: boolean }[]
  /** Verkehrsschwerpunkte (Hauptstadt-Level). */
  brennpunkte: Brennpunkt[]
  cities: City[]
}

export const CLUSTER: ClusterConfig = {
  key: 'bonn',
  region: 'Rhein-Sieg',
  regionDative: 'Rhein-Sieg-Kreis',
  quellenAnker: 'Polizei-Bonn-Verkehrsstatistik 2025',
  achsen: ['A565', 'A562', 'A59', 'B9', 'B56'],
  stadtteile: ['Bad Godesberg', 'Beuel', 'Hardtberg', 'Poppelsdorf', 'Bonn-Zentrum'],
  domain: 'kfz-unfallgutachter-bonn.de',
  theme: 'nacht', // Bonn: Tinten-Schwarz + Antikgold — globals.css :root traegt die Vars
  themeColor: '#0F1014',
  imgPath: '/assets/img/bonn/',
  logoExt: 'svg', // Bonn: logo-bonn-dark.svg vorhanden — TODO Aaron: logo-bonn-white.svg fehlt noch
  assetVersion: '1',
  h1SubSpan: 'Unabhängige Sachverständige. Gerichtsfeste Gutachten nach BVSK-Standard.',
  teamImg: '/assets/img/bonn/team-bonn.webp?v=1',
  svName: 'Tobias',
  svSurname: 'Becker', // Persona-Nachname (Tobias Becker)
  phone: { display: '+49 1515 3608515', displayNational: '0151 5360 8515', tel: '+4915153608515', wa: '4915153608515' },
  landmark: { label: 'Bonner Münster', img: 'stadt-bonn.png' },
  facts: [
    { value: 'A59', label: 'Hauptachse' },
    { value: 'A565', label: 'Hauptachse' },
    { value: 'A555', label: 'Hauptachse' },
    { value: '60 Min', label: 'vor Ort', accent: true },
  ],
  brennpunkte: [
    { name: 'Reuterstraße', img: 'bonn_reuterstrasse.webp', desc: 'Stark befahrene Innenstadtachse mit vielen Kreuzungen — erhöhtes Risiko für Auffahr- und Abbiegeunfälle.' },
    { name: 'Hochkreuzallee', img: 'bonn_hochkreuzallee.webp', desc: 'Vielspurige Hauptverkehrsstraße im Süden — dichter Berufsverkehr und häufige Spurwechsel.' },
    { name: 'Hermannstraße', img: 'bonn_hermannstrasse.webp', desc: 'Belebte Straße mit Rad- und Lieferverkehr — typische Park- und Abbiegekollisionen.' },
  ],
  cities: [
    { slug: 'bonn',           name: 'Bonn',           plz: '53111', main: true, h1Sub: 'unabhängiger Sachverständiger',          residents: 'Bonner',            lat: 50.7374, lng: 7.0982 },
    { slug: 'sankt-augustin', name: 'Sankt Augustin', plz: '53757',             h1Sub: 'Kfz-Sachverständiger Rhein-Sieg',          residents: 'Sankt Augustiner',  lat: 50.7700, lng: 7.1870 },
    { slug: 'siegburg',       name: 'Siegburg',       plz: '53721',             h1Sub: 'Kfz-Sachverständiger Rhein-Sieg',          residents: 'Siegburger',        lat: 50.7959, lng: 7.2070 },
    { slug: 'troisdorf',      name: 'Troisdorf',      plz: '53840',             h1Sub: 'unabhängiger Unfallgutachter',             residents: 'Troisdorfer',       lat: 50.8160, lng: 7.1560 },
    { slug: 'koenigswinter',  name: 'Königswinter',   plz: '53639',             h1Sub: 'Kfz-Sachverständiger Siebengebirge',       residents: 'Königswinterer',    lat: 50.6840, lng: 7.1880 },
    { slug: 'bad-honnef',     name: 'Bad Honnef',     plz: '53604',             h1Sub: 'Kfz-Sachverständiger Siebengebirge',       residents: 'Bad Honnefer',      lat: 50.6450, lng: 7.2270 },
    { slug: 'hennef',         name: 'Hennef',         plz: '53773',             h1Sub: 'Kfz-Sachverständiger Rhein-Sieg',          residents: 'Hennefer',          lat: 50.7730, lng: 7.2830 },
    { slug: 'bornheim',       name: 'Bornheim',       plz: '53332',             h1Sub: 'unabhängiger Schadengutachter',            residents: 'Bornheimer',        lat: 50.7600, lng: 6.9900 },
    { slug: 'rheinbach',      name: 'Rheinbach',      plz: '53359',             h1Sub: 'Kfz-Sachverständiger Voreifel',            residents: 'Rheinbacher',       lat: 50.6258, lng: 6.9490 },
    { slug: 'meckenheim',     name: 'Meckenheim',     plz: '53340',             h1Sub: 'Kfz-Sachverständiger Voreifel',            residents: 'Meckenheimer',      lat: 50.6256, lng: 7.0289 },
  ],
}

/** Hauptstadt (Hub-Page /). */
export const MAIN_CITY: City = CLUSTER.cities.find((c) => c.main) ?? CLUSTER.cities[0]

/** Alle Slugs. */
export const CITY_SLUGS: string[] = CLUSTER.cities.map((c) => c.slug)

/** Spoke-Slugs (alle ausser Hauptstadt) — generateStaticParams. */
export const SPOKE_SLUGS: string[] = CLUSTER.cities.filter((c) => !c.main).map((c) => c.slug)

/** Routing-Pfad einer Stadt (Hauptstadt → "/"). */
export function cityHref(city: City): string {
  return city.main ? '/' : `/lp/${city.slug}`
}

/** Stadt per Slug (oder undefined → 404). */
export function getCity(slug: string): City | undefined {
  return CLUSTER.cities.find((c) => c.slug === slug)
}

/** Vorausgefuellter WhatsApp-Text pro Stadt. */
export function waText(city: City): string {
  return `Hallo, ich hatte einen Unfall in ${city.name} und brauche einen Gutachter.`
}

/** Vollstaendiger wa.me-Link mit vorausgefuelltem Text. */
export function waHref(city: City): string {
  return `https://wa.me/${CLUSTER.phone.wa}?text=${encodeURIComponent(waText(city))}`
}

/** Komma-Liste aller Staedte (Servicegebiet-Text / areaServed). */
export function cityNamesList(): string {
  const names = CLUSTER.cities.map((c) => c.name)
  return names.slice(0, -1).join(', ') + ' und ' + names[names.length - 1]
}

// ── SEO-Body (08o O6: strukturierte Absaetze statt Fliesstext) ───────────────
// `vorort: true` markiert den Absatz, der in der Einsatzgebiet-Lokalstrecke
// rendert (lib/seoVorOrt); `liste` rendert als kompakte Leistungs-Liste.
//
// AUSBAU 24.08.2026 — WARUM: Die 10 LP-Seiten dieser Domain glichen einander zu
// 72,8 % (4-Gramm-Jaccard, Siegburg<->Hennef, Ortsnamen entfernt); die Spec des
// Programms setzt die Grenze bei 40 %. Ursache war nicht die Technik, sondern
// die Masse: der ortsspezifische Anteil betrug ~80 Woerter je Stadt, alles
// uebrige auf der Seite ist Template. Bei Near-Duplicates indexiert Google nur
// einen Repraesentanten. Die Schwesterdomain Koeln liegt mit 282-396 Woertern
// bei 36 % — gemessener Zusammenhang: +240 Woerter ≈ -13 Prozentpunkte.
//
// Jede Stadt traegt jetzt >= 350 Woerter mit je 4 EIGENEN h3-Fragen. Die h3s
// sind editorial an ihren Absatz gebunden und je Stadt verschieden formuliert
// (10x dieselbe Frage waere wieder Template). Auch die `liste` ist je Stadt
// anders geschnitten — eine cluster-weite Konstante waere 10x identische Masse.
//
// ⚠ NICHT WIEDERHOLEN: Unterhalb dieses Blocks rendert LokalinhaltSection die
// Ortstiefe aus `stadt_lokalinhalte` (Stadtbezirke, Verkehrsachsen, Unfall-
// schwerpunkte, lokale FAQs) — fuer alle 10 Staedte veroeffentlicht. Dieser
// Text ERGAENZT: Fahrverhalten, typische Schadensbilder, Begutachtung,
// Regulierung. Die h3-Fragen sind gegen die dort vorhandenen FAQ-Fragen
// abgeglichen, damit nicht dieselbe Frage zweimal auf einer Seite steht.
//
// ⚠ Der erste Satz des ersten h3-Absatzes wird von SeoBodySection als
// Pull-Quote gerendert (>= 40 Zeichen noetig) — er ist je Stadt eigen.
//
// Keine erfundenen Zahlen, Strassen, Knoten oder Ortsteile: Lokalfakten stammen
// aus dem quellen-gegateten `stadt_lokalinhalte`-Bestand bzw. sind einzeln
// belegt (Faehre Koenigswinter-Mehlem, Sportschule Hennef, Glasfachschule NRW +
// H-BRS Campus Rheinbach, Industriepark Kottenforst am Voreifelbahn-Halt, HUMA
// + Schloss Birlinghoven, Wahner Heide, Bornheimer Spargel/Linie 18).
// Rechtsnorm ausschliesslich § 249 BGB.
export interface SeoAbsatz {
  /** Editorial gebundene Zwischenueberschrift. */
  h3?: string
  text: string
  /** Kompakte Leistungs-Liste nach dem Text. */
  liste?: string[]
  /** Rendert in der Einsatzgebiet-Lokalstrecke ("Vor Ort"), nicht im SeoBody. */
  vorort?: boolean
}

export const SEO_BODY: Record<string, SeoAbsatz[]> = {
  bonn: [
    { text: `Bonn fährt anders als andere Großstädte. Die A565 zieht als Stadtautobahn mitten hindurch, die B9 folgt dem Rhein nach Süden, und dazwischen mischen sich Behörden- und Pendlerfahrten, Lieferverkehr und viel Rad- und Fußverkehr rund um Universität und Innenstadt. Wer hier unverschuldet in einen Unfall gerät, hat es selten mit einem eindeutigen Schadensbild zu tun. Ein unabhängiger Kfz-Gutachter Bonn nimmt den Schaden dort auf, wo Ihr Fahrzeug steht, und dokumentiert ihn so, dass er später nicht auslegbar ist. Das Honorar trägt bei unverschuldetem Unfall die gegnerische Haftpflicht — für Sie 0 € nach § 249 BGB.` },
    { vorort: true, text: `Die vier Bonner Stadtbezirke bringen jeweils eigene Schadensbilder hervor. In der Innenstadt und rund um Poppelsdorf und Endenich prägen enge Straßenräume, ausparkende Fahrzeuge und Radverkehr das Bild — Streifschäden an Türen und Kotflügeln, abgerissene Spiegel, Tür-Öffner-Kollisionen. In Bad Godesberg mit Plittersdorf, Rüngsdorf und Mehlem kommen Villenstraßen mit unübersichtlichen Einmündungen und Besucherverkehr dazu. Beuel, Küdinghoven und Holzlar sind rechtsrheinisch Wohn- und Durchgangslagen, deren Berufsverkehr sich über die Rheinbrücken schiebt. Auf dem Hardtberg mit Duisdorf, Lengsdorf und Brüser Berg sind es die Zubringer zur A565, an denen im Berufsverkehr aufgefahren wird.` },
    { h3: 'Was macht ein Gutachten gerichtsfest?', text: `Nicht sein Umfang, sondern die Nachprüfbarkeit jeder einzelnen Position. Wir arbeiten nach BVSK-Standard und halten fest, was ein Dritter später nachvollziehen können muss:`, liste: ['Lackschichtmessung an allen betroffenen Bauteilen', 'Prüfung auf Struktur- und Rahmenschäden', 'Foto- und Maßdokumentation der Anstoßstelle', 'Reparaturkosten in marktüblicher Kalkulation', 'Merkantiler Minderwert bei jüngeren Fahrzeugen', 'Gutachten im Regelfall binnen 48 Stunden'] },
    { h3: 'Dienstwagen, Leasing, Firmenfahrzeug — wer meldet den Schaden?', text: `Rund um das ehemalige Regierungsviertel, den UN-Campus und die Bundesbehörden gehört ein großer Teil der Fahrzeuge nicht der Person am Steuer. Bei Leasing ist der Leasinggeber Eigentümer, und viele Verträge verlangen eine Reparatur nach Herstellervorgabe — beides beeinflusst, was abgerechnet werden darf. Wir dokumentieren so, dass Leasinggeber, Arbeitgeber und gegnerische Haftpflicht mit demselben Papier arbeiten, statt dass Sie zwischen drei Stellen vermitteln.` },
    { h3: 'Auto gegen Fahrrad: Warum der Hergang so oft strittig bleibt', text: `In der Bonner Innenstadt und auf den Zufahrten zur Universität treffen Autos, Räder und Fußgänger auf engem Raum aufeinander, und Zeugen sind selten greifbar. Bleibt der Hergang strittig, entscheidet die Spur am Fahrzeug: Anstoßhöhe, Lackantrag, Verformungsrichtung und das Beschädigungsbild an Spiegel, Tür oder Kotflügel lassen sich einem Ablauf zuordnen. Deshalb zählt die frühe Aufnahme — nach der Reparatur ist diese Spur weg, und es bleibt Aussage gegen Aussage.` },
    { h3: 'Die Versicherung kürzt — was können Sie tun?', text: `Kürzungen kommen selten als Ablehnung, sondern als Prüfbericht mit niedrigeren Stundensätzen, gestrichener Wertminderung oder abgezogenen Verbringungskosten. Hinnehmen müssen Sie das nicht: Nach einem unverschuldeten Unfall haben Sie Anspruch auf einen eigenen Sachverständigen, und wir begründen strittige Positionen einzeln nach. Über das Claimondo-Netzwerk vermitteln wir auf Wunsch einen Verkehrsrechtsanwalt, dessen Kosten die gegnerische Versicherung ebenfalls trägt.` },
    { h3: 'Was zählt in den ersten Minuten nach dem Unfall?', text: `Auf einer Stadtautobahn wie der A565 zuerst die Absicherung: Warnblinker, Weste, Warndreieck, Personen hinter die Schutzplanke. Danach die Feststellungen, die später niemand mehr nachholen kann — Kennzeichen und Versicherungsdaten des Gegners, Fotos aus mehreren Abständen, die Endstellung der Fahrzeuge vor dem Räumen und Namen möglicher Zeugen. Ein Schuldanerkenntnis unterschreiben Sie nicht; die Haftung beurteilt sich nach dem Hergang, nicht nach einer Unterschrift am Straßenrand. Ist die Lage unklar oder jemand verletzt, rufen Sie die Polizei. Alles Weitere — Gutachter, Anwalt, Werkstatt, Mietwagen — lässt sich danach in Ruhe organisieren.` },
    { h3: 'Airbag ausgelöst, Gurtstraffer gezogen — was bedeutet das für die Kalkulation?', text: `Sobald das Rückhaltesystem ausgelöst hat, verlässt der Schaden die Größenordnung, die man dem Blech ansieht. Airbagmodule, Gurtstraffer und die zugehörigen Steuergeräte sind pyrotechnische Einwegbauteile: Sie lassen sich nicht zurücksetzen, sondern nur ersetzen. Betroffen sind je nach Auslösung Lenkrad, Armaturenträger, Dachhimmel, Sitzverkleidungen und die Gurte selbst, dazu die Verkabelung und ein Crash-Eintrag im Steuergerät, der ausgelesen und dokumentiert gehört. Auf einer Strecke wie der A565 mit dichtem Berufsverkehr ist genau das der Fall, der von außen nach Frontschaden aussieht und in der Kalkulation ein Vielfaches erreicht. Wir erfassen die ausgelösten Komponenten einzeln, weil eine pauschale Position hier regelmäßig gekürzt wird — und weil ein Fahrzeug mit unvollständig instandgesetztem Rückhaltesystem beim Weiterverkauf ein Problem bleibt.` },
    { h3: 'Fast neues Auto beschädigt — gibt es mehr als den Zeitwert?', text: `Unter Umständen ja. Bei sehr jungen Fahrzeugen mit geringer Laufleistung kommt im Totalschadenfall statt des Wiederbeschaffungswerts eine Abrechnung auf Neupreisbasis in Betracht, wenn der Schaden erheblich ist und tatsächlich ein Neufahrzeug angeschafft wird. Die Voraussetzungen sind eng und werden von Versicherungen selten von sich aus angeboten. Entscheidend ist deshalb, dass das Gutachten Erstzulassung, Laufleistung, Schadenumfang und den Eingriff in tragende Teile sauber ausweist — daran hängt, ob diese Tür offensteht. Auch unterhalb der Totalschadenschwelle gilt für junge Fahrzeuge: Der merkantile Minderwert fällt hier am höchsten aus, weil ein Unfallschaden bei einem Zweijährigen den Marktwert stärker drückt als bei einem Zehnjährigen. In Bonn mit seinem hohen Anteil an Dienst- und Leasingfahrzeugen ist das ein häufiger Fall.` },
    { text: `Kfz-Gutachter Bonn — unabhängig, gerichtsfest, schnell vor Ort. Ein Anruf oder eine Nachricht über WhatsApp genügt, und wir klären in wenigen Minuten, ob ein Gutachten sinnvoll ist und wie es weitergeht.` },
  ],
  'sankt-augustin': [
    { text: `Sankt Augustin liegt zwischen Bonn und Siegburg und ist für seine Größe ungewöhnlich stark erschlossen: A59 und A560 treffen im Westen aufeinander, die B56 führt mitten hindurch. Dazu kommen Ziele, die den ganzen Tag über Verkehr erzeugen — der HUMA Einkaufspark, der Campus der Hochschule Bonn-Rhein-Sieg, die Fraunhofer-Institute auf Schloss Birlinghoven und der Flugplatz Hangelar. Wer hier unverschuldet in einen Unfall gerät, sollte den Schaden nicht von der Gegenseite bewerten lassen. Ein unabhängiger Kfz-Sachverständiger Sankt Augustin kommt zu Ihnen, nimmt das Schadensbild neutral auf und rechnet das Honorar mit der gegnerischen Haftpflicht ab — 0 € für Sie nach § 249 BGB.` },
    { vorort: true, text: `Die Stadtteile unterscheiden sich deutlich. In Mülldorf, Ort und Menden bündelt sich der Einkaufs- und Verwaltungsverkehr: viel Parksuchverkehr, viele Rangiervorgänge, entsprechend Streif- und Rempelschäden auf engem Raum. Hangelar und Meindorf im Norden liegen an den Siegauen, wo Landstraßen und Wohnstraßen ineinander übergehen und in der Dämmerung mit Wild zu rechnen ist. Niederpleis, Birlinghoven und Buisdorf im Osten steigen zum Pleistal hin an — dort sind es Kurven, Gefällstrecken und unübersichtliche Einmündungen, an denen es typischerweise kracht.` },
    { h3: 'Woran erkennen Sie, dass ein Gutachten vollständig ist?', text: `Daran, dass es auch die Positionen benennt, die niemand freiwillig bezahlt. Wir arbeiten nach BVSK-Standard und führen jede davon einzeln auf:`, liste: ['Schadenaufnahme mit Fotostrecke und Maßangaben', 'Lackschichtmessung und Prüfung auf Vorschäden', 'Verdeckte Schäden hinter Stoßfänger und Verkleidung', 'Reparaturweg mit marktüblichen Stundensätzen', 'Wertminderung und Wiederbeschaffungsdauer', 'Gutachten im Regelfall binnen 48 Stunden'] },
    { h3: 'Parkschaden am Einkaufszentrum — und niemand hat gewartet?', text: `Auf großen Parkflächen wie am HUMA passiert genau das regelmäßig. Bleibt der Verursacher unbekannt, greift Ihre Vollkasko, in engen Grenzen kommt auch die Verkehrsopferhilfe in Betracht. Beide Wege verlangen eine saubere Dokumentation: Anstoßhöhe, Lackantrag in Fremdfarbe, Kratzverlauf und Stellung des Fahrzeugs. Wir nehmen den Schaden so auf, dass Ihnen diese Wege offenbleiben — und dass die eigene Versicherung ihn nicht als Altschaden abtut.` },
    { h3: 'Lohnt die Reparatur bei einem älteren Fahrzeug überhaupt noch?', text: `In einer Hochschulstadt sind viele Fahrzeuge ältere Gebrauchte, bei denen die Reparaturkosten schnell in die Nähe des Wiederbeschaffungswerts rücken. Dann entscheidet sich, ob fiktiv auf Gutachtenbasis abgerechnet wird, ob die 130-Prozent-Regelung greift oder ob der Wiederbeschaffungswert ausgezahlt wird. Diese Weiche stellt das Gutachten, nicht die Versicherung — deshalb muss der Restwert auf belastbaren Marktdaten stehen und nicht auf einem beliebigen Aufkäuferangebot.` },
    { h3: 'Und was kostet Sie das?', text: `Bei unverschuldetem Unfall nichts. Das Sachverständigenhonorar gehört zum erstattungsfähigen Schaden und wird direkt mit der gegnerischen Haftpflicht abgerechnet, ebenso Anwalt und Mietwagen. Nur bei eigener Schuld oder einem reinen Kaskofall gelten andere Regeln — auch das sagen wir Ihnen vorher und nicht hinterher.` },
    { h3: 'Hat beim Auffahrunfall wirklich immer der Hintermann schuld?', text: `Im Berufsverkehr auf A59, A560 und B56 ist der Auffahrunfall der Klassiker, und meist trägt tatsächlich der Auffahrende die Hauptlast — es gilt der Anscheinsbeweis, dass er zu dicht war oder unaufmerksam. Dieser Anschein lässt sich aber erschüttern: bei grundlosem starken Bremsen, bei einem Spurwechsel kurz vor dem Aufprall, bei defekter Beleuchtung des Vordermanns oder wenn ein dritter Wagen aufgeschoben hat. Ob das im Einzelfall trägt, entscheidet sich am Schadensbild — Aufprallhöhe, Verformungstiefe und Eindruckrichtung zeigen, in welcher Konstellation die Fahrzeuge standen. Deshalb lohnt die technische Aufnahme auch dann, wenn die Schuldfrage scheinbar feststeht.` },
    { h3: 'Fahrradträger, Dachbox, Ladung — wird der Zubehörschaden mitersetzt?', text: `Ja, soweit er unfallbedingt ist und nachgewiesen wird. Zum ersatzfähigen Schaden gehört nicht nur das Fahrzeug, sondern auch das, was daran oder darin beschädigt wurde: Heckträger samt Rädern, Dachbox mitsamt Inhalt, Kindersitze, Ladung. Bei Kindersitzen ist der Austausch nach einem Aufprall der Regelfall, weil das Gurtband und die Schale unsichtbar überdehnt sein können — kein Sichtbefund, sondern eine Herstellervorgabe. Der praktische Fehler passiert früh: Solche Teile werden am Unfallort abgenommen, verstaut und später vergessen, und dann fehlt der Beleg für ihren Zustand. Wir nehmen sie ausdrücklich mit ins Gutachten auf, mit Foto und Zuordnung zum Anstoß. Rund um Campus und Freizeitverkehr ist das häufiger relevant, als es klingt.` },
    { h3: 'Was kostet mich ein Kaskofall auf lange Sicht?', text: `Mehr als die Selbstbeteiligung. Wer die eigene Kasko in Anspruch nimmt, wird im Schadenfreiheitsrabatt zurückgestuft, und diese Rückstufung wirkt über Jahre nach — bei kleineren Schäden übersteigt der Mehrbeitrag die Erstattung mitunter. Ob sich die Inanspruchnahme lohnt, lässt sich erst beurteilen, wenn die Schadenhöhe belastbar feststeht; genau dafür ist das Gutachten da, auch wenn keine Gegenseite existiert. Ist der Unfall dagegen fremdverschuldet, stellt sich die Frage gar nicht: Dann läuft alles über die Haftpflicht des Verursachers, Ihr Rabatt bleibt unberührt. Bei ungeklärter Haftung ist die Reihenfolge deshalb wichtig — erst den Schaden feststellen und die Haftungslage klären, dann entscheiden, welche Versicherung überhaupt in Anspruch genommen wird.` },
    { text: `Kfz-Sachverständiger Sankt Augustin — neutral, gerichtsfest, kurzfristig vor Ort. Rufen Sie an oder schreiben Sie über WhatsApp; die erste Einschätzung dauert wenige Minuten und kostet nichts.` },
  ],
  siegburg: [
    { text: `Siegburg ist Kreisstadt des Rhein-Sieg-Kreises und trägt entsprechend viel Verkehr, der gar nicht aus Siegburg kommt: Behördenwege, Einkaufsfahrten in die Innenstadt, Zubringerverkehr zum ICE-Halt und den Durchgangsverkehr auf B56 und B484. Dazu eine gewachsene Altstadt am Fuß des Michaelsbergs, in der die Straßen enger sind als die Fahrzeuge, die heute darin unterwegs sind. Passiert Ihnen dort ein fremdverschuldeter Unfall, sichert ein unabhängiger Kfz-Gutachter Siegburg das Schadensbild, bevor es sich verändert. Das Honorar trägt die gegnerische Haftpflicht — 0 € für Sie nach § 249 BGB.` },
    { vorort: true, text: `Innerhalb Siegburgs ändert sich das Schadensbild von Viertel zu Viertel. In der Innenstadt rund um Marktplatz und Mühlenstraße dominieren Rangier- und Parkschäden: Lieferfahrzeuge in zweiter Reihe, kurze Sichtachsen, viele Fußgänger. Wolsdorf, Zange und Brückberg im Norden sind Wohnlagen mit Pendlerverkehr Richtung Autobahn. Kaldauen, Braschoß und Seligenthal im Osten liegen bereits am Anstieg ins Bergische — dort sind Landstraßen mit Gefälle, engen Kurven und nasser Fahrbahn das Thema. Stallberg und Deichhaus im Süden verbinden beide Welten miteinander.` },
    { h3: 'Was Ihr Gutachten leisten muss', text: `Es muss den Schaden so festhalten, dass er auch nach der Reparatur noch beweisbar ist. Was dafür nötig ist, dokumentieren wir nach BVSK-Standard:`, liste: ['Fotodokumentation aus definierten Perspektiven', 'Lackschichtmessung und Abgrenzung von Altschäden', 'Prüfung tragender Teile auf Verzug', 'Reparaturkalkulation zu ortsüblichen Sätzen', 'Merkantiler Minderwert und Restwert', 'Gutachten im Regelfall binnen 48 Stunden'] },
    { h3: 'Beide haben etwas falsch gemacht — was heißt das für die Auszahlung?', text: `An Kreuzungen und beim Einfahren aus Grundstückszufahrten endet es oft nicht mit einem eindeutigen Schuldigen, sondern mit einer Quote. Die Haftung wird dann geteilt, etwa siebzig zu dreißig, und Sie bekommen Ihren Schaden anteilig ersetzt — auch das Gutachterhonorar nur in dieser Höhe. Genau deshalb lohnt es sich, die Quote nicht der Gegenseite zu überlassen: Sie ergibt sich aus dem Hergang, und der lässt sich technisch belegen statt verhandeln. Wo Anstoßhöhe, Kontaktverlauf und Endstellung dokumentiert sind, verschiebt sich eine Quote erfahrungsgemäß zu Ihren Gunsten.` },
    { h3: 'Mietwagen oder Nutzungsausfall?', text: `Solange Ihr Fahrzeug repariert wird, haben Sie die Wahl: ein gleichwertiger Mietwagen auf Kosten der Gegenseite oder eine Nutzungsausfallentschädigung, wenn Sie ohne Ersatzfahrzeug auskommen. Welche Variante für Sie günstiger ist, hängt von Fahrzeugklasse und Ausfalldauer ab — und beides steht im Gutachten. Wir beziffern Reparatur- und Wiederbeschaffungsdauer deshalb konkret, weil genau daran Ihr Anspruch hängt.` },
    { h3: 'Wer bestimmt die Werkstatt?', text: `Sie. Nach der Rechtsprechung des Bundesgerichtshofs dürfen Sie eine qualifizierte Werkstatt Ihrer Wahl beauftragen, freien Fachbetrieb ebenso wie Markenwerkstatt. Verweist die Versicherung auf einen günstigeren Partnerbetrieb, ist das ein Vorschlag und keine Vorgabe. Auf Wunsch vermitteln wir einen Betrieb aus dem Claimondo-Netzwerk, der auf Basis des Gutachtens abrechnet.` },
    { h3: 'Reparieren lassen oder das Geld nehmen?', text: `Beides ist möglich. Bei der konkreten Abrechnung lassen Sie reparieren und die Werkstattrechnung wird bezahlt, inklusive Mehrwertsteuer. Bei der fiktiven Abrechnung lassen Sie sich den im Gutachten ermittelten Netto-Reparaturbetrag auszahlen und entscheiden selbst, ob, wann und wie Sie reparieren — die Mehrwertsteuer bleibt dann außen vor, und die Versicherung versucht häufiger, über günstigere Stundensätze zu kürzen. Für ältere Fahrzeuge, bei denen sich eine vollständige Instandsetzung nicht mehr lohnt, ist die fiktive Variante oft die sinnvollere. Sie brauchen dafür allerdings ein Gutachten, das den Reparaturweg vollständig ausweist — sonst fehlt später die Grundlage für genau die Positionen, die gestrichen werden.` },
    { h3: 'Darf ich mit dem beschädigten Auto weiterfahren?', text: `Nur wenn es verkehrssicher ist — und das ist eine technische Frage, keine Ermessensfrage. Kritisch sind beschädigte Beleuchtung, eingeschränkte Sicht, lose Anbauteile, austretende Betriebsstoffe, Schäden an Lenkung, Bremse oder Rädern sowie eine Tür oder Haube, die nicht sicher schließt. Wer trotz erkennbarem Mangel weiterfährt, riskiert nicht nur ein Bußgeld, sondern auch den Vorwurf, den Schaden vergrößert zu haben — und dieser Teil wird dann nicht ersetzt. Umgekehrt gilt die Schadenminderungspflicht auch in die andere Richtung: Ein fahrbereites Fahrzeug ohne Not stillzulegen und stattdessen wochenlang einen Mietwagen zu nehmen, ist ebenfalls angreifbar. Der Sachverständige beurteilt die Verkehrssicherheit ausdrücklich und hält fest, ob und unter welchen Einschränkungen das Fahrzeug bewegt werden darf.` },
    { h3: 'Und wenn ich das Gutachten selbst zahlen muss?', text: `Dann richtet sich das Honorar nach der Höhe des ermittelten Schadens, nicht nach dem Zeitaufwand — das ist in der Branche üblich und orientiert sich an den Honorarbefragungen des BVSK. Der Gedanke dahinter: Ein größerer Schaden bedeutet mehr Prüfumfang und mehr Haftung für den Sachverständigen. Dazu kommen Nebenkosten für Fotodokumentation, Fahrt und Ausfertigungen, die getrennt ausgewiesen werden. Bei sehr kleinen Schäden lohnt statt eines vollen Gutachtens oft ein Kurzbericht oder ein Kostenvoranschlag; welche Form sinnvoll ist, sagen wir Ihnen vor der Beauftragung und nicht danach. Bei unverschuldetem Unfall ist die Frage ohnehin hinfällig, weil das Honorar zum ersatzfähigen Schaden gehört — dann zahlt die Gegenseite, unabhängig davon, wie hoch der Schaden am Ende ausfällt.` },
    { text: `Kfz-Gutachter Siegburg — unabhängig, gerichtsfest, schnell vor Ort. Melden Sie sich telefonisch oder über WhatsApp, dann klären wir das weitere Vorgehen in wenigen Minuten.` },
  ],
  troisdorf: [
    { text: `Troisdorf ist die einwohnerstärkste Stadt des Rhein-Sieg-Kreises und zugleich eine der grünsten: Große Teile des Stadtgebiets liegen in der Wahner Heide. Zwischen diesen Rändern liegt ein dicht bebauter Kern mit gewachsenen Gewerbe- und Industrieflächen, drei Bahnhalten und entsprechend viel Berufs- und Lieferverkehr. Diese Mischung erzeugt Schäden, die selten eindeutig sind — Lkw gegen Pkw, Rangieren auf Betriebshöfen, Auffahrunfälle im gestauten Berufsverkehr. Ein unabhängiger Kfz-Sachverständiger Troisdorf nimmt sie vor Ort auf, neutral und unabhängig von der Versicherung der Gegenseite. Für Sie 0 € nach § 249 BGB.` },
    { vorort: true, text: `Die drei Stadtbereiche prägen jeweils andere Schäden. In Troisdorf-Mitte mit Friedrich-Wilhelms-Hütte und Oberlar ist es der Alltagsverkehr rund um Einkauf, Bahnhof und Betriebe: Auffahrschäden, Streifschäden beim Vorbeifahren, Rangierschäden auf Firmenparkplätzen. Sieglar mit Eschmar, Kriegsdorf und Müllekoven liegt zur Sieg hin offener, mit Landstraßencharakter und höheren Geschwindigkeiten. Spich, Bergheim und Altenrath grenzen an die Wahner Heide — dort sind Wildwechsel und plötzliche Bremsmanöver ein reales Thema, gerade früh am Morgen und in der Dämmerung.` },
    { h3: 'Was ein belastbares Gutachten enthält', text: `Alles, was später jemand anzweifeln könnte — und zwar bevor es jemand anzweifelt. Nach BVSK-Standard heißt das im Einzelnen:`, liste: ['Schadenbild in Übersichts- und Detailaufnahmen', 'Maßaufnahme von Anstoßhöhe und Beschädigungsbreite', 'Lackschichtmessung zur Abgrenzung von Vorschäden', 'Ersatzteile, Arbeits- und Lackierzeiten einzeln kalkuliert', 'Wertminderung, Restwert, Wiederbeschaffungswert', 'Gutachten im Regelfall binnen 48 Stunden'] },
    { h3: 'Firmenwagen, Transporter, Flotte — wer meldet, wer haftet?', text: `Bei einem Betriebsfahrzeug fallen Halter, Fahrer und Geschädigter oft auseinander. Für die Regulierung heißt das: Die Halterdaten müssen stimmen, der Fahrer muss benannt sein, und der Schaden muss so beziffert werden, dass Firmenversicherung und gegnerische Haftpflicht mit demselben Stand arbeiten. Kommt Ausfall hinzu, gehört auch der ins Gutachten — bei gewerblich genutzten Fahrzeugen ist das häufig der größere Posten.` },
    { h3: 'Warum rechnet der Gutachter oft direkt mit der Versicherung ab?', text: `Weil Sie sonst in Vorleistung gehen müssten. Üblich ist eine Abtretung erfüllungshalber: Sie treten den Honoraranspruch gegen den Schädiger an das Sachverständigenbüro ab, das dann selbst gegenüber der gegnerischen Haftpflicht abrechnet. Zahlt die Versicherung nicht oder kürzt sie, bleibt die Forderung zunächst dort, wo sie hingehört — beim Verursacher, nicht bei Ihnen. Wichtig zu wissen: Bei geteilter Schuld oder wenn sich die Haftung später anders darstellt, lebt Ihre Zahlungspflicht anteilig wieder auf. Deshalb klären wir die Haftungslage vorher offen an, statt Ihnen pauschal Kostenfreiheit zuzusagen.` },
    { h3: 'Wer zahlt den Anwalt?', text: `Bei unverschuldetem Unfall die gegnerische Versicherung — genau wie Gutachter, Mietwagen und Abschleppkosten. Ein Verkehrsrechtsanwalt lohnt sich fast immer, weil er Fristen überwacht und Kürzungen widerspricht, statt sie stillschweigend hinzunehmen. Über das Claimondo-Netzwerk vermitteln wir einen aus der Region, wenn Sie das möchten.` },
    { h3: 'Das Fahrzeug hatte schon einen Vorschaden — ist der Anspruch weg?', text: `Nein, aber er wird anspruchsvoller zu belegen. Ersatz bekommen Sie für den Schaden aus diesem Unfall, und wenn ein früherer Schaden dieselbe Stelle betrifft, müssen beide sauber voneinander getrennt werden. Ein fachgerecht reparierter Vorschaden ist dabei unproblematisch, sofern die Reparatur nachweisbar ist — kritisch wird es bei unreparierten Altschäden im selben Bereich, weil die Gegenseite dann pauschal bestreitet. Genau dafür ist die Lackschichtmessung da: Sie zeigt, wo nachlackiert wurde und wo nicht. Wir dokumentieren Vorschäden ausdrücklich mit, statt sie zu übergehen — ein Gutachten, das sie verschweigt, verliert bei der ersten Nachfrage seine Glaubwürdigkeit.` },
    { h3: 'Transporter oder Nutzfahrzeug: Warum der Ausfall schwerer wiegt', text: `Weil ein Handwerker- oder Lieferfahrzeug kein Fortbewegungsmittel ist, sondern Betriebsmittel. Fällt es aus, entsteht neben dem Reparaturschaden ein wirtschaftlicher Folgeschaden, und der wird anders bemessen als bei einem Privatwagen: Statt der pauschalen Nutzungsausfallentschädigung kommen Mietkosten für ein Ersatzfahrzeug, Vorhaltekosten oder entgangener Gewinn in Betracht. Welcher Weg der richtige ist, hängt von Einsatzprofil und Nachweisbarkeit ab. Das Gutachten muss dafür zwei Dinge liefern: eine belastbare Reparaturdauer und eine Beschreibung der Ausstattung, die das Fahrzeug zum Arbeitsmittel macht — Regalsysteme, Kühlaufbau, Ladebordwand, Beschriftung. Genau diese Aufbauten werden bei einer Standardkalkulation gern übersehen, obwohl sie den Wiederbeschaffungswert und die Ausfallzeit erheblich beeinflussen. In den Troisdorfer Gewerbelagen ist das der Regelfall, nicht die Ausnahme.` },
    { h3: 'Ladung fällt vom Lkw — wer haftet für den Schaden?', text: `Grundsätzlich die Halterhaftung des Lkw beziehungsweise die Haftpflichtversicherung der Spedition, denn der Verlust von Ladung ist dem Betrieb des Fahrzeugs zuzurechnen. Praktisch scheitert es aber oft am Nachweis, weil der Verursacher weiterfährt und nichts davon bemerkt. Umso wichtiger ist, was am eigenen Fahrzeug zurückbleibt: Ein aufgeschlagenes Teil hinterlässt eine charakteristische Spur mit Materialübertrag, oft an Frontscheibe, Haube oder Dach, und deren Winkel lässt Rückschlüsse auf Flugbahn und Herkunft zu. Wir sichern diese Spuren, einschließlich Materialresten, bevor das Fahrzeug gereinigt wird. Bleibt der Verursacher unbekannt, verlagert sich der Fall in die Kasko — und auch dort entscheidet die Dokumentation darüber, ob der Schaden als Unfallschaden anerkannt wird oder als unerklärter Schaden gilt.` },
    { text: `Kfz-Sachverständiger Troisdorf — neutral, gerichtsfest, kurzfristig vor Ort. Ein Anruf oder eine WhatsApp-Nachricht reicht, und Sie wissen, woran Sie sind.` },
  ],
  koenigswinter: [
    { text: `Königswinter reicht vom Rheinufer bis in die Höhen des Siebengebirges, und dazwischen liegen wenige Kilometer mit erheblichem Höhenunterschied. Das prägt den Verkehr: unten die B42 als Durchgangsachse und die Autofähre nach Bonn-Mehlem, oben die A3 und die Verbindungsstraßen ins Pleiser Ländchen. Ortskundige und Auswärtige nutzen dieselben Strecken, nur mit sehr unterschiedlichem Tempo. Nach einem fremdverschuldeten Unfall dokumentiert ein unabhängiger Kfz-Gutachter Königswinter den Schaden vor Ort, bevor das Fahrzeug bewegt wird. Das Honorar übernimmt die gegnerische Haftpflicht — für Sie 0 € nach § 249 BGB.` },
    { vorort: true, text: `Die drei Teile der Stadt bringen jeweils eigene Schäden hervor. In der Talstadt mit Altstadt, Niederdollendorf und Oberdollendorf ist es der enge Straßenraum zwischen Rhein und Hang: Rangierschäden, Streifkontakte an parkenden Fahrzeugen, Konflikte mit Rad- und Fußverkehr. In Ittenbach und Heisterbacherrott im Siebengebirge sind es Steigungen, enge Kurven und Fahrzeuge, die bergauf langsamer unterwegs sind als der Nachfolgende erwartet. Im Pleiser Ländchen um Oberpleis, Thomasberg, Stieldorf und Eudenbach herrscht Landstraßenverkehr mit landwirtschaftlichen Fahrzeugen und wechselnden Fahrbahnzuständen.` },
    { h3: 'Was am Siebengebirge ins Gutachten gehört', text: `Ein Schadensbild ist nur so belastbar wie seine Abgrenzung zu dem, was vorher schon da war. Wir nehmen deshalb beides auf und führen es getrennt aus:`, liste: ['Aktuelles Schadenbild mit Fotostrecke und Maßen', 'Abgrenzung von Alt- und Vorschäden per Lackmessung', 'Prüfung von Unterboden und Anbauteilen', 'Reparaturkosten in marktüblicher Kalkulation', 'Wertminderung und Wiederbeschaffungsdauer', 'Gutachten im Regelfall binnen 48 Stunden'] },
    { h3: 'Der Unfallgegner ist von auswärts — wird das komplizierter?', text: `Königswinter zieht Besucher aus dem ganzen Rheinland und aus dem Ausland an, und über die Fähre nach Bonn-Mehlem wechseln täglich Fahrzeuge die Rheinseite. Für Ihre Ansprüche ändert das wenig: Bei ausländischen Kennzeichen läuft die Regulierung über die Grüne Karte und den Zentralruf der Autoversicherer, bei deutschen ohnehin über die Haftpflicht des Verursachers. Entscheidend ist nur, dass Kennzeichen, Versicherungsdaten und Schadensbild noch am Unfallort festgehalten werden.` },
    { h3: 'Wohnmobil, Anhänger, Motorrad: anders zu bewerten?', text: `Ja, und zwar deutlich. Bei Wohnmobilen und Anhängern hängt viel am Aufbau — Rahmen, Verzug, Dichtigkeit — und der Wiederbeschaffungswert folgt einem eigenen Markt statt der Pkw-Liste. Bei Motorrädern zählen Rahmen, Gabel und Anbauteile, und die Wertminderung fällt anders aus. Solche Fahrzeuge gehören in ein Gutachten, das ihren Markt kennt, sonst wird der Schaden zu niedrig angesetzt.` },
    { h3: 'Was kostet die Begutachtung?', text: `Bei unverschuldetem Unfall nichts: Das Sachverständigenhonorar ist Teil des Schadens und wird direkt mit der gegnerischen Haftpflicht abgerechnet. Ob der Termin kurzfristig zustande kommt oder nicht, ändert daran nichts. Über das Netzwerk vermitteln wir bei Bedarf zusätzlich Anwalt, Werkstatt und Mietwagen.` },
    { h3: 'Das Fahrzeug ist nicht mehr fahrbereit — wer organisiert das?', text: `Auf einer Bergstrecke oder in der engen Talstadt ist ein liegengebliebenes Fahrzeug schnell selbst zur Gefahr, und Bergung und Abschleppen sind bei unverschuldetem Unfall erstattungsfähige Positionen. Wichtig ist die Reihenfolge: Der Schaden sollte dokumentiert sein, bevor das Fahrzeug bewegt oder gewaschen wird, weil Endstellung, Spuren und Anhaftungen sonst verloren gehen. Lässt sich das nicht abwarten, halten Sie den Zustand wenigstens mit eigenen Fotos fest. Der Sachverständige kann anschließend auch am Abstellort begutachten — auf dem Betriebshof, in der Werkstatt oder bei Ihnen zu Hause. Standkosten gehören ebenfalls in die Aufstellung, wenn das Fahrzeug dort länger steht.` },
    { h3: 'Steinschlag vom Hang, herabfallendes Material — wer kommt dafür auf?', text: `Das hängt davon ab, wer für die Strecke verantwortlich ist. Löst sich Material aus einer Böschung oder von einem Felsen, kann eine Verletzung der Verkehrssicherungspflicht durch den Straßenbaulastträger in Betracht kommen — vorausgesetzt, die Gefahr war erkennbar und es wurde nichts unternommen. Das ist eine hohe Hürde, und in der Praxis führt der Weg meist über die eigene Teilkasko, die Schäden durch herabfallende Gegenstände in aller Regel abdeckt. Für beide Wege zählt dasselbe: Die Aufprallspur muss zum behaupteten Hergang passen. Ein von oben aufschlagendes Stück hinterlässt ein anderes Bild als ein aufgewirbelter Stein von der Fahrbahn — Einschlagwinkel, Verformungsrichtung und die Lage auf Dach, Haube oder Scheibe sind hier das eigentliche Beweismittel und gehören dokumentiert, bevor das Fahrzeug bewegt wird.` },
    { h3: 'Was ist, wenn Insassen verletzt wurden?', text: `Dann laufen zwei Verfahren nebeneinander: der Sachschaden am Fahrzeug und der Personenschaden. Letzterer umfasst Behandlungskosten, Verdienstausfall, Schmerzensgeld und bei längerer Beeinträchtigung auch den Haushaltsführungsschaden. Wichtig ist der frühe Arztbesuch, selbst bei zunächst leichten Beschwerden — Nacken- und Rückenbeschwerden treten häufig erst Stunden später auf, und ohne zeitnahes Attest wird der Zusammenhang später bestritten. Sach- und Personenschaden hängen dabei enger zusammen, als es scheint: Versicherungen argumentieren bei geringem Fahrzeugschaden regelmäßig, die Kollision sei zu schwach für eine Verletzung gewesen. Ein Gutachten, das Anstoßrichtung und Verformungsarbeit sauber ausweist, ist deshalb auch für den Personenschaden von Bedeutung. Den ärztlichen Teil übernimmt selbstverständlich die Medizin, nicht der Sachverständige.` },
    { text: `Kfz-Gutachter Königswinter — unabhängig, gerichtsfest, schnell vor Ort in Tal- und Bergstadt. Rufen Sie an oder schreiben Sie über WhatsApp, und wir klären in wenigen Minuten, was für Sie sinnvoll ist.` },
  ],
  'bad-honnef': [
    { text: `Bad Honnef ist die südlichste Stadt Nordrhein-Westfalens und besteht verkehrlich aus zwei Welten: unten das Rheintal mit Stadtmitte, Rhöndorf und der autofreien Insel Grafenwerth, oben Aegidienberg auf dem Asbacher Plateau. Verbunden werden sie über das Schmelztal, und wer täglich zwischen beiden pendelt, durchfährt zweimal am Tag einen kompletten Wechsel von Straßentyp, Steigung und Witterung. Passiert dabei ein fremdverschuldeter Unfall, hilft ein unabhängiger Kfz-Sachverständiger Bad Honnef, der den Schaden neutral aufnimmt, statt ihn von der Gegenseite schätzen zu lassen. Für Sie 0 € nach § 249 BGB.` },
    { vorort: true, text: `Die Ortslagen unterscheiden sich stark. In der Stadtmitte mit Rommersdorf, Reitersdorf und Bondorf prägt der Kurort-Charakter das Bild: Besucherverkehr, Parksuchverkehr in gewachsenen Straßen, entsprechend Rempel- und Streifschäden. Die Rheinlage mit Rhöndorf und Selhof lebt vom Ausflugs- und Anliegerverkehr entlang des Ufers. Aegidienberg mit Himberg, Orscheid, Rottbitze und den kleineren Höhenorten ist dagegen ländlich geprägt: Landstraßen, landwirtschaftlicher Verkehr, längere Wege zur nächsten Werkstatt — und deshalb auch längere Standzeiten, wenn ein Fahrzeug nicht mehr fahrbereit ist.` },
    { h3: 'Was in Bad Honnef ins Gutachten gehört', text: `Neben dem Schaden selbst die Frage, wie lange Sie ohne Ihr Fahrzeug auskommen müssen. Gerade auf der Höhe wiegt ein Ausfall schwerer als in der Stadt, deshalb beziffern wir ihn mit:`, liste: ['Reparaturdauer und Wiederbeschaffungsdauer', 'Nutzungsausfall nach Fahrzeugklasse', 'Schadenbild in Foto- und Maßdokumentation', 'Lackschichtmessung und Vorschadenabgrenzung', 'Wertminderung und Restwert', 'Gutachten im Regelfall binnen 48 Stunden'] },
    { h3: 'Der Unfallgegner kommt aus Rheinland-Pfalz — welches Recht gilt?', text: `Bad Honnef grenzt an Rheinland-Pfalz, und über A3 und B42 ist ein erheblicher Teil des Verkehrs überregional. Für Ihre Ansprüche spielt die Landesgrenze keine Rolle: Es gilt dasselbe Schadenersatzrecht, reguliert wird über die Haftpflichtversicherung des Verursachers, unabhängig von dessen Wohnort. Sie sind auch nicht verpflichtet, einen Gutachter aus dessen Region zu akzeptieren — den Sachverständigen wählen Sie.` },
    { h3: 'Wertminderung — warum sie so oft gestrichen wird', text: `Der merkantile Minderwert bildet ab, dass ein Unfallfahrzeug beim Verkauf weniger einbringt, auch wenn es fachgerecht repariert wurde. Weil er schwerer zu greifen ist als eine Rechnung, wird er von Versicherungen gern gekürzt oder ganz gestrichen. Wir leiten ihn nachvollziehbar aus Fahrzeugalter, Laufleistung, Schadenumfang und Marktlage her — eine Zahl mit Herleitung lässt sich schwerer wegdiskutieren als eine ohne.` },
    { h3: 'Der Gegner schildert den Hergang anders', text: `Das kommt häufiger vor als gedacht, besonders wenn keine Zeugen da sind. Dann entscheidet die Spur am Fahrzeug: Anstoßhöhe, Verformungsrichtung, Lackantrag und Schadensverlauf lassen Rückschlüsse auf Bewegungsrichtung und Geschwindigkeit zu. Wird früh und vollständig dokumentiert, steht am Ende eine technische Rekonstruktion gegen eine Behauptung — und nicht Aussage gegen Aussage.` },
    { h3: 'Muss die Polizei kommen?', text: `Bei reinem Blechschaden gibt es keine allgemeine Pflicht, die Polizei zu rufen — aber Sie müssen dem Geschädigten die Feststellung von Person, Fahrzeug und Beteiligung ermöglichen, sonst steht Unfallflucht im Raum. Auf den Landstraßen rund um Aegidienberg und die Höhenorte, wo oft keine Zeugen in der Nähe sind, ist die polizeiliche Aufnahme trotzdem meist die bessere Wahl: Sie hält den Hergang fest, bevor er strittig wird. Verletzte, erheblicher Sachschaden, Alkoholverdacht, ausländische Beteiligung oder ein Verursacher, der sich entfernen will — in all diesen Fällen sollten Sie die Polizei in jedem Fall hinzuziehen. Das eigene Gutachten ersetzt die Aufnahme nicht, es ergänzt sie um die technische Seite.` },
    { h3: 'Sie sind nur zu Besuch hier — was heißt das für die Abwicklung?', text: `Als Kurort und Ausflugsziel hat Bad Honnef viele Beteiligte, die nicht in der Region wohnen. Für die Begutachtung ist das kein Hindernis: Maßgeblich ist, wo das Fahrzeug steht, nicht wo Sie gemeldet sind. Sinnvoll ist die Aufnahme vor der Abreise, denn ein Fahrzeug, das erst zu Hause begutachtet wird, hat die Fahrt bereits hinter sich — bei Schäden an Achse, Rad oder Unterboden ist dann nicht mehr trennbar, was aus dem Unfall stammt und was aus der Weiterfahrt. Ist das Fahrzeug nicht mehr fahrbereit, gehören auch Rücktransport oder die Heimreise mit einem Mietwagen zum ersatzfähigen Schaden. Die Reparatur können Sie anschließend an Ihrem Wohnort durchführen lassen; das Gutachten ist bundesweit die gleiche Abrechnungsgrundlage.` },
    { h3: 'Standgeld, Abmeldung, Fahrten zur Werkstatt — zählen die Kleinposten?', text: `Sie zählen, werden aber am häufigsten vergessen. Neben Reparatur, Gutachten und Mietwagen sind auch Abschlepp- und Bergungskosten ersatzfähig, dazu Standgeld, wenn das Fahrzeug bei Werkstatt oder Abschleppdienst untergestellt werden muss, sowie An- und Abmeldekosten, wenn ein Ersatzfahrzeug zugelassen wird. Hinzu kommt eine Auslagenpauschale für Telefonate, Porto und Fahrten. Bei einem Ausfall in Aegidienberg oder den Höhenorten wiegt dieser Block schwerer als im Tal, weil die Wege länger sind und ein nicht fahrbereites Fahrzeug oft tagelang steht, bevor der Abtransport organisiert ist. Wir halten Standort, Standdauer und Fahrbereitschaft im Gutachten fest, damit diese Positionen später belegt sind und nicht als nachträgliche Behauptung erscheinen.` },
    { text: `Kfz-Sachverständiger Bad Honnef — unabhängig, gerichtsfest, schnell vor Ort in Tal- und Höhenlage. Melden Sie sich telefonisch oder über WhatsApp, dann klären wir die nächsten Schritte.` },
  ],
  hennef: [
    { text: `Hennef zieht sich über das Siegtal und die angrenzenden Höhen und besteht aus ungewöhnlich vielen einzelnen Ortslagen. Verkehrlich heißt das: Die A560 endet am westlichen Stadtrand, danach verteilt sich alles auf Bundes- und Landstraßen, die Dörfer, Höfe und Gewerbe miteinander verbinden. Dazu kommt überregionaler Verkehr zur Sportschule Hennef, wo das ganze Jahr über Mannschaften und Lehrgangsgruppen anreisen. Nach einem unverschuldeten Unfall nimmt ein unabhängiger Kfz-Gutachter Hennef den Schaden dort auf, wo das Fahrzeug steht. Das Honorar trägt die gegnerische Haftpflicht — 0 € für Sie nach § 249 BGB.` },
    { vorort: true, text: `Zwischen den Hennefer Ortslagen liegen Welten. Im Zentrum mit Hennef-Mitte, Geistingen, Warth und Geisbach ist es der verdichtete Alltagsverkehr: Einkauf, Bahnhof, Berufsverkehr, entsprechend Auffahr- und Parkschäden. Im Westen um Allner, Weldergoven, Lauthausen und Stoßdorf prägt die Talachse das Bild, mit höheren Geschwindigkeiten und Abbiegekonflikten. Im Osten Richtung Uckerath, Söven und Happerschoß sowie im Süden um Bödingen und Stadt Blankenberg wird es ländlich: schmale Fahrbahnen, landwirtschaftliche Fahrzeuge, unbeleuchtete Strecken und weite Wege bis zur nächsten Werkstatt.` },
    { h3: 'Was ein Gutachten aus dem Siegtal belegen muss', text: `Vor allem die Umstände, die man auf einem Foto vom Kotflügel nicht sieht. Wir halten deshalb nicht nur das Blech fest, sondern den ganzen Vorgang:`, liste: ['Schadenbild mit Fotostrecke, Maßen und Anstoßhöhe', 'Lackschichtmessung und Vorschadenabgrenzung', 'Prüfung von Achse, Lenkung und Unterboden', 'Reparaturkosten in marktüblicher Kalkulation', 'Wertminderung, Restwert, Ausfalldauer', 'Gutachten im Regelfall binnen 48 Stunden'] },
    { h3: 'Vereinsbus, Mannschaftswagen, Fahrzeug mit vielen Nutzern', text: `Rund um die Sportschule sind Kleinbusse und Vereinsfahrzeuge unterwegs, bei denen Halter und Fahrer nicht dieselbe Person sind. Für die Regulierung muss klar sein, wer gefahren ist, wer Halter ist und wer den Schaden geltend macht — sonst verzögert sich die Auszahlung, obwohl die Haftung längst unstrittig ist. Wir nehmen diese Angaben mit auf, damit der Vorgang nicht an einer Formalie hängen bleibt.` },
    { h3: 'Wie kommt der Gutachter in einen abgelegenen Ortsteil?', text: `Er fährt hin. Der Vor-Ort-Termin ist kein Zugeständnis, sondern die Voraussetzung dafür, dass ein nicht fahrbereites Fahrzeug überhaupt begutachtet werden kann — und nach einem Unfall auf einer Landstraße ist das eher die Regel als die Ausnahme. Sie müssen Ihr Fahrzeug also nicht auf eigene Kosten in eine Werkstatt bringen lassen, bevor der Schaden aufgenommen ist.` },
    { h3: 'Reparatur oder Totalschaden — wer entscheidet das?', text: `Rechnerisch das Gutachten, praktisch Sie. Liegen die Reparaturkosten über dem Wiederbeschaffungswert, stehen fiktive Abrechnung, die 130-Prozent-Regelung und die Auszahlung des Wiederbeschaffungswerts nebeneinander; welche Option offenbleibt, hängt davon ab, wie sauber Restwert und Reparaturweg belegt sind. Wir rechnen die Varianten durch, bevor Sie sich festlegen.` },
    { h3: 'Der Unfall liegt ein paar Tage zurück — ist es zu spät?', text: `Für Ihren Anspruch nicht, für die Beweise schon eher. Schadenersatzansprüche verjähren nicht innerhalb weniger Tage, und auch ein nachträglich erstelltes Gutachten wird von den Versicherern akzeptiert. Was verloren geht, ist der Zustand: Bremsspuren verwischen, Fahrzeuge werden gewaschen, Teile werden schon getauscht, und je länger es dauert, desto leichter lässt sich behaupten, ein Schaden stamme aus einem anderen Ereignis. Wer nach einem Unfall im abgelegenen Siegtal erst einmal abwartet, weil die Versicherung eine Regulierung angekündigt hat, verliert oft genau diese Woche. Melden Sie sich lieber zu früh — wenn kein Gutachten nötig ist, sagen wir Ihnen das.` },
    { h3: 'Ausweichen ohne Berührung — ist das überhaupt ein Unfall?', text: `Ja, und es ist einer der schwierigsten Fälle. Wer auf einer Landstraße im Siegtal einem Tier oder einem entgegenkommenden Fahrzeug ausweicht und dabei von der Fahrbahn abkommt, hat oft keinerlei Kontaktspur — und damit kein Gegenstück, das den Hergang belegt. Bei einem fremden Verursacher hängt alles an Zeugen und an der Plausibilität der Spurenlage. Bei einem Tier greift die Teilkasko, aber nur, wenn das Ausweichmanöver als geboten anzusehen war; bei Kleintieren wird das regelmäßig bestritten. Was hilft, ist die Rekonstruktion: Fahrspuren im Bankett, Bremsspuren, die Anstoßstelle an Böschung, Leitplanke oder Baum und die daraus ableitbare Geschwindigkeit. Diese Spuren verschwinden binnen Tagen — beim ersten Regen, spätestens beim nächsten Mähgang.` },
    { h3: 'Zwei Fahrzeuge im Haushalt — entfällt dann der Nutzungsausfall?', text: `Nicht automatisch, aber es wird geprüft. Nutzungsausfallentschädigung setzt voraus, dass Sie das Fahrzeug nutzen wollten und konnten und dass Ihnen die Nutzung tatsächlich gefehlt hat. Steht ein gleichwertiges Zweitfahrzeug bereit, das die Aufgabe übernimmt, kürzt die Versicherung gern mit diesem Argument. Es zieht aber nicht, wenn der Zweitwagen selbst gebraucht wird — etwa weil im Haushalt zwei Personen pendeln — oder wenn er nicht gleichwertig ist. Gerade in den weit verstreuten Hennefer Ortslagen, wo der Weg zur Arbeit, zur Schule und zum Einkauf ohne Auto kaum zu bewältigen ist, ist die zweite Fahrzeugnutzung meist real und keine Reserve. Das Gutachten liefert dafür die Grundlage: Fahrzeugklasse und Ausfalldauer, aus denen sich der Tagessatz ergibt.` },
    { text: `Kfz-Gutachter Hennef — neutral, gerichtsfest, vor Ort in allen Ortslagen. Ein Anruf oder eine WhatsApp-Nachricht genügt für die erste Einschätzung.` },
  ],
  bornheim: [
    { text: `Bornheim liegt zwischen Rheinufer und Ville und ist landwirtschaftlich geprägt wie kaum eine andere Stadt der Region: Auf den Lössböden des Vorgebirges wachsen Obst und Gemüse, der Bornheimer Spargel ist als regionale Spezialität geschützt. Für den Verkehr bedeutet das ein Nebeneinander von Pendlerachsen entlang des Rheins, der Stadtbahnlinie 18 durch die Ortsteile und landwirtschaftlichem Verkehr, der vom Wirtschaftsweg auf die Landstraße wechselt. Ein unabhängiger Kfz-Sachverständiger Bornheim nimmt Ihren Schaden nach einem fremdverschuldeten Unfall neutral auf — 0 € für Sie, weil die gegnerische Haftpflicht nach § 249 BGB zahlt.` },
    { vorort: true, text: `Bornheim ist eine Stadt aus Dörfern, und jedes bringt anderes mit. Auf der Rheinschiene mit Hersel, Uedorf und Widdig ist es der Durchgangsverkehr entlang des Ufers mit engen Ortsdurchfahrten. Im Vorgebirge um Bornheim, Brenig, Rösberg und Botzdorf steigt das Gelände an, und zwischen den Anbauflächen kreuzen Wirtschaftswege die Straßen. Im Norden mit Sechtem, Walberberg und Kardorf prägt der Bahnhaltepunkt den Pendlerverkehr; im Süden um Roisdorf, Merten, Dersdorf und Waldorf teilt sich die Stadtbahn 18 den Straßenraum mit dem Autoverkehr.` },
    { h3: 'Was das Gutachten im Vorgebirge festhält', text: `Auch die Umstände am Unfallort, weil sie über die Haftungsquote mitentscheiden. Dokumentiert wird deshalb nach BVSK-Standard:`, liste: ['Schadenbild in Foto- und Maßdokumentation', 'Fahrbahn- und Sichtverhältnisse am Unfallort', 'Lackschichtmessung und Vorschadenabgrenzung', 'Reparaturkosten zu marktüblichen Sätzen', 'Wertminderung und Restwert', 'Gutachten im Regelfall binnen 48 Stunden'] },
    { h3: 'Darf die Werkstattrechnung höher ausfallen als das Gutachten?', text: `Ja, und das ist häufiger der Fall, als viele erwarten — beim Zerlegen kommt zum Vorschein, was von außen niemand sehen konnte. Das sogenannte Prognoserisiko trägt dabei nicht der Geschädigte: Wer einen Sachverständigen sorgfältig ausgewählt hat und die Reparatur auf dessen Grundlage beauftragt, muss die Mehrkosten nicht selbst tragen, auch wenn sich die Kalkulation im Nachhinein als zu niedrig erweist. Voraussetzung ist, dass die Abweichung dokumentiert wird. Deshalb sollte die Werkstatt Rücksprache halten und nachdokumentieren, statt still weiterzuarbeiten — sonst fehlt später der Beleg für genau diese Position.` },
    { h3: 'Unfall mit der Stadtbahn 18', text: `Wo die Linie 18 den Straßenraum mitbenutzt, kommt es beim Abbiegen, beim Ausparken und an Übergängen zu Kollisionen. Solche Fälle laufen gegen ein Verkehrsunternehmen, das seinerseits einen Prüfer schickt — mit eigenen Interessen. Ein unabhängiges Gutachten stellt Ihre Seite dagegen: Anstoßhöhe und Beschädigungsbild zeigen, in welcher Bewegung die Fahrzeuge zueinander standen.` },
    { h3: 'Anwalt, Mietwagen, Abschleppen — was wird ersetzt?', text: `Bei unverschuldetem Unfall alles, was zur Wiederherstellung gehört: Gutachterhonorar, Reparatur oder Wiederbeschaffung, Anwaltskosten, Mietwagen oder Nutzungsausfall, Abschleppkosten und die Auslagenpauschale. Diese Positionen fallen aber nicht automatisch an, sie müssen geltend gemacht werden — deshalb lohnt der Anwalt aus dem Netzwerk, auch wenn er Sie nichts kostet.` },
    { h3: 'Hagel oder Unfall — woran unterscheidet man das?', text: `In den offenen Lagen des Vorgebirges trifft Unwetter Fahrzeuge, die frei stehen, und danach ist nicht immer klar, welche Delle woher stammt. Ein Hagelschaden zeigt ein charakteristisches Bild: viele kleine, runde Einschläge, verteilt auf horizontalen Flächen wie Dach, Motorhaube und Kofferraumdeckel, meist ohne Lackverletzung. Ein Anstoß hinterlässt dagegen eine gerichtete Verformung mit Lackabtrag, oft mit Fremdlack an der Kontaktstelle. Die Unterscheidung ist keine Feinheit, sondern entscheidet, wer zahlt: Hagel läuft über die Teilkasko, der Anstoß über die Haftpflicht des Verursachers. Wir trennen die Schadensbilder im Gutachten, damit nicht ein Ereignis das andere verdeckt.` },
    { h3: 'Sonderausstattung, Anbauten, Nachrüstungen — fließen die in den Wert ein?', text: `Sie müssen es, sonst wird der Wiederbeschaffungswert zu niedrig angesetzt. Serienferne Ausstattung wirkt sich unterschiedlich stark aus: Werkseitige Sonderausstattung schlägt in der Bewertung deutlicher durch als nachträglich Angebautes, und manches steigert den Gebrauchswert, ohne den Marktwert zu erhöhen. In einer landwirtschaftlich geprägten Umgebung sind das oft Anhängerkupplung, Allradantrieb, Ladeflächenschutz, Trennwand oder eine zweite Bereifung auf Felgen. Für die Erfassung zählt der Nachweis: Ausstattungsliste, Rechnungen, Einbaubelege. Fehlen sie, wird geschätzt — und zwar zu Ihren Lasten. Wir nehmen die Ausstattung deshalb einzeln auf und ordnen sie dem Fahrzeug zu, statt sie in einer Sammelposition verschwinden zu lassen. Beim Totalschaden entscheidet genau diese Liste über mehrere hundert Euro Differenz.` },
    { h3: 'Wer bekommt das Gutachten eigentlich zu sehen?', text: `Sie zuerst — es ist Ihr Gutachten, beauftragt von Ihnen, nicht von der Versicherung. Weitergegeben wird es an die Stellen, die es für die Regulierung brauchen: die gegnerische Haftpflicht, Ihren Anwalt und die Werkstatt, die auf seiner Grundlage kalkuliert. Ein Prüfdienstleister der Versicherung erhält es damit ebenfalls, das gehört zum Verfahren. Es enthält personenbezogene Daten — Halter, Kennzeichen, Fahrzeugidentnummer, Fotos, gelegentlich auch Umgebung des Unfallorts —, weshalb es nicht ohne Anlass in weitere Hände gehört. Aufbewahren sollten Sie es dauerhaft: Beim späteren Verkauf ist ein vollständiges Gutachten nebst Reparaturnachweis das beste Mittel gegen den pauschalen Preisabschlag, den Käufer bei einem gemeldeten Vorschaden ansetzen.` },
    { text: `Kfz-Sachverständiger Bornheim — unabhängig, gerichtsfest, kurzfristig vor Ort zwischen Rhein und Vorgebirge. Rufen Sie an oder schreiben Sie über WhatsApp.` },
  ],
  rheinbach: [
    { text: `Rheinbach liegt am Übergang der Swistniederung in die Voreifel und ist zugleich Hochschul- und Glasstadt: Die Glasfachschule NRW und der Rheinbacher Campus der Hochschule Bonn-Rhein-Sieg bringen Studierende, Beschäftigte und Lieferverkehr in die Kernstadt. Erschlossen wird das Gebiet über die A61 im Westen und die B266, die als Ortsdurchfahrt und als Verbindung Richtung Ahrgebirge zwei sehr verschiedene Rollen spielt. Nach einem fremdverschuldeten Unfall sichert ein unabhängiger Kfz-Gutachter Rheinbach das Schadensbild, bevor es verändert wird. Das Honorar trägt die gegnerische Haftpflicht — 0 € für Sie nach § 249 BGB.` },
    { vorort: true, text: `Innerhalb Rheinbachs liegen die Verhältnisse weit auseinander. In der Kernstadt ist es dichter Alltagsverkehr mit Parksuchverkehr, Lieferfahrzeugen sowie Rad- und Fußverkehr rund um Schulen und Campus. In der Swistniederung mit Flerzheim, Ramershoven, Oberdrees und Niederdrees dominieren Landstraßen zwischen den Dörfern, mit Abbiege- und Einmündungskonflikten. Wormersdorf im Osten liegt am Übergang zur offenen Feldflur. Und auf der Voreifel-Höhe um Todenfeld, Hilberath, Neukirchen und Queckenberg wird es kurvig, steil und im Winter deutlich rauer als unten im Tal.` },
    { h3: 'Was in Rheinbach ins Gutachten gehört', text: `Eine Kalkulation, die einer Nachprüfung durch die gegnerische Versicherung standhält. Wir weisen deshalb nach BVSK-Standard einzeln aus:`, liste: ['Ersatzteile, Arbeits- und Lackierzeiten getrennt', 'Marktübliche Stundenverrechnungssätze der Region', 'Lackschichtmessung und Vorschadenabgrenzung', 'Verdeckte Schäden hinter Anbauteilen', 'Wertminderung, Restwert, Ausfalldauer', 'Gutachten im Regelfall binnen 48 Stunden'] },
    { h3: 'Die Versicherung schickt einen eigenen Prüfbericht — was gilt dann?', text: `Der Prüfbericht der gegnerischen Versicherung ist kein Gutachten, sondern eine Stellungnahme im Interesse dessen, der zahlen soll. Weicht er ab, ist das kein Beleg dafür, dass Ihr Gutachten falsch wäre — meist sind es gekürzte Stundensätze, gestrichene Verbringungs- oder Beilackierungskosten. Solche Positionen lassen sich Punkt für Punkt begründen, und genau das tun wir, statt die Differenz stillschweigend hinzunehmen.` },
    { h3: 'Woher kommt der Restwert in Ihrem Gutachten?', text: `Aus dem regionalen Markt, nicht aus einem einzelnen Höchstgebot. Im Totalschadenfall legen Versicherungen gern ein Angebot aus einer überregionalen Restwertbörse vor, das über dem regionalen Niveau liegt und Ihre Auszahlung senkt. Darauf müssen Sie sich nicht einlassen, wenn Ihr Gutachten einen belastbar ermittelten Restwert ausweist — deshalb dokumentieren wir, worauf die Zahl beruht.` },
    { h3: 'Wie lange dauert das Ganze?', text: `Der Termin lässt sich meist am selben oder am folgenden Tag legen, das Gutachten liegt im Regelfall binnen 48 Stunden vor — auch in den Höhenorten. Danach läuft die Regulierung, und die Reparatur kann parallel beginnen. Warten müssen Sie am Ende auf die Versicherung, nicht auf uns.` },
    { h3: 'Unfall auf dem Weg zur Arbeit oder zum Campus — zahlt eine andere Stelle?', text: `Für Personenschäden ja, für das Fahrzeug nicht. Wer auf dem direkten Weg zur Arbeit, zur Hochschule oder zur Ausbildungsstätte verunglückt, steht unter dem Schutz der gesetzlichen Unfallversicherung: Sie übernimmt Heilbehandlung und die Folgen von Körperschäden. Den Schaden am Auto regelt sie nicht — dafür bleibt die Haftpflicht des Unfallverursachers zuständig, und bei einem selbstverschuldeten Wegeunfall die eigene Kaskoversicherung. Beide Wege laufen parallel und schließen einander nicht aus. Praktisch heißt das: Melden Sie den Wegeunfall Ihrem Arbeitgeber oder der Hochschule, und lassen Sie den Fahrzeugschaden davon unabhängig begutachten.` },
    { h3: 'Der Schaden fällt erst später auf — geht da noch etwas?', text: `Ja, über eine Nachbesichtigung mit Nachtragsgutachten. Nicht jeder Schaden zeigt sich sofort: Ein Verzug im Fahrwerk macht sich erst nach einigen hundert Kilometern als ungleichmäßiger Reifenverschleiß bemerkbar, Feuchtigkeit hinter einer verformten Dichtung erst bei anhaltendem Regen, ein angeschlagenes Lager erst als Geräusch. Die Nachmeldung ist möglich, wird aber umso kritischer geprüft, je mehr Zeit vergangen ist — die Gegenseite verweist dann auf mögliche zwischenzeitliche Ereignisse. Was hilft, ist ein vollständiges Erstgutachten: Wenn dort dokumentiert ist, welche Bereiche betroffen waren und welche ausdrücklich unauffällig, lässt sich ein später auftretender Folgeschaden dem Unfall zuordnen. Deshalb halten wir auch fest, was wir geprüft und für unauffällig befunden haben, nicht nur den Schaden selbst.` },
    { h3: 'Kann ich das Fahrzeug beschädigt verkaufen?', text: `Können ja, aber nicht ohne Vorbereitung. Wer im Totalschadenfall verkauft, bevor der Restwert gutachterlich ermittelt ist, riskiert, dass die Versicherung später einen höheren Restwert ansetzt, als Sie erzielt haben — die Differenz tragen dann Sie. Umgekehrt sind Sie an ein Restwertangebot der Versicherung nicht gebunden, das erst nach dem Verkauf eintrifft. Die sichere Reihenfolge ist deshalb: erst das Gutachten mit belastbar ermitteltem Restwert, dann verkaufen, und zwar nicht unter diesem Wert. Beim Verkauf selbst gilt Offenheit: Ein Unfallschaden ist ein offenbarungspflichtiger Umstand, und das Verschweigen kann den Kaufvertrag angreifbar machen. Das Gutachten hilft hier doppelt — es beziffert den Wert und dokumentiert, was Sie dem Käufer mitgeteilt haben.` },
    { text: `Kfz-Gutachter Rheinbach — unabhängig, gerichtsfest, schnell vor Ort in Kernstadt und Höhenorten. Melden Sie sich telefonisch oder über WhatsApp.` },
  ],
  meckenheim: [
    { text: `Meckenheim liegt am Übergang von der Kölner Bucht in die Voreifel und lebt von zwei sehr unterschiedlichen Verkehrsarten. Auf der einen Seite der Industriepark Kottenforst, ein ausgedehntes Gewerbegebiet mit eigenem Halt an der Voreifelbahn und entsprechend viel Lkw- und Berufsverkehr. Auf der anderen die Obstanbauflächen und der Kottenforst als großes Waldgebiet direkt vor der Haustür. Wer hier unverschuldet in einen Unfall gerät, sollte den Schaden nicht von der Gegenseite bewerten lassen. Ein unabhängiger Kfz-Sachverständiger Meckenheim kommt zu Ihnen — 0 € für Sie, weil die gegnerische Haftpflicht nach § 249 BGB zahlt.` },
    { vorort: true, text: `Die Meckenheimer Ortsteile fordern jeweils anderes. In Merl und am Neuen Markt ist es Wohn- und Einkaufsverkehr mit vielen Ein- und Ausparkvorgängen auf begrenzter Fläche. Die Altstadt bringt engere Straßenführung und Lieferverkehr mit sich. Ersdorf und Altendorf im Süden liegen bereits im offenen Gelände zwischen Obstflächen und Wirtschaftswegen. Und Lüftelberg im Westen ist über Landstraßen angebunden, die an Feld und Waldrand entlangführen — dort ist in der Dämmerung mit Wild zu rechnen, und die nächste Werkstatt liegt nicht um die Ecke.` },
    { h3: 'Was das Gutachten in Meckenheim erfasst', text: `Den Schaden, seine Ursache und alles, was sich daraus für Ihre Ansprüche ergibt. Aufgenommen wird nach BVSK-Standard:`, liste: ['Fotodokumentation mit Übersicht, Detail und Maßangaben', 'Lackschichtmessung und Abgrenzung von Vorschäden', 'Prüfung tragender Teile und verdeckter Schäden', 'Reparaturkalkulation zu marktüblichen Sätzen', 'Wertminderung, Restwert, Wiederbeschaffungswert', 'Gutachten im Regelfall binnen 48 Stunden'] },
    { h3: 'Streifschaden durch einen Lkw im Gewerbegebiet', text: `Im Industriepark Kottenforst gehören Sattelzüge, Wechselbrücken und Rangiervorgänge zum Alltag, und Streifschäden entstehen dort oft, ohne dass der Lkw-Fahrer sie überhaupt bemerkt. Für die Regulierung sind zwei Dinge entscheidend: die Anstoßhöhe, denn ein Lkw streift auf anderer Höhe als ein Pkw, und die Frage, ob Spedition, Halter oder Fahrer haftet. Beides lässt sich am Schadensbild belegen, wenn es früh aufgenommen wird.` },
    { h3: 'Wildunfall am Kottenforst — was verlangt die Versicherung?', text: `Wildschäden laufen über die Teilkasko; klassisch gedeckt ist der Zusammenstoß mit Haarwild, je nach Tarif auch mehr. Verlangt werden in der Regel eine Wildschadenbescheinigung von Polizei oder Jagdpächter und ein Schadensbild, das zum geschilderten Hergang passt: Haare, Blutspuren, Aufprallhöhe und Verformungsrichtung. Wir dokumentieren diese Spuren, bevor das Fahrzeug gewaschen oder abgeschleppt wird — danach fehlen sie unwiederbringlich.` },
    { h3: 'Und wer sucht die Werkstatt aus?', text: `Sie, nicht die Versicherung. Ein Verweis auf einen günstigeren Partnerbetrieb ist ein Angebot und keine Verpflichtung; Sie dürfen eine qualifizierte Werkstatt Ihrer Wahl beauftragen und auf Basis des Gutachtens abrechnen lassen. Wenn Sie möchten, vermitteln wir einen Betrieb aus dem Claimondo-Netzwerk in Meckenheim oder der Umgebung.` },
    { h3: 'Der Verursacher hat gar keine gültige Versicherung — was dann?', text: `Auch dann bleiben Sie nicht auf dem Schaden sitzen. Für Fälle, in denen das schädigende Fahrzeug nicht versichert war, der Fahrer den Unfall vorsätzlich herbeigeführt hat oder sich nicht ermitteln lässt, existiert die Verkehrsopferhilfe als Auffangstelle. Die Voraussetzungen sind enger als bei einer normalen Haftpflichtregulierung — besonders beim unbekannt gebliebenen Verursacher, wo Sachschäden nur eingeschränkt ersetzt werden — und die Anforderungen an den Nachweis sind entsprechend hoch. Umso mehr zählt ein Gutachten, das Schadenumfang und Hergang belegt statt beschreibt. Auf dem Pendlerverkehr Richtung Bonn und Köln kommt diese Konstellation seltener vor, als viele denken, aber sie kommt vor.` },
    { h3: 'Hohe Laufleistung durch das tägliche Pendeln — was ist der Wagen noch wert?', text: `Weniger, als der Kilometerstand allein vermuten lässt, und oft mehr, als die Versicherung ansetzt. In den Wiederbeschaffungswert fließen Laufleistung, Alter, Ausstattung, Zustand, Wartungshistorie und die aktuelle Marktlage für genau dieses Modell ein — und die regionale Nachfrage weicht spürbar vom bundesweiten Mittel ab. Ein durchgängig scheckheftgepflegtes Pendlerfahrzeug mit hoher Autobahnlaufleistung steht technisch meist besser da als ein gleich altes Fahrzeug aus reinem Kurzstreckenbetrieb; in einer pauschalen Bewertung nach Kilometern geht dieser Unterschied verloren. Wir stützen den Wert deshalb auf vergleichbare Angebote statt auf eine Tabelle und weisen aus, worauf er beruht. Das ist entscheidend, weil im Totalschadenfall die Differenz zwischen Wiederbeschaffungswert und Restwert die tatsächliche Auszahlung bestimmt.` },
    { h3: 'Originalteil, Identteil oder Gebrauchtteil — was darf verbaut werden?', text: `Kalkuliert wird grundsätzlich mit Originalersatzteilen des Herstellers, denn Sie haben Anspruch darauf, dass Ihr Fahrzeug in den Zustand vor dem Unfall zurückversetzt wird. Versicherungen verweisen bei älteren Fahrzeugen gern auf günstigere Identteile anderer Hersteller oder auf Gebrauchtteile — zulässig ist das nur in Grenzen, und bei jungen oder scheckheftgepflegten Fahrzeugen regelmäßig nicht. Praktisch relevant ist das vor allem bei Karosserieteilen, Scheinwerfern und Verglasung, wo die Preisunterschiede am größten sind. Der Punkt, der oft untergeht: Eine Reparatur mit Fremdteilen kann Garantie- oder Kulanzansprüche beim Hersteller berühren. Wir kalkulieren deshalb mit Originalteilen und weisen aus, wo eine Alternative fachlich vertretbar wäre — die Entscheidung bleibt bei Ihnen, nicht bei der Gegenseite.` },
    { text: `Kfz-Sachverständiger Meckenheim — neutral, gerichtsfest, kurzfristig vor Ort. Ein Anruf oder eine WhatsApp-Nachricht reicht für die erste Einschätzung.` },
  ],
}

export function seoBodyFor(slug: string): SeoAbsatz[] {
  return SEO_BODY[slug] ?? []
}

// Per-Stadt-metaHook (Lever 2): kurzer, unique lokaler Aufhaenger fuer die Meta-
// Description (seo.ts) statt des recycelten h1Sub -> killt near-duplicate-Snippets.
// Distilliert aus SEO_BODY, <=40 Z. Fehlt ein Slug -> Fallback auf city.h1Sub.
export const META_HOOKS: Record<string, string> = {
  bonn: 'Ehem. Bundeshauptstadt am Rhein, A565',
  'sankt-augustin': 'Rhein-Sieg östlich Bonn, A560',
  siegburg: 'Verwaltungszentrum Rhein-Sieg, A3',
  troisdorf: 'A59-Korridor Köln-Bonn, Rhein-Sieg',
  koenigswinter: 'Siebengebirge & Rhein-Ausflugsverkehr',
  'bad-honnef': 'Südlichster Rhein-Sieg-Ort, B42',
  hennef: 'An der Sieg, A560 & Siegtalbahn',
  bornheim: 'Vorgebirgsterrasse, A555 Bonn-Köln',
  rheinbach: 'Voreifel-Rand Rhein-Sieg, A61',
  meckenheim: 'A61/A565-Kreuz in der Voreifel',
}
