-- GENERIERT von scripts/kasko-wb/generate-seed-sql.mjs aus scripts/kasko-wb/wissensbasis-2026-07-20.json
-- Quelle: CHECK24 Kfz-Versicherungstarife, Stand 20.07.2026 (71 Marken) + HDI (Broschüre); Auswertung 03.09.2026. Idempotent (Upserts), keine UUIDs, Rechtstraeger-FK per Name (versicherungen-Seed ist nicht versioniert).

-- 1) Marken (72)
INSERT INTO public.kasko_versicherer_marken
  (slug, marke, wb_status, wb_marker, nicht_wb_marker, hinweis, varianten_hinweis, check24_vertrieb, quelle, stand, sortierung)
SELECT v.slug, v.marke, v.wb_status, v.wb_marker, v.nicht_wb_marker, v.hinweis, v.varianten_hinweis, v.check24_vertrieb,
  'CHECK24 Kfz-Versicherungstarife, Stand 20.07.2026 (71 Marken) + HDI (Broschüre); Auswertung 03.09.2026', '2026-07-20'::date, v.sortierung
FROM (VALUES
  ('adac-autoversicherung', 'ADAC Autoversicherung', 'optional', ARRAY['mit Werkstattbonus']::text[], ARRAY['(Mitglieder)']::text[], NULL, 'Der Zusatz „(Mitglieder)“ ändert nichts an der Werkstattwahl.', 'P', 10),
  ('admiraldirekt', 'AdmiralDirekt', 'optional', ARRAY['mit Werkstattbonus']::text[], ARRAY['CHECK24-Sonderrabatt','Junge Fahrer','mit Vorkasse']::text[], 'Vertriebsmarke (Risikoträger Itzehoer); kein eigener Rechtsträger in den Stammdaten.', 'Zusätze wie „CHECK24-Sonderrabatt“ oder „Junge Fahrer“ ändern nichts an der Werkstattwahl.', 'P', 20),
  ('aig-europe', 'AIG Europe', 'keine', '{}'::text[], '{}'::text[], 'Kein Werkstattbindungs-Tarif im Angebot. Rechtsträger in den Stammdaten unter dem Altnamen Chartis Europe S.A.', NULL, 'L', 30),
  ('allianz', 'Allianz', 'optional', ARRAY['WerkstattBonus']::text[], '{}'::text[], NULL, NULL, 'L', 40),
  ('allianz-direct', 'Allianz Direct', 'optional', ARRAY['mit Werkstattbindung']::text[], ARRAY['Vorkasse']::text[], NULL, NULL, 'P', 50),
  ('alte-leipziger', 'Alte Leipziger', 'optional', ARRAY['mit Werkstattservice']::text[], '{}'::text[], NULL, NULL, 'P', 60),
  ('autosan', 'Autosan', 'optional', ARRAY['mit Werkstattbindung']::text[], '{}'::text[], NULL, NULL, 'P', 70),
  ('avd', 'AvD', 'optional', ARRAY['mit Werkstattbindung']::text[], ARRAY['(Mitglieder)']::text[], '„Select“ ist bei AvD ein Linienname, kein Werkstattbindungs-Marker (anders als bei HUK).', 'Der Zusatz „(Mitglieder)“ ändert nichts an der Werkstattwahl.', 'P', 80),
  ('axa', 'AXA', 'optional', ARRAY['mit Werkstattservice']::text[], ARRAY['mit Extraschutz']::text[], NULL, NULL, 'P', 90),
  ('barmenia-direkt', 'Barmenia Direkt', 'optional', ARRAY['mit Werkstattservice']::text[], '{}'::text[], NULL, NULL, 'P', 100),
  ('barmeniagothaer', 'BarmeniaGothaer', 'optional', ARRAY['mit Werkstattservice']::text[], '{}'::text[], 'Zweiter Rechtsträger: Barmenia Allgemeine Versicherungs-AG.', NULL, 'P', 110),
  ('bavariadirekt', 'BavariaDirekt', 'optional', ARRAY['mit Werkstattbindung']::text[], ARRAY['Elektro Paket','Youngtimer','Vorkasse']::text[], NULL, 'Zusätze „Elektro Paket“, „Youngtimer“ oder „Vorkasse“ ändern nichts an der Werkstattwahl.', 'P', 120),
  ('bavariaprotect', 'BavariaProtect', 'optional', ARRAY['mit Werkstattbindung']::text[], ARRAY['Elektro Paket']::text[], NULL, 'Der Zusatz „Elektro Paket“ ändert nichts an der Werkstattwahl.', 'P', 130),
  ('bgv', 'BGV / Badische Versicherungen', 'optional', ARRAY['mit Schadenservice Plus']::text[], ARRAY['Elektro Plus']::text[], 'Bindungscharakter aus der Bezeichnung abgeleitet – AKB prüfen. Zweiter Rechtsträger: Badische Allgemeine Versicherung AG.', 'Der Zusatz „Elektro Plus“ ändert nichts an der Werkstattwahl.', 'P', 140),
  ('concordia', 'Concordia', 'optional', ARRAY['Partner']::text[], ARRAY['VollkaskoPlus','oecodrive']::text[], NULL, NULL, 'P', 150),
  ('cosmosdirekt', 'CosmosDirekt', 'optional', ARRAY['mit Werkstattbindung']::text[], ARRAY['inkl. Verkehrsrechtsschutz']::text[], 'Basis: frühere Recherche nannte die Werkstattbindung im Basis als Pflicht; CHECK24 listet Basis auch ohne – AKB prüfen.', 'Der Zusatz „inkl. Verkehrsrechtsschutz“ ändert nichts an der Werkstattwahl.', 'P', 160),
  ('da-direkt', 'DA Direkt', 'optional', ARRAY['mit Werkstattbindung']::text[], '{}'::text[], NULL, NULL, 'P', 170),
  ('dbv', 'DBV', 'optional', ARRAY['mit Werkstattservice']::text[], '{}'::text[], 'AXA-Gruppe (Systematik wie AXA Werkstattservice).', NULL, 'P', 180),
  ('debeka', 'Debeka', 'optional', ARRAY['mit Unfallreparatur-Service']::text[], '{}'::text[], NULL, NULL, 'L', 190),
  ('devk', 'DEVK', 'optional', ARRAY['Kasko-Mobil']::text[], ARRAY['ACV Mitglieder','Vorkasse']::text[], NULL, 'Zusätze „ACV Mitglieder“ oder „Vorkasse“ ändern nichts an der Werkstattwahl.', 'P', 200),
  ('dialog', 'Dialog', 'optional', ARRAY['WerkstattservicePLUS']::text[], ARRAY['VollkaskoPLUS']::text[], 'Generali-Gruppe; kein eigener Rechtsträger in den Stammdaten.', NULL, 'L', 210),
  ('die-bayerische', 'Die Bayerische', 'optional', ARRAY['mit Werkstattservice']::text[], ARRAY['E-Drive']::text[], NULL, 'Der Zusatz „E-Drive“ ändert nichts an der Werkstattwahl.', 'P', 220),
  ('die-continentale', 'Die Continentale', 'optional', ARRAY['Sorglos-Kasko']::text[], '{}'::text[], NULL, NULL, 'L', 230),
  ('die-lippische', 'Die Lippische', 'optional', ARRAY['Werkstattservice']::text[], '{}'::text[], NULL, NULL, 'L', 240),
  ('ergo', 'ERGO', 'optional', ARRAY['mit Werkstattbonus']::text[], ARRAY['Wertschutz24','Wertschutz36','ErsatzfahrzeugPlus']::text[], NULL, 'Zusätze „mit Wertschutz24/36“ oder „ErsatzfahrzeugPlus“ ändern nichts an der Werkstattwahl.', 'P', 250),
  ('europa', 'Europa', 'optional', ARRAY['Spar-Kasko']::text[], '{}'::text[], NULL, NULL, 'L', 260),
  ('europa-go', 'EUROPA-go', 'optional', ARRAY['Spar-Kasko']::text[], '{}'::text[], 'Online-Marke der EUROPA.', NULL, 'P', 270),
  ('fahrlehrerversicherung', 'Fahrlehrerversicherung', 'optional', ARRAY['mit Werkstattbindung']::text[], '{}'::text[], NULL, NULL, 'P', 280),
  ('feuersozietaet', 'Feuersozietät', 'optional', ARRAY['mit Werkstattservice']::text[], '{}'::text[], 'VKB-Gruppe.', NULL, 'L', 290),
  ('generali', 'Generali', 'optional', ARRAY['mit Werkstattbindung']::text[], '{}'::text[], NULL, NULL, 'L', 300),
  ('gvv-direkt', 'GVV Direkt', 'optional', ARRAY['mit Werkstatt Direkt']::text[], ARRAY['Kasko PLUS']::text[], NULL, NULL, 'P', 310),
  ('hansemerkur', 'HanseMerkur', 'optional', ARRAY['mit Werkstattbindung']::text[], '{}'::text[], NULL, NULL, 'P', 320),
  ('helvetia-baloise', 'Helvetia Baloise', 'optional', ARRAY['mit Werkstattservice']::text[], '{}'::text[], 'Zweiter Rechtsträger: Baloise Sachversicherung AG Deutschland.', NULL, 'L', 330),
  ('huk-coburg', 'HUK-COBURG', 'optional', ARRAY['SELECT','Kasko SELECT']::text[], ARRAY['Kasko PLUS']::text[], 'Zweiter Rechtsträger: HUK-COBURG Haftpflicht-Unterstützungs-Kasse (öffentlicher Dienst).', NULL, 'L', 340),
  ('huk24', 'HUK24', 'optional', ARRAY['SELECT','Kasko SELECT']::text[], ARRAY['Kasko PLUS']::text[], NULL, NULL, 'L', 350),
  ('inshared', 'Inshared', 'optional', ARRAY['mit Werkstattbindung']::text[], '{}'::text[], 'Achmea-Gruppe; kein eigener Rechtsträger in den Stammdaten.', NULL, 'P', 360),
  ('itzehoer', 'Itzehoer', 'optional', ARRAY['mit Werkstattbonus']::text[], '{}'::text[], NULL, NULL, 'L', 370),
  ('janitos', 'Janitos', 'optional', ARRAY['mit Werkstatt-Management']::text[], '{}'::text[], 'HDI-Gruppe; kein eigener Rechtsträger in den Stammdaten.', NULL, 'P', 380),
  ('kravag', 'KRAVAG', 'optional', ARRAY['mit Werkstattservice','Glas']::text[], ARRAY['Kasko Spezial','BleibMobil']::text[], '„Glas“-Varianten vermutlich reine Glas-Bindung – nicht belegt, AKB prüfen. „Kasko Spezial“ und „BleibMobil“ sind keine Bindungs-Marker.', NULL, 'P', 390),
  ('lvm', 'LVM', 'keine', '{}'::text[], ARRAY['mit LVM-SchadenService']::text[], '„mit LVM-SchadenService“ ist ein Steuerungsangebot, keine belegte vertragliche Bindung; LVM wirbt mit freier Werkstattwahl.', NULL, 'L', 400),
  ('mannheimer', 'Mannheimer', 'keine', '{}'::text[], '{}'::text[], 'Kein Werkstattbindungs-Tarif im Angebot.', NULL, 'L', 410),
  ('mecklenburgische', 'Mecklenburgische', 'optional', ARRAY['mit Partnerkasko']::text[], '{}'::text[], NULL, NULL, 'L', 420),
  ('muenchener-verein', 'Münchener Verein', 'keine', '{}'::text[], '{}'::text[], 'Kein Werkstattbindungs-Tarif im Angebot.', NULL, 'P', 430),
  ('neodigital', 'Neodigital', 'optional', ARRAY['mit Werkstattbindung']::text[], '{}'::text[], '„NEO Select“ ist ein Linienname, kein Werkstattbindungs-Marker. Kein Rechtsträger in den Stammdaten.', NULL, 'P', 440),
  ('oeffentliche-braunschweig', 'Öffentliche Braunschweig', 'optional', ARRAY['mit Werkstattservice Plus']::text[], '{}'::text[], NULL, NULL, 'L', 450),
  ('oeffentliche-oldenburg', 'Öffentliche Oldenburg', 'optional', ARRAY['mit Werkstattservice']::text[], '{}'::text[], 'Basis ist nur als Werkstattbindungs-Variante gelistet.', NULL, 'L', 460),
  ('oesa', 'ÖSA', 'optional', ARRAY['mit Werkstattservice']::text[], '{}'::text[], NULL, NULL, 'P', 470),
  ('prokundo', 'Prokundo', 'optional', ARRAY['mit Werkstatt-Service']::text[], '{}'::text[], 'Kein Rechtsträger in den Stammdaten.', NULL, 'P', 480),
  ('provinzial', 'Provinzial', 'optional', ARRAY['mit Werkstattbindung']::text[], '{}'::text[], 'Zweiter Rechtsträger: Westfälische Provinzial Versicherung AG.', NULL, 'L', 490),
  ('provinzial-nord', 'Provinzial Nord', 'optional', ARRAY['mit Werkstattbindung']::text[], ARRAY['Plus-Paket']::text[], NULL, 'Zusätze „Plus-Paket Kfz-Haftpflicht/Kasko“ ändern nichts an der Werkstattwahl.', 'L', 500),
  ('r-plus-v', 'R+V', 'optional', ARRAY['mit Werkstattservice']::text[], ARRAY['Kasko Spezial']::text[], '„Kasko Spezial“ ist KEIN Bindungs-Marker – existiert mit und ohne Werkstattservice.', NULL, 'L', 510),
  ('rheinland', 'RheinLand', 'optional', ARRAY['mit Werkstattservice']::text[], '{}'::text[], NULL, NULL, 'L', 520),
  ('rhion-digital', 'rhion.digital', 'optional', ARRAY['mit Werkstattservice']::text[], '{}'::text[], 'Digitalmarke der RheinLand.', NULL, 'L', 530),
  ('saarland', 'Saarland', 'optional', ARRAY['mit Werkstatt Service']::text[], '{}'::text[], 'VKB-Gruppe.', NULL, 'L', 540),
  ('signal-iduna', 'Signal Iduna', 'optional', ARRAY['Sorglos Kasko','Sorglos Kasko Glas']::text[], '{}'::text[], 'Zwei Stufen: „Sorglos Kasko“ = Vollbindung, „Sorglos Kasko Glas“ = nur Glasschäden (Leasing-Variante).', NULL, 'P', 550),
  ('sparkassen-direkt', 'Sparkassen Direkt', 'optional', ARRAY['mit Werkstattservice']::text[], ARRAY['Mobil','Vorkasse','(Sparkassenkunden)']::text[], 'Vorkasse-Varianten ohne Werkstattbindung.', 'Zusätze „(Sparkassenkunden)“ oder „Vorkasse“ ändern nichts an der Werkstattwahl; „Mobil“ ist der Schutzbrief.', 'P', 560),
  ('sv-sachsen', 'SV Sachsen', 'optional', ARRAY['mit Werkstatt-Management']::text[], ARRAY['KaskoPlus']::text[], NULL, NULL, 'L', 570),
  ('sv-sparkassenversicherung', 'SV SparkassenVersicherung', 'optional', ARRAY['mit Werkstattbindung']::text[], ARRAY['Top-Schutz']::text[], 'Stammdaten-Eintrag ist die Holding.', NULL, 'L', 580),
  ('universa', 'uniVersa', 'optional', ARRAY['mit Werkstatt-Service']::text[], '{}'::text[], NULL, NULL, 'P', 590),
  ('versicherungskammer-bayern', 'Versicherungskammer Bayern', 'optional', ARRAY['mit Werkstattservice']::text[], ARRAY['KaskoPLUS']::text[], NULL, NULL, 'L', 600),
  ('verti', 'Verti', 'optional', ARRAY['Kasko Clever']::text[], ARRAY['Nix-Passiert','Vorkasse']::text[], NULL, 'Zusätze „Nix-Passiert“ oder „Vorkasse“ ändern nichts an der Werkstattwahl.', 'P', 610),
  ('vgh', 'VGH', 'optional', ARRAY['mit Werkstattservice']::text[], '{}'::text[], NULL, NULL, 'L', 620),
  ('vhv', 'VHV', 'optional', ARRAY['Schadenservice PLUS mit Werkstattservice']::text[], ARRAY['EXKLUSIV','mit gesetzlicher Mindestdeckung']::text[], NULL, NULL, 'P', 630),
  ('voedag', 'VÖDAG', 'optional', ARRAY['Sorglos Kasko','Sorglos Kasko Glas']::text[], '{}'::text[], 'Tarifsystematik identisch mit Signal Iduna. Kein Rechtsträger in den Stammdaten.', NULL, 'P', 640),
  ('volkswagen-autoversicherung', 'Volkswagen Autoversicherung', 'standard', ARRAY['mit Werkstattbindung']::text[], '{}'::text[], 'Alle gelisteten Tarife ausschließlich als Werkstattbindungs-Varianten. Kein Rechtsträger in den Stammdaten.', NULL, 'L', 650),
  ('volkswohl-bund', 'Volkswohl-Bund', 'optional', ARRAY['mit Werkstattservice']::text[], '{}'::text[], NULL, NULL, 'L', 660),
  ('vrk', 'VRK', 'optional', ARRAY['Select']::text[], ARRAY['Kasko Plus']::text[], 'HUK-Systematik (Versicherer im Raum der Kirchen).', NULL, 'L', 670),
  ('wgv', 'WGV', 'optional', ARRAY['Kasko SELECT']::text[], '{}'::text[], NULL, NULL, 'P', 680),
  ('wuerttembergische', 'Württembergische', 'optional', ARRAY['mit Schadenservice+']::text[], '{}'::text[], 'Bindungscharakter aus der Bezeichnung abgeleitet – AKB prüfen.', NULL, 'L', 690),
  ('wwk', 'WWK', 'optional', ARRAY['mit Werkstattmanagement']::text[], ARRAY['XtraSchutz']::text[], NULL, 'Der Zusatz „mit XtraSchutz“ ändert nichts an der Werkstattwahl.', 'L', 700),
  ('zurich', 'Zurich', 'optional', ARRAY['mit Werkstattbindung']::text[], '{}'::text[], NULL, NULL, 'L', 710),
  ('hdi', 'HDI', 'optional', ARRAY['Werkstattbindung','Partnerwerkstatt']::text[], ARRAY['Freie Werkstattwahl (nur für private Pkw)']::text[], 'Nicht in der CHECK24-Liste. Werkstattbindungs-Baustein laut HDI-Broschüre vorhanden (Bezeichnung und Nachlass nicht belegt); Alternative „Freie Werkstattwahl (nur für private Pkw)“ = keine Bindung. Ohne Tarifliste – Rückfrage am Versicherungsschein.', NULL, NULL, 720)
) AS v(slug, marke, wb_status, wb_marker, nicht_wb_marker, hinweis, varianten_hinweis, check24_vertrieb, sortierung)
ON CONFLICT (slug) DO UPDATE SET marke = EXCLUDED.marke, wb_status = EXCLUDED.wb_status, wb_marker = EXCLUDED.wb_marker,
  nicht_wb_marker = EXCLUDED.nicht_wb_marker, hinweis = EXCLUDED.hinweis, varianten_hinweis = EXCLUDED.varianten_hinweis,
  check24_vertrieb = EXCLUDED.check24_vertrieb, quelle = EXCLUDED.quelle, stand = EXCLUDED.stand, sortierung = EXCLUDED.sortierung,
  aktualisiert_am = now();

-- 2) Rechtstraeger-Backfill per Name (60; nur wenn noch leer)
UPDATE public.kasko_versicherer_marken m SET versicherung_id = v.id
FROM (VALUES
  ('adac-autoversicherung', 'ADAC Autoversicherung AG'),
  ('aig-europe', 'Chartis Europe S.A.'),
  ('allianz', 'Allianz Versicherungs-AG'),
  ('allianz-direct', 'Allianz Direct'),
  ('alte-leipziger', 'Alte Leipziger Versicherung AG'),
  ('axa', 'AXA Versicherung AG'),
  ('barmenia-direkt', 'Barmenia Allgemeine Versicherungs-AG'),
  ('barmeniagothaer', 'Gothaer Allgemeine Versicherung AG'),
  ('bgv', 'Badischer Gemeinde-Versicherungs-Verband'),
  ('concordia', 'Concordia Versicherungs-Gesellschaft a.G.'),
  ('cosmosdirekt', 'Cosmos Versicherung AG'),
  ('da-direkt', 'DA Deutsche Allgemeine Versicherung AG'),
  ('dbv', 'DBV Deutsche Beamten-Versicherung AG'),
  ('debeka', 'Debeka Allgemeine Versicherung AG'),
  ('devk', 'DEVK Allgemeine Versicherungs-AG'),
  ('die-bayerische', 'Bayerische Beamten Versicherung AG'),
  ('die-continentale', 'Continentale Sachversicherung AG'),
  ('die-lippische', 'Lippische Landesbrandversicherung AG'),
  ('ergo', 'ERGO Versicherung AG'),
  ('europa', 'EUROPA Sachversicherung AG'),
  ('europa-go', 'EUROPA Sachversicherung AG'),
  ('fahrlehrerversicherung', 'Fahrlehrerversicherung VaG'),
  ('feuersozietaet', 'Feuersozietät Berlin Brandenburg Versicherung AG'),
  ('generali', 'Generali Deutschland Versicherung AG'),
  ('gvv-direkt', 'GVV-Privatversicherung AG'),
  ('hansemerkur', 'HanseMerkur Allgemeine Versicherung AG'),
  ('helvetia-baloise', 'Helvetia Schweizerische Versicherungsgesellschaft AG'),
  ('huk-coburg', 'HUK-COBURG-Allgemeine Versicherung AG'),
  ('huk24', 'HUK24 AG'),
  ('itzehoer', 'Itzehoer Versicherung Brandgilde von 1691 VVaG'),
  ('kravag', 'KRAVAG-ALLGEMEINE Versicherungs-AG'),
  ('lvm', 'LVM Landwirtschaftlicher Versicherungsverein Münster a.G.'),
  ('mannheimer', 'Mannheimer Versicherung AG'),
  ('mecklenburgische', 'Mecklenburgische Versicherungs-Gesellschaft a.G.'),
  ('muenchener-verein', 'Münchener Verein Allgemeine Versicherungs-AG'),
  ('oeffentliche-braunschweig', 'Öffentliche Versicherung Braunschweig'),
  ('oeffentliche-oldenburg', 'Öffentliche Versicherung Oldenburg'),
  ('oesa', 'Öffentliche Feuerversicherung Sachsen-Anhalt'),
  ('provinzial', 'Provinzial Rheinland Versicherung AG'),
  ('provinzial-nord', 'Provinzial Nord Brandkasse AG'),
  ('r-plus-v', 'R+V Allgemeine Versicherung AG'),
  ('rheinland', 'Rheinland Versicherungs AG'),
  ('rhion-digital', 'Rheinland Versicherungs AG'),
  ('saarland', 'Saarland Feuerversicherung AG'),
  ('signal-iduna', 'Signal Iduna Allgemeine Versicherung AG'),
  ('sparkassen-direkt', 'Sparkassen DirektVersicherung AG'),
  ('sv-sachsen', 'Sparkassen-Versicherung Sachsen'),
  ('sv-sparkassenversicherung', 'SV Sparkassen-Versicherung Holding AG'),
  ('universa', 'UniVersa Allgemeine Versicherung AG'),
  ('versicherungskammer-bayern', 'Versicherungskammer Bayern'),
  ('verti', 'Verti Versicherung AG'),
  ('vgh', 'VGH Landschaftliche Brandkasse Hannover'),
  ('vhv', 'VHV Allgemeine Versicherung AG'),
  ('volkswohl-bund', 'VOLKSWOHL-BUND Sachversicherung AG'),
  ('vrk', 'Bruderhilfe Sachversicherung AG im Raum der Kirchen'),
  ('wgv', 'WGV-Versicherung AG'),
  ('wuerttembergische', 'Württembergische Versicherung AG'),
  ('wwk', 'WWK Allgemeine Versicherung AG'),
  ('zurich', 'Zurich Insurance plc'),
  ('hdi', 'HDI Versicherung AG')
) AS x(slug, versicherung_name)
JOIN public.versicherungen v ON v.name = x.versicherung_name
WHERE m.slug = x.slug AND m.versicherung_id IS NULL;

-- 3) Tarife (408 Zeilen; Spalten: slug, linie, wb_zusatz, anzeigename, hat_werkstattbindung, bindungsumfang, verlaesslichkeit, reihenfolge)
INSERT INTO public.kasko_tarife (marke_id, linie, wb_zusatz, anzeigename, hat_werkstattbindung, bindungsumfang, verlaesslichkeit, reihenfolge)
SELECT m.id, t.linie, t.wb_zusatz, t.anzeigename, t.hat_werkstattbindung, t.bindungsumfang, t.verlaesslichkeit, t.reihenfolge
FROM (VALUES
  ('adac-autoversicherung', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('adac-autoversicherung', 'Basis', 'mit Werkstattbonus', 'Basis mit Werkstattbonus', true, 'voll', 'belegt', 20),
  ('adac-autoversicherung', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 30),
  ('adac-autoversicherung', 'Komfort', 'mit Werkstattbonus', 'Komfort mit Werkstattbonus', true, 'voll', 'belegt', 40),
  ('adac-autoversicherung', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 50),
  ('adac-autoversicherung', 'Premium', 'mit Werkstattbonus', 'Premium mit Werkstattbonus', true, 'voll', 'belegt', 60),
  ('admiraldirekt', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('admiraldirekt', 'Basis', 'mit Werkstattbonus', 'Basis mit Werkstattbonus', true, 'voll', 'belegt', 20),
  ('admiraldirekt', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 30),
  ('admiraldirekt', 'Komfort', 'mit Werkstattbonus', 'Komfort mit Werkstattbonus', true, 'voll', 'belegt', 40),
  ('admiraldirekt', 'Komfort smart', NULL, 'Komfort smart', false, 'keine', 'belegt', 50),
  ('admiraldirekt', 'Komfort smart', 'mit Werkstattbonus', 'Komfort smart mit Werkstattbonus', true, 'voll', 'belegt', 60),
  ('admiraldirekt', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 70),
  ('admiraldirekt', 'Premium', 'mit Werkstattbonus', 'Premium mit Werkstattbonus', true, 'voll', 'belegt', 80),
  ('admiraldirekt', 'Premium smart', NULL, 'Premium smart', false, 'keine', 'belegt', 90),
  ('admiraldirekt', 'Premium smart', 'mit Werkstattbonus', 'Premium smart mit Werkstattbonus', true, 'voll', 'belegt', 100),
  ('admiraldirekt', 'Basis mit Vorkasse', NULL, 'Basis mit Vorkasse', false, 'keine', 'belegt', 110),
  ('aig-europe', 'AIG Europe (Einzeltarif)', NULL, 'AIG Europe (Einzeltarif)', false, 'keine', 'belegt', 10),
  ('allianz', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 10),
  ('allianz', 'Komfort', 'WerkstattBonus', 'Komfort WerkstattBonus', true, 'voll', 'belegt', 20),
  ('allianz', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 30),
  ('allianz', 'Premium', 'WerkstattBonus', 'Premium WerkstattBonus', true, 'voll', 'belegt', 40),
  ('allianz-direct', 'DIRECT', NULL, 'DIRECT', false, 'keine', 'belegt', 10),
  ('allianz-direct', 'DIRECT', 'mit Werkstattbindung', 'DIRECT mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('allianz-direct', 'DIRECT Plus', NULL, 'DIRECT Plus', false, 'keine', 'belegt', 30),
  ('allianz-direct', 'DIRECT Plus', 'mit Werkstattbindung', 'DIRECT Plus mit Werkstattbindung', true, 'voll', 'belegt', 40),
  ('allianz-direct', 'DIRECT Vorkasse', NULL, 'DIRECT Vorkasse', false, 'keine', 'belegt', 50),
  ('alte-leipziger', 'Classic', NULL, 'Classic', false, 'keine', 'belegt', 10),
  ('alte-leipziger', 'Classic', 'mit Werkstattservice', 'Classic mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('alte-leipziger', 'Comfort', NULL, 'Comfort', false, 'keine', 'belegt', 30),
  ('alte-leipziger', 'Comfort', 'mit Werkstattservice', 'Comfort mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('alte-leipziger', 'Compact', NULL, 'Compact', false, 'keine', 'belegt', 50),
  ('autosan', 'Serie', NULL, 'Serie', false, 'keine', 'belegt', 10),
  ('autosan', 'Serie', 'mit Werkstattbindung', 'Serie mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('autosan', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 30),
  ('autosan', 'Komfort', 'mit Werkstattbindung', 'Komfort mit Werkstattbindung', true, 'voll', 'belegt', 40),
  ('avd', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 10),
  ('avd', 'Komfort', 'mit Werkstattbindung', 'Komfort mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('avd', 'Plus', NULL, 'Plus', false, 'keine', 'belegt', 30),
  ('avd', 'Plus', 'mit Werkstattbindung', 'Plus mit Werkstattbindung', true, 'voll', 'belegt', 40),
  ('avd', 'Select', NULL, 'Select', false, 'keine', 'belegt', 50),
  ('avd', 'Select', 'mit Werkstattbindung', 'Select mit Werkstattbindung', true, 'voll', 'belegt', 60),
  ('axa', 'easy mobil online S', NULL, 'easy mobil online S', false, 'keine', 'belegt', 10),
  ('axa', 'easy mobil online S', 'mit Werkstattservice', 'easy mobil online S mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('axa', 'easy mobil online S Plus', NULL, 'easy mobil online S Plus', false, 'keine', 'belegt', 30),
  ('axa', 'easy mobil online S Plus', 'mit Werkstattservice', 'easy mobil online S Plus mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('axa', 'easy mobil online M', NULL, 'easy mobil online M', false, 'keine', 'belegt', 50),
  ('axa', 'easy mobil online M', 'mit Werkstattservice', 'easy mobil online M mit Werkstattservice', true, 'voll', 'belegt', 60),
  ('axa', 'easy mobil online L', NULL, 'easy mobil online L', false, 'keine', 'belegt', 70),
  ('axa', 'easy mobil online L', 'mit Werkstattservice', 'easy mobil online L mit Werkstattservice', true, 'voll', 'belegt', 80),
  ('axa', 'easy mobil online', NULL, 'easy mobil online', false, 'keine', 'belegt', 90),
  ('axa', 'easy mobil online mit Extraschutz', NULL, 'easy mobil online mit Extraschutz', false, 'keine', 'belegt', 100),
  ('barmenia-direkt', 'Basis-Schutz', NULL, 'Basis-Schutz', false, 'keine', 'belegt', 10),
  ('barmenia-direkt', 'Basis-Schutz', 'mit Werkstattservice', 'Basis-Schutz mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('barmenia-direkt', 'Top-Schutz', NULL, 'Top-Schutz', false, 'keine', 'belegt', 30),
  ('barmenia-direkt', 'Top-Schutz', 'mit Werkstattservice', 'Top-Schutz mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('barmenia-direkt', 'Premium-Schutz', NULL, 'Premium-Schutz', false, 'keine', 'belegt', 50),
  ('barmenia-direkt', 'Premium-Schutz', 'mit Werkstattservice', 'Premium-Schutz mit Werkstattservice', true, 'voll', 'belegt', 60),
  ('barmenia-direkt', 'Premium Plus-Schutz', NULL, 'Premium Plus-Schutz', false, 'keine', 'belegt', 70),
  ('barmenia-direkt', 'Premium Plus-Schutz', 'mit Werkstattservice', 'Premium Plus-Schutz mit Werkstattservice', true, 'voll', 'belegt', 80),
  ('barmeniagothaer', 'Privat', NULL, 'Privat', false, 'keine', 'belegt', 10),
  ('barmeniagothaer', 'Privat', 'mit Werkstattservice', 'Privat mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('barmeniagothaer', 'Privat Top-Schutz', NULL, 'Privat Top-Schutz', false, 'keine', 'belegt', 30),
  ('barmeniagothaer', 'Privat Top-Schutz', 'mit Werkstattservice', 'Privat Top-Schutz mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('barmeniagothaer', 'Privat Premium-Schutz', NULL, 'Privat Premium-Schutz', false, 'keine', 'belegt', 50),
  ('barmeniagothaer', 'Privat Premium-Schutz', 'mit Werkstattservice', 'Privat Premium-Schutz mit Werkstattservice', true, 'voll', 'belegt', 60),
  ('bavariadirekt', 'Komfort S online', NULL, 'Komfort S online', false, 'keine', 'belegt', 10),
  ('bavariadirekt', 'Komfort S online', 'mit Werkstattbindung', 'Komfort S online mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('bavariadirekt', 'Komfort M online', NULL, 'Komfort M online', false, 'keine', 'belegt', 30),
  ('bavariadirekt', 'Komfort M online', 'mit Werkstattbindung', 'Komfort M online mit Werkstattbindung', true, 'voll', 'belegt', 40),
  ('bavariadirekt', 'Komfort M Plus online', NULL, 'Komfort M Plus online', false, 'keine', 'belegt', 50),
  ('bavariadirekt', 'Komfort M Plus online', 'mit Werkstattbindung', 'Komfort M Plus online mit Werkstattbindung', true, 'voll', 'belegt', 60),
  ('bavariadirekt', 'Komfort L online', NULL, 'Komfort L online', false, 'keine', 'belegt', 70),
  ('bavariadirekt', 'Komfort L online', 'mit Werkstattbindung', 'Komfort L online mit Werkstattbindung', true, 'voll', 'belegt', 80),
  ('bavariaprotect', 'Komfort S online', NULL, 'Komfort S online', false, 'keine', 'belegt', 10),
  ('bavariaprotect', 'Komfort S online', 'mit Werkstattbindung', 'Komfort S online mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('bavariaprotect', 'Komfort M online', NULL, 'Komfort M online', false, 'keine', 'belegt', 30),
  ('bavariaprotect', 'Komfort M online', 'mit Werkstattbindung', 'Komfort M online mit Werkstattbindung', true, 'voll', 'belegt', 40),
  ('bavariaprotect', 'Komfort M Plus online', NULL, 'Komfort M Plus online', false, 'keine', 'belegt', 50),
  ('bavariaprotect', 'Komfort M Plus online', 'mit Werkstattbindung', 'Komfort M Plus online mit Werkstattbindung', true, 'voll', 'belegt', 60),
  ('bavariaprotect', 'Komfort L online', NULL, 'Komfort L online', false, 'keine', 'belegt', 70),
  ('bavariaprotect', 'Komfort L online', 'mit Werkstattbindung', 'Komfort L online mit Werkstattbindung', true, 'voll', 'belegt', 80),
  ('bgv', 'Basis', NULL, 'Basis', false, 'keine', 'abgeleitet', 10),
  ('bgv', 'Basis', 'mit Schadenservice Plus', 'Basis mit Schadenservice Plus', true, 'voll', 'abgeleitet', 20),
  ('bgv', 'Klassik', NULL, 'Klassik', false, 'keine', 'abgeleitet', 30),
  ('bgv', 'Klassik', 'mit Schadenservice Plus', 'Klassik mit Schadenservice Plus', true, 'voll', 'abgeleitet', 40),
  ('bgv', 'Exklusiv', NULL, 'Exklusiv', false, 'keine', 'abgeleitet', 50),
  ('bgv', 'Exklusiv', 'mit Schadenservice Plus', 'Exklusiv mit Schadenservice Plus', true, 'voll', 'abgeleitet', 60),
  ('concordia', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 10),
  ('concordia', 'Premium', 'Partner', 'Premium Partner', true, 'voll', 'belegt', 20),
  ('concordia', 'Premium VollkaskoPlus', NULL, 'Premium VollkaskoPlus', false, 'keine', 'belegt', 30),
  ('concordia', 'Premium VollkaskoPlus', 'Partner', 'Premium VollkaskoPlus Partner', true, 'voll', 'belegt', 40),
  ('concordia', 'Classic', NULL, 'Classic', false, 'keine', 'belegt', 50),
  ('concordia', 'Premium oecodrive', NULL, 'Premium oecodrive', false, 'keine', 'belegt', 60),
  ('concordia', 'Premium VollkaskoPlus oecodrive', NULL, 'Premium VollkaskoPlus oecodrive', false, 'keine', 'belegt', 70),
  ('cosmosdirekt', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('cosmosdirekt', 'Basis', 'mit Werkstattbindung', 'Basis mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('cosmosdirekt', 'Comfort', NULL, 'Comfort', false, 'keine', 'belegt', 30),
  ('cosmosdirekt', 'Comfort', 'mit Werkstattbindung', 'Comfort mit Werkstattbindung', true, 'voll', 'belegt', 40),
  ('da-direkt', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('da-direkt', 'Basis', 'mit Werkstattbindung', 'Basis mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('da-direkt', 'Komfort Smart', NULL, 'Komfort Smart', false, 'keine', 'belegt', 30),
  ('da-direkt', 'Komfort Smart', 'mit Werkstattbindung', 'Komfort Smart mit Werkstattbindung', true, 'voll', 'belegt', 40),
  ('da-direkt', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 50),
  ('da-direkt', 'Komfort', 'mit Werkstattbindung', 'Komfort mit Werkstattbindung', true, 'voll', 'belegt', 60),
  ('da-direkt', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 70),
  ('da-direkt', 'Premium', 'mit Werkstattbindung', 'Premium mit Werkstattbindung', true, 'voll', 'belegt', 80),
  ('da-direkt', 'Komfort Plus', NULL, 'Komfort Plus', false, 'keine', 'belegt', 90),
  ('dbv', 'mobil kompakt Online', NULL, 'mobil kompakt Online', false, 'keine', 'belegt', 10),
  ('dbv', 'mobil kompakt Online', 'mit Werkstattservice', 'mobil kompakt Online mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('dbv', 'mobil komfort Online', NULL, 'mobil komfort Online', false, 'keine', 'belegt', 30),
  ('dbv', 'mobil komfort Online', 'mit Werkstattservice', 'mobil komfort Online mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('dbv', 'mobil komfort Premium Online', NULL, 'mobil komfort Premium Online', false, 'keine', 'belegt', 50),
  ('dbv', 'mobil komfort Premium Online', 'mit Werkstattservice', 'mobil komfort Premium Online mit Werkstattservice', true, 'voll', 'belegt', 60),
  ('debeka', 'Comfort', NULL, 'Comfort', false, 'keine', 'belegt', 10),
  ('debeka', 'Comfort', 'mit Unfallreparatur-Service', 'Comfort mit Unfallreparatur-Service', true, 'voll', 'belegt', 20),
  ('debeka', 'Comfort Plus', NULL, 'Comfort Plus', false, 'keine', 'belegt', 30),
  ('debeka', 'Comfort Plus', 'mit Unfallreparatur-Service', 'Comfort Plus mit Unfallreparatur-Service', true, 'voll', 'belegt', 40),
  ('devk', 'Basis-Schutz', NULL, 'Basis-Schutz', false, 'keine', 'belegt', 10),
  ('devk', 'Basis-Schutz', 'Kasko-Mobil', 'Basis-Schutz Kasko-Mobil', true, 'voll', 'belegt', 20),
  ('devk', 'Komfort-Schutz', NULL, 'Komfort-Schutz', false, 'keine', 'belegt', 30),
  ('devk', 'Komfort-Schutz', 'Kasko-Mobil', 'Komfort-Schutz Kasko-Mobil', true, 'voll', 'belegt', 40),
  ('devk', 'Premium-Schutz', NULL, 'Premium-Schutz', false, 'keine', 'belegt', 50),
  ('devk', 'Premium-Schutz', 'Kasko-Mobil', 'Premium-Schutz Kasko-Mobil', true, 'voll', 'belegt', 60),
  ('devk', 'DEVK Eisenbahn Basis', NULL, 'DEVK Eisenbahn Basis', false, 'keine', 'belegt', 70),
  ('devk', 'DEVK Eisenbahn Basis', 'Kasko-Mobil', 'DEVK Eisenbahn Basis Kasko-Mobil', true, 'voll', 'belegt', 80),
  ('devk', 'DEVK Eisenbahn Komfort', NULL, 'DEVK Eisenbahn Komfort', false, 'keine', 'belegt', 90),
  ('devk', 'DEVK Eisenbahn Komfort', 'Kasko-Mobil', 'DEVK Eisenbahn Komfort Kasko-Mobil', true, 'voll', 'belegt', 100),
  ('devk', 'DEVK Eisenbahn Premium', NULL, 'DEVK Eisenbahn Premium', false, 'keine', 'belegt', 110),
  ('devk', 'DEVK Eisenbahn Premium', 'Kasko-Mobil', 'DEVK Eisenbahn Premium Kasko-Mobil', true, 'voll', 'belegt', 120),
  ('dialog', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 10),
  ('dialog', 'Premium', 'WerkstattservicePLUS', 'Premium WerkstattservicePLUS', true, 'voll', 'belegt', 20),
  ('dialog', 'Premium VollkaskoPLUS', NULL, 'Premium VollkaskoPLUS', false, 'keine', 'belegt', 30),
  ('dialog', 'Premium VollkaskoPLUS', 'WerkstattservicePLUS', 'Premium VollkaskoPLUS WerkstattservicePLUS', true, 'voll', 'belegt', 40),
  ('die-bayerische', 'Smart', NULL, 'Smart', false, 'keine', 'belegt', 10),
  ('die-bayerische', 'Smart', 'mit Werkstattservice', 'Smart mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('die-bayerische', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 30),
  ('die-bayerische', 'Komfort', 'mit Werkstattservice', 'Komfort mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('die-bayerische', 'Prestige', NULL, 'Prestige', false, 'keine', 'belegt', 50),
  ('die-bayerische', 'Prestige', 'mit Werkstattservice', 'Prestige mit Werkstattservice', true, 'voll', 'belegt', 60),
  ('die-continentale', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('die-continentale', 'Basis', 'Sorglos-Kasko', 'Basis Sorglos-Kasko', true, 'voll', 'belegt', 20),
  ('die-continentale', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 30),
  ('die-continentale', 'Komfort', 'Sorglos-Kasko', 'Komfort Sorglos-Kasko', true, 'voll', 'belegt', 40),
  ('die-lippische', 'AutoBasis', NULL, 'AutoBasis', false, 'keine', 'belegt', 10),
  ('die-lippische', 'AutoBasis', 'Werkstattservice', 'AutoBasis Werkstattservice', true, 'voll', 'belegt', 20),
  ('die-lippische', 'AutoPlus', NULL, 'AutoPlus', false, 'keine', 'belegt', 30),
  ('die-lippische', 'AutoPlus', 'Werkstattservice', 'AutoPlus Werkstattservice', true, 'voll', 'belegt', 40),
  ('ergo', 'Smart', NULL, 'Smart', false, 'keine', 'belegt', 10),
  ('ergo', 'Smart', 'mit Werkstattbonus', 'Smart mit Werkstattbonus', true, 'voll', 'belegt', 20),
  ('ergo', 'Best', NULL, 'Best', false, 'keine', 'belegt', 30),
  ('ergo', 'Best', 'mit Werkstattbonus', 'Best mit Werkstattbonus', true, 'voll', 'belegt', 40),
  ('europa', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('europa', 'Basis', 'Spar-Kasko', 'Basis Spar-Kasko', true, 'voll', 'belegt', 20),
  ('europa', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 30),
  ('europa', 'Komfort', 'Spar-Kasko', 'Komfort Spar-Kasko', true, 'voll', 'belegt', 40),
  ('europa-go', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('europa-go', 'Basis', 'Spar-Kasko', 'Basis Spar-Kasko', true, 'voll', 'belegt', 20),
  ('europa-go', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 30),
  ('europa-go', 'Komfort', 'Spar-Kasko', 'Komfort Spar-Kasko', true, 'voll', 'belegt', 40),
  ('fahrlehrerversicherung', 'B-Tarif Basis', NULL, 'B-Tarif Basis', false, 'keine', 'belegt', 10),
  ('fahrlehrerversicherung', 'B-Tarif Basis', 'mit Werkstattbindung', 'B-Tarif Basis mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('fahrlehrerversicherung', 'B-Tarif Komfort', NULL, 'B-Tarif Komfort', false, 'keine', 'belegt', 30),
  ('fahrlehrerversicherung', 'B-Tarif Komfort', 'mit Werkstattbindung', 'B-Tarif Komfort mit Werkstattbindung', true, 'voll', 'belegt', 40),
  ('fahrlehrerversicherung', 'B-Tarif Premium', NULL, 'B-Tarif Premium', false, 'keine', 'belegt', 50),
  ('fahrlehrerversicherung', 'B-Tarif Premium', 'mit Werkstattbindung', 'B-Tarif Premium mit Werkstattbindung', true, 'voll', 'belegt', 60),
  ('fahrlehrerversicherung', 'P-Tarif Basis', NULL, 'P-Tarif Basis', false, 'keine', 'belegt', 70),
  ('fahrlehrerversicherung', 'P-Tarif Basis', 'mit Werkstattbindung', 'P-Tarif Basis mit Werkstattbindung', true, 'voll', 'belegt', 80),
  ('fahrlehrerversicherung', 'P-Tarif Komfort', NULL, 'P-Tarif Komfort', false, 'keine', 'belegt', 90),
  ('fahrlehrerversicherung', 'P-Tarif Komfort', 'mit Werkstattbindung', 'P-Tarif Komfort mit Werkstattbindung', true, 'voll', 'belegt', 100),
  ('fahrlehrerversicherung', 'P-Tarif Premium', NULL, 'P-Tarif Premium', false, 'keine', 'belegt', 110),
  ('fahrlehrerversicherung', 'P-Tarif Premium', 'mit Werkstattbindung', 'P-Tarif Premium mit Werkstattbindung', true, 'voll', 'belegt', 120),
  ('fahrlehrerversicherung', 'X-Tarif Basis', NULL, 'X-Tarif Basis', false, 'keine', 'belegt', 130),
  ('fahrlehrerversicherung', 'X-Tarif Basis', 'mit Werkstattbindung', 'X-Tarif Basis mit Werkstattbindung', true, 'voll', 'belegt', 140),
  ('fahrlehrerversicherung', 'X-Tarif Komfort', NULL, 'X-Tarif Komfort', false, 'keine', 'belegt', 150),
  ('fahrlehrerversicherung', 'X-Tarif Komfort', 'mit Werkstattbindung', 'X-Tarif Komfort mit Werkstattbindung', true, 'voll', 'belegt', 160),
  ('fahrlehrerversicherung', 'X-Tarif Premium', NULL, 'X-Tarif Premium', false, 'keine', 'belegt', 170),
  ('fahrlehrerversicherung', 'X-Tarif Premium', 'mit Werkstattbindung', 'X-Tarif Premium mit Werkstattbindung', true, 'voll', 'belegt', 180),
  ('feuersozietaet', 'Vario', NULL, 'Vario', false, 'keine', 'belegt', 10),
  ('feuersozietaet', 'Vario', 'mit Werkstattservice', 'Vario mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('feuersozietaet', 'Vario Kasko-Plus', NULL, 'Vario Kasko-Plus', false, 'keine', 'belegt', 30),
  ('feuersozietaet', 'Vario Kasko-Plus', 'mit Werkstattservice', 'Vario Kasko-Plus mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('feuersozietaet', 'Vario Kasko-Plus mit Elektro/Hybrid', NULL, 'Vario Kasko-Plus mit Elektro/Hybrid', false, 'keine', 'belegt', 50),
  ('feuersozietaet', 'Vario Kasko-Plus mit Elektro/Hybrid', 'mit Werkstattservice', 'Vario Kasko-Plus mit Elektro/Hybrid mit Werkstattservice', true, 'voll', 'belegt', 60),
  ('generali', 'Optimal', NULL, 'Optimal', false, 'keine', 'belegt', 10),
  ('generali', 'Optimal', 'mit Werkstattbindung', 'Optimal mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('gvv-direkt', 'Classic', NULL, 'Classic', false, 'keine', 'belegt', 10),
  ('gvv-direkt', 'Classic', 'mit Werkstatt Direkt', 'Classic mit Werkstatt Direkt', true, 'voll', 'belegt', 20),
  ('gvv-direkt', 'Classic Kasko PLUS', NULL, 'Classic Kasko PLUS', false, 'keine', 'belegt', 30),
  ('gvv-direkt', 'Classic Kasko PLUS', 'mit Werkstatt Direkt', 'Classic Kasko PLUS mit Werkstatt Direkt', true, 'voll', 'belegt', 40),
  ('gvv-direkt', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 50),
  ('hansemerkur', 'Drive Easy', NULL, 'Drive Easy', false, 'keine', 'belegt', 10),
  ('hansemerkur', 'Drive Easy', 'mit Werkstattbindung', 'Drive Easy mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('hansemerkur', 'Drive Best', NULL, 'Drive Best', false, 'keine', 'belegt', 30),
  ('hansemerkur', 'Drive Best', 'mit Werkstattbindung', 'Drive Best mit Werkstattbindung', true, 'voll', 'belegt', 40),
  ('hansemerkur', 'Drive Smart', NULL, 'Drive Smart', false, 'keine', 'belegt', 50),
  ('helvetia-baloise', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('helvetia-baloise', 'Basis', 'mit Werkstattservice', 'Basis mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('helvetia-baloise', 'All-in', NULL, 'All-in', false, 'keine', 'belegt', 30),
  ('helvetia-baloise', 'All-in', 'mit Werkstattservice', 'All-in mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('huk-coburg', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('huk-coburg', 'Basis', 'SELECT', 'Basis SELECT', true, 'voll', 'belegt', 20),
  ('huk-coburg', 'Classic', NULL, 'Classic', false, 'keine', 'belegt', 30),
  ('huk-coburg', 'Classic', 'SELECT', 'Classic SELECT', true, 'voll', 'belegt', 40),
  ('huk-coburg', 'Classic Kasko PLUS', NULL, 'Classic Kasko PLUS', false, 'keine', 'belegt', 50),
  ('huk-coburg', 'Classic Kasko PLUS', 'SELECT', 'Classic Kasko PLUS SELECT', true, 'voll', 'belegt', 60),
  ('huk24', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('huk24', 'Basis', 'SELECT', 'Basis SELECT', true, 'voll', 'belegt', 20),
  ('huk24', 'Classic', NULL, 'Classic', false, 'keine', 'belegt', 30),
  ('huk24', 'Classic', 'SELECT', 'Classic SELECT', true, 'voll', 'belegt', 40),
  ('huk24', 'Classic Kasko PLUS', NULL, 'Classic Kasko PLUS', false, 'keine', 'belegt', 50),
  ('huk24', 'Classic Kasko PLUS', 'SELECT', 'Classic Kasko PLUS SELECT', true, 'voll', 'belegt', 60),
  ('inshared', 'Kfz-Versicherung', NULL, 'Kfz-Versicherung', false, 'keine', 'belegt', 10),
  ('inshared', 'Kfz-Versicherung', 'mit Werkstattbindung', 'Kfz-Versicherung mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('inshared', 'Kfz-Versicherung mit Auslandsschadenschutz', NULL, 'Kfz-Versicherung mit Auslandsschadenschutz', false, 'keine', 'belegt', 30),
  ('inshared', 'Kfz-Versicherung mit Auslandsschadenschutz', 'mit Werkstattbindung', 'Kfz-Versicherung mit Auslandsschadenschutz mit Werkstattbindung', true, 'voll', 'belegt', 40),
  ('itzehoer', 'Comfort Drive', NULL, 'Comfort Drive', false, 'keine', 'belegt', 10),
  ('itzehoer', 'Comfort Drive', 'mit Werkstattbonus', 'Comfort Drive mit Werkstattbonus', true, 'voll', 'belegt', 20),
  ('itzehoer', 'TopDrive', NULL, 'TopDrive', false, 'keine', 'belegt', 30),
  ('itzehoer', 'TopDrive', 'mit Werkstattbonus', 'TopDrive mit Werkstattbonus', true, 'voll', 'belegt', 40),
  ('janitos', 'Compact', NULL, 'Compact', false, 'keine', 'belegt', 10),
  ('janitos', 'Compact', 'mit Werkstatt-Management', 'Compact mit Werkstatt-Management', true, 'voll', 'belegt', 20),
  ('janitos', 'Advanced', NULL, 'Advanced', false, 'keine', 'belegt', 30),
  ('janitos', 'Advanced', 'mit Werkstatt-Management', 'Advanced mit Werkstatt-Management', true, 'voll', 'belegt', 40),
  ('kravag', 'KfzPolice Kompakt', NULL, 'KfzPolice Kompakt', false, 'keine', 'belegt', 10),
  ('kravag', 'KfzPolice Kompakt', 'mit Werkstattservice', 'KfzPolice Kompakt mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('kravag', 'KfzPolice Kompakt', 'Glas', 'KfzPolice Kompakt Glas', true, 'nur_glas', 'nicht_belegt', 30),
  ('kravag', 'KfzPolice Kompakt BleibMobil', NULL, 'KfzPolice Kompakt BleibMobil', false, 'keine', 'belegt', 40),
  ('kravag', 'KfzPolice Kompakt BleibMobil', 'mit Werkstattservice', 'KfzPolice Kompakt BleibMobil mit Werkstattservice', true, 'voll', 'belegt', 50),
  ('kravag', 'KfzPolice Kompakt BleibMobil', 'Glas', 'KfzPolice Kompakt BleibMobil Glas', true, 'nur_glas', 'nicht_belegt', 60),
  ('kravag', 'KfzPolice Exklusiv', NULL, 'KfzPolice Exklusiv', false, 'keine', 'belegt', 70),
  ('kravag', 'KfzPolice Exklusiv', 'mit Werkstattservice', 'KfzPolice Exklusiv mit Werkstattservice', true, 'voll', 'belegt', 80),
  ('kravag', 'KfzPolice Exklusiv', 'Glas', 'KfzPolice Exklusiv Glas', true, 'nur_glas', 'nicht_belegt', 90),
  ('kravag', 'KfzPolice Exklusiv BleibMobil', NULL, 'KfzPolice Exklusiv BleibMobil', false, 'keine', 'belegt', 100),
  ('kravag', 'KfzPolice Exklusiv BleibMobil', 'mit Werkstattservice', 'KfzPolice Exklusiv BleibMobil mit Werkstattservice', true, 'voll', 'belegt', 110),
  ('kravag', 'KfzPolice Exklusiv BleibMobil', 'Glas', 'KfzPolice Exklusiv BleibMobil Glas', true, 'nur_glas', 'nicht_belegt', 120),
  ('kravag', 'KfzPolice Exklusiv Kasko Spezial', NULL, 'KfzPolice Exklusiv Kasko Spezial', false, 'keine', 'belegt', 130),
  ('kravag', 'KfzPolice Exklusiv Kasko Spezial', 'mit Werkstattservice', 'KfzPolice Exklusiv Kasko Spezial mit Werkstattservice', true, 'voll', 'belegt', 140),
  ('kravag', 'KfzPolice Exklusiv Kasko Spezial', 'Glas', 'KfzPolice Exklusiv Kasko Spezial Glas', true, 'nur_glas', 'nicht_belegt', 150),
  ('lvm', 'AutoPlus', NULL, 'AutoPlus', false, 'keine', 'belegt', 10),
  ('lvm', 'AutoPlus mit LVM-SchadenService', NULL, 'AutoPlus mit LVM-SchadenService', false, 'keine', 'belegt', 20),
  ('mannheimer', 'Maximos', NULL, 'Maximos', false, 'keine', 'belegt', 10),
  ('mecklenburgische', 'Grunddeckung', NULL, 'Grunddeckung', false, 'keine', 'belegt', 10),
  ('mecklenburgische', 'Grunddeckung', 'mit Partnerkasko', 'Grunddeckung mit Partnerkasko', true, 'voll', 'belegt', 20),
  ('mecklenburgische', 'Komfortdeckung', NULL, 'Komfortdeckung', false, 'keine', 'belegt', 30),
  ('mecklenburgische', 'Komfortdeckung', 'mit Partnerkasko', 'Komfortdeckung mit Partnerkasko', true, 'voll', 'belegt', 40),
  ('muenchener-verein', 'Münchener Verein (Einzeltarif)', NULL, 'Münchener Verein (Einzeltarif)', false, 'keine', 'belegt', 10),
  ('neodigital', 'NEO M', NULL, 'NEO M', false, 'keine', 'belegt', 10),
  ('neodigital', 'NEO M', 'mit Werkstattbindung', 'NEO M mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('neodigital', 'NEO L', NULL, 'NEO L', false, 'keine', 'belegt', 30),
  ('neodigital', 'NEO L', 'mit Werkstattbindung', 'NEO L mit Werkstattbindung', true, 'voll', 'belegt', 40),
  ('neodigital', 'NEO Select', NULL, 'NEO Select', false, 'keine', 'belegt', 50),
  ('neodigital', 'NEO Select', 'mit Werkstattbindung', 'NEO Select mit Werkstattbindung', true, 'voll', 'belegt', 60),
  ('oeffentliche-braunschweig', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('oeffentliche-braunschweig', 'Basis', 'mit Werkstattservice Plus', 'Basis mit Werkstattservice Plus', true, 'voll', 'belegt', 20),
  ('oeffentliche-braunschweig', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 30),
  ('oeffentliche-braunschweig', 'Komfort', 'mit Werkstattservice Plus', 'Komfort mit Werkstattservice Plus', true, 'voll', 'belegt', 40),
  ('oeffentliche-braunschweig', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 50),
  ('oeffentliche-braunschweig', 'Premium', 'mit Werkstattservice Plus', 'Premium mit Werkstattservice Plus', true, 'voll', 'belegt', 60),
  ('oeffentliche-oldenburg', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 10),
  ('oeffentliche-oldenburg', 'Komfort', 'mit Werkstattservice', 'Komfort mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('oeffentliche-oldenburg', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 30),
  ('oeffentliche-oldenburg', 'Premium', 'mit Werkstattservice', 'Premium mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('oeffentliche-oldenburg', 'Basis', 'mit Werkstattservice', 'Basis mit Werkstattservice', true, 'voll', 'belegt', 50),
  ('oesa', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('oesa', 'Basis', 'mit Werkstattservice', 'Basis mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('oesa', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 30),
  ('oesa', 'Komfort', 'mit Werkstattservice', 'Komfort mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('oesa', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 50),
  ('oesa', 'Premium', 'mit Werkstattservice', 'Premium mit Werkstattservice', true, 'voll', 'belegt', 60),
  ('prokundo', 'EASY', NULL, 'EASY', false, 'keine', 'belegt', 10),
  ('prokundo', 'EASY', 'mit Werkstatt-Service', 'EASY mit Werkstatt-Service', true, 'voll', 'belegt', 20),
  ('prokundo', 'COMFORT', NULL, 'COMFORT', false, 'keine', 'belegt', 30),
  ('prokundo', 'COMFORT', 'mit Werkstatt-Service', 'COMFORT mit Werkstatt-Service', true, 'voll', 'belegt', 40),
  ('prokundo', 'BEST', NULL, 'BEST', false, 'keine', 'belegt', 50),
  ('prokundo', 'BEST', 'mit Werkstatt-Service', 'BEST mit Werkstatt-Service', true, 'voll', 'belegt', 60),
  ('provinzial', 'AutoBasis', NULL, 'AutoBasis', false, 'keine', 'belegt', 10),
  ('provinzial', 'AutoBasis', 'mit Werkstattbindung', 'AutoBasis mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('provinzial', 'AutoPlus', NULL, 'AutoPlus', false, 'keine', 'belegt', 30),
  ('provinzial', 'AutoPlus', 'mit Werkstattbindung', 'AutoPlus mit Werkstattbindung', true, 'voll', 'belegt', 40),
  ('provinzial', 'Provinzial', NULL, 'Provinzial', false, 'keine', 'belegt', 50),
  ('provinzial', 'Provinzial', 'mit Werkstattbindung', 'Provinzial mit Werkstattbindung', true, 'voll', 'belegt', 60),
  ('provinzial', 'Plus-Paket Haftpflicht', NULL, 'Plus-Paket Haftpflicht', false, 'keine', 'belegt', 70),
  ('provinzial', 'Plus-Paket Haftpflicht', 'mit Werkstattbindung', 'Plus-Paket Haftpflicht mit Werkstattbindung', true, 'voll', 'belegt', 80),
  ('provinzial', 'Plus-Paket Kasko', NULL, 'Plus-Paket Kasko', false, 'keine', 'belegt', 90),
  ('provinzial', 'Plus-Paket Kasko', 'mit Werkstattbindung', 'Plus-Paket Kasko mit Werkstattbindung', true, 'voll', 'belegt', 100),
  ('provinzial', 'Plus-Paket Kasko und Haftpflicht', NULL, 'Plus-Paket Kasko und Haftpflicht', false, 'keine', 'belegt', 110),
  ('provinzial', 'Plus-Paket Kasko und Haftpflicht', 'mit Werkstattbindung', 'Plus-Paket Kasko und Haftpflicht mit Werkstattbindung', true, 'voll', 'belegt', 120),
  ('provinzial-nord', 'Provinzial Nord', NULL, 'Provinzial Nord', false, 'keine', 'belegt', 10),
  ('provinzial-nord', 'Provinzial Nord', 'mit Werkstattbindung', 'Provinzial Nord mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('r-plus-v', 'KfzPolice classic', NULL, 'KfzPolice classic', false, 'keine', 'belegt', 10),
  ('r-plus-v', 'KfzPolice classic', 'mit Werkstattservice', 'KfzPolice classic mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('r-plus-v', 'KfzPolice comfort', NULL, 'KfzPolice comfort', false, 'keine', 'belegt', 30),
  ('r-plus-v', 'KfzPolice comfort', 'mit Werkstattservice', 'KfzPolice comfort mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('r-plus-v', 'KfzPolice premium', NULL, 'KfzPolice premium', false, 'keine', 'belegt', 50),
  ('r-plus-v', 'KfzPolice premium', 'mit Werkstattservice', 'KfzPolice premium mit Werkstattservice', true, 'voll', 'belegt', 60),
  ('r-plus-v', 'KfzPolice premium Kasko Spezial', NULL, 'KfzPolice premium Kasko Spezial', false, 'keine', 'belegt', 70),
  ('r-plus-v', 'KfzPolice premium Kasko Spezial', 'mit Werkstattservice', 'KfzPolice premium Kasko Spezial mit Werkstattservice', true, 'voll', 'belegt', 80),
  ('rheinland', 'Standard', NULL, 'Standard', false, 'keine', 'belegt', 10),
  ('rheinland', 'Standard', 'mit Werkstattservice', 'Standard mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('rheinland', 'Plus', NULL, 'Plus', false, 'keine', 'belegt', 30),
  ('rheinland', 'Plus', 'mit Werkstattservice', 'Plus mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('rheinland', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 50),
  ('rheinland', 'Premium', 'mit Werkstattservice', 'Premium mit Werkstattservice', true, 'voll', 'belegt', 60),
  ('rhion-digital', 'Standard', NULL, 'Standard', false, 'keine', 'belegt', 10),
  ('rhion-digital', 'Standard', 'mit Werkstattservice', 'Standard mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('rhion-digital', 'Plus', NULL, 'Plus', false, 'keine', 'belegt', 30),
  ('rhion-digital', 'Plus', 'mit Werkstattservice', 'Plus mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('rhion-digital', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 50),
  ('rhion-digital', 'Premium', 'mit Werkstattservice', 'Premium mit Werkstattservice', true, 'voll', 'belegt', 60),
  ('saarland', 'Vario', NULL, 'Vario', false, 'keine', 'belegt', 10),
  ('saarland', 'Vario', 'mit Werkstatt Service', 'Vario mit Werkstatt Service', true, 'voll', 'belegt', 20),
  ('saarland', 'Vario Kasko-Plus', NULL, 'Vario Kasko-Plus', false, 'keine', 'belegt', 30),
  ('saarland', 'Vario Kasko-Plus', 'mit Werkstatt Service', 'Vario Kasko-Plus mit Werkstatt Service', true, 'voll', 'belegt', 40),
  ('signal-iduna', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('signal-iduna', 'Basis', 'Sorglos Kasko', 'Basis Sorglos Kasko', true, 'voll', 'belegt', 20),
  ('signal-iduna', 'Basis', 'Sorglos Kasko Glas', 'Basis Sorglos Kasko Glas', true, 'nur_glas', 'belegt', 30),
  ('signal-iduna', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 40),
  ('signal-iduna', 'Premium', 'Sorglos Kasko', 'Premium Sorglos Kasko', true, 'voll', 'belegt', 50),
  ('signal-iduna', 'Premium', 'Sorglos Kasko Glas', 'Premium Sorglos Kasko Glas', true, 'nur_glas', 'belegt', 60),
  ('sparkassen-direkt', 'AutoBasis', NULL, 'AutoBasis', false, 'keine', 'belegt', 10),
  ('sparkassen-direkt', 'AutoBasis', 'mit Werkstattservice', 'AutoBasis mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('sparkassen-direkt', 'AutoBasis Mobil', NULL, 'AutoBasis Mobil', false, 'keine', 'belegt', 30),
  ('sparkassen-direkt', 'AutoBasis Mobil', 'mit Werkstattservice', 'AutoBasis Mobil mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('sparkassen-direkt', 'AutoPlusProtect', NULL, 'AutoPlusProtect', false, 'keine', 'belegt', 50),
  ('sparkassen-direkt', 'AutoPlusProtect', 'mit Werkstattservice', 'AutoPlusProtect mit Werkstattservice', true, 'voll', 'belegt', 60),
  ('sparkassen-direkt', 'AutoPlusProtect Mobil', NULL, 'AutoPlusProtect Mobil', false, 'keine', 'belegt', 70),
  ('sparkassen-direkt', 'AutoPlusProtect Mobil', 'mit Werkstattservice', 'AutoPlusProtect Mobil mit Werkstattservice', true, 'voll', 'belegt', 80),
  ('sparkassen-direkt', 'AutoPremium', NULL, 'AutoPremium', false, 'keine', 'belegt', 90),
  ('sparkassen-direkt', 'AutoPremium', 'mit Werkstattservice', 'AutoPremium mit Werkstattservice', true, 'voll', 'belegt', 100),
  ('sparkassen-direkt', 'AutoPremium Mobil', NULL, 'AutoPremium Mobil', false, 'keine', 'belegt', 110),
  ('sparkassen-direkt', 'AutoPremium Mobil', 'mit Werkstattservice', 'AutoPremium Mobil mit Werkstattservice', true, 'voll', 'belegt', 120),
  ('sv-sachsen', 'Kfz-Versicherung', NULL, 'Kfz-Versicherung', false, 'keine', 'belegt', 10),
  ('sv-sachsen', 'Kfz-Versicherung', 'mit Werkstatt-Management', 'Kfz-Versicherung mit Werkstatt-Management', true, 'voll', 'belegt', 20),
  ('sv-sachsen', 'Kfz-Versicherung KaskoPlus', NULL, 'Kfz-Versicherung KaskoPlus', false, 'keine', 'belegt', 30),
  ('sv-sachsen', 'Kfz-Versicherung KaskoPlus', 'mit Werkstatt-Management', 'Kfz-Versicherung KaskoPlus mit Werkstatt-Management', true, 'voll', 'belegt', 40),
  ('sv-sparkassenversicherung', 'Kfz-Versicherung', NULL, 'Kfz-Versicherung', false, 'keine', 'belegt', 10),
  ('sv-sparkassenversicherung', 'Kfz-Versicherung', 'mit Werkstattbindung', 'Kfz-Versicherung mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('sv-sparkassenversicherung', 'Kfz-Versicherung Top-Schutz', NULL, 'Kfz-Versicherung Top-Schutz', false, 'keine', 'belegt', 30),
  ('sv-sparkassenversicherung', 'Kfz-Versicherung Top-Schutz', 'mit Werkstattbindung', 'Kfz-Versicherung Top-Schutz mit Werkstattbindung', true, 'voll', 'belegt', 40),
  ('universa', 'FLEXXdrive', NULL, 'FLEXXdrive', false, 'keine', 'belegt', 10),
  ('universa', 'FLEXXdrive', 'mit Werkstatt-Service', 'FLEXXdrive mit Werkstatt-Service', true, 'voll', 'belegt', 20),
  ('versicherungskammer-bayern', 'Vario', NULL, 'Vario', false, 'keine', 'belegt', 10),
  ('versicherungskammer-bayern', 'Vario', 'mit Werkstattservice', 'Vario mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('versicherungskammer-bayern', 'Vario KaskoPLUS', NULL, 'Vario KaskoPLUS', false, 'keine', 'belegt', 30),
  ('versicherungskammer-bayern', 'Vario KaskoPLUS', 'mit Werkstattservice', 'Vario KaskoPLUS mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('verti', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('verti', 'Basis', 'Kasko Clever', 'Basis Kasko Clever', true, 'voll', 'belegt', 20),
  ('verti', 'Pur', NULL, 'Pur', false, 'keine', 'belegt', 30),
  ('verti', 'Pur', 'Kasko Clever', 'Pur Kasko Clever', true, 'voll', 'belegt', 40),
  ('verti', 'Klassik', NULL, 'Klassik', false, 'keine', 'belegt', 50),
  ('verti', 'Klassik', 'Kasko Clever', 'Klassik Kasko Clever', true, 'voll', 'belegt', 60),
  ('verti', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 70),
  ('verti', 'Premium', 'Kasko Clever', 'Premium Kasko Clever', true, 'voll', 'belegt', 80),
  ('verti', 'PlusBONUS', NULL, 'PlusBONUS', false, 'keine', 'belegt', 90),
  ('verti', 'PlusBONUS', 'Kasko Clever', 'PlusBONUS Kasko Clever', true, 'voll', 'belegt', 100),
  ('vgh', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('vgh', 'Basis', 'mit Werkstattservice', 'Basis mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('vgh', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 30),
  ('vgh', 'Komfort', 'mit Werkstattservice', 'Komfort mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('vgh', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 50),
  ('vgh', 'Premium', 'mit Werkstattservice', 'Premium mit Werkstattservice', true, 'voll', 'belegt', 60),
  ('vhv', 'Klassik-Garant 2.0', NULL, 'Klassik-Garant 2.0', false, 'keine', 'belegt', 10),
  ('vhv', 'Klassik-Garant 2.0', 'Schadenservice PLUS mit Werkstattservice', 'Klassik-Garant 2.0 Schadenservice PLUS mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('vhv', 'Klassik-Garant 2.0 EXKLUSIV', NULL, 'Klassik-Garant 2.0 EXKLUSIV', false, 'keine', 'belegt', 30),
  ('vhv', 'Klassik-Garant 2.0 EXKLUSIV', 'Schadenservice PLUS mit Werkstattservice', 'Klassik-Garant 2.0 EXKLUSIV Schadenservice PLUS mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('vhv', 'Klassik-Garant 2.0 mit gesetzlicher Mindestdeckung', NULL, 'Klassik-Garant 2.0 mit gesetzlicher Mindestdeckung', false, 'keine', 'belegt', 50),
  ('voedag', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('voedag', 'Basis', 'Sorglos Kasko', 'Basis Sorglos Kasko', true, 'voll', 'belegt', 20),
  ('voedag', 'Basis', 'Sorglos Kasko Glas', 'Basis Sorglos Kasko Glas', true, 'nur_glas', 'belegt', 30),
  ('voedag', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 40),
  ('voedag', 'Premium', 'Sorglos Kasko', 'Premium Sorglos Kasko', true, 'voll', 'belegt', 50),
  ('voedag', 'Premium', 'Sorglos Kasko Glas', 'Premium Sorglos Kasko Glas', true, 'nur_glas', 'belegt', 60),
  ('volkswagen-autoversicherung', 'Basis', 'mit Werkstattbindung', 'Basis mit Werkstattbindung', true, 'voll', 'belegt', 10),
  ('volkswagen-autoversicherung', 'Optimal', 'mit Werkstattbindung', 'Optimal mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('volkswagen-autoversicherung', 'Premium', 'mit Werkstattbindung', 'Premium mit Werkstattbindung', true, 'voll', 'belegt', 30),
  ('volkswohl-bund', 'Komfort', NULL, 'Komfort', false, 'keine', 'belegt', 10),
  ('volkswohl-bund', 'Komfort', 'mit Werkstattservice', 'Komfort mit Werkstattservice', true, 'voll', 'belegt', 20),
  ('volkswohl-bund', 'KomfortPlus', NULL, 'KomfortPlus', false, 'keine', 'belegt', 30),
  ('volkswohl-bund', 'KomfortPlus', 'mit Werkstattservice', 'KomfortPlus mit Werkstattservice', true, 'voll', 'belegt', 40),
  ('vrk', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('vrk', 'Basis', 'Select', 'Basis Select', true, 'voll', 'belegt', 20),
  ('vrk', 'Classic', NULL, 'Classic', false, 'keine', 'belegt', 30),
  ('vrk', 'Classic', 'Select', 'Classic Select', true, 'voll', 'belegt', 40),
  ('vrk', 'Classic Kasko Plus', NULL, 'Classic Kasko Plus', false, 'keine', 'belegt', 50),
  ('vrk', 'Classic Kasko Plus', 'Select', 'Classic Select Kasko Plus', true, 'voll', 'belegt', 60),
  ('wgv', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('wgv', 'Basis', 'Kasko SELECT', 'Basis Kasko SELECT', true, 'voll', 'belegt', 20),
  ('wgv', 'Optimal', NULL, 'Optimal', false, 'keine', 'belegt', 30),
  ('wgv', 'Optimal', 'Kasko SELECT', 'Optimal Kasko SELECT', true, 'voll', 'belegt', 40),
  ('wgv', 'Beamten Basis', NULL, 'Beamten Basis', false, 'keine', 'belegt', 50),
  ('wgv', 'Beamten Basis', 'Kasko SELECT', 'Beamten Basis Kasko SELECT', true, 'voll', 'belegt', 60),
  ('wgv', 'Beamten Optimal', NULL, 'Beamten Optimal', false, 'keine', 'belegt', 70),
  ('wgv', 'Beamten Optimal', 'Kasko SELECT', 'Beamten Optimal Kasko SELECT', true, 'voll', 'belegt', 80),
  ('wuerttembergische', 'KompaktSchutz', NULL, 'KompaktSchutz', false, 'keine', 'abgeleitet', 10),
  ('wuerttembergische', 'KompaktSchutz', 'mit Schadenservice+', 'KompaktSchutz mit Schadenservice+', true, 'voll', 'abgeleitet', 20),
  ('wuerttembergische', 'PremiumSchutz', NULL, 'PremiumSchutz', false, 'keine', 'abgeleitet', 30),
  ('wuerttembergische', 'PremiumSchutz', 'mit Schadenservice+', 'PremiumSchutz mit Schadenservice+', true, 'voll', 'abgeleitet', 40),
  ('wwk', 'KFZ Basis', NULL, 'KFZ Basis', false, 'keine', 'belegt', 10),
  ('wwk', 'KFZ Basis', 'mit Werkstattmanagement', 'KFZ Basis mit Werkstattmanagement', true, 'voll', 'belegt', 20),
  ('wwk', 'KFZ plus', NULL, 'KFZ plus', false, 'keine', 'belegt', 30),
  ('wwk', 'KFZ plus', 'mit Werkstattmanagement', 'KFZ plus mit Werkstattmanagement', true, 'voll', 'belegt', 40),
  ('zurich', 'Basis', NULL, 'Basis', false, 'keine', 'belegt', 10),
  ('zurich', 'Basis', 'mit Werkstattbindung', 'Basis mit Werkstattbindung', true, 'voll', 'belegt', 20),
  ('zurich', 'Top', NULL, 'Top', false, 'keine', 'belegt', 30),
  ('zurich', 'Top', 'mit Werkstattbindung', 'Top mit Werkstattbindung', true, 'voll', 'belegt', 40),
  ('zurich', 'Premium', NULL, 'Premium', false, 'keine', 'belegt', 50),
  ('zurich', 'Premium', 'mit Werkstattbindung', 'Premium mit Werkstattbindung', true, 'voll', 'belegt', 60)
) AS t(slug, linie, wb_zusatz, anzeigename, hat_werkstattbindung, bindungsumfang, verlaesslichkeit, reihenfolge)
JOIN public.kasko_versicherer_marken m ON m.slug = t.slug
ON CONFLICT (marke_id, anzeigename) DO UPDATE SET linie = EXCLUDED.linie, wb_zusatz = EXCLUDED.wb_zusatz,
  hat_werkstattbindung = EXCLUDED.hat_werkstattbindung, bindungsumfang = EXCLUDED.bindungsumfang,
  verlaesslichkeit = EXCLUDED.verlaesslichkeit, reihenfolge = EXCLUDED.reihenfolge, aktiv = true;

-- 4) Konditionen (23; key=__default__ mit slug NULL = GDV-Muster fuer alle Marken ohne belegte Werte)
INSERT INTO public.kasko_wb_konditionen
  (key, marke_id, nachlass_text, sanktion_modell, sanktion_text, gilt_fuer, ausnahmen_text, partnernetz, akb_fundstelle, quelle)
SELECT k.key, m.id, k.nachlass_text, k.sanktion_modell, k.sanktion_text, k.gilt_fuer, k.ausnahmen_text, k.partnernetz, k.akb_fundstelle, k.quelle
FROM (VALUES
  ('__default__', NULL, 'marktüblich 10–20 % auf den Kaskobeitrag', 'kuerzung_80', 'Bis zur Reparatur in der vom Versicherer benannten Werkstatt wird die Erstattung auf 80 % der marktüblich kalkulierten Reparaturkosten begrenzt, mindestens mit einer zusätzlichen Selbstbeteiligung von 100 € (GDV-Muster-AKB A.2.5.2.5.2).', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter · Totalschaden · Reparatur im Ausland · keine erreichbare Partnerwerkstatt', 'jeweiliges Partnernetz (häufig Innovation Group, HUK-Netz, DEKRA)', 'GDV-Muster-AKB A.2.5.2.5.1 / A.2.5.2.5.2', 'GDV-Muster-AKB; CHECK24'),
  ('adac-autoversicherung', 'adac-autoversicherung', '20 %', 'kuerzung_unbestimmt', 'Kürzung der Erstattung bei Reparatur außerhalb des Partnernetzes (Höhe laut AKB).', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter · für Leasing und Neuwagen nicht empfohlen', 'zertifizierte Partnerwerkstätten; Ersatzfahrzeug max. 7 Tage', NULL, 'adac.de (Magazin Werkstattbindung)'),
  ('allianz', 'allianz', '20 %', 'kuerzung_80', 'Kürzung der Erstattung auf 80 % bei Reparatur außerhalb des Partnernetzes.', 'Vollkasko und Teilkasko inkl. Glas (Voraussetzung TK oder VK)', 'Haftpflichtschaden Dritter · Ausland', 'TÜV-/DEKRA-zertifizierte Allianz-Partnerwerkstätten; Glas: Carglass, Euromaster, junited, Wintec; Hol-/Bringservice, Reinigung, Ersatzwagen', 'Allianz-AKB WerkstattBonus', 'allianz.de/auto/kfz-versicherung/werkstattbindung'),
  ('allianz-direct', 'allianz-direct', NULL, 'kuerzung_unbestimmt', 'Kürzung der Erstattung bei Reparatur außerhalb des Partnernetzes (Höhe laut AKB).', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter', 'Allianz-Netz', NULL, 'CHECK24'),
  ('axa', 'axa', '„attraktiver Nachlass“ (Höhe nicht belegt)', 'kuerzung_80', 'Karosserie/Lack: Kürzung auf 80 %; Glas: zusätzliche Selbstbeteiligung von 300 €.', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter', 'ca. 3.000 DEKRA-geprüfte Partner; Glas über Innovation Group, riparo', 'AXA-AKB Werkstattservice', 'axa.de; jdcnews.de'),
  ('barmeniagothaer', 'barmeniagothaer', NULL, 'kuerzung_unbestimmt', 'Kürzung der Erstattung bei Reparatur außerhalb des Partnernetzes (Höhe laut AKB).', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter', '„Die Partnerwerkstatt“ (HUK-Netz)', NULL, 'CHECK24; handwerk-magazin.de'),
  ('bavariadirekt', 'bavariadirekt', NULL, 'kuerzung_80', 'Kürzung auf 80 %, mindestens 100 € zusätzliche Selbstbeteiligung (AKB Stand 30.09.2015); bei fiktiver Abrechnung laut LG Hildesheim 3 S 12/20 unwirksam.', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter', 'Partnernetz', 'A.2.5.2.5.1 / A.2.5.2.5.2', 'bavariadirekt.de (AKB-PDF); von-boehn.de'),
  ('bavariaprotect', 'bavariaprotect', NULL, 'kuerzung_80', 'Kürzung auf 80 %, mindestens 100 € zusätzliche Selbstbeteiligung (AKB-Systematik BavariaDirekt).', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter', 'Partnernetz', 'A.2.5.2.5.1 / A.2.5.2.5.2', 'bavariadirekt.de (AKB-PDF)'),
  ('cosmosdirekt', 'cosmosdirekt', NULL, 'deckelung', 'Erstattung nur bis zur Höhe der Kosten, die in der Partnerwerkstatt angefallen wären.', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter', 'DEKRA-Netz (Generali/Cosmos)', NULL, 'cosmosdirekt.de; CHECK24'),
  ('dbv', 'dbv', '„attraktiver Nachlass“ (Höhe nicht belegt)', 'kuerzung_80', 'Karosserie/Lack: Kürzung auf 80 %; Glas: zusätzliche Selbstbeteiligung von 300 € (AXA-Systematik).', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter', 'ca. 3.000 DEKRA-geprüfte Partner; Glas über Innovation Group, riparo', 'AXA-AKB Werkstattservice', 'axa.de; jdcnews.de'),
  ('debeka', 'debeka', NULL, 'kuerzung_unbestimmt', 'Kürzung der Erstattung bei Reparatur außerhalb des Partnernetzes (Höhe laut AKB).', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter', '„Die Partnerwerkstatt“ (HUK-Netz)', NULL, 'CHECK24; handwerk-magazin.de'),
  ('devk', 'devk', 'bis 20 % (Werbung; Website laut Recherche „bis 13 %“ – Stand prüfen)', 'kuerzung_85', 'Kürzung um 15 %, mindestens 300 € zusätzliche Selbstbeteiligung.', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter · bestimmte Hersteller-/Leasingfahrzeuge ausgeschlossen', 'über 4.000 Partnerbetriebe (ca. 70 % markengebunden); Glas: A.T.U., Carglass, junited, Wintec, Nobleglass; Hol-/Bringservice, Ersatzfahrzeug', 'DEVK-AKB Kasko-Mobil', 'devk.de; sdrive-gutachter.de'),
  ('ergo', 'ergo', '10 %', 'kuerzung_unbestimmt', 'Kürzung der Erstattung; der Selbstbeteiligungs-Vorteil entfällt.', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter', 'ERGO Premium-Partnerwerkstätten', NULL, 'ergo.de; CHECK24'),
  ('huk-coburg', 'huk-coburg', 'bis 20 %', 'vollverweigerung', 'Altverträge: Kürzung auf 85 %. Verträge ab 2014: Die Erstattung kann vollständig verweigert werden (laut Fachpresse und Anwaltsberichten – am konkreten AKB-Stand prüfen); gilt auch bei fiktiver Abrechnung.', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter · Notfall im Ausland', '„Die Partnerwerkstatt“, über 1.800 Betriebe (DEKRA-geprüft); Glas: Carglass', 'HUK-AKB Kasko SELECT (versionsabhängig)', 'huk.de; kfz-betrieb (Vogel); Versicherungsbote'),
  ('huk24', 'huk24', 'bis 20 %', 'vollverweigerung', 'Altverträge: Kürzung auf 85 %. Verträge ab 2014: Die Erstattung kann vollständig verweigert werden (laut Fachpresse und Anwaltsberichten – am konkreten AKB-Stand prüfen); gilt auch bei fiktiver Abrechnung.', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter · Notfall im Ausland', '„Die Partnerwerkstatt“, über 1.800 Betriebe (DEKRA-geprüft); Glas: Carglass', 'HUK-AKB Kasko SELECT (versionsabhängig)', 'huk.de; kfz-betrieb (Vogel); Versicherungsbote'),
  ('kravag', 'kravag', NULL, 'kuerzung_85', 'Glas: Kürzung auf 85 % bei Reparatur außerhalb des Netzes; übrige Schäden nicht belegt.', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter', 'R+V-Partnernetz (Innovation Group)', NULL, 'CHECK24; autoglaser.de'),
  ('lvm', 'lvm', NULL, 'keine', 'Keine Werkstattbindung. Der LVM-SchadenService ist eine freiwillige Steuerung in eine Partnerwerkstatt (Abholung, Ersatzwagen, Reinigung).', NULL, NULL, 'LVM-Partnerwerkstätten (Steuerungsquote über 25 %, 2021)', NULL, 'lvm.de; schaden.news 06.07.2022'),
  ('r-plus-v', 'r-plus-v', NULL, 'kuerzung_85', 'Glas: Kürzung auf 85 % bei Reparatur außerhalb des Netzes; übrige Schäden nicht belegt.', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter', 'R+V-Partnernetz (Innovation Group)', NULL, 'CHECK24; autoglaser.de'),
  ('signal-iduna', 'signal-iduna', 'bis 15 %; Sorglos Kasko Glas bis 5 %', 'kuerzung_unbestimmt', 'Kürzung der Erstattung bei Reparatur außerhalb des Partnernetzes (Höhe laut AKB).', 'Sorglos Kasko: Vollkasko und Teilkasko inkl. Glas; Sorglos Kasko Glas: nur Glas', 'Haftpflichtschaden Dritter · für Leasing wird die Glas-Variante angeboten', 'Signal-Iduna-Partnerwerkstätten', NULL, 'signal-iduna.de; asscompact.de'),
  ('verti', 'verti', 'bis 15 %', 'deckelung', 'Erstattung nur bis zur Höhe der Kosten der nächstgelegenen Partnerwerkstatt.', 'Vollkasko und Teilkasko (Glas ohne Hol-/Bringservice)', 'Haftpflichtschaden Dritter', 'Verti/MAPFRE-Netz', NULL, 'verti.de; CHECK24'),
  ('vhv', 'vhv', '15 %', 'unbekannt', 'Kürzung bei Reparatur außerhalb des Netzes laut AKB (Höhe öffentlich nicht belegt).', 'Vollkasko und Teilkasko inkl. Glas', 'Haftpflichtschaden Dritter', 'zertifizierte VHV-Partnerwerkstätten, Reparatur nach Herstellervorgaben; Zuweisung nur über die VHV-Steuerung', 'VHV-AKB Werkstattbindung', 'vhv.de/auto-versicherung/ratgeber/werkstattbindung'),
  ('voedag', 'voedag', 'bis 15 %; Sorglos Kasko Glas bis 5 %', 'kuerzung_unbestimmt', 'Kürzung der Erstattung bei Reparatur außerhalb des Partnernetzes (Höhe laut AKB).', 'Sorglos Kasko: Vollkasko und Teilkasko inkl. Glas; Sorglos Kasko Glas: nur Glas', 'Haftpflichtschaden Dritter · für Leasing wird die Glas-Variante angeboten', 'Signal-Iduna-Partnerwerkstätten', NULL, 'signal-iduna.de; asscompact.de'),
  ('hdi', 'hdi', '„Sie sparen dabei“ (Höhe nicht belegt)', 'unbekannt', 'Kürzung bei Reparatur außerhalb des Netzes laut AKB (Höhe öffentlich nicht belegt).', 'Kaskofall', 'Alternative „Freie Werkstattwahl (nur für private Pkw)“ = keine Bindung', 'zertifizierte HDI-Partnerwerkstätten, Herstellergarantie bleibt erhalten', NULL, 'HDI-Broschüre Mobilität/Auto (hdi.de/kfz)')
) AS k(key, slug, nachlass_text, sanktion_modell, sanktion_text, gilt_fuer, ausnahmen_text, partnernetz, akb_fundstelle, quelle)
LEFT JOIN public.kasko_versicherer_marken m ON m.slug = k.slug
ON CONFLICT (key) DO UPDATE SET marke_id = EXCLUDED.marke_id, nachlass_text = EXCLUDED.nachlass_text,
  sanktion_modell = EXCLUDED.sanktion_modell, sanktion_text = EXCLUDED.sanktion_text, gilt_fuer = EXCLUDED.gilt_fuer,
  ausnahmen_text = EXCLUDED.ausnahmen_text, partnernetz = EXCLUDED.partnernetz, akb_fundstelle = EXCLUDED.akb_fundstelle,
  quelle = EXCLUDED.quelle;
