// ============================================================================
// CLUSTER-VORLAGE · AACHEN (Städteregion Aachen)  —  Abgabe für Nicolas (09.06.2026)
// ============================================================================
// Das ist die EINZIGE Datei, in der die Cluster-Identität lebt. Alle Komponenten,
// SEO, Hub (/) und Spokes (/lp/<slug>) werden aus dieser Datei generiert.
//
// NICOLAS — DU FÜLLST DEN INHALT. Die Struktur steht. Such nach `TODO Nicolas`.
// Pro neuem Cluster nur 4 Stellen anpassen (Details in HANDOFF.md):
//   1) diese Datei (lib/cluster.ts)  — Städte, Region, Brennpunkte, SEO-Texte
//   2) app/globals.css  — :root Cluster-Vars (Theme-Farben)
//   3) app/layout.tsx   — themeColor (muss zu globals.css passen)
//   4) public/assets/img/aachen/  — echte Bilder (ersetzen die Platzhalter)
//
// Bilder rendern lokal als PLATZHALTER (grau, beschriftet) — echte Assets liefert
// Aaron beim Paste-back nach. Die Bild-DATEINAMEN unten sind verbindlich (die
// Komponenten erwarten genau diese Pfade) — beim Tauschen die Namen beibehalten.
// ============================================================================

export interface City {
  slug: string
  name: string
  plz: string
  /** H1-Untertitel (SEO-Variation pro Stadt). */
  h1Sub: string
  /** Einwohner-Bezeichnung ("Aachener") fuer Reviews-Headline. */
  residents: string
  /** Stadt-Zentrum-Koordinaten (LocalBusiness-geo + Map-Pin). */
  lat: number
  lng: number
  /** Hauptstadt des Clusters (Hub). */
  main?: boolean
}

export interface Brennpunkt {
  name: string
  /** Pfad relativ zu /assets/img/local/brennpunkte/ */
  img: string
  desc: string
}

export interface ClusterConfig {
  key: string
  region: string
  /** Region im Dativ ("im Aachener Raum") fuer Ueber-uns-Copy. */
  regionDative: string
  /** Quellen-Anker fuer Brennpunkt-Statistik (Einsatzgebiet-Disclaimer). */
  quellenAnker: string
  /** Hauptachsen (FAQ-Q2, cluster-spezifisch). */
  achsen: string[]
  /** Stadtteile der Hauptstadt (FAQ-Lokal-Card). */
  stadtteile: string[]
  domain: string
  /** data-theme-Key (dokumentarisch — :root in globals.css traegt die Vars). */
  theme: string
  themeColor: string
  /** Basis-Pfad fuer cluster-spezifische Bilder. */
  imgPath: string
  /** Dateiendung der Logo-Varianten logo-{key}-dark/-white (BRIEF 08d: Aachen hat echte Vektor-SVGs, Koeln PNG). */
  logoExt: 'png' | 'svg'
  /** 08m A6 · Cache-Busting: bei INHALTS-Tausch eines Assets (gleicher Dateiname)
   *  hochzaehlen — haengt als ?v=… an Hero-/Logo-/Team-Referenzen (Komponenten +
   *  die beiden image-set-Vars in globals.css manuell mitziehen!). */
  assetVersion: string
  /** H1-Sub-Span im Hero (NUR Desktop lg:+, Action 0 P2). Copy FINAL von Aaron 10.06. — Code formuliert nichts selbst. */
  h1SubSpan: string
  /** Team-Foto (Netzwerk-Mobile Team-Hero-Card). */
  teamImg: string
  /** Vorname des lokalen SV (CTA-Rolle + Ueber-uns). */
  svName: string
  /** Nachname des lokalen SV (Person-Schema / formale Nennung). */
  svSurname: string
  /** Fachliche Spezialisierung (Differenzierungs-Anker, Person-Schema knowsAbout). */
  svSpezialitaet: string
  phone: {
    display: string
    /** National formatiertes CTA-Label (Mock Z.4295, 08e A2) — href/tel bleibt international. */
    displayNational: string
    tel: string
    wa: string
  }
  /** Wahrzeichen-Hero (Einsatzgebiet). */
  landmark: { label: string; img: string }
  /** Verkehrs-Hauptachsen + Vor-Ort-Zeit (Facts-Grid). */
  facts: { value: string; label: string; accent?: boolean }[]
  /** Verkehrsschwerpunkte (Hauptstadt-Level). */
  brennpunkte: Brennpunkt[]
  cities: City[]
}

export const CLUSTER: ClusterConfig = {
  key: 'aachen',
  region: 'Städteregion Aachen',
  regionDative: 'Aachener Raum', // ergibt "im Aachener Raum" — TODO Nicolas: ggf. anpassen
  quellenAnker: 'Polizeibericht Aachen 2024 + ADAC Stau-Statistik 2025',
  achsen: ['A4', 'A44', 'A544'], // TODO Nicolas: relevante Achsen bestaetigen
  stadtteile: ['Mitte', 'Brand', 'Eilendorf', 'Haaren', 'Laurensberg', 'Richterich', 'Kornelimünster'],
  domain: 'kfz-unfallgutachter-aachen.de',
  theme: 'patina', // Aachen-Cluster v2: Dom-Patina + Kupfer — globals.css :root traegt die Vars
  themeColor: '#234F46', // Aachen-Cluster: Patina-Grün (matched globals.css :root --petrol / Brand-Primary)
  imgPath: '/assets/img/aachen/',
  logoExt: 'svg',
  assetVersion: '2', // 08m: q90-Heros + neue 08h-Assets + dilate-Logos
  h1SubSpan: 'Unabhängige Sachverständige. Gerichtsfeste Gutachten nach BVSK-Standard.', // 08n N1: Geo-Schwanz raus (Aaron)
  teamImg: '/assets/img/aachen/team-aachen.webp?v=2',
  svName: 'Markus', // Aachen-Cluster Persona (Vorname — CTA/Ueber-uns) — Aaron-Vorgabe 2026-06-09
  svSurname: 'Lennartz', // Aachen-Cluster Persona (Nachname — Person-Schema) — Aaron-Vorgabe 2026-06-09
  svSpezialitaet: 'Hochwasser-2021-Sachverständigung + BVSK-Standard', // Differenzierung (Düren/Eschweiler/Stolberg)
  // Telefon einheitlich ueber alle Cluster (Aaron-Vorgabe Mobil). Bei eigener Nummer hier aendern.
  phone: { display: '+49 1515 3608515', displayNational: '0151 5360 8515', tel: '+4915153608515', wa: '4915153608515' },
  landmark: { label: 'Aachener Dom', img: 'stadt-aachen.png' }, // TODO Nicolas: Wahrzeichen-Bild
  facts: [
    { value: 'A4', label: 'Hauptachse' },
    { value: 'A44', label: 'Hauptachse' },
    { value: 'A544', label: 'Hauptachse' },
    { value: '60 Min', label: 'vor Ort', accent: true },
  ],
  // Verkehrsschwerpunkte Aachen-Hub — lokal verankert, keine erfundenen Stats (Quellen s. quellenAnker).
  brennpunkte: [
    {
      name: 'Aachener Kreuz',
      img: 'aachen_kreuz.webp',
      desc: 'Das Aachener Kreuz (A 4 / A 44) ist eine der wichtigsten Drehscheiben im Westen NRWs — täglich kreuzen sich hier Pendlerströme aus Köln, Maastricht und Lüttich. Stop-and-Go im Berufsverkehr und Spurwechsel-Manöver sind die häufigsten Unfallursachen. Markus ist binnen 60 Minuten vor Ort.',
    },
    {
      name: 'Adalbertstraße',
      img: 'aachen_adalbertstrasse.webp',
      desc: 'Die Adalbertstraße zählt zu den meistbefahrenen Innenstadtachsen Aachens — Fußgängerzonen-Übergang, Tram-Linien und Lieferverkehr treffen aufeinander. Tür-Öffner-Schäden, Park-Rempler und Vorfahrt-Konflikte prägen das Schadensbild. Wir kennen die Sondersituationen rund um den Markt und die Pontstraße.',
    },
    {
      name: 'Europaplatz',
      img: 'aachen_europaplatz.webp',
      desc: 'Der Europaplatz liegt am Übergang zur belgisch-niederländischen Grenzregion und ist Drehscheibe für grenzüberschreitenden Verkehr. Versicherungstechnisch besonders: Schäden mit ausländischen Beteiligten erfordern Spezialkenntnis. Markus arbeitet seit Jahren mit BE/NL-Versicherern und kennt die Regulierungswege.',
    },
  ],
  // Hub = Aachen (main:true). Düren = Power-Spoke (170 Vol/mo, +182% YoY) direkt nach dem Hub.
  // h1Sub = SEO-Variation + cluster-spezifische Anker (Hochwasser-2021, A4/Veldener, NL-Grenze).
  cities: [
    { slug: 'aachen',       name: 'Aachen',       plz: '52062', main: true, h1Sub: 'unabhängiger Sachverständiger für Aachen + Region',             residents: 'Aachener',       lat: 50.7753, lng: 6.0839 },
    // === POWER-SPOKE: Düren (170 Vol/mo, +182% YoY) ===
    { slug: 'dueren',       name: 'Düren',        plz: '52349',             h1Sub: 'Düren-Spezialist seit 2020 — A 4 + Veldener Straße in 60 Minuten', residents: 'Dürener',        lat: 50.8047, lng: 6.4936 },
    // === Spokes (Städteregion + Kreis Düren) ===
    { slug: 'alsdorf',      name: 'Alsdorf',      plz: '52477',             h1Sub: 'Kfz-Sachverständiger Städteregion Aachen',                        residents: 'Alsdorfer',      lat: 50.8769, lng: 6.1611 },
    { slug: 'wuerselen',    name: 'Würselen',     plz: '52146',             h1Sub: 'unabhängiger Unfallgutachter',                                    residents: 'Würselener',     lat: 50.8197, lng: 6.1322 },
    { slug: 'baesweiler',   name: 'Baesweiler',   plz: '52499',             h1Sub: 'Sachverständiger Städteregion + NL-Grenze',                       residents: 'Baesweiler',     lat: 50.9089, lng: 6.1894 },
    { slug: 'eschweiler',   name: 'Eschweiler',   plz: '52249',             h1Sub: 'Hochwasser-2021-Erfahrung — Eschweiler + Inde-Region',            residents: 'Eschweiler',     lat: 50.8181, lng: 6.2731 },
    { slug: 'juelich',      name: 'Jülich',       plz: '52428',             h1Sub: 'unabhängiger Kfz-Sachverständiger',                               residents: 'Jülicher',       lat: 50.9239, lng: 6.3625 },
    { slug: 'stolberg',     name: 'Stolberg',     plz: '52222',             h1Sub: 'Hochwasser-2021-Spezialist + Sachverständiger',                   residents: 'Stolberger',     lat: 50.7706, lng: 6.2289 },
    { slug: 'herzogenrath', name: 'Herzogenrath', plz: '52134',             h1Sub: 'Sachverständiger Grenzregion DE/NL',                              residents: 'Herzogenrather', lat: 50.8694, lng: 6.0936 },
  ],
}

/** Hauptstadt (Hub-Page /). */
export const MAIN_CITY: City = CLUSTER.cities.find((c) => c.main) ?? CLUSTER.cities[0]

/** Alle Slugs. */
export const CITY_SLUGS: string[] = CLUSTER.cities.map((c) => c.slug)

/** Spoke-Slugs (alle ausser Hauptstadt) — generateStaticParams. Die Hauptstadt
 *  IST der Hub "/" → kein dupliziertes /lp/{main}/ (SEO-Dedup). */
export const SPOKE_SLUGS: string[] = CLUSTER.cities.filter((c) => !c.main).map((c) => c.slug)

/** Routing-Pfad einer Stadt (Hauptstadt → "/"). */
export function cityHref(city: City): string {
  return city.main ? '/' : `/lp/${city.slug}`
}

/** Stadt per Slug (oder undefined → 404). */
export function getCity(slug: string): City | undefined {
  return CLUSTER.cities.find((c) => c.slug === slug)
}

/** Vorausgefuellter WhatsApp-Text pro Stadt. */
export function waText(city: City): string {
  return `Hallo, ich hatte einen Unfall in ${city.name} und brauche einen Gutachter.`
}

/** Vollstaendiger wa.me-Link mit vorausgefuelltem Text. */
export function waHref(city: City): string {
  return `https://wa.me/${CLUSTER.phone.wa}?text=${encodeURIComponent(waText(city))}`
}

/** Komma-Liste aller Staedte (Servicegebiet-Text / areaServed). */
export function cityNamesList(): string {
  const names = CLUSTER.cities.map((c) => c.name)
  return names.slice(0, -1).join(', ') + ' und ' + names[names.length - 1]
}

// TODO Nicolas: pro Stadt einen EINZIGARTIGEN lokalen SEO-Absatz (gegen Duplicate-/
// Doorway-Content) — echte Nachbarorte, PLZ, Autobahnen; KEINE erfundenen Statistiken.
// Muster + Tonfall: siehe Wuppertal-Cluster (5-6 Saetze, lokal verankert). Die Platzhalter
// unten rendern bereits, damit der Local-Build vollstaendig aussieht.
// ── SEO-Body (08o O6: strukturierte Absaetze statt Fliesstext) ───────────────
// H3s sind EDITORIAL an ihre Absaetze gebunden (kein Trigger-Katalog mehr —
// Fehlgriff-Klasse N9/O6). `vorort: true` markiert den Absatz, der in der
// Einsatzgebiet-Lokalstrecke rendert (lib/seoVorOrt); `liste` rendert als
// kompakte Leistungs-Liste. Lokale Fakten (Strassen, Bruecken, Stadtteile)
// sind der Ranking-Kern — beim Straffen unangetastet.
export interface SeoAbsatz {
  /** Editorial gebundene Zwischenueberschrift — stellt die Frage, die der Absatz beantwortet. */
  h3?: string
  text: string
  /** Kompakte Leistungs-Liste nach dem Text. */
  liste?: string[]
  /** Rendert in der Einsatzgebiet-Lokalstrecke ("Vor Ort"), nicht im SeoBody. */
  vorort?: boolean
}

// Leistungs-Kern (identisch je Stadt — die Uniqueness tragen die lokalen Absaetze).
const LEISTUNGS_LISTE = [
  'Lackmessung & Strukturschäden-Prüfung',
  'Foto- und Maß-Dokumentation',
  'Reparaturkosten nach marktübliche Kalkulation',
  'Wertminderung (merkantiler Minderwert)',
  'Restwert nach belastbaren Marktdaten',
  'Gutachten binnen 48 Stunden',
]

export const SEO_BODY: Record<string, SeoAbsatz[]> = {
  aachen: [
    { text: `Aachen ist Krönungsstadt, Hochschulstadt und Grenzstadt in einem — und das prägt jeden Schadenfall hier. Zwischen Dom, Markt und Elisenbrunnen bewegt sich ein dichter Innenstadtverkehr aus Lieferfahrzeugen, Bussen und Radverkehr; an den Rändern der Stadt beginnt binnen Minuten Belgien oder die Niederlande. Wer hier unverschuldet in einen Unfall gerät, braucht kein Standard-Formular, sondern einen Sachverständigen, der beide Welten kennt: die enge deutsche Beweislage und die grenzüberschreitende Regulierung. Markus ist meist binnen 60 Minuten bei Ihnen. Ihr Anteil an den Kosten bleibt bei 0 € — bei unverschuldetem Unfall trägt die gegnerische Haftpflicht das Sachverständigenhonorar als Teil des Schadens nach § 249 BGB.` },
    { vorort: true, text: `Wir kommen ins ganze Stadtgebiet, und die Wege dorthin sind sehr verschieden: Das Frankenberger Viertel und Burtscheid sind dicht bebaute Gründerzeitquartiere mit Laternenparken und schmalen Fahrgassen — dort passieren die kleinen, aber ärgerlichen Streif- und Türschäden. Brand, Eilendorf und Haaren sind gewachsene Ortslagen mit eigenem Zentrum, Laurensberg und Richterich sind offener und schneller gefahren, Kornelimünster liegt am Übergang zur Eifel. Für die Aufnahme heißt das: Wir kommen zu Ihnen, zur Werkstatt oder zum Abstellort — auch wenn das Fahrzeug nicht mehr fahrbereit ist.` },
    { h3: 'Der Unfallgegner fährt ein belgisches oder niederländisches Kennzeichen — was sichern Sie jetzt?', text: `Drei Dinge entscheiden später über das Tempo der Regulierung, und alle drei bekommen Sie nur am Unfallort: das vollständige Kennzeichen mit Länderkennung, den Namen der Versicherung und — falls vorhanden — die Nummer der Grünen Karte oder der Versicherungsbestätigung. Fotografieren Sie beides ab, nicht abschreiben. Ist die Versicherung unbekannt, lässt sie sich über den Zentralruf der Autoversicherer anhand des Kennzeichens ermitteln; das gelingt jedoch deutlich zuverlässiger, wenn das Kennzeichen wirklich vollständig und scharf dokumentiert ist. Notieren Sie zusätzlich Uhrzeit, genaue Örtlichkeit und mögliche Zeugen mit Erreichbarkeit.` },
    { h3: 'Wer reguliert, wenn der Versicherer gar nicht in Deutschland sitzt?', text: `Nicht Sie müssen ins Ausland — der Weg führt umgekehrt. Für Unfälle, die ein ausländisch zugelassenes Fahrzeug in Deutschland verursacht, ist das Deutsche Büro Grüne Karte die zuständige Stelle; zusätzlich muss jeder Versicherer aus dem europäischen Wirtschaftsraum einen Schadenregulierungsbeauftragten in Deutschland benennen, der in deutscher Sprache korrespondiert. Wichtig für die Höhe Ihres Anspruchs: Weil sich der Unfall in Deutschland ereignet hat, wird auch nach deutschem Schadenrecht abgerechnet — also mit Wertminderung, Nutzungsausfall und freier Werkstattwahl, unabhängig davon, was im Heimatland des Gegners üblich wäre.` },
    { h3: 'Kein Personenschaden, die Polizei kommt nicht — reicht das Aufnehmen unter Beteiligten?', text: `Bei reinen Blechschäden nimmt die Polizei den Unfall in der Regel nicht auf, und genau daraus entsteht später der häufigste Streit: Aussage gegen Aussage. Verlassen Sie sich deshalb nicht auf den europäischen Unfallbericht allein. Halten Sie die Endstellung beider Fahrzeuge fest, bevor Sie räumen, fotografieren Sie aus mehreren Abständen inklusive Umfeld und Fahrbahnmarkierung, und lassen Sie sich Personalien per Ausweis zeigen statt diktieren. Ein späteres Gutachten kann aus Schadenbild und Spurenlage viel rekonstruieren — aber nur, wenn der Ausgangszustand überhaupt dokumentiert wurde.` },
    { h3: 'Sie tragen eine Teilschuld — bekommen Sie dann überhaupt etwas?', text: `Ja, nur eben anteilig. Steht am Ende eine Haftungsquote, wird nicht eine Position gestrichen und die andere voll bezahlt, sondern der gesamte Schaden nach dieser Quote geteilt: Reparaturkosten, Wertminderung, Nutzungsausfall — und ebenso das Sachverständigenhonorar, das dann nur in Höhe der Quote erstattet wird. Genau deshalb lohnt es sich, die Quote nicht ungeprüft hinzunehmen. Sie entsteht aus der Bewertung der beiderseitigen Verursachungsbeiträge, und die technische Rekonstruktion des Hergangs kann diese Bewertung verschieben. Wer sofort eine hälftige Teilung akzeptiert, verzichtet häufig auf einen erheblichen Teil des Anspruchs, ohne es zu merken.` },
    { h3: 'Wer zahlt den Anwalt?', text: `Bei einem unverschuldeten Unfall die gegnerische Haftpflichtversicherung — die außergerichtlichen Anwaltskosten gehören zum ersatzfähigen Schaden, genau wie Gutachten und Mietwagen. Sie brauchen dafür weder eine Rechtsschutzversicherung noch ein Kostenrisiko einzugehen. Bei einer Mithaftungsquote gilt allerdings dasselbe wie oben: Auch die Anwaltskosten werden dann nur anteilig erstattet. Sinnvoll ist die anwaltliche Vertretung vor allem dann, wenn die Gegenseite die Schuldfrage bestreitet, eine Quote ins Spiel bringt oder einzelne Positionen kürzt. Über das Claimondo-Partnernetzwerk vermitteln wir einen Verkehrsrechtsanwalt aus der Region, der den Fall von der Schadenmeldung bis zur Auszahlung führt.` },
    { h3: 'Zusammenstoß mit Rad oder E-Scooter — warum Sie auch dann selten voll im Recht sind.', text: `Weil vom Auto eine Betriebsgefahr ausgeht, die im Haftungsverhältnis mitzählt, selbst wenn die andere Seite den Fehler gemacht hat. In einer Stadt mit derart hohem Rad- und Rollerverkehr ist das der Regelfall statt der Ausnahme: Selbst bei klarem Verstoß des Radfahrers bleibt häufig eine Restquote beim Kraftfahrzeug, die nur entfällt, wenn der Unfall für Sie unabwendbar war. Für die Dokumentation heißt das, dass die Kontaktstelle, die Anstoßhöhe und die Endpositionen besonders sorgfältig festzuhalten sind — bei einem Zweirad entscheidet oft ein einziger Zentimeter darüber, ob der geschilderte Hergang technisch überhaupt möglich war. E-Scooter sind übrigens versicherungspflichtig und tragen ein Versicherungskennzeichen; notieren Sie es.` },
    { h3: 'Was steckt in einem gerichtsfesten Gutachten?', text: `Nicht nur eine Reparaturkostensumme, sondern die vollständige, nachprüfbare Grundlage Ihres Anspruchs. Wir arbeiten nach BVSK-Standard; die weitere Abwicklung läuft parallel über das Claimondo-Partnernetzwerk:`, liste: LEISTUNGS_LISTE },
    { text: `Kfz-Gutachter Aachen — unabhängig, gerichtsfest und schnell vor Ort, im Dreiländereck ebenso wie in der Innenstadt. Ein kurzer Anruf oder eine Nachricht über WhatsApp genügt, um zu klären, ob sich ein Gutachten in Ihrem Fall lohnt und welche Unterlagen Sie bereithalten sollten.` },
  ],
  dueren: [
    { text: `Düren liegt an der Rur, auf halbem Weg zwischen Aachen und Köln, und lebt seit Generationen von Papier, Maschinenbau und Logistik. Das schlägt bis in die Schadenfälle durch: Neben dem privaten Pkw stehen hier auffällig oft Firmenwagen, Transporter und Pendlerfahrzeuge auf dem Hof, die schnell wieder laufen müssen. Genau deshalb entscheidet in Düren selten die Frage, ob ein Schaden vorliegt — sondern wie er bewertet wird. Markus ist meist binnen 60 Minuten vor Ort, von Düren-Mitte über Birkesdorf und Gürzenich bis Lendersdorf, Niederau und Rölsdorf. Kosten entstehen Ihnen dabei keine: Nach § 249 BGB gehört das Sachverständigenhonorar bei unverschuldetem Unfall zum ersatzfähigen Schaden.` },
    { vorort: true, text: `Das Dürener Stadtgebiet ist weitläufig, und die Ortslagen unterscheiden sich stark. Die Innenstadt ist kompakt und von Einbahnstraßen und Kreisverkehren geprägt, Birkesdorf und Mariaweiler sind dicht bebaute Wohnquartiere mit beidseitigem Parken, und nach Süden hin — Gürzenich, Lendersdorf, Rölsdorf — wird es hügeliger und ländlicher. Wir fahren alle diese Lagen an, auch die Gewerbeflächen am Stadtrand, und nehmen das Fahrzeug dort auf, wo es nach dem Unfall steht.` },
    { h3: 'Die Versicherung schickt ein Restwertangebot aus dem Internet — müssen Sie darauf eingehen?', text: `In aller Regel nicht. Der Restwert Ihres Fahrzeugs wird im Gutachten anhand des regionalen Marktes ermittelt — also dessen, was Sie in und um Düren tatsächlich erzielen könnten. Versicherer halten dem gern ein höheres Gebot aus einer bundesweiten Online-Restwertbörse entgegen, oft von einem Aufkäufer mehrere hundert Kilometer entfernt. Ein höherer Restwert senkt unmittelbar Ihre Auszahlung, denn er wird vom Wiederbeschaffungswert abgezogen. Wichtig ist deshalb die Reihenfolge: Verkaufen Sie das Fahrzeug nicht, bevor das Gutachten vorliegt und der Restwert bewertet ist — ein voreiliger Verkauf kann Ihnen den Einwand abschneiden.` },
    { h3: 'Merkantiler Minderwert: Woran bemisst er sich eigentlich?', text: `Der merkantile Minderwert bildet ab, dass ein reparierter Unfallwagen am Markt weniger bringt als ein unfallfreier — auch dann, wenn die Reparatur handwerklich einwandfrei war, weil der Schaden offenbarungspflichtig bleibt. Maßgeblich sind Alter und Laufleistung, der Fahrzeugtyp und seine Marktgängigkeit, vor allem aber Art und Tiefe des Schadens: Ein ausgetauschtes Anbauteil wiegt anders als eine gerichtete Trägerstruktur. Weil sich daraus ein Betrag ergibt, den die Gegenseite zusätzlich zahlen muss, ist es die Position, die am häufigsten bestritten wird — und die am ehesten durchgeht, wenn sie sauber hergeleitet ist.` },
    { h3: 'Das Auto ist längst repariert — lässt sich die Wertminderung trotzdem noch verlangen?', text: `Häufig ja, aber es wird deutlich schwieriger. Nach der Reparatur ist der Ausgangszustand nicht mehr sichtbar, und die Herleitung stützt sich dann auf Reparaturrechnung, Ersatzteilpositionen und vorhandene Fotos statt auf das Fahrzeug selbst. Das ist möglich, aber angreifbar. Deutlich belastbarer wird es, wenn das Fahrzeug vor Beginn der Arbeiten aufgenommen wurde — ein Grund, warum sich der Anruf beim Sachverständigen lohnt, bevor der Werkstatttermin steht, nicht danach.` },
    { h3: 'Die Versicherung meldet sich einfach nicht — wie lange müssen Sie warten?', text: `Ein Versicherer darf prüfen, und eine angemessene Prüffrist müssen Sie ihm zugestehen; er darf die Sache aber nicht liegen lassen. Der übliche Weg führt über eine schriftliche Zahlungsaufforderung mit konkret gesetzter Frist. Verstreicht sie, tritt Verzug ein — und ab diesem Zeitpunkt schuldet die Gegenseite zusätzlich Verzugszinsen und die Kosten der weiteren Rechtsverfolgung. Wichtig ist, dass die Forderung überhaupt bezifferbar war: Solange kein Gutachten vorliegt, kann der Versicherer schlicht auf fehlende Unterlagen verweisen und die Uhr läuft nicht. Wer früh begutachten lässt, setzt damit auch den Fristenlauf früher in Gang.` },
    { h3: 'Porto, Telefon, Fahrten zur Werkstatt — bleiben Sie auf den Nebenkosten sitzen?', text: `Nein, dafür gibt es die allgemeine Kostenpauschale. Sie deckt den Kleinkram ab, der bei jeder Schadenabwicklung anfällt und den niemand einzeln belegen kann: Telefonate, Schriftverkehr, Portokosten, Wege. Über ihre Höhe entscheiden die Gerichte nicht einheitlich, sie wird aber regelmäßig zuerkannt, ohne dass Sie Belege sammeln müssen. Daneben stehen erstattungsfähige Einzelpositionen, die tatsächlich anfallen können — etwa Abmelde- und Anmeldekosten bei einer Ersatzbeschaffung oder die Kosten für eine notwendige Nachbesichtigung. Diese Posten sind klein, werden aber gern vergessen und summieren sich.` },
    { h3: 'Beim Zerlegen kommt mehr zum Vorschein als erwartet — was passiert dann?', text: `Dann wird nachgetragen, und das ist ein normaler Vorgang, kein Fehler der ersten Kalkulation. Eine Erstbesichtigung erfolgt am unzerlegten Fahrzeug; was hinter Verkleidungen, im Längsträger oder an Aufnahmepunkten liegt, ist zu diesem Zeitpunkt technisch nur eingeschränkt beurteilbar. Meldet die Werkstatt beim Zerlegen einen weitergehenden Befund, kommen wir zur Nachbesichtigung und erstellen ein Nachtragsgutachten, das den zusätzlichen Umfang dokumentiert und begründet. Wichtig ist, dass die Werkstatt sich meldet, bevor sie weiterarbeitet — ist das Teil bereits ersetzt und entsorgt, lässt sich der Mehraufwand später kaum noch belegen, und genau an dieser Stelle setzen Kürzungen an.` },
    { h3: 'Was liefert die Kalkulation konkret?', text: `Eine nachvollziehbare, prüffähige Grundlage für jede einzelne Anspruchsposition — nicht nur eine Endsumme. Dokumentiert wird nach BVSK-Standard, die Abwicklung begleitet das Claimondo-Partnernetzwerk:`, liste: LEISTUNGS_LISTE },
    { text: `Kfz-Gutachter Düren — unabhängig, schnell erreichbar und mit Blick auf die Positionen, an denen es finanziell wirklich hängt. Melden Sie sich telefonisch oder über WhatsApp; wir sagen Ihnen offen, ob sich ein Gutachten in Ihrem Fall rechnet.` },
  ],
  alsdorf: [
    { text: `Alsdorf, nordöstlich von Aachen, hat sich vom Steinkohlestandort zur Wohn- und Gewerbestadt gewandelt — und diese doppelte Herkunft sieht man dem Verkehr an. Neben dem Berufspendelverkehr Richtung Aachen prägen Transporter, Handwerkerfahrzeuge und Lieferverkehr das Bild. Ein beschädigtes Fahrzeug ist hier deshalb oft nicht nur ein privates Ärgernis, sondern ein Betriebsmittel, das ausfällt. Markus ist meist binnen 60 Minuten vor Ort — in Alsdorf-Mitte ebenso wie in Mariadorf, Hoengen, Schaufenberg oder Warden. Für Sie bleibt es bei 0 €: Bei unverschuldetem Unfall zählt das Sachverständigenhonorar nach § 249 BGB zum Schaden, den die Gegenseite zu ersetzen hat.` },
    { vorort: true, text: `Alsdorf ist stark zersiedelt — mehrere gewachsene Ortslagen, die über Ortsverbindungsstraßen zusammenhängen, dazwischen offene Flächen. Für die Schadenaufnahme ist das praktisch relevant: Fahrzeuge stehen nach einem Unfall selten zentral, sondern in einer Wohnstraße, auf einem Betriebshof oder am Straßenrand außerhalb. Wir kommen in alle Ortslagen und nehmen auch nicht mehr fahrbereite Fahrzeuge dort auf, wo sie abgestellt wurden — ein Transport zur Begutachtung ist nicht nötig.` },
    { h3: 'Firmenwagen oder Leasingfahrzeug beschädigt — wer macht den Schaden überhaupt geltend?', text: `Das hängt daran, wer Eigentümer ist, und genau hier wird es oft falsch gemacht. Beim geleasten Fahrzeug ist der Leasinggeber Eigentümer; Reparatur- und Wertminderungsansprüche stehen deshalb regelmäßig ihm zu, während Nutzungsausfall und die Kosten des Mietwagens beim Leasingnehmer liegen. Viele Leasingverträge schreiben zusätzlich vor, wie und wo repariert werden darf und dass der Leasinggeber unverzüglich zu informieren ist. Beim reinen Firmenwagen im Eigentum des Betriebs ist die Firma Anspruchsinhaberin — nicht die Person am Steuer. Ein Gutachten, das den falschen Anspruchsinhaber ausweist, kostet Zeit; wir klären das vor der Aufnahme.` },
    { h3: 'Was ist ein Ausfallschaden — und wann tritt er an die Stelle des Mietwagens?', text: `Fällt ein gewerblich genutztes Fahrzeug aus, ist der Schaden nicht der entgangene Fahrspaß, sondern der entgangene Ertrag. Wer keinen Ersatzwagen anmietet, kann stattdessen den konkreten Ausfallschaden geltend machen — bei Nutzfahrzeugen häufig über Vorhaltekosten oder entgangenen Gewinn. Das setzt allerdings voraus, dass die Ausfalldauer belastbar begründet ist. Genau dafür braucht es zwei Angaben aus dem Gutachten: die Reparaturdauer beziehungsweise, im Totalschadenfall, die Wiederbeschaffungsdauer. Ohne diese Zahlen bleibt die Forderung eine Behauptung.` },
    { h3: 'Netto oder brutto: Warum die Vorsteuer die Abrechnung verändert.', text: `Ist der Geschädigte vorsteuerabzugsberechtigt — bei Betrieben der Normalfall —, wird der Schaden netto abgerechnet, weil die Umsatzsteuer über die Vorsteuer zurückfließt und insoweit kein Nachteil entsteht. Für Privatpersonen gilt das nicht; dort ist die Umsatzsteuer erstattungsfähig, sobald sie tatsächlich angefallen ist. Deshalb weisen wir im Gutachten die Beträge getrennt aus. Wird das übersehen, entsteht auf der einen Seite eine Überzahlung, die zurückgefordert wird, auf der anderen eine unnötige Kürzung.` },
    { h3: 'Leasingrückgabe nach einem Unfall: Was kommt da noch auf Sie zu?', text: `Der unangenehme Teil kommt oft erst am Vertragsende. Bei der Rückgabe bewertet der Leasinggeber das Fahrzeug, und ein dokumentierter Unfallschaden schlägt dort ein zweites Mal durch — auch dann, wenn fachgerecht repariert wurde. Steht die Wertminderung nicht im Gutachten oder wurde sie nie geltend gemacht, tragen Sie diese Differenz am Ende selbst, obwohl sie der Gegenseite zuzurechnen wäre. Ebenso wichtig ist die Reparaturqualität: Viele Verträge verlangen die Instandsetzung in einer bestimmten Werkstattkategorie, und eine abweichende Reparatur kann bei der Rückgabe zu Nachforderungen führen. Beides lässt sich vorher klären, hinterher kaum noch.` },
    { h3: 'Der Transporter wird jeden Tag gebraucht — wie kurz lässt sich die Standzeit halten?', text: `Kurz, aber nicht auf Kosten der Beweislage. Von Ihnen wird erwartet, den Schaden gering zu halten — also nicht wochenlang zuzuwarten und die Ausfallzeit unnötig zu verlängern. Gleichzeitig darf die Eile nicht dazu führen, dass repariert wird, bevor der Zustand dokumentiert ist; danach ist der Nachweis weg. Der praktikable Weg ist deshalb die frühe Besichtigung: Sobald das Fahrzeug aufgenommen ist, kann die Werkstatt sofort beginnen, und Reparaturdauer wie Ausfallzeitraum sind zugleich belegt. Rufen Sie also eher zu früh an als zu spät — der Termin lässt sich meist noch am selben Tag legen.` },
    { h3: 'Ein Mitarbeiter hat den Unfall verursacht — muss er dafür aufkommen?', text: `Meist nicht, jedenfalls nicht in voller Höhe. Für Schäden bei betrieblich veranlassten Fahrten gilt der innerbetriebliche Schadensausgleich, und der staffelt die Haftung nach dem Grad des Verschuldens: Bei leichter Fahrlässigkeit — dem klassischen Moment der Unaufmerksamkeit — haftet der Beschäftigte in der Regel gar nicht, bei mittlerer wird zwischen Betrieb und Mitarbeiter geteilt, und erst bei grober Fahrlässigkeit oder Vorsatz kommt eine volle Inanspruchnahme in Betracht, die selbst dann noch aus Billigkeitsgründen begrenzt sein kann. Für die Schadenaufnahme ist das insofern relevant, als der Hergang sauber festgehalten werden sollte: Er entscheidet nicht nur über die Haftung nach außen, sondern auch über diese interne Aufteilung.` },
    { h3: 'Was wird am Fahrzeug festgehalten?', text: `Alles, was später eine Anspruchsposition tragen muss — technisch geprüft, fotografisch belegt und nach BVSK-Standard aufbereitet. Die weitere Abwicklung übernimmt das Claimondo-Partnernetzwerk:`, liste: LEISTUNGS_LISTE },
    { text: `Kfz-Gutachter Alsdorf — unabhängig, kurzfristig vor Ort und vertraut mit gewerblichen Schadenfällen. Ein Anruf oder eine WhatsApp-Nachricht genügt, um zu klären, wer in Ihrem Fall Anspruchsinhaber ist und was das für die Abrechnung bedeutet.` },
  ],
  wuerselen: [
    { text: `Würselen hat eine Doppelrolle, die für Unfallschäden erstaunlich viel ausmacht: innen gewachsene Ortslagen mit ruhigem Anwohnerverkehr, außen die großen Achsen, auf denen der Fernverkehr Richtung Belgien und Niederlande abbiegt. Dadurch treffen hier zwei sehr unterschiedliche Schadentypen aufeinander — der niedrige Rempler im Ortskern und der Auffahrschaden bei hoher Differenzgeschwindigkeit. Beide werden von Versicherern gern in Zweifel gezogen, allerdings aus entgegengesetzten Gründen. Markus ist meist binnen 60 Minuten in Würselen-Mitte, Bardenberg oder Broichweiden. Ihr Kostenanteil bleibt bei 0 €, denn nach § 249 BGB trägt die eintrittspflichtige Gegenseite das Sachverständigenhonorar.` },
    { vorort: true, text: `Die drei Ortslagen liegen räumlich getrennt, und wir fahren sie alle an. Würselen-Mitte ist der dichteste Bereich mit Geschäftsverkehr und entsprechend vielen Park- und Rangierschäden, Bardenberg ist überwiegend Wohnlage mit engen Straßenquerschnitten, Broichweiden liegt offener am östlichen Stadtrand. Wo Ihr Fahrzeug nach dem Unfall steht — Wohnstraße, Werkstatthof oder Stellplatz —, spielt für die Aufnahme keine Rolle; wir kommen dorthin, auch wenn es nicht mehr fahrbereit ist.` },
    { h3: 'Die Versicherung bestreitet, dass der Schaden zum Unfall passt — was hilft dann?', text: `Dieser Einwand kommt häufiger, als die meisten erwarten, und er ist zunächst kein Vorwurf, sondern eine Behauptung, die widerlegt werden kann. Geprüft wird, ob Schadenbild, Höhenlage und Verformungsrichtung zum geschilderten Hergang und zum Gegnerfahrzeug passen. Dafür zählen Details, die im Alltag niemand fotografiert: Anstoßhöhe über Fahrbahn, Kontaktspuren und Lackantragungen, die Richtung, in die Bauteile verschoben wurden. Wird das Fahrzeug früh und vollständig aufgenommen, lässt sich der Einwand meist sachlich ausräumen. Ist es bereits repariert, fehlt die Grundlage — deshalb gilt hier besonders: erst begutachten, dann reparieren.` },
    { h3: 'Was ist ein Kompatibilitätsgutachten?', text: `Es beantwortet ausschließlich die Frage, ob die Schäden an beiden Fahrzeugen technisch zueinander passen — unabhängig davon, wie hoch die Reparatur ausfällt. Versicherer beauftragen so etwas, wenn sie einen manipulierten oder einen bereits vorhandenen Schaden vermuten. Für Sie als Geschädigten ist das kein Grund zur Sorge, solange die eigene Dokumentation trägt: Ein sauber aufgenommener Schaden mit nachvollziehbarer Spurenlage hält einer solchen Prüfung stand. Problematisch wird es erst, wenn die einzigen Belege drei Handyfotos aus derselben Perspektive sind.` },
    { h3: 'Kleiner Schaden — lohnt ein Gutachten überhaupt noch?', text: `Bei sehr geringfügigen Schäden reicht ein Kostenvoranschlag manchmal aus, und dann sagen wir Ihnen das auch. Die Grenze verläuft aber niedriger, als viele denken, und sie verläuft nicht nach Optik: Moderne Stoßfängersysteme verbergen Träger, Aufnahmen und Sensorik, sodass hinter einer nur leicht angekratzten Verkleidung ein Vielfaches an Instandsetzungsaufwand stecken kann. Ein Kostenvoranschlag erfasst zudem weder Wertminderung noch Nutzungsausfall. Rufen Sie im Zweifel kurz an — die Einschätzung kostet nichts.` },
    { h3: 'Warum die Reparatur mit dem Lackieren nicht zu Ende ist.', text: `Weil an modernen Fahrzeugen halbe Sensorik in genau den Bauteilen sitzt, die bei einem Auffahrunfall zuerst getroffen werden. Radarsensoren hinter dem Stoßfänger, Kameras an der Windschutzscheibe, Ultraschallgeber in Verkleidungen, dazu Systeme für Abstandsregelung, Spurhaltung und Notbremsung. Werden diese Teile aus- und wieder eingebaut oder ersetzt, müssen sie anschließend kalibriert werden — sonst arbeitet ein Assistenzsystem mit falschem Bezugspunkt weiter, ohne eine Warnung anzuzeigen. Die Kalibrierung ist ein eigener, kostenpflichtiger Arbeitsschritt und gehört deshalb in die Kalkulation. Fehlt sie dort, wird sie später gestrichen und Sie zahlen sie selbst.` },
    { h3: 'Beschwerden nach dem Aufprall werden bestritten — was kann ein Sachverständiger dazu beitragen?', text: `Nur den technischen Teil, und der ist begrenzt, aber wichtig. Ermittelt wird die kollisionsbedingte Geschwindigkeitsänderung, also die Belastung, die aus Schadenbild, Fahrzeuggewichten und Aufprallwinkel rekonstruierbar ist. Diese Größe beantwortet nicht die medizinische Frage — eine feste Grenze, unterhalb derer Beschwerden ausgeschlossen wären, gibt es nicht, und Versicherer argumentieren gelegentlich so, als gäbe es sie. Die technische Rekonstruktion liefert aber die belastbare Grundlage, auf der medizinisch überhaupt erst bewertet werden kann. Ohne sie steht Behauptung gegen Behauptung.` },
    { h3: 'Wer muss eigentlich was beweisen?', text: `Grundsätzlich Sie als Anspruchsteller — Hergang, Verursachung und Höhe des Schadens. Das klingt ungünstiger, als es ist, denn im Straßenverkehr helfen Beweiserleichterungen: Bei typischen Konstellationen wie einem Auffahrunfall spricht der erste Anschein zunächst gegen den Auffahrenden, und er muss diesen Anschein erschüttern. Solche Regeln greifen jedoch nur, wenn der Hergang unstreitig oder belegt ist. Genau daran scheitern viele Fälle: Nicht die Rechtslage ist das Problem, sondern dass niemand mehr rekonstruieren kann, was passiert ist. Fotos, Zeugen und eine frühe Fahrzeugaufnahme sind deshalb wertvoller als jede nachträgliche Schilderung.` },
    { h3: 'Sie haben eine Dashcam — hilft die Aufnahme Ihnen weiter?', text: `Als Beweismittel im Unfallhaftpflichtprozess ja, auch wenn die dauerhafte anlasslose Aufzeichnung datenschutzrechtlich problematisch bleibt. Die Rechtsprechung trennt diese beiden Ebenen: Ein Verstoß gegen Datenschutzvorgaben führt nicht automatisch dazu, dass das Video nicht verwertet werden darf; abgewogen wird zwischen dem Persönlichkeitsrecht des Gefilmten und Ihrem Interesse an einer wirksamen Rechtsverfolgung — und bei einem Unfall im öffentlichen Straßenraum geht diese Abwägung häufig zu Ihren Gunsten aus. Praktisch heißt das: Sichern Sie die Datei sofort und überschreiben Sie sie nicht. Für die technische Rekonstruktion ist sie besonders wertvoll, weil sie Geschwindigkeiten und Abstände belegt, die sich sonst nur schätzen lassen.` },
    { h3: 'Was wird bei der Aufnahme geprüft?', text: `Der gesamte technische Zusammenhang, nicht nur die sichtbare Beschädigung. Dokumentiert wird nach BVSK-Standard; die Abwicklung begleitet das Claimondo-Partnernetzwerk:`, liste: LEISTUNGS_LISTE },
    { text: `Kfz-Gutachter Würselen — unabhängig, schnell vor Ort und darauf eingestellt, dass Schäden hier oft nicht nur beziffert, sondern auch belegt werden müssen. Melden Sie sich telefonisch oder über WhatsApp, bevor die Reparatur beginnt.` },
  ],
  baesweiler: [
    { text: `Baesweiler liegt im Norden der Städteregion Aachen, wenige Kilometer von der niederländischen Grenze entfernt, und war über Generationen eine Bergbaustadt. Geblieben sind daraus zwei Dinge, die den Straßenverkehr bis heute prägen: großzügig angelegte Gewerbe- und Logistikflächen am Rand — und Wohnquartiere, deren Straßenzuschnitt aus einer Zeit stammt, in der weder heutige Fahrzeugbreiten noch beidseitiges Dauerparken vorgesehen waren. Dazu kommt der alltägliche Verkehr über die Grenze. Markus ist meist binnen 60 Minuten in Baesweiler-Mitte, Setterich, Oidtweiler oder Beggendorf. Kosten entstehen Ihnen keine: Bei unverschuldetem Unfall gehört das Sachverständigenhonorar nach § 249 BGB zum ersatzfähigen Schaden.` },
    { vorort: true, text: `Baesweiler besteht aus mehreren eigenständigen Ortslagen, zwischen denen freie Feldflur liegt — Baesweiler-Mitte als Zentrum, Setterich im Süden, Oidtweiler und Beggendorf nördlich davon. Für die Schadenaufnahme heißt das: kurze Wege innerhalb einer Ortslage, aber keine zentrale Anlaufstelle, an der alles zusammenläuft. Wir kommen deshalb zu Ihnen — nach Hause, zum Betrieb oder an den Ort, an dem das Fahrzeug nach dem Unfall abgestellt wurde. Ein nicht mehr fahrbereites Auto muss für die Begutachtung nirgendwohin transportiert werden.` },
    { h3: 'Unfallgegner mit niederländischem Kennzeichen: Welche Angaben sichern Ihren Anspruch?', text: `Vier Angaben tragen den ganzen weiteren Vorgang, und sie sind später kaum nachzuholen. Erstens das Kennzeichen vollständig samt Länderkennung — fotografiert, nicht notiert. Zweitens der Name der Versicherungsgesellschaft; er steht häufig auf der Grünen Karte oder der Versicherungsbestätigung im Fahrzeug. Drittens Name und Anschrift des Fahrers sowie, falls abweichend, des Halters. Und viertens der genaue Unfallort, denn er entscheidet darüber, welches Recht angewendet wird. Ist die Versicherung nicht zu ermitteln, hilft der Zentralruf der Autoversicherer weiter, der anhand des Kennzeichens den zuständigen Versicherer zuordnet.` },
    { h3: 'Wer bearbeitet den Schaden, wenn der Versicherer in den Niederlanden sitzt?', text: `Sie müssen sich nicht selbst mit einem Unternehmen in Heerlen, Landgraaf oder Kerkrade auseinandersetzen. Für Unfälle, die ein ausländisch zugelassenes Fahrzeug in Deutschland verursacht hat, ist das Deutsche Büro Grüne Karte die zuständige Anlaufstelle. Zusätzlich muss jeder Versicherer aus dem europäischen Wirtschaftsraum in Deutschland einen Schadenregulierungsbeauftragten benennen, der den Fall in deutscher Sprache bearbeitet und innerhalb einer gesetzlich vorgesehenen Frist begründet Stellung nehmen muss. Die Korrespondenz läuft also im Inland — auch wenn das Geld am Ende aus dem Ausland kommt.` },
    { h3: 'Gilt ein deutsches Gutachten gegenüber einem ausländischen Versicherer?', text: `Ja, und zwar aus einem systematischen Grund: Für einen Unfall, der sich in Deutschland ereignet hat, gilt grundsätzlich deutsches Schadenrecht — unabhängig davon, wo der Verursacher wohnt oder versichert ist. Damit bleiben Ihnen genau die Positionen erhalten, die andere Rechtsordnungen so nicht kennen: Wertminderung, Nutzungsausfall, freie Wahl der Werkstatt und eben die Erstattung des Sachverständigenhonorars. Sie müssen auch keinen Gutachter der gegnerischen Seite akzeptieren; die Auswahl bleibt Ihre. Ein nach deutschem Standard erstelltes Gutachten ist deshalb nicht nur zulässig, sondern die passende Grundlage.` },
    { h3: 'Und wenn der Verursacher gar nicht versichert war oder einfach weiterfährt?', text: `Auch dann ist der Fall nicht automatisch verloren. Für Schäden durch nicht versicherte, unbekannt gebliebene oder entwendete Fahrzeuge existiert mit der Verkehrsopferhilfe eine Auffangeinrichtung. Die Voraussetzungen unterscheiden sich allerdings je nach Konstellation deutlich und sind bei unbekanntem Verursacher spürbar strenger als bei einem bekannten, aber unversicherten Gegner. Gemeinsam ist beiden Wegen: Ohne dokumentierten Schadenumfang lässt sich der Anspruch nicht einmal prüfen. Die Aufnahme sollte deshalb auch dann erfolgen, wenn zunächst unklar ist, wer am Ende zahlt.` },
    { h3: 'Der umgekehrte Fall: Sie selbst verunglücken jenseits der Grenze.', text: `Dann dreht sich die Systematik um, und das ist folgenreich. Passiert der Unfall in den Niederlanden, gilt grundsätzlich niederländisches Schadenrecht — mit anderen Maßstäben als hier. Positionen, die Sie aus Deutschland kennen, sind dort nicht selbstverständlich; die Wertminderung etwa spielt eine deutlich geringere Rolle, und auch beim Nutzungsausfall wird anders gerechnet. Sie können den Anspruch trotzdem in Deutschland verfolgen: Über den in Deutschland ansässigen Schadenregulierungsbeauftragten des ausländischen Versicherers läuft die Korrespondenz im Inland. Die Höhe richtet sich aber nach dem Recht des Unfallorts, nicht nach dem Ihres Wohnsitzes. Wer das vorher weiß, kalkuliert realistischer.` },
    { h3: 'Was wird von Ihnen erwartet, damit der Schaden nicht unnötig wächst?', text: `Sie müssen den Schaden gering halten, soweit Ihnen das zumutbar ist — das ist keine Formalie, sondern der häufigste Ansatzpunkt für Kürzungen. Konkret heißt es: das Fahrzeug sichern, damit keine Folgeschäden entstehen; die Reparatur nicht ohne Grund hinauszögern; einen Mietwagen nur so lange und in der Klasse nehmen, wie es dem beschädigten Fahrzeug entspricht; und bei geringer Fahrleistung prüfen, ob Nutzungsausfall statt Mietwagen die angemessene Lösung ist. Umgekehrt verlangt niemand von Ihnen, das billigste Angebot zu suchen oder auf ein Ersatzfahrzeug zu verzichten. Es geht um Angemessenheit, nicht um Sparsamkeit.` },
    { h3: 'Wem gehört das Gutachten, wenn es fertig ist?', text: `Ihnen — Sie sind der Auftraggeber, und Sie entscheiden, wer es bekommt. In der Regel geht es an die gegnerische Versicherung, an Ihren Anwalt und an die Werkstatt, die auf seiner Grundlage kalkuliert. Wichtig ist der Unterschied zu einem Gutachten, das die Gegenseite selbst beauftragt hat: Deren Sachverständiger arbeitet für sie, nicht für Sie, und das Ergebnis müssen Sie nicht gegen sich gelten lassen. Sie sind auch nicht verpflichtet, sich auf einen von der Versicherung geschickten Prüfer einzulassen, bevor ein eigenes Gutachten vorliegt. Ein zweiter Termin auf Wunsch der Gegenseite ist möglich, aber er ersetzt Ihr Gutachten nicht.` },
    { h3: 'Der Unfallgegner spricht kein Deutsch — wie halten Sie den Hergang fest?', text: `Möglichst ohne Worte. Verzichten Sie auf eine gemeinsame Schilderung, die keiner von beiden zweifelsfrei versteht, und dokumentieren Sie stattdessen: Endstellung beider Fahrzeuge vor dem Räumen, Schäden an beiden Wagen, Kennzeichen, Fahrzeugpapiere und Versicherungsnachweis abfotografiert. Der europäische Unfallbericht existiert genau dafür — er ist zweisprachig aufgebaut, sodass beide Seiten dieselbe Zeile in ihrer Sprache lesen, und er kommt weitgehend ohne freien Text aus. Unterschreiben Sie darin niemals ein Schuldanerkenntnis, auch nicht in einer Sprache, die Sie nicht sicher beherrschen. Die Bewertung der Schuldfrage ist ohnehin Sache der Versicherer, nicht Ihre Aufgabe am Unfallort.` },
    { h3: 'Der Verursacher fuhr einen ausländischen Lkw — worauf kommt es dann zusätzlich an?', text: `Auf die Frage, welches Fahrzeug eigentlich haftet. Bei einem Gespann sind Zugmaschine und Auflieger häufig getrennt zugelassen, teils in verschiedenen Ländern, gelegentlich sogar bei verschiedenen Versicherern — und der Schaden kann von beiden ausgehen. Fotografieren Sie deshalb beide Kennzeichen, nicht nur das vordere, und wenn möglich auch die seitliche Beschriftung des Fuhrunternehmens. Hinzu kommt die technische Seite: Anstöße durch schwere Fahrzeuge wirken auf einer anderen Höhe und übertragen deutlich mehr Energie in die Struktur, als das Schadenbild an der Außenhaut vermuten lässt. Ein scheinbar harmloser Streifschaden am Kotflügel kann Aufnahmen und Achsgeometrie betreffen. Genau deshalb sollte hier auch bei kleinem Erscheinungsbild vollständig vermessen werden.` },
    { h3: 'Was steht am Ende im Gutachten?', text: `Eine belastbare, prüffähige Aufstellung sämtlicher Positionen — auch gegenüber einem ausländischen Regulierer. Erstellt nach BVSK-Standard, begleitet vom Claimondo-Partnernetzwerk:`, liste: LEISTUNGS_LISTE },
    { text: `Kfz-Gutachter Baesweiler — unabhängig, kurzfristig vor Ort und mit Routine in der grenzüberschreitenden Regulierung. Rufen Sie an oder schreiben Sie über WhatsApp; wir sagen Ihnen, welche Angaben Sie zuerst sichern sollten.` },
  ],
  eschweiler: [
    { text: `Eschweiler liegt im Talgrund der Inde, und die Stadt hat 2021 in kürzester Zeit erlebt, was ein Totalschaden im großen Maßstab bedeutet. Markus war damals über Monate hier im Einsatz. Was aus dieser Zeit bleibt, ist weniger die Erinnerung an das Wasser als eine sehr praktische Erfahrung: Sobald ein Fahrzeug nicht mehr repariert, sondern ersetzt wird, verschiebt sich der ganze Streit — weg von der Reparaturkalkulation, hin zu Wiederbeschaffungswert, Restwert und Abrechnungsweg. Genau dort werden bis heute die meisten Beträge gekürzt. Markus ist meist binnen 60 Minuten vor Ort, und für Sie bleibt es bei 0 €: Nach § 249 BGB trägt die eintrittspflichtige Gegenseite das Honorar.` },
    { vorort: true, text: `Das Stadtgebiet zerfällt in zwei sehr unterschiedliche Hälften: unten die Innenstadt im engen Talgrund mit dichter Bebauung und knappen Fahrgassen, oben und nördlich der offene Nordraum um Dürwiß und die angrenzenden Ortslagen mit weiten Sichtachsen und höherem Tempo. Weisweiler im Osten ist industriell geprägt. Wir fahren alle Lagen an und nehmen das Fahrzeug dort auf, wo es steht — im Hof, an der Straße oder beim Abschleppdienst.` },
    { h3: 'Totalschaden: Wie entsteht eigentlich der Wiederbeschaffungswert?', text: `Er ist nicht das, was Sie damals bezahlt haben, und auch nicht der Betrag aus einer Online-Bewertung. Maßgeblich ist, was Sie heute aufwenden müssten, um ein gleichwertiges Fahrzeug bei einem seriösen Händler zu erwerben — also mit vergleichbarer Ausstattung, Laufleistung, Vorschadenfreiheit und Zustand. Der regionale Markt spielt dabei eine erhebliche Rolle. Von diesem Wert wird der Restwert abgezogen; die Differenz ist Ihre Auszahlung. Deshalb entscheidet die Sorgfalt bei diesen beiden Zahlen über deutlich mehr Geld als jede einzelne Position der Reparaturkalkulation.` },
    { h3: 'Reparieren lassen oder auszahlen lassen?', text: `Beides ist möglich, und die Wahl gehört Ihnen. Rechnen Sie fiktiv ab, erhalten Sie den ermittelten Betrag ausgezahlt und entscheiden selbst, ob und wie repariert wird — die Umsatzsteuer bleibt dann allerdings außen vor, solange sie nicht tatsächlich anfällt. Lassen Sie konkret reparieren, wird nach Rechnung erstattet. Liegen die Reparaturkosten nur wenig über dem Wiederbeschaffungswert, kann die Instandsetzung trotzdem durchsetzbar sein, wenn Sie das Fahrzeug anschließend weiter nutzen; hier lohnt es sich, vor der Entscheidung kurz zu sprechen, weil die Reihenfolge der Schritte über die Erstattungsfähigkeit mitentscheidet.` },
    { h3: 'Wiederbeschaffungsdauer — warum diese eine Angabe über Ihren Mietwagen entscheidet.', text: `Im Totalschadenfall bemisst sich der Anspruch auf Mietwagen oder Nutzungsausfall nicht an der Reparaturdauer, denn es wird ja nicht repariert. Maßgeblich ist stattdessen die Wiederbeschaffungsdauer: der Zeitraum, den Sie realistischerweise brauchen, um ein vergleichbares Fahrzeug zu finden und zuzulassen. Fehlt diese Angabe im Gutachten, kürzt die Gegenseite den Mietwagen erfahrungsgemäß auf wenige Tage. Wir weisen sie deshalb ausdrücklich aus und begründen sie — zusammen mit dem Zeitpunkt, ab dem die Frist überhaupt zu laufen beginnt.` },
    { h3: 'Abschleppen, Standgebühren, Verwahrung — wer trägt diese Kosten?', text: `Grundsätzlich die Gegenseite, denn sie gehören zur Schadenbeseitigung. Erstattet werden die Bergung beziehungsweise das Abschleppen zur nächstgelegenen geeigneten Werkstatt sowie die Standkosten für den Zeitraum, in dem das Fahrzeug dort auf die Begutachtung und die Freigabe warten musste. Die Grenze verläuft dort, wo die Standzeit vermeidbar war: Bleibt ein Totalschaden nach Abschluss des Gutachtens noch wochenlang auf einem kostenpflichtigen Gelände stehen, wird der Versicherer diesen Teil streichen — zu Recht. Praktisch heißt das, dass die Begutachtung zügig erfolgen sollte und Sie nach Vorliegen des Gutachtens über den Verbleib des Fahrzeugs entscheiden müssen, statt es liegen zu lassen.` },
    { h3: 'Sie behalten den Wagen und fahren ihn weiter — was ist dann nachzuweisen?', text: `Die Weiternutzung selbst. Rechnen Sie fiktiv ab und liegt der Schaden im Grenzbereich zum Totalschaden, hängt Ihr Anspruch daran, dass das Fahrzeug tatsächlich weiterbenutzt wird — und zwar in verkehrssicherem Zustand über einen gewissen Zeitraum, nicht nur bis zur Auszahlung. Belegt wird das über eine Reparaturbestätigung: eine Nachbesichtigung, bei der wir dokumentieren, dass die maßgeblichen Schäden behoben und die Verkehrssicherheit hergestellt ist. Das gilt auch dann, wenn Sie in Eigenregie oder in einer freien Werkstatt haben arbeiten lassen. Ohne diesen Nachweis kürzt die Versicherung im Nachhinein auf die Totalschadenabrechnung zurück.` },
    { h3: 'Es steht noch ein zweites Auto vor der Tür — entfällt der Nutzungsausfall dann?', text: `Häufig ja, und das überrascht viele. Nutzungsausfall entschädigt den entgangenen Gebrauch — steht Ihnen ein anderes, gleichwertiges und tatsächlich verfügbares Fahrzeug im Haushalt zur Verfügung, fehlt es an diesem Nachteil, und der Anspruch entfällt oder wird gekürzt. Entscheidend ist allerdings das Wort gleichwertig: Ein deutlich kleinerer Wagen, ein Fahrzeug, das eine andere Person im Haushalt selbst täglich benötigt, oder eines, das für den konkreten Zweck nicht taugt, ersetzt das beschädigte Auto nicht. Verschweigen sollten Sie das Zweitfahrzeug trotzdem nicht — kommt es später heraus, gerät die gesamte Forderung in Zweifel, nicht nur diese Position.` },
    { h3: 'Was liefert das Gutachten dafür?', text: `Die Zahlen, auf die es bei einer Ersatzbeschaffung ankommt — hergeleitet, belegt und nach BVSK-Standard dokumentiert. Die Abwicklung begleitet das Claimondo-Partnernetzwerk:`, liste: LEISTUNGS_LISTE },
    { text: `Kfz-Gutachter Eschweiler — unabhängig, schnell vor Ort und erfahren dort, wo aus einem Schaden eine Ersatzbeschaffung wird. Melden Sie sich telefonisch oder über WhatsApp, bevor Sie ein Restwertangebot annehmen.` },
  ],
  juelich: [
    { text: `Jülich ist eine kleine Stadt an der Rur mit einer ungewöhnlich großen Pendlerbewegung. Das Forschungszentrum zählt zu den größten interdisziplinären Forschungseinrichtungen Europas, dazu kommt der Campus Jülich der FH Aachen — mit der Folge, dass sich der Verkehr hier stark auf Arbeitsbeginn und Arbeitsende konzentriert und dass ein erheblicher Teil der Beschäftigten von außerhalb, teils aus dem Ausland anreist. Für Schadenfälle bedeutet das zwei Besonderheiten: Sehr viele Unfälle passieren auf dem Arbeitsweg, und ungewöhnlich oft ist ein Dienst- oder Firmenfahrzeug beteiligt. Markus ist meist binnen 60 Minuten in Jülich-Mitte, Stetternich, Koslar oder Selgersdorf. Für Sie: 0 € — das Sachverständigenhonorar gehört nach § 249 BGB zum ersatzfähigen Schaden.` },
    { vorort: true, text: `Der historische Kern rund um Zitadelle und Hexenturm ist kompakt und von engen Zufahrten geprägt — dort entstehen vor allem Rangier-, Bordstein- und Parkschäden. Nach außen hin öffnet sich das Stadtgebiet schnell in Richtung der umliegenden Ortslagen wie Stetternich, Koslar und Selgersdorf, wo Wohnbebauung und offene Feldflur direkt aneinandergrenzen. Wir kommen in alle Ortsteile, auch auf Betriebs- und Institutsgelände, und begutachten das Fahrzeug an seinem Standort.` },
    { h3: 'Unfall auf dem Weg zur Arbeit — welche Versicherung greift hier eigentlich?', text: `Es sind häufig mehrere gleichzeitig, und sie decken Unterschiedliches ab. Der Schaden an Ihrem Fahrzeug ist und bleibt eine zivilrechtliche Sache zwischen Ihnen und der gegnerischen Kfz-Haftpflicht — daran ändert der Arbeitsweg nichts. Die gesetzliche Unfallversicherung springt beim Wegeunfall für Personenschäden ein, also für Heilbehandlung und Verdienstausfall, nicht aber für Ihr Blech. Und die eigene Kaskoversicherung kommt nur ins Spiel, wenn die Gegenseite nicht haftet oder nicht greifbar ist. Wer das vermischt, meldet den Fahrzeugschaden bei der falschen Stelle und verliert Wochen.` },
    { h3: 'Dienstwagen beschädigt: Wer beauftragt den Gutachter?', text: `Nicht automatisch die Person, die gefahren ist. Gehört das Fahrzeug dem Arbeitgeber, ist er der Geschädigte und damit derjenige, dem Reparaturkosten und Wertminderung zustehen; ist es geleast, tritt zusätzlich der Leasinggeber als Eigentümer hinzu. Der Anspruch auf Nutzungsausfall oder Mietwagen kann davon abweichen und beim Nutzer liegen. In der Praxis lässt sich das schnell klären — es muss nur vor der Begutachtung geklärt werden, nicht danach, sonst weist das Gutachten den falschen Auftraggeber aus und die Regulierung stockt.` },
    { h3: 'Der Unfallgegner ist im Ausland versichert — ändert das etwas an Ihrem Anspruch?', text: `An der Höhe nicht. Weil sich der Unfall in Deutschland ereignet hat, wird nach deutschem Schadenrecht abgerechnet, mit allen Positionen, die dazugehören. Anders ist nur der Weg: Die Bearbeitung läuft über den in Deutschland benannten Schadenregulierungsbeauftragten des ausländischen Versicherers beziehungsweise über das Deutsche Büro Grüne Karte. Realistisch einplanen sollten Sie allerdings, dass eine solche Regulierung länger dauert als eine rein inländische — ein Grund mehr, die Schadenhöhe früh und vollständig zu belegen, statt später nachzubessern.` },
    { h3: 'Elektro- oder Hybridfahrzeug nach dem Aufprall: Was passiert mit der Batterie?', text: `Sie wird zum eigenen Prüfgegenstand, und das verändert den Ablauf spürbar. Nach einer Kollision im Bereich von Unterboden, Schweller oder Heck muss die Hochvoltbatterie beurteilt werden, auch wenn außen wenig zu sehen ist — mechanische Einwirkung auf das Gehäuse, Eindringen von Feuchtigkeit oder eine ausgelöste Schutzabschaltung sind Befunde, die man nicht ansieht. Die Arbeiten dürfen nur Betriebe mit entsprechender Hochvolt-Qualifikation ausführen, und bei Verdacht auf eine Zellschädigung gelten besondere Vorgaben für Lagerung und Transport. Für die Bewertung heißt das zweierlei: Die Instandsetzung kann deutlich teurer ausfallen als das Schadenbild vermuten lässt, und die wirtschaftliche Grenze zum Totalschaden ist schneller erreicht.` },
    { h3: 'Sie nehmen die eigene Kaskoversicherung in Anspruch — was kostet das später?', text: `Es kommt darauf an, welche. Die Vollkaskoversicherung ist nach Schadenfreiheitsklassen gestaffelt; eine Inanspruchnahme führt zur Rückstufung und damit über Jahre zu höheren Beiträgen — der Nachteil kann den ausgezahlten Betrag bei kleineren Schäden übersteigen. Die Teilkasko kennt diese Staffelung nicht, dort droht keine Rückstufung. Wichtig ist die Reihenfolge: Solange die Haftung der Gegenseite realistisch durchsetzbar ist, gibt es keinen Grund, den eigenen Vertrag zu belasten. Die Kasko ist der Weg, wenn niemand haftet, der Verursacher unbekannt bleibt oder die Regulierung erkennbar stockt — und selbst dann lohnt vorher die Rechnung, ob sie sich trägt.` },
    { h3: 'Der Unfall passierte auf einem Firmen- oder Institutsparkplatz — gilt dort anderes Recht?', text: `Im Kern nicht, in der Praxis schon. Auf öffentlich zugänglichen Parkflächen gilt das Gebot der gegenseitigen Rücksichtnahme; die vertrauten Vorfahrtsregeln greifen dort aber nur eingeschränkt, weil Fahrgassen zwischen Stellplätzen in der Regel keine Straßen im Sinne der Vorfahrtsregelung sind. Das Ergebnis ist bemerkenswert häufig eine geteilte Haftung, selbst wenn eine Seite sich eindeutig im Recht sieht. Hinzu kommt, dass es auf einem Betriebsgelände oft weder unbeteiligte Zeugen noch eine polizeiliche Aufnahme gibt. Fotografieren Sie deshalb die Endstellung, die Fahrgassenführung und die Markierungen, bevor jemand rangiert.` },
    { h3: 'Wie lange können Sie sich mit der Geltendmachung Zeit lassen?', text: `Länger, als viele annehmen, aber nicht unbegrenzt. Die regelmäßige Verjährungsfrist für Schadenersatzansprüche beträgt drei Jahre und beginnt erst mit dem Schluss des Jahres, in dem der Unfall passiert ist und Sie den Schädiger kennen — ein Unfall im Januar verjährt also praktisch erst fast vier Jahre später. Das ist kein Grund zu warten: Beweise altern schneller als Fristen. Zeugen erinnern sich unschärfer, Fahrzeuge werden verkauft oder repariert, und ein Schadenbild, das niemand aufgenommen hat, existiert rechtlich kaum noch. Wer den Anspruch offen hat, sollte ihn früh dokumentieren, auch wenn die Klärung dauert.` },
    { h3: 'Sie saßen als Mitfahrer im Wagen — welche Ansprüche haben Sie?', text: `Als Insasse stehen Sie besser da als jeder Fahrer, und in einer Stadt mit so vielen Fahrgemeinschaften ist das keine Randfrage. Wer mitfährt, trifft am Unfall regelmäßig kein Verschulden und muss sich deshalb um die Schuldverteilung zwischen den Fahrzeugen nicht kümmern: Sie können sich grundsätzlich an beide beteiligten Halter beziehungsweise deren Haftpflichtversicherer halten, die insoweit gemeinsam einstehen — auch dann, wenn der Fahrer, bei dem Sie mitgefahren sind, den Unfall selbst verursacht hat. Ersetzt werden neben Personenschäden auch mitgeführte, beschädigte Gegenstände. Melden Sie sich deshalb eigenständig, statt darauf zu warten, dass der Fahrer das für Sie miterledigt.` },
    { h3: 'Steinschlag und Glasbruch auf der täglichen Pendelstrecke — ein Fall für die Teilkasko?', text: `Ja, und zwar mit ungewöhnlich glimpflichen Folgen: Glasschäden laufen über die Teilkasko, und die kennt keine Schadenfreiheitsklassen — Ihr Beitrag steigt dadurch nicht. Entscheidend ist, ob repariert oder ersetzt wird. Kleine Einschläge außerhalb des Sichtfelds lassen sich häufig harzen, was günstiger ist und meist ohne Selbstbeteiligung abgewickelt wird; liegt der Schaden im direkten Sichtfeld oder ist er zu groß, muss die Scheibe getauscht werden. Wichtig bei modernen Fahrzeugen: Sitzt eine Kamera für Assistenzsysteme an der Windschutzscheibe, gehört nach dem Austausch die Kalibrierung zwingend dazu. Ein Gutachten braucht es dafür selten — kommt allerdings ein Haftpflichtschaden hinzu, etwa durch aufgewirbeltes Ladegut eines vorausfahrenden Fahrzeugs, ändert sich die Lage.` },
    { h3: 'Was enthält das Gutachten?', text: `Die vollständige, prüffähige Grundlage Ihres Anspruchs — unabhängig davon, wer am Ende reguliert. Erstellt nach BVSK-Standard, begleitet vom Claimondo-Partnernetzwerk:`, liste: LEISTUNGS_LISTE },
    { text: `Kfz-Gutachter Jülich — unabhängig, kurzfristig vor Ort und vertraut mit Dienstwagen- und Pendlerfällen. Ein Anruf oder eine WhatsApp-Nachricht reicht, um zu klären, wer den Schaden geltend macht und bei wem er zu melden ist.` },
  ],
  stolberg: [
    { text: `Die Kupferstadt Stolberg ist eine Talstadt: Der historische Kern liegt eingeschnitten am Vichtbach unterhalb der Burg, die Wohnlagen liegen auf den Höhen darüber, und dazwischen verlaufen kurvige Steigungsstrecken. Eine eigene Autobahn-Anschlussstelle hat Stolberg nicht — der Verkehr verteilt sich stattdessen über Ortsdurchfahrten und Talstraßen. In Verbindung mit einem vergleichsweise alten Fahrzeugbestand und der Schadenhistorie des Jahres 2021 führt das zu einer Konstellation, die hier häufiger auftritt als anderswo: Der Versicherer behauptet, der geltend gemachte Schaden sei ganz oder teilweise ein Vorschaden. Markus ist meist binnen 60 Minuten vor Ort, und für Sie bleibt es bei 0 € nach § 249 BGB.` },
    { vorort: true, text: `Wir fahren das gesamte Stadtgebiet an, und die Anfahrt unterscheidet sich erheblich. In der Altstadt und den Tallagen sind die Gassen eng und die Stellplätze knapp; auf den Höhen um Münsterbusch und Donnerberg wird offener und schneller gefahren. Nach Südosten, Richtung Vicht und die angrenzenden Waldgebiete, wird es ländlich und unübersichtlich. Steht Ihr Fahrzeug nach dem Unfall in einer Hofeinfahrt, am Hang oder beim Abschleppdienst, ist das für die Aufnahme kein Hindernis — wir kommen dorthin.` },
    { h3: 'Die Versicherung beruft sich auf einen Vorschaden — was bedeutet das für Ihren Anspruch?', text: `Zunächst einmal nicht, dass Sie leer ausgehen. Ein Vorschaden schließt den Anspruch nicht aus; er verlagert nur die Beweisfrage. Zu ersetzen ist der Schaden, der durch dieses Unfallereignis neu entstanden ist — der bereits vorhandene bleibt außen vor. Kritisch wird es in zwei Fällen: wenn sich alter und neuer Schaden im selben Bauteil überlagern, und wenn ein früherer Schaden gar nicht erst offengelegt wurde. Wer einen Vorschaden von sich aus benennt, steht regelmäßig besser da als jemand, bei dem er in der Fahrzeughistorie auftaucht, nachdem er im Gutachten unerwähnt blieb.` },
    { h3: 'Wie trennt ein Gutachten Alt- von Neuschaden?', text: `Über den Zustand des Materials, nicht über die Erinnerung der Beteiligten. Frische Verformungen zeigen blanke Bruch- und Risskanten, während ältere Beschädigungen Korrosionsansätze, Verschmutzung oder gealterte Lackkanten aufweisen. Hinzu kommen Hinweise auf frühere Instandsetzungen: abweichende Schichtdicken bei der Lackmessung, Spachtelaufträge, nachlackierte Anbauteile, Spaltmaße, die nicht zur Serie passen. Aus dieser Kombination lässt sich in vielen Fällen belastbar abgrenzen, welcher Anteil dem aktuellen Ereignis zuzuordnen ist — vorausgesetzt, das Fahrzeug wird vor Beginn der Reparatur untersucht.` },
    { h3: 'Der Vorschaden wurde damals nur notdürftig behoben — was folgt daraus?', text: `Dann sinkt in der Regel der Wiederbeschaffungswert, und der neue Schaden kann teurer in der Instandsetzung sein, weil zuerst die unsachgemäße Reparatur zurückgebaut werden muss. Beides gehört ins Gutachten, und zwar getrennt ausgewiesen — sonst entsteht der Eindruck, es werde eine Altlast auf Kosten der Gegenseite mitsaniert, und die gesamte Position gerät unter Druck. Sauber getrennt bleibt dagegen nachvollziehbar, was dem aktuellen Unfall zuzurechnen ist und was nicht.` },
    { h3: 'Abzug neu für alt: Wann darf die Versicherung überhaupt etwas abziehen?', text: `Nur dann, wenn Sie durch die Reparatur messbar besser dastehen als vorher. Der Gedanke dahinter ist, dass ein neues Teil an einem gebrauchten Fahrzeug einen Wertzuwachs bringen kann, den Sie nicht auf Kosten der Gegenseite behalten sollen. Praktisch betrifft das vor allem Verschleißteile mit begrenzter Lebensdauer — Reifen, Auspuffanlagen, Batterien, teils Lackflächen bei stark gealterter Substanz. Für tragende Karosserieteile gilt es gerade nicht, denn deren Erneuerung verlängert die Lebensdauer des Fahrzeugs nicht. Bei älteren Fahrzeugen wird dieser Abzug gern pauschal und zu großzügig angesetzt; er muss aber für jede Position einzeln begründet werden und darf keine verdeckte Kürzung sein.` },
    { h3: 'Der Wagen hat einige Jahre auf dem Buckel — lohnt sich das Gutachten dann noch?', text: `Gerade dann, und zwar aus einem Grund, der zunächst gegen ihn zu sprechen scheint. Bei älteren Fahrzeugen liegt der Wiederbeschaffungswert niedriger, die Grenze zum wirtschaftlichen Totalschaden ist also schneller erreicht — und genau an dieser Grenze entscheidet sich, ob Sie eine kleine Auszahlung erhalten oder eine Reparatur durchsetzen können. Diese Bewertung hängt an Details, die nur eine Besichtigung liefert: tatsächlicher Pflegezustand, Ausstattung, Historie, regionale Marktlage. Eine pauschale Tabellenbewertung fällt hier fast immer zu Ihren Ungunsten aus. Hinzu kommt: Das Sachverständigenhonorar zahlt bei unverschuldetem Unfall ohnehin die Gegenseite, Ihr Risiko ist also nicht der Preis, sondern die fehlende Bewertung.` },
    { h3: 'Ein Schaden zeigt sich erst Monate später — lässt sich das noch nachfordern?', text: `Grundsätzlich ja, denn Sie können nur das geltend machen, was Sie kennen — und ein verdeckter Schaden, der erst bei der Reparatur oder im Betrieb auftritt, war Ihnen vorher nicht zugänglich. Solange der Anspruch nicht verjährt ist und Sie keine abschließende Erklärung gegenüber der Versicherung abgegeben haben, ist eine Nachforderung möglich. Die Hürde liegt beim Zusammenhang: Sie müssen plausibel machen, dass der neue Befund auf dieses Unfallereignis zurückgeht und nicht auf Verschleiß oder ein späteres Ereignis. Das gelingt umso besser, je vollständiger der Ausgangszustand dokumentiert war — ein weiterer Grund, das Fahrzeug vollständig aufnehmen zu lassen und nicht nur die offensichtliche Beule.` },
    { h3: 'Was wird bei der Untersuchung aufgenommen?', text: `Der aktuelle Schaden ebenso wie alles, was auf frühere Eingriffe hindeutet — vollständig belegt und nach BVSK-Standard dokumentiert. Die Abwicklung begleitet das Claimondo-Partnernetzwerk:`, liste: LEISTUNGS_LISTE },
    { text: `Kfz-Sachverständiger Stolberg — unabhängig, schnell vor Ort und geübt darin, Alt- und Neuschaden sauber auseinanderzuhalten. Rufen Sie an oder schreiben Sie über WhatsApp, bevor am Fahrzeug gearbeitet wird.` },
  ],
  herzogenrath: [
    { text: `Herzogenrath zieht sich langgestreckt am Wurmtal entlang, unmittelbar an der Grenze zu Kerkrade — an der Neustraße verläuft sie mitten durch die Straße hindurch. Eine Autobahn führt durch das Stadtgebiet nicht; der Verkehr bewegt sich über Ortsdurchfahrten und die Verbindungen zwischen den drei getrennten Ortskernen. Weil hier viel im niedrigen Geschwindigkeitsbereich passiert und viele Fahrzeuge älter sind, ist der häufigste Konflikt nach dem Unfall nicht die Schuldfrage, sondern die Höhe: Die gegnerische Versicherung kürzt die Reparaturkosten und verweist auf eine günstigere Werkstatt. Markus ist meist binnen 60 Minuten in Herzogenrath-Mitte, Kohlscheid oder Merkstein — für Sie zu 0 € nach § 249 BGB.` },
    { vorort: true, text: `Die drei Ortskerne liegen räumlich deutlich getrennt: Kohlscheid im Süden, die Mitte um die Burg Rode und Merkstein im Norden, dazwischen das Wurmtal. Wer hier eine Werkstatt oder einen Sachverständigen sucht, hat es selten mit kurzen Wegen zu tun. Wir kommen deshalb in alle drei Ortslagen und nehmen das Fahrzeug dort auf, wo es nach dem Unfall steht — auf dem Stellplatz, im Hof oder am Straßenrand, auch wenn es nicht mehr fahrbereit ist.` },
    { h3: 'Die Versicherung verweist Sie auf eine günstigere Werkstatt — müssen Sie das hinnehmen?', text: `Nicht ohne Weiteres. Grundsätzlich dürfen Sie Ihre Werkstatt frei wählen und auf Basis des Gutachtens abrechnen. Ein Verweis auf einen billigeren Betrieb ist nur unter Voraussetzungen zulässig, die die Versicherung darlegen muss: Die benannte Werkstatt muss qualitativ gleichwertig arbeiten und für Sie ohne Weiteres erreichbar sein. Zusätzlich spielt eine Rolle, ob Ihr Fahrzeug jung ist oder durchgehend in einer Fachwerkstatt gewartet wurde — dann wiegt das Interesse an der markengebundenen Reparatur schwerer. Ein pauschales Verweisungsschreiben ohne diese Prüfung trägt die Kürzung nicht.` },
    { h3: 'Was ist dieser Prüfbericht, den die Versicherung mitschickt?', text: `Ein von der Gegenseite beauftragtes Papier, das Ihr Gutachten nachrechnet — meist ohne dass jemand das Fahrzeug je gesehen hat. Gekürzt wird darin typischerweise nach einem wiederkehrenden Muster: Verbringungskosten gestrichen, Ersatzteilaufschläge herausgerechnet, Lackierstufen reduziert, Instandsetzung statt Austausch angesetzt. Ein Prüfbericht ist keine Entscheidung und kein Gegengutachten, sondern eine Position. Sie lässt sich Punkt für Punkt beantworten — dafür muss allerdings jede Position im Ausgangsgutachten so hergeleitet sein, dass sie einzeln verteidigt werden kann.` },
    { h3: 'Stundenverrechnungssätze: Woher kommt die Differenz überhaupt?', text: `Aus zwei ganz unterschiedlichen Quellen. Im Gutachten stehen die Sätze, die eine geeignete Werkstatt in Ihrer Region tatsächlich verlangt. Die Kürzung stützt sich dagegen häufig auf regionale Durchschnittswerte oder auf Sätze einer Partnerwerkstatt der Versicherung, die über Rahmenverträge günstiger kalkuliert. Rechnen Sie konkret ab, zählt am Ende ohnehin die Werkstattrechnung. Rechnen Sie fiktiv ab, wird genau diese Differenz zum eigentlichen Streitwert — und dann entscheidet, wie sorgfältig die angesetzten Sätze belegt wurden.` },
    { h3: 'Die Werkstattrechnung fällt höher aus als kalkuliert — bleiben Sie darauf sitzen?', text: `In aller Regel nicht, denn das sogenannte Werkstattrisiko liegt beim Schädiger, nicht bei Ihnen. Sie sind weder Fachbetrieb noch in der Lage, während der Reparatur zu kontrollieren, ob jeder Arbeitsschritt erforderlich und jede Stunde angemessen war. Rechnet die Werkstatt unwirtschaftlich oder fallen unterwegs zusätzliche Arbeiten an, geht das grundsätzlich zulasten der Gegenseite — vorausgesetzt, Sie haben die Werkstatt sorgfältig ausgewählt und die Mehrkosten nicht selbst zu verantworten. Anders liegt es, wenn Sie fiktiv abrechnen: Dann gibt es keine Rechnung, und der Streit verlagert sich vollständig auf die Kalkulation. Bewahren Sie die Rechnung deshalb auf und geben Sie sie weiter.` },
    { h3: 'Mietwagen: Woran entzündet sich der Streit fast immer?', text: `An zwei Punkten, die beide vorhersehbar sind. Der erste ist die Fahrzeugklasse: Erstattet wird ein Wagen, der dem beschädigten entspricht — wer deutlich größer anmietet, bekommt die Differenz nicht. Der zweite ist die Eigenersparnis: Weil Sie während der Mietzeit Ihr eigenes Fahrzeug schonen, wird bei klassengleicher Anmietung ein Abzug vorgenommen. Wer eine Klasse niedriger mietet, umgeht diesen Abzug meist ganz. Hinzu kommt die Dauer, die sich an der im Gutachten ausgewiesenen Reparatur- beziehungsweise Wiederbeschaffungsdauer bemisst, nicht daran, wie lange Sie den Wagen tatsächlich stehen ließen. Bei geringer Fahrleistung ist Nutzungsausfall oft die bessere Wahl.` },
    { h3: 'Die Versicherung bietet einen Pauschalbetrag zur endgültigen Erledigung — annehmen?', text: `Nur mit klarem Blick auf das, was Sie damit aufgeben. Ein Abfindungsvergleich beendet die Sache vollständig: Gegen Zahlung des vereinbarten Betrags erklären Sie, dass keine weiteren Forderungen aus diesem Unfall bestehen — auch nicht für Schäden, die erst später sichtbar werden, und auch nicht für Positionen, an die im Moment der Unterschrift niemand gedacht hat. Das kann sinnvoll sein, wenn der Schaden vollständig erfasst ist und Sie den Vorgang abschließen möchten. Es ist riskant, solange kein Gutachten vorliegt, die Reparatur noch nicht abgeschlossen ist oder verdeckte Schäden im Raum stehen. Prüfen Sie ein solches Angebot deshalb nie ohne belastbare Zahlen.` },
    { h3: 'Was macht das Gutachten belastbar?', text: `Dass jede Position einzeln nachvollziehbar bleibt und nicht in einer Endsumme verschwindet. Dokumentiert nach BVSK-Standard, die weitere Abwicklung übernimmt das Claimondo-Partnernetzwerk:`, liste: LEISTUNGS_LISTE },
    { text: `Kfz-Gutachter Herzogenrath — unabhängig, schnell vor Ort und darauf ausgelegt, einer Kürzung standzuhalten. Haben Sie bereits ein Kürzungsschreiben erhalten, bringen Sie es zum Termin mit; wir gehen es gemeinsam durch.` },
  ],
}

export function seoBodyFor(slug: string): SeoAbsatz[] {
  return SEO_BODY[slug] ?? []
}

// Per-Stadt-metaHook (Lever 2): kurzer, unique lokaler Aufhaenger fuer die Meta-
// Description (seo.ts) statt des recycelten h1Sub -> killt near-duplicate-Snippets.
// Distilliert aus SEO_BODY, <=40 Z. Fehlt ein Slug -> Fallback auf city.h1Sub.
export const META_HOOKS: Record<string, string> = {
  aachen: 'Dreiländereck DE/NL/BE & Aachener Kreuz',
  dueren: 'Rur-Industriestadt an der A4',
  alsdorf: 'Ex-Bergbaustadt & A44-Logistikachse',
  wuerselen: 'A44/A4-Pendlerstadt im Aachener Norden',
  baesweiler: 'NL-Grenznähe & B57-Pendlerachse',
  eschweiler: 'Indetal-Hochwasser 2021 & A4',
  juelich: 'Forschungszentrum & A44/B56-Kreuz',
  stolberg: 'Vichtbach-Hochwasser & A4-Eifelrand',
  herzogenrath: 'Grenzstadt DE/NL & B57 Roermonder',
}
