-- Phase 2b Swap: v_faelle_mit_aktuellem_termin wird duenner Layer auf v_claim_base.
-- Harness-verifiziert (nonexempt_diffs=0 UND total_diffs=0 ueber 89 Claims, Shape 339=339)
-- -> byte-identischer No-op. Legacy-Aliase (schadens_*/unfall*) + NULL-Platzhalter im Layer.
-- Reversibel: alte Def via git/#3098 re-applien.
CREATE OR REPLACE VIEW public.v_faelle_mit_aktuellem_termin AS
  SELECT base.fall_id AS id, base.lead_id, base.kunde_id, base.fall_status AS status, base.betreuungspaket,
    base.hergang_kunde_text AS schadens_beschreibung, base.schadentag AS schadens_datum, base.entdeckt_am AS schadens_entdeckt_am,
    base.schadenort_adresse AS schadens_adresse, base.schadens_plz, base.schadens_ort, base.abtretung_pdf, base.vollmacht_pdf,
    base.abtretung_signiert_am, base.vollmacht_signiert_am, base.sv_id, base.sv_zugewiesen_am, base.gutachten_eingegangen_am,
    base.gutachten_betrag, base.kanzlei_uebergeben_am, base.anschlussschreiben_am, base.regulierung_betrag, base.regulierung_am,
    base.filmcheck_ok, base.filmcheck_am, base.filmcheck_notizen, base.notizen, base.created_at, base.fall_updated_at AS updated_at,
    base.schadens_fall_typ, base.kunden_konstellation, base.kennzeichen, base.fahrzeug_typ, base.fahrzeug_hersteller_raw AS fahrzeug_hersteller,
    base.fahrzeug_modell, base.fahrzeug_baujahr, base.gegner_name, base.gegner_versicherung, base.gegner_kennzeichen,
    base.gegner_bekannt, base.polizei_aktenzeichen, base.polizei_bericht_vorhanden, base.personenschaden_flag, base.mietwagen_flag,
    base.gewerbe_flag, base.halter_ungleich_fahrer_flag, NULL::text AS ust_id, base.leasinggeber_name, base.leasinggeber_informiert,
    NULL::text AS bank_name, base.prioritaet, base.onboarding_complete, base.dispatch_id, base.kundenbetreuer_id, base.konvertiert_am,
    base.lead_id AS konvertiert_von_lead, base.status_changed_at, base.regulierung_angekuendigt_am, NULL::timestamp with time zone AS zahlung_eingegangen_am,
    base.abgeschlossen_am, base.google_review_gesendet, base.vs_eskalationsstufe, base.fin_quelle, base.fin_extrahiert_am,
    base.vorschaden_geprueft, base.vorschaden_anzahl, base.vorschaden_letzter_datum, base.vorschaden_typ_a_ergebnis,
    base.vorschaden_typ_b_bericht, base.vorschaden_typ_b_pdf_url, base.cardentity_abfrage_am, base.schadens_hoehe_netto,
    base.nutzungsausfall_tagessatz, base.reparaturdauer_tage, base.gutachter_honorar, base.ocr_extrahiert_am, base.ocr_rohdaten,
    base.ki_kalkulation, base.ki_kalkulation_am, base.ki_geschaetzte_kosten_min, base.ki_geschaetzte_kosten_max,
    base.kanzlei_ansprechpartner_name, base.kanzlei_ansprechpartner_email, base.kanzlei_ansprechpartner_telefon,
    base.kanzlei_ansprechpartner_position, base.mandatsnummer, base.losfahren_erinnerung_gesendet, base.termin_erinnerung_5min_gesendet,
    base.geschaetzte_fahrzeit_min, base.geschaetzte_fahrdistanz_km, base.gcal_event_id, base.gutachten_vorhanden,
    base.gutachten_hochgeladen_am, base.gutachten_positionen, base.gutachten_nummer, base.reparaturkosten, base.wertminderung,
    base.nutzungsausfall_gesamt, base.regulierungsweise, base.gegner_versicherungsnummer, base.sa_unterschrieben,
    base.sa_unterschrieben_am, base.sa_pdf_url, base.sa_unterschrift_url, base.datenschutz_akzeptiert, base.datenschutz_akzeptiert_am,
    base.vollmacht_status, base.polizei_vor_ort, base.hergang_kunde_text AS unfallhergang, base.unfallmitteilung_status,
    base.schadenort_adresse AS unfallort, base.schadentag AS unfalldatum, base.interne_notizen, base.anschlussschreiben_url,
    base.anschlussschreiben_sendedatum, base.anschlussschreiben_unterschrift, base.anschlussschreiben_ocr_am,
    base.besichtigungsort_adresse, base.besichtigungsort_lat, base.besichtigungsort_lng, base.besichtigungsort_place_id,
    base.ist_aktiv, base.deaktiviert_am, base.deaktiviert_grund, base.deaktiviert_notiz, base.szenario, base.ruege_erhalten_am,
    base.ruege_grund, base.fahrzeug_farbe, base.erstzulassung::text AS erstzulassung, base.kilometerstand, NULL::text AS firma_name,
    base.marketing_quelle, base.marketing_provision, base.marketing_provision_status, NULL::numeric(10,2) AS gutachten_stundensatz, base.kanzlei_id,
    base.kanzlei_honorar, NULL::date AS zahlung_erwartet_am, NULL::numeric(10,2) AS zahlung_betrag, base.lead_preis_netto, base.lead_preis_typ,
    base.lead_preis_berechnet_am, base.guthaben_verrechnet_netto, base.sv_nachzahlung_netto, base.abrechnung_id, base.storniert_am,
    base.storno_grund, base.storno_durch_user_id, base.no_show_gemeldet_am, base.spezifikation, base.schadens_art,
    base.organisation_id, base.dokumente_vollstaendig_fuer_phase, base.dokumente_vollstaendig_am_phase, base.unfall_konstellation,
    base.gegner_anzahl_beteiligte, base.gegner_fahrzeugtyp, base.dokumente_reminder_whatsapp_letzte_sendung, base.fin_vin::text AS fin_vin,
    NULL::text AS source_channel, NULL::text AS source_domain, base.schadens_ursache, base.kanzlei_abrechnung_id, base.kanzlei_provision_status,
    base.kanzlei_provision_ausgezahlt_am, base.service_typ, base.vs_reaktion_typ, base.vs_reaktion_am, base.vs_ablehnungsgrund,
    base.ruege_gesendet_am, base.ruege_betrag, base.no_show_count, base.kuerzungs_betrag, base.vs_frist_bis, base.ruege_counter,
    base.schlussabrechnung_am, base.iban, base.bic, base.kontoinhaber, base.bankdaten_hinterlegt_am, base.ist_fahrzeughalter,
    base.finanzierung_leasing, base.vorsteuerabzugsberechtigt, base.hergang_kunde_text AS schadens_hergang, base.halter_vorname,
    base.halter_nachname, base.halter_strasse, base.halter_plz, base.halter_stadt, base.halter_telefon, base.halter_email,
    base.finanzierungsgeber_name, base.finanzierungsgeber_adresse, base.finanzierungsgeber_vertragsnr, base.zahlungsweg,
    base.hat_vorschaeden, base.vorschaeden_beschreibung, base.technische_stellungnahme_status, base.technische_stellungnahme_beauftragt_am,
    base.technische_stellungnahme_hochgeladen_am, base.technische_stellungnahme_freigabe_am, base.nachbesichtigung_status,
    base.nachbesichtigung_angefordert_am, base.nachbesichtigung_termin_datum, base.nachbesichtigung_konfrontation,
    base.as_geforderte_summe, base.as_frist, base.as_vs_reaktion_text, base.as_salesforce_id, base.as_zuletzt_synced_am,
    base.lexdrive_case_id, base.eskalation_tag_14_am, base.eskalation_tag_21_am, base.eskalation_tag_28_am,
    base.unfallort_kategorie, base.unfallskizze_url, base.fahrzeug_ausstattung, base.cardentity_enriched_at, base.cardentity_report,
    base.vollmacht_geprueft_am, base.vollmacht_geprueft_von, base.vollmacht_pruefung_status, base.vollmacht_pruefung_begruendung,
    base.lexdrive_ocr_data, base.lexdrive_ocr_received_at, base.vs_kuerzung_grund, base.geschlossen_grund, base.nachbesichtigung_ergebnis,
    base.bevorzugter_kanal, base.gegner_versicherung_id, base.zeugen_kontakte, base.werkstatt_seit_datum, base.fahrzeug_fahrbereit,
    base.nutzungsausfall, base.mietwagen_kanzlei_informiert, base.mietwagen_kanzlei_informiert_am, base.halter_geburtsdatum,
    base.abrechnungsart_besprochen, base.abrechnungsart_notiz, base.abrechnungsart_besprochen_am, NULL::date AS gegner_versicherung_anfrage_datum,
    base.sprache, base.unfallskizze_svg, base.unfallskizze_bestaetigt, base.unfallskizze_ablehnung_grund, base.unfallskizze_generiert_am,
    base.zeugen_vorhanden, base.vorschaden_erkannt, base.sv_termin_dokument_reminder_gesendet_am, base.kundenbetreuer_fallback_flag,
    base.kundenbetreuer_zugewiesen_am, base.sv_briefing_text, base.sv_briefing_generated_at, base.sv_briefing_model,
    base.sv_briefing_version, base.sv_briefing_struktur, base.sv_notizen_vor_ort, base.makler_id, base.sachschaden_flag,
    base.sachschaden_beschreibung, base.gegner_schadennummer, base.halter_name, base.wunschtermin, base.vs_quote_prozent,
    base.vs_quote_grund, base.vs_quote_akzeptiert_am, base.vs_quote_betrag_ausgezahlt, base.vs_kuerzungs_typ,
    NULL::numeric(10,2) AS auszahlung_kunde_betrag, NULL::timestamp with time zone AS auszahlung_kunde_eingegangen_am, base.auszahlung_gutachter_eingegangen_am,
    base.auszahlung_zahlungsweg, base.eskalation_tag_14_ergebnis, base.eskalation_tag_14_ergebnis_am, base.eskalation_tag_14_ergebnis_von,
    base.eskalation_tag_21_ergebnis, base.eskalation_tag_21_ergebnis_am, base.eskalation_tag_21_ergebnis_von,
    base.eskalation_tag_28_ergebnis, base.eskalation_tag_28_ergebnis_am, base.eskalation_tag_28_ergebnis_von,
    base.nachbesichtigung_kunde_termin_vorschlaege, base.nachbesichtigung_kunde_termin_eingereicht_am,
    base.nachbesichtigung_sv_konfrontation_gewuenscht, base.nachbesichtigung_sv_termin_vereinbart_am, base.auszahlung_gutachter_betrag,
    base.ruege_frist_tage, base.klage_uebergeben_am, base.fallakte_angelegt_am, base.kunde_vorname, base.kunde_nachname,
    base.kunde_telefon, base.kunde_email, base.kunde_strasse, base.kunde_plz, base.kunde_stadt, base.kunde_adresse, base.kunde_lat,
    base.kunde_lng, base.hsn::text AS hsn, base.tsn::text AS tsn, base.technische_stellungnahme_notiz_sv, base.fahrerflucht, base.auslandskennzeichen,
    base.polizeibericht_status, base.zb1_status, base.unfall_uhrzeit, base.unfallort_lat, base.unfallort_lng, base.bkat_unfallart,
    base.fahrzeugschaden_beschreibung, base.mietwagen_hat, base.mietwagen_seit_datum, base.mietwagen_limit_tage,
    base.mietwagen_limit_grund, base.mietwagen_rechnung_vorhanden, base.mietwagen_rechnung_url, base.mietwagen_argumentations_puffer,
    base.mietwagen_vermieter, base.vehicle_id, base.claim_id, base.lackfarbe_code, base.aktueller_termin_id, base.aktueller_termin_start,
    base.aktueller_termin_end, base.aktueller_termin_status, base.aktueller_termin_sv_id, base.aktueller_termin_kanal,
    base.aktueller_termin_typ, base.aktueller_termin_final_verbindlich_ab, base.sv_termin, base.gutachter_termin_status,
    base.gutachter_termin_bestaetigt, base.gutachter_gegenvorschlag_datum, base.gutachter_gegenvorschlag_grund, base.claim_nummer,
    base.main_phase, base.sub_phase
  FROM v_claim_base base;