-- v_claim_base: einziges Entity-Sourcing-SSoT (Phase 1, vcf-Umfang).
-- Minimaler Transform von v_claim_full: 6 JSONB-Aggregate entfernt (-> vcf-Layer),
-- Termin-LATERAL spd_termin auf get_aktueller_gt_termin_id repointed (Decision a).
-- Additiv (nichts liest v_claim_base) -> safe. Phase 2 erweitert die Base fuer vfmat.
create view v_claim_base as
 select c.id,
    c.vehicle_id,
    c.schadentag,
    c.schadenzeit,
    c.entdeckt_am,
    c.schadenort_adresse,
    c.schadenort_plz,
    c.schadenort_ort,
    c.schadenort_land,
    c.schadenort_lat,
    c.schadenort_lng,
    c.schadenort_kategorie,
    c.hergang_kunde_text,
    c.hergang_sv_text,
    c.schadenart,
    c.fall_typ,
    c.unfall_konstellation,
    c.fahrerflucht,
    c.auslandskennzeichen,
    c.polizei_aktenzeichen,
    c.polizei_bericht_vorhanden,
    c.polizei_vor_ort,
    c.polizeibericht_status,
    c.geschaedigter_user_id,
    c.gegnerisches_vehicle_id,
    c.gegner_versicherung_id,
    gp.versicherungsnummer as gegner_versicherungsnummer,
    gp.versicherungs_aktenzeichen as gegner_aktenzeichen,
    c.gegner_bekannt,
    c.anzahl_beteiligte_total,
    c.hat_personenschaden,
    c.hat_mietwagen,
    c.hat_nutzungsausfall,
    c.hat_sachschaden,
    c.hat_abschleppung,
    c.sachschaden_beschreibung,
    c.halter_ungleich_fahrer,
    c.kunden_konstellation,
    c.unfallskizze_url,
    c.unfallskizze_svg,
    c.unfallskizze_bestaetigt,
    c.unfallskizze_ablehnung_grund,
    c.unfallskizze_generiert_am,
    c.status,
    c.abgeschlossen_am,
    c.verjaehrt_am,
    c.created_at,
    c.updated_at,
    c.created_by_user_id,
    c.created_via,
    c.claim_nummer,
    c.lead_id,
    c.kundenbetreuer_id,
    c.vs_ablehnungs_grund,
    c.regulierungs_betrag,
    c.endzustand_gesetzt_durch_user_id,
    c.endzustand_gesetzt_am,
    c.endzustand_grund,
    c.kanzlei_wunsch,
    c.kanzlei_wunsch_gefragt_am,
    c.kanzlei_wunsch_gefragt_in_phase,
    fcb.fall_id,
    c.sv_id,
    c.service_typ,
    c.operative_status::fall_status as fall_status,
    fcb.fall_created_at,
    COALESCE(( SELECT cr.last_activity_at FROM claim_recency cr WHERE cr.claim_id = c.id), c.created_at) as fall_updated_at,
    c.kundenbetreuer_fallback_flag,
    c.szenario,
    c.dokumente_vollstaendig_fuer_phase,
    c.dokumente_reminder_whatsapp_letzte_sendung,
    spd_termin.no_show_gemeldet_am,
    spd_termin.re_termin_token,
    c.sa_unterschrieben_am,
    c.vollmacht_signiert_am,
    kf.mandatsnummer,
    spd_termin.re_termin_token_eingelaufen_am,
    spd_termin.re_termin_eskalation_an_kb_am,
    cur_auftrag.storniert_am,
    kf.anschlussschreiben_am,
    COALESCE(kf.vs_eskalationsstufe, 'vs-01'::text) as vs_eskalationsstufe,
    veh.kennzeichen_aktuell::text as kennzeichen,
    NULLIF(veh.hersteller, 'Unbekannt'::text) as fahrzeug_hersteller,
    veh.modell_haupttyp as fahrzeug_modell,
    veh.bauart as fahrzeug_typ,
    c.sa_unterschrieben,
    kf.regulierung_am,
    c.regulierungs_betrag as regulierung_betrag,
    g.gesamt_schadensbetrag::numeric(10,2) as gutachten_betrag,
    g.fertiggestellt_am as gutachten_eingegangen_am,
    c.sv_zugewiesen_am,
    c.schadens_ursache,
    c.schadenort_plz::text as schadens_plz,
    c.schadenort_ort as schadens_ort,
    c.fall_typ as schadens_fall_typ,
    c.anzahl_beteiligte_total - 1 as gegner_anzahl_beteiligte,
    COALESCE(gveh.bauart, gp.fahrzeugtyp_klartext) as gegner_fahrzeugtyp,
    NULL::uuid as organisation_id,
    NULL::uuid as dispatch_id,
    c.geschaedigter_user_id as kunde_id,
    c.ist_aktiv,
    c.deaktiviert_grund,
    c.hat_vorschaeden,
    vv.anzahl as vorschaden_anzahl,
    vv.letzter_datum as vorschaden_letzter_datum,
    veh.cardentity_report -> 'typB'::text as vorschaden_typ_b_bericht,
    veh.cardentity_letzter_pull as cardentity_abfrage_am,
    spd_termin.besichtigungsort_adresse,
    spd_termin.besichtigungsort_lat,
    spd_termin.besichtigungsort_lng,
    spd_termin.besichtigungsort_notiz,
    spd_termin.besichtigungsort_place_id,
    vcp.main_phase,
    vcp.sub_phase,
    halter_p.vorname as halter_vorname,
    halter_p.nachname as halter_nachname,
    halter_p.adresse_strasse as halter_strasse,
    halter_p.adresse_plz as halter_plz,
    halter_p.adresse_ort as halter_stadt,
    halter_p.telefon as halter_telefon,
    halter_p.email as halter_email,
    halter_p.geburtsdatum as halter_geburtsdatum,
    NULLIF(TRIM(BOTH FROM (COALESCE(halter_p.vorname, ''::text) || ' '::text) || COALESCE(halter_p.nachname, ''::text)), ''::text) as halter_name,
    COALESCE(gf.name, NULLIF(TRIM(BOTH FROM (COALESCE(gpp.vorname, ''::text) || ' '::text) || COALESCE(gpp.nachname, ''::text)), ''::text)) as gegner_name,
    gv.name as gegner_versicherung_name,
    COALESCE(gveh.kennzeichen_aktuell, gp.kennzeichen)::text as gegner_kennzeichen,
    veh.fin as fin_vin,
    veh.farbcode as lackfarbe_code,
    EXTRACT(year FROM veh.baujahr_monat)::integer as fahrzeug_baujahr,
    veh.farbe_klartext as fahrzeug_farbe,
    veh.fahrzeug_ausstattung,
    veh.hsn,
    veh.tsn,
    veh.aktueller_kilometerstand as kilometerstand,
    veh.erstzulassung,
    veh.kennzeichen_buchstaben,
    veh.fin_quelle,
    veh.fin_extrahiert_am,
    c.vorschaden_erkannt,
    c.notizen,
    c.zeugen_kontakte,
    kunde_p.email as kunde_email,
    c.vorsteuerabzugsberechtigt,
    kunde_p.vorname as kunde_vorname,
    kunde_p.nachname as kunde_nachname,
    kunde_p.telefon as kunde_telefon,
    kunde_p.strasse as kunde_strasse,
    kunde_p.plz as kunde_plz,
    kunde_p.ort as kunde_stadt,
    kunde_p.firma_name,
    kunde_p.ist_fahrzeughalter,
    c.fahrzeug_fahrbereit,
    c.fahrzeugschaden_beschreibung,
    veh.aufbau as fahrzeug_aufbau,
    COALESCE(gv.name, gp.versicherung_klartext) as gegner_versicherung,
    c.operative_status,
    c.spezifikation,
    c.zeugen_vorhanden,
    c.sprache
   from claims c
     left join faelle_claim_bridge fcb on fcb.claim_id = c.id
     left join lateral ( select pe.vorname, pe.nachname, pe.adresse_strasse, pe.adresse_plz, pe.adresse_ort, pe.telefon, pe.email, pe.geburtsdatum
           from claim_parties hp left join personen pe on pe.id = hp.person_id
          where hp.claim_id = c.id and hp.ist_halter = true
          order by hp.reihenfolge, hp.created_at limit 1) halter_p on true
     left join vehicles veh on veh.id = c.vehicle_id
     left join gutachten g on g.claim_id = c.id
     left join kanzlei_faelle kf on kf.claim_id = c.id
     left join lateral ( select a.storniert_am from auftraege a where a.claim_id = c.id order by a.reihenfolge desc limit 1) cur_auftrag on true
     left join lateral ( select gt.besichtigungsort_adresse, gt.besichtigungsort_lat, gt.besichtigungsort_lng, gt.besichtigungsort_notiz, gt.besichtigungsort_place_id, gt.no_show_gemeldet_am, gt.re_termin_token, gt.re_termin_token_eingelaufen_am, gt.re_termin_eskalation_an_kb_am
           from gutachter_termine gt where gt.id = get_aktueller_gt_termin_id(c.id)) spd_termin on true
     left join lateral ( select NULLIF(count(*), 0)::integer as anzahl, max(vv0.schaden_datum) as letzter_datum
           from vehicle_vorschaeden vv0 where vv0.vehicle_id = c.vehicle_id) vv on true
     left join v_claim_phase vcp on vcp.claim_id = c.id
     left join lateral ( select vp.firma_id, vp.versicherungsnummer, vp.versicherungs_aktenzeichen, vp.person_id, vp.vehicle_id, vp.fahrzeugtyp_klartext, vp.kennzeichen, vp.versicherung_klartext
           from claim_parties vp where vp.claim_id = c.id and vp.rolle = 'verursacher'::text
          order by vp.reihenfolge, vp.created_at limit 1) gp on true
     left join firmen gf on gf.id = gp.firma_id
     left join personen gpp on gpp.id = gp.person_id
     left join versicherungen gv on gv.id = c.gegner_versicherung_id
     left join vehicles gveh on gveh.id = gp.vehicle_id
     left join lateral ( select kpe.vorname, kpe.email, kpe.nachname, COALESCE(kpe.telefon, kpe.mobil) as telefon, kpe.adresse_strasse as strasse, kpe.adresse_plz as plz, kpe.adresse_ort as ort, COALESCE(kfi.name, kpe.firma) as firma_name, kcp.ist_halter as ist_fahrzeughalter
           from claim_parties kcp left join personen kpe on kpe.id = kcp.person_id left join firmen kfi on kfi.id = kcp.firma_id
          where kcp.claim_id = c.id and kcp.rolle = 'geschaedigter'::text
          order by kcp.reihenfolge, kcp.created_at limit 1) kunde_p on true;