-- KFZ-86: Gutachter Tasking System Spalten
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS gutachter_termin_bestaetigt BOOLEAN DEFAULT false;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS gutachter_gegenvorschlag_datum TIMESTAMPTZ;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS gutachter_gegenvorschlag_grund TEXT;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS besichtigung_datum TIMESTAMPTZ;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS gutachten_vorhanden BOOLEAN DEFAULT false;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS gutachten_hochgeladen_am TIMESTAMPTZ;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS gutachten_positionen JSONB;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS gutachten_nummer TEXT;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS reparaturkosten DECIMAL(10,2);
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS wertminderung DECIMAL(10,2);
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS nutzungsausfall_tage INTEGER;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS nutzungsausfall_pro_tag DECIMAL(10,2);
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS nutzungsausfall_gesamt DECIMAL(10,2);
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS totalschaden BOOLEAN DEFAULT false;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS wiederbeschaffungswert DECIMAL(10,2);
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS restwert DECIMAL(10,2);
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS regulierungsweise TEXT;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS versicherungsnummer_gegner TEXT;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS versicherung_gegner_name TEXT;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS schadennummer_versicherung TEXT;
