-- CMM-44 SP-C1 PR1 — Backfill kunde-Snapshot -> claim_parties (rolle=geschaedigter) + view repoint.
-- Reader/Writer-Switch base: NO ADD COLUMN (target cols + 45 geschaedigter rows exist; verified live 2026-05-21).
-- COALESCE: cp wins (SSoT party); faelle.kunde_* only fills cp NULL gaps. 1:1 per claim (max 1 verified).
-- No row-create (claims without geschaedigter -> skipped; 2 such claims). faelle.kunde_* stays until Phase 6.
--
-- View repoint: v_faelle_mit_aktuellem_termin exposed all 7 kunde-snapshot cols from f.; repointed to the
--   geschaedigter party via LEFT JOIN LATERAL ... LIMIT 1 (defensive: no UNIQUE constraint on
--   claim_parties(claim_id,rolle), so plain LEFT JOIN could fan out this heavily-consumed view).
--   adresse_plz cast ::text (cp.adresse_plz is varchar(10); view col kunde_plz is text -> avoid 42P16).
--   kunde_adresse (legacy combined field, cov 1) mapped to cp.adresse_strasse (matches reader-fallback rule).
-- v_claim_listing NOT touched: its kunde_vorname/nachname already read from profiles (claims.geschaedigter_user_id),
--   not faelle.kunde_* -> not stale-prone from SP-C1 writes.
-- Dry-run (ROLLBACK) verified: view_vorname_mismatch_vs_cp=0, view_rowcount=faelle_rowcount=46 (no fan-out).
BEGIN;

UPDATE public.claim_parties cp SET
  vorname         = COALESCE(cp.vorname, f.kunde_vorname),
  nachname        = COALESCE(cp.nachname, f.kunde_nachname),
  telefon         = COALESCE(cp.telefon, f.kunde_telefon),
  adresse_strasse = COALESCE(cp.adresse_strasse, f.kunde_strasse, f.kunde_adresse),
  adresse_plz     = COALESCE(cp.adresse_plz, f.kunde_plz),
  adresse_ort     = COALESCE(cp.adresse_ort, f.kunde_stadt)
FROM public.faelle f
WHERE cp.claim_id = f.claim_id AND cp.rolle = 'geschaedigter';

CREATE OR REPLACE VIEW public.v_faelle_mit_aktuellem_termin AS SELECT f.id,
    f.lead_id,
    f.kunde_id,
    f.status,
    c.betreuungspaket,
    c.hergang_kunde_text AS schadens_beschreibung,
    c.schadentag AS schadens_datum,
    c.entdeckt_am AS schadens_entdeckt_am,
    c.schadenort_adresse AS schadens_adresse,
    c.schadenort_plz::text AS schadens_plz,
    c.schadenort_ort AS schadens_ort,
    c.abtretung_pdf,
    c.vollmacht_pdf,
    c.abtretung_signiert_am,
    c.vollmacht_signiert_am,
    f.sv_id,
    c.sv_zugewiesen_am,
    g.fertiggestellt_am AS gutachten_eingegangen_am,
    g.gesamt_schadensbetrag::numeric(10,2) AS gutachten_betrag,
    c.kanzlei_uebergeben_am,
    f.anschlussschreiben_am,
    c.regulierungs_betrag AS regulierung_betrag,
    f.regulierung_am,
    cur_auftrag.filmcheck_ok,
    cur_auftrag.filmcheck_am,
    cur_auftrag.filmcheck_notizen,
    c.notizen,
    f.created_at,
    f.updated_at,
    c.fall_typ AS schadens_fall_typ,
    c.kunden_konstellation,
    f.kennzeichen,
    f.fahrzeug_typ,
    f.fahrzeug_hersteller,
    f.fahrzeug_modell,
    f.fahrzeug_baujahr,
    f.gegner_name,
    f.gegner_versicherung,
    f.gegner_kennzeichen,
    c.gegner_bekannt,
    c.polizei_aktenzeichen,
    c.polizei_bericht_vorhanden,
    c.hat_personenschaden AS personenschaden_flag,
    c.hat_mietwagen AS mietwagen_flag,
    c.gewerbe_flag,
    c.halter_ungleich_fahrer AS halter_ungleich_fahrer_flag,
    f.ust_id,
    f.leasinggeber_name,
    c.leasinggeber_informiert,
    f.bank_name,
    c.prioritaet,
    c.onboarding_complete,
    f.dispatch_id,
    c.kundenbetreuer_id,
    f.konvertiert_am,
    c.lead_id AS konvertiert_von_lead,
    c.status_changed_at,
    f.regulierung_angekuendigt_am,
    f.zahlung_eingegangen_am,
    c.abgeschlossen_am,
    c.google_review_gesendet,
    f.vs_eskalationsstufe,
    f.fin_quelle,
    f.fin_extrahiert_am,
    f.vorschaden_geprueft,
    f.vorschaden_anzahl,
    f.vorschaden_letzter_datum,
    f.vorschaden_typ_a_ergebnis,
    f.vorschaden_typ_b_bericht,
    f.vorschaden_typ_b_pdf_url,
    f.cardentity_abfrage_am,
    c.schadens_hoehe_netto,
    g.gutachten_nutzungsausfall_tagessatz_eur::numeric(10,2) AS nutzungsausfall_tagessatz,
    g.wiederbeschaffungsdauer_tage AS reparaturdauer_tage,
    g.gutachten_sv_honorar_netto AS gutachter_honorar,
    g.ocr_finished_at AS ocr_extrahiert_am,
    g.gutachten_ocr_raw AS ocr_rohdaten,
    g.ki_kalkulation,
    g.ki_kalkulation_am,
    g.ki_geschaetzte_kosten_min::numeric(10,2) AS ki_geschaetzte_kosten_min,
    g.ki_geschaetzte_kosten_max::numeric(10,2) AS ki_geschaetzte_kosten_max,
    c.kanzlei_ansprechpartner_name,
    c.kanzlei_ansprechpartner_email,
    c.kanzlei_ansprechpartner_telefon,
    c.kanzlei_ansprechpartner_position,
    f.mandatsnummer,
    t.losfahren_erinnerung_gesendet,
    t.termin_erinnerung_5min_gesendet,
    t.geschaetzte_fahrtzeit_min AS geschaetzte_fahrzeit_min,
    t.geschaetzte_fahrdistanz_km,
    t.google_event_id AS gcal_event_id,
    g.id IS NOT NULL AS gutachten_vorhanden,
    g.pdf_uploaded_at AS gutachten_hochgeladen_am,
    g.positionen AS gutachten_positionen,
    g.auftragsnummer AS gutachten_nummer,
    g.reparaturkosten_netto AS reparaturkosten,
    g.minderwert AS wertminderung,
    (g.gutachten_nutzungsausfall_tagessatz_eur * g.nutzungsausfall_tage::numeric)::numeric(10,2) AS nutzungsausfall_gesamt,
    f.regulierungsweise,
    c.gegner_versicherungsnummer,
    c.sa_unterschrieben,
    c.sa_unterschrieben_am,
    c.sa_pdf_url,
    c.sa_unterschrift_url,
    c.datenschutz_akzeptiert,
    c.datenschutz_akzeptiert_am,
    c.vollmacht_status,
    c.polizei_vor_ort,
    c.hergang_kunde_text AS unfallhergang,
    c.unfallmitteilung_status,
    c.schadenort_adresse AS unfallort,
    c.schadentag AS unfalldatum,
    c.interne_notizen,
    f.anschlussschreiben_url,
    f.anschlussschreiben_sendedatum,
    f.anschlussschreiben_unterschrift,
    f.anschlussschreiben_ocr_am,
    t.besichtigungsort_adresse,
    t.besichtigungsort_lat,
    t.besichtigungsort_lng,
    t.besichtigungsort_place_id,
    c.ist_aktiv,
    c.deaktiviert_am,
    c.deaktiviert_grund,
    c.deaktiviert_notiz,
    c.szenario,
    f.ruege_erhalten_am,
    f.ruege_grund,
    f.fahrzeug_farbe,
    f.erstzulassung,
    f.kilometerstand,
    f.firma_name,
    f.marketing_quelle,
    f.marketing_provision,
    f.marketing_provision_status,
    NULL::numeric(10,2) AS gutachten_stundensatz,
    f.kanzlei_id,
    f.kanzlei_honorar,
    f.zahlung_erwartet_am,
    f.zahlung_betrag,
    f.lead_preis_netto,
    f.lead_preis_typ,
    f.lead_preis_berechnet_am,
    f.guthaben_verrechnet_netto,
    f.sv_nachzahlung_netto,
    f.abrechnung_id,
    cur_auftrag.storniert_am,
    cur_auftrag.storno_grund,
    cur_auftrag.storno_durch_user_id,
    t.no_show_gemeldet_am,
    c.spezifikation,
    c.schadenart AS schadens_art,
    f.organisation_id,
    c.phase AS aktuelle_phase,
    c.dokumente_vollstaendig_fuer_phase,
    c.dokumente_vollstaendig_am_phase,
    c.unfall_konstellation,
    f.gegner_anzahl_beteiligte,
    f.gegner_fahrzeugtyp,
    c.dokumente_reminder_whatsapp_letzte_sendung,
    f.fin_vin,
    f.source_channel,
    f.source_domain,
    c.schadens_ursache,
    f.kanzlei_abrechnung_id,
    f.kanzlei_provision_status,
    f.kanzlei_provision_ausgezahlt_am,
    c.service_typ,
    f.vs_reaktion_typ,
    f.vs_reaktion_am,
    c.vs_ablehnungs_grund AS vs_ablehnungsgrund,
    f.ruege_gesendet_am,
    f.ruege_betrag,
    c.kunde_no_show_count AS no_show_count,
    f.kuerzungs_betrag,
    f.vs_frist_bis,
    f.ruege_counter,
    f.schlussabrechnung_am,
    f.iban,
    f.bic,
    f.kontoinhaber,
    f.bankdaten_hinterlegt_am,
    f.ist_fahrzeughalter,
    c.finanzierung_leasing,
    c.vorsteuerabzugsberechtigt,
    c.hergang_kunde_text AS schadens_hergang,
    f.halter_vorname,
    f.halter_nachname,
    f.halter_strasse,
    f.halter_plz,
    f.halter_stadt,
    f.halter_telefon,
    f.halter_email,
    c.finanzierungsgeber_name,
    c.finanzierungsgeber_adresse,
    c.finanzierungsgeber_vertragsnr,
    f.zahlungsweg,
    f.hat_vorschaeden,
    f.vorschaeden_beschreibung,
    cur_auftrag.technische_stellungnahme_status,
    cur_auftrag.technische_stellungnahme_beauftragt_am,
    cur_auftrag.technische_stellungnahme_hochgeladen_am,
    cur_auftrag.technische_stellungnahme_freigabe_am,
    t.nachbesichtigung_status,
    t.nachbesichtigung_angefordert_am,
    t.nachbesichtigung_termin_datum,
    t.nachbesichtigung_konfrontation,
    f.as_geforderte_summe,
    f.as_frist,
    f.as_vs_reaktion_text,
    f.as_salesforce_id,
    f.as_zuletzt_synced_am,
    f.lexdrive_case_id,
    f.eskalation_tag_14_am,
    f.eskalation_tag_21_am,
    f.eskalation_tag_28_am,
    c.schadenort_kategorie AS unfallort_kategorie,
    c.unfallskizze_url,
    f.fahrzeug_ausstattung,
    f.cardentity_enriched_at,
    f.cardentity_report,
    c.vollmacht_geprueft_am,
    c.vollmacht_geprueft_von,
    c.vollmacht_pruefung_status,
    c.vollmacht_pruefung_begruendung,
    f.lexdrive_ocr_data,
    f.lexdrive_ocr_received_at,
    f.vs_kuerzung_grund,
    c.geschlossen_grund,
    t.nachbesichtigung_ergebnis,
    c.bevorzugter_kanal,
    c.gegner_versicherung_id,
    c.zeugen_kontakte,
    c.werkstatt_seit_datum,
    c.fahrzeug_fahrbereit,
    c.hat_nutzungsausfall AS nutzungsausfall,
    f.mietwagen_kanzlei_informiert,
    f.mietwagen_kanzlei_informiert_am,
    f.halter_geburtsdatum,
    c.abrechnungsart_besprochen,
    c.abrechnungsart_notiz,
    c.abrechnungsart_besprochen_am,
    f.gegner_versicherung_anfrage_datum,
    c.sprache,
    c.unfallskizze_svg,
    c.unfallskizze_bestaetigt,
    c.unfallskizze_ablehnung_grund,
    c.unfallskizze_generiert_am,
    c.zeugen_vorhanden,
    f.vorschaden_erkannt,
    t.sv_termin_dokument_reminder_gesendet_am,
    c.kundenbetreuer_fallback_flag,
    c.kundenbetreuer_zugewiesen_am,
    cur_auftrag.sv_briefing_text,
    cur_auftrag.sv_briefing_generated_at,
    cur_auftrag.sv_briefing_model,
    cur_auftrag.sv_briefing_version,
    cur_auftrag.sv_briefing_struktur,
    cur_auftrag.sv_notizen_vor_ort,
    c.makler_id,
    c.hat_sachschaden AS sachschaden_flag,
    c.sachschaden_beschreibung,
    c.gegner_aktenzeichen AS gegner_schadennummer,
    f.halter_name,
    t.wunschtermin,
    f.vs_quote_prozent,
    f.vs_quote_grund,
    f.vs_quote_akzeptiert_am,
    f.vs_quote_betrag_ausgezahlt,
    f.vs_kuerzungs_typ,
    f.auszahlung_kunde_betrag,
    f.auszahlung_kunde_eingegangen_am,
    f.auszahlung_gutachter_eingegangen_am,
    f.auszahlung_zahlungsweg,
    f.eskalation_tag_14_ergebnis,
    f.eskalation_tag_14_ergebnis_am,
    f.eskalation_tag_14_ergebnis_von,
    f.eskalation_tag_21_ergebnis,
    f.eskalation_tag_21_ergebnis_am,
    f.eskalation_tag_21_ergebnis_von,
    f.eskalation_tag_28_ergebnis,
    f.eskalation_tag_28_ergebnis_am,
    f.eskalation_tag_28_ergebnis_von,
    t.nachbesichtigung_kunde_termin_vorschlaege,
    t.nachbesichtigung_kunde_termin_eingereicht_am,
    t.nachbesichtigung_sv_konfrontation_gewuenscht,
    t.nachbesichtigung_sv_termin_vereinbart_am,
    f.auszahlung_gutachter_betrag,
    f.ruege_frist_tage,
    f.klage_uebergeben_am,
    c.fallakte_angelegt_am,
    cp_g.vorname AS kunde_vorname,
    cp_g.nachname AS kunde_nachname,
    cp_g.telefon AS kunde_telefon,
    c.kunde_email,
    cp_g.adresse_strasse AS kunde_strasse,
    cp_g.adresse_plz::text AS kunde_plz,
    cp_g.adresse_ort AS kunde_stadt,
    cp_g.adresse_strasse AS kunde_adresse,
    f.kunde_lat,
    f.kunde_lng,
    f.hsn,
    f.tsn,
    cur_auftrag.technische_stellungnahme_notiz_sv,
    c.fahrerflucht,
    c.auslandskennzeichen,
    c.polizeibericht_status,
    c.zb1_status,
    c.schadenzeit::text AS unfall_uhrzeit,
    c.schadenort_lat::numeric AS unfallort_lat,
    c.schadenort_lng::numeric AS unfallort_lng,
    c.bkat_unfallart,
    c.fahrzeugschaden_beschreibung,
    c.hat_mietwagen AS mietwagen_hat,
    c.mietwagen_seit_datum,
    c.mietwagen_limit_tage,
    c.mietwagen_limit_grund,
    c.mietwagen_rechnung_vorhanden,
    c.mietwagen_rechnung_url,
    c.mietwagen_argumentations_puffer,
    c.mietwagen_vermieter,
    c.vehicle_id,
    f.claim_id,
    f.lackfarbe_code,
    t.id AS aktueller_termin_id,
    t.start_zeit AS aktueller_termin_start,
    t.end_zeit AS aktueller_termin_end,
    t.status AS aktueller_termin_status,
    t.sv_id AS aktueller_termin_sv_id,
    t.kanal AS aktueller_termin_kanal,
    t.typ AS aktueller_termin_typ,
    t.final_verbindlich_ab AS aktueller_termin_final_verbindlich_ab,
    t.start_zeit AS sv_termin,
    t.status AS gutachter_termin_status,
    t.status = 'bestaetigt'::text AS gutachter_termin_bestaetigt,
    t.vorgeschlagenes_datum AS gutachter_gegenvorschlag_datum,
    t.gegenvorschlag_grund AS gutachter_gegenvorschlag_grund,
    c.claim_nummer
   FROM faelle f
     LEFT JOIN claims c ON c.id = f.claim_id
     LEFT JOIN gutachten g ON g.claim_id = c.id
     LEFT JOIN LATERAL ( SELECT gt.id,
            gt.sv_id,
            gt.fall_id,
            gt.start_zeit,
            gt.end_zeit,
            gt.status,
            gt.externer_kalender_id,
            gt.ablehnungsgrund,
            gt.gegenvorschlag_zeit,
            gt.created_at,
            gt.erinnerung_24h_gesendet,
            gt.erinnerung_2h_gesendet,
            gt.erinnerung_48h_docs_gesendet,
            gt.ankunft_zeit,
            gt.abschluss_zeit,
            gt.uebersprungen,
            gt.uebersprung_grund,
            gt.notizen_vor_ort,
            gt.gps_lat_ankunft,
            gt.gps_lng_ankunft,
            gt.lead_id,
            gt.ablehnen_token,
            gt.abgelehnt_am,
            gt.abgelehnt_grund,
            gt.vorgeschlagenes_datum,
            gt.gegenvorschlag_grund,
            gt.gegenvorschlag_von,
            gt.ankunft_via,
            gt.verspaetung_minuten,
            gt.losgefahren_am,
            gt.kunden_tracking_token,
            gt.notification_losgefahren_gesendet_am,
            gt.notification_5min_gesendet_am,
            gt.notification_angekommen_gesendet_am,
            gt.ablehnen_token_expires_at,
            gt.final_verbindlich_ab,
            gt.sv_ablehnung_grund,
            gt.sv_ablehnung_am,
            gt.sv_vorgeschlagene_slots,
            gt.typ,
            gt.kanal,
            gt.video_link,
            gt.kb_id,
            gt.notiz_kunde,
            gt.notiz_intern,
            gt.reminder_sent_at,
            gt.reminder_1h_sent_at,
            gt.cancelled_at,
            gt.navigation_started_at,
            gt.sv_unterwegs_seit,
            gt.sv_eta_minuten,
            gt.sv_eta_letzte_berechnung,
            gt.sv_angekommen_am,
            gt.reminder_15min_sent_at,
            gt.reminder_5min_sent_at,
            gt.durchgefuehrt_am,
            gt.kunde_tracking_aktiviert,
            gt.kunde_losgefahren_am,
            gt.kunde_eta_minuten,
            gt.kunde_eta_letzte_berechnung,
            gt.kunde_angekommen_am,
            gt.kunde_verspaetung_gemeldet_am,
            gt.bezahlt,
            gt.honorar_betrag,
            gt.google_event_id,
            gt.google_calendar_id,
            gt.google_event_synced_at,
            gt.kunde_response_token,
            gt.kunde_response_token_expires_at,
            gt.gesehen_am,
            gt.geschaetzte_fahrtzeit_min,
            gt.auftrag_id,
            gt.verlegung_quelle_id,
            gt.verlegung_grund,
            gt.verlegung_kunde_benachrichtigt_an,
            gt.verlegung_eskalation_an_kb_an,
            gt.verlegung_initiator_kunde,
            gt.besichtigung_gestartet_am,
            gt.caldav_object_url,
            gt.caldav_event_uid,
            gt.caldav_synced_at,
            gt.erinnerung_morgen_gesendet,
            gt.sv_lead_id,
            gt.besichtigungsort_adresse,
            gt.besichtigungsort_lat,
            gt.besichtigungsort_lng,
            gt.besichtigungsort_place_id,
            gt.geschaetzte_fahrdistanz_km,
            gt.termin_erinnerung_5min_gesendet,
            gt.sv_termin_dokument_reminder_gesendet_am,
            gt.losfahren_erinnerung_gesendet,
            gt.wunschtermin,
            gt.no_show_gemeldet_am,
            gt.nachbesichtigung_status,
            gt.nachbesichtigung_angefordert_am,
            gt.nachbesichtigung_termin_datum,
            gt.nachbesichtigung_konfrontation,
            gt.nachbesichtigung_ergebnis,
            gt.nachbesichtigung_kunde_termin_vorschlaege,
            gt.nachbesichtigung_kunde_termin_eingereicht_am,
            gt.nachbesichtigung_sv_konfrontation_gewuenscht,
            gt.nachbesichtigung_sv_termin_vereinbart_am
           FROM gutachter_termine gt
          WHERE gt.claim_id = c.id AND (gt.status = ANY (ARRAY['bestaetigt'::text, 'verlegung_pending'::text, 'reserviert'::text, 'durchgefuehrt'::text, 'gegenvorschlag'::text]))
          ORDER BY (
                CASE gt.status
                    WHEN 'bestaetigt'::text THEN 1
                    WHEN 'verlegung_pending'::text THEN 2
                    WHEN 'gegenvorschlag'::text THEN 3
                    WHEN 'reserviert'::text THEN 4
                    WHEN 'durchgefuehrt'::text THEN 5
                    ELSE 6
                END), gt.start_zeit DESC NULLS LAST
         LIMIT 1) t ON true
     LEFT JOIN LATERAL ( SELECT a.filmcheck_ok,
            a.filmcheck_am,
            a.filmcheck_notizen,
            a.storniert_am,
            a.storno_grund,
            a.storno_durch_user_id,
            a.sv_briefing_text,
            a.sv_briefing_generated_at,
            a.sv_briefing_model,
            a.sv_briefing_version,
            a.sv_briefing_struktur,
            a.sv_notizen_vor_ort,
            a.technische_stellungnahme_status,
            a.technische_stellungnahme_notiz_sv,
            a.technische_stellungnahme_beauftragt_am,
            a.technische_stellungnahme_hochgeladen_am,
            a.technische_stellungnahme_freigabe_am
           FROM auftraege a
          WHERE a.claim_id = c.id
          ORDER BY a.reihenfolge DESC
         LIMIT 1) cur_auftrag ON true
     LEFT JOIN LATERAL ( SELECT cp.vorname,
            cp.nachname,
            cp.telefon,
            cp.adresse_strasse,
            cp.adresse_plz,
            cp.adresse_ort
           FROM claim_parties cp
          WHERE cp.claim_id = c.id AND cp.rolle = 'geschaedigter'
          ORDER BY cp.created_at NULLS LAST, cp.id
         LIMIT 1) cp_g ON true;

COMMIT;
