-- Phase 1 Swap: v_claim_full wird duenner Layer auf v_claim_base.
-- Harness-verifiziert (nonexempt_diffs=0 ueber 89 Claims, Shape 165=165); 1 exempt-Delta
-- (CLM-2026-00115 re_termin_token) = approvte Decision-a-Haertung (aktiver Termin statt
-- "neuester per start_zeit"). Reversibel: alte Def via git / #3098-Stand re-applien.
create or replace view v_claim_full as
  select base.id, base.vehicle_id, base.schadentag, base.schadenzeit, base.entdeckt_am,
    base.schadenort_adresse, base.schadenort_plz, base.schadenort_ort, base.schadenort_land,
    base.schadenort_lat, base.schadenort_lng, base.schadenort_kategorie, base.hergang_kunde_text,
    base.hergang_sv_text, base.schadenart, base.fall_typ, base.unfall_konstellation, base.fahrerflucht,
    base.auslandskennzeichen, base.polizei_aktenzeichen, base.polizei_bericht_vorhanden, base.polizei_vor_ort,
    base.polizeibericht_status, base.geschaedigter_user_id, base.gegnerisches_vehicle_id, base.gegner_versicherung_id,
    base.gegner_versicherungsnummer, base.gegner_aktenzeichen, base.gegner_bekannt, base.anzahl_beteiligte_total,
    base.hat_personenschaden, base.hat_mietwagen, base.hat_nutzungsausfall, base.hat_sachschaden, base.hat_abschleppung,
    base.sachschaden_beschreibung, base.halter_ungleich_fahrer, base.kunden_konstellation, base.unfallskizze_url,
    base.unfallskizze_svg, base.unfallskizze_bestaetigt, base.unfallskizze_ablehnung_grund, base.unfallskizze_generiert_am,
    base.status, base.abgeschlossen_am, base.verjaehrt_am, base.created_at, base.updated_at, base.created_by_user_id,
    base.created_via, base.claim_nummer, base.lead_id, base.kundenbetreuer_id, base.vs_ablehnungs_grund,
    base.regulierungs_betrag, base.endzustand_gesetzt_durch_user_id, base.endzustand_gesetzt_am, base.endzustand_grund,
    base.kanzlei_wunsch, base.kanzlei_wunsch_gefragt_am, base.kanzlei_wunsch_gefragt_in_phase, base.fall_id, base.sv_id,
    base.service_typ, base.fall_status, base.fall_created_at, base.fall_updated_at, base.kundenbetreuer_fallback_flag,
    base.szenario, base.dokumente_vollstaendig_fuer_phase, base.dokumente_reminder_whatsapp_letzte_sendung,
    base.no_show_gemeldet_am, base.re_termin_token, base.sa_unterschrieben_am, base.vollmacht_signiert_am,
    base.mandatsnummer, base.re_termin_token_eingelaufen_am, base.re_termin_eskalation_an_kb_am, base.storniert_am,
    base.anschlussschreiben_am, base.vs_eskalationsstufe, base.kennzeichen, base.fahrzeug_hersteller, base.fahrzeug_modell,
    base.fahrzeug_typ, base.sa_unterschrieben, base.regulierung_am, base.regulierung_betrag, base.gutachten_betrag,
    base.gutachten_eingegangen_am, base.sv_zugewiesen_am, base.schadens_ursache, base.schadens_plz, base.schadens_ort,
    base.schadens_fall_typ, base.gegner_anzahl_beteiligte, base.gegner_fahrzeugtyp, base.organisation_id, base.dispatch_id,
    base.kunde_id, base.ist_aktiv, base.deaktiviert_grund, base.hat_vorschaeden, base.vorschaden_anzahl,
    base.vorschaden_letzter_datum, base.vorschaden_typ_b_bericht, base.cardentity_abfrage_am, base.besichtigungsort_adresse,
    base.besichtigungsort_lat, base.besichtigungsort_lng, base.besichtigungsort_notiz, base.besichtigungsort_place_id,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cp.*) || jsonb_build_object('vorname', p.vorname, 'nachname', p.nachname, 'adresse_strasse', p.adresse_strasse, 'adresse_plz', p.adresse_plz, 'adresse_ort', p.adresse_ort, 'telefon', p.telefon, 'email', p.email, 'geburtsdatum', p.geburtsdatum, 'person', to_jsonb(p.*)) ORDER BY cp.reihenfolge, cp.created_at) FROM claim_parties cp LEFT JOIN personen p ON p.id = cp.person_id WHERE cp.claim_id = base.id), '[]'::jsonb) AS parties,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cvi.*) ORDER BY cvi.reihenfolge, cvi.created_at) FROM claim_vehicle_involvements cvi WHERE cvi.claim_id = base.id), '[]'::jsonb) AS vehicle_involvements,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cp2.*) ORDER BY cp2.created_at) FROM claim_payments cp2 WHERE cp2.claim_id = base.id), '[]'::jsonb) AS payments,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cm.*) ORDER BY cm.created_at) FROM claim_mietwagen cm WHERE cm.claim_id = base.id), '[]'::jsonb) AS mietwagen,
    COALESCE(( SELECT jsonb_agg(to_jsonb(vk.*) ORDER BY vk.datum) FROM vs_korrespondenz vk WHERE vk.claim_id = base.id), '[]'::jsonb) AS vs_korrespondenz,
    COALESCE(( SELECT jsonb_agg(to_jsonb(r.*) ORDER BY r.created_at) FROM repairs r WHERE r.claim_id = base.id), '[]'::jsonb) AS repairs,
    base.main_phase, base.sub_phase, base.halter_vorname, base.halter_nachname, base.halter_strasse, base.halter_plz,
    base.halter_stadt, base.halter_telefon, base.halter_email, base.halter_geburtsdatum, base.halter_name, base.gegner_name,
    base.gegner_versicherung_name, base.gegner_kennzeichen, base.fin_vin, base.lackfarbe_code, base.fahrzeug_baujahr,
    base.fahrzeug_farbe, base.fahrzeug_ausstattung, base.hsn, base.tsn, base.kilometerstand, base.erstzulassung,
    base.kennzeichen_buchstaben, base.fin_quelle, base.fin_extrahiert_am, base.vorschaden_erkannt, base.notizen,
    base.zeugen_kontakte, base.kunde_email, base.vorsteuerabzugsberechtigt, base.kunde_vorname, base.kunde_nachname,
    base.kunde_telefon, base.kunde_strasse, base.kunde_plz, base.kunde_stadt, base.firma_name, base.ist_fahrzeughalter,
    base.fahrzeug_fahrbereit, base.fahrzeugschaden_beschreibung, base.fahrzeug_aufbau, base.gegner_versicherung,
    base.operative_status, base.spezifikation, base.zeugen_vorhanden, base.sprache
  from v_claim_base base;