-- CMM-44 SP-G PR1 — additive Migration (kein DROP)
--
-- Block 1: 5x ADD COLUMN auf gutachten (4 ki_* + positionen)
-- Block 2: UPSERT-Backfill der 16 MOVE-Spalten faelle -> gutachten via
--          ON CONFLICT (claim_id) DO UPDATE SET COALESCE(...).
--          Bestehende gutachten-Werte gewinnen — faelle füllt nur NULL-Slots.
-- Block 3: View-Repoint — konditional, ergänzt vor Apply falls View-Audit
--          Treffer fand (Output-Spalten-Namen unverändert für Backward-Compat).
--
-- Trigger-Behandlung (siehe docs/20.05.2026/cmm44-spg-views-audit.md
-- Trigger-Audit): trg_gutachten_benachrichtigung im Backfill-Block ggf.
-- DISABLE/ENABLE wrappen, falls Body Notifications/Emails feuert.
-- set_gutachten_updated_at + trg_fn_refresh_claim_phase_from_gutachten bleiben
-- aktiv (gewünschte Side-Effects: updated_at + claims.phase synchron).
--
-- Nach Apply: npx supabase migration repair --status applied 20260520095539
-- Ticket: CMM-44 / Sub-Projekt SP-G

BEGIN;

-- ============================================================
-- Block 1: ADD COLUMN — 5 neue Spalten auf public.gutachten
-- ============================================================
ALTER TABLE public.gutachten
  ADD COLUMN ki_kalkulation jsonb,
  ADD COLUMN ki_kalkulation_am timestamptz,
  ADD COLUMN ki_geschaetzte_kosten_min numeric,
  ADD COLUMN ki_geschaetzte_kosten_max numeric,
  ADD COLUMN positionen jsonb;

-- ============================================================
-- Block 2: Initial-Backfill — gutachten <- faelle via UPSERT
-- COALESCE-Pattern: bestehende gutachten-Werte gewinnen, faelle füllt Lücken.
-- ============================================================

-- Hinweis: gutachten.sv_id ist NOT NULL und hat keinen Default. Der Backfill
-- übernimmt sv_id direkt aus faelle (CMM-60 hält faelle.sv_id <-> claims.sv_id
-- via Sync-Trigger konsistent). Zeilen ohne sv_id werden geskippt — ein Gutachten
-- ohne zugewiesenen SV macht semantisch keinen Sinn.

INSERT INTO public.gutachten (
  claim_id,
  sv_id,
  fertiggestellt_am,
  gesamt_schadensbetrag,
  gutachten_sv_honorar_netto,
  ocr_finished_at,
  gutachten_ocr_raw,
  pdf_uploaded_at,
  auftragsnummer,
  reparaturkosten_netto,
  minderwert,
  gutachten_nutzungsausfall_tagessatz_eur,
  wiederbeschaffungsdauer_tage,
  ki_kalkulation,
  ki_kalkulation_am,
  ki_geschaetzte_kosten_min,
  ki_geschaetzte_kosten_max,
  positionen
)
SELECT
  claim_id,
  sv_id,
  gutachten_eingegangen_am,
  gutachten_betrag,
  gutachter_honorar,
  ocr_extrahiert_am,
  ocr_rohdaten,
  gutachten_hochgeladen_am,
  gutachten_nummer,
  reparaturkosten,
  wertminderung,
  nutzungsausfall_tagessatz,
  reparaturdauer_tage,
  ki_kalkulation,
  ki_kalkulation_am,
  ki_geschaetzte_kosten_min,
  ki_geschaetzte_kosten_max,
  gutachten_positionen
FROM public.faelle
WHERE claim_id IS NOT NULL
  AND sv_id IS NOT NULL
  AND (
       gutachten_eingegangen_am IS NOT NULL
    OR gutachten_betrag IS NOT NULL
    OR gutachter_honorar IS NOT NULL
    OR ocr_extrahiert_am IS NOT NULL
    OR ocr_rohdaten IS NOT NULL
    OR gutachten_hochgeladen_am IS NOT NULL
    OR gutachten_nummer IS NOT NULL
    OR reparaturkosten IS NOT NULL
    OR wertminderung IS NOT NULL
    OR nutzungsausfall_tagessatz IS NOT NULL
    OR reparaturdauer_tage IS NOT NULL
    OR ki_kalkulation IS NOT NULL
    OR ki_kalkulation_am IS NOT NULL
    OR ki_geschaetzte_kosten_min IS NOT NULL
    OR ki_geschaetzte_kosten_max IS NOT NULL
    OR gutachten_positionen IS NOT NULL
  )
ON CONFLICT (claim_id) DO UPDATE SET
  fertiggestellt_am                       = COALESCE(public.gutachten.fertiggestellt_am, EXCLUDED.fertiggestellt_am),
  gesamt_schadensbetrag                   = COALESCE(public.gutachten.gesamt_schadensbetrag, EXCLUDED.gesamt_schadensbetrag),
  gutachten_sv_honorar_netto              = COALESCE(public.gutachten.gutachten_sv_honorar_netto, EXCLUDED.gutachten_sv_honorar_netto),
  ocr_finished_at                         = COALESCE(public.gutachten.ocr_finished_at, EXCLUDED.ocr_finished_at),
  gutachten_ocr_raw                       = COALESCE(public.gutachten.gutachten_ocr_raw, EXCLUDED.gutachten_ocr_raw),
  pdf_uploaded_at                         = COALESCE(public.gutachten.pdf_uploaded_at, EXCLUDED.pdf_uploaded_at),
  auftragsnummer                          = COALESCE(public.gutachten.auftragsnummer, EXCLUDED.auftragsnummer),
  reparaturkosten_netto                   = COALESCE(public.gutachten.reparaturkosten_netto, EXCLUDED.reparaturkosten_netto),
  minderwert                              = COALESCE(public.gutachten.minderwert, EXCLUDED.minderwert),
  gutachten_nutzungsausfall_tagessatz_eur = COALESCE(public.gutachten.gutachten_nutzungsausfall_tagessatz_eur, EXCLUDED.gutachten_nutzungsausfall_tagessatz_eur),
  wiederbeschaffungsdauer_tage            = COALESCE(public.gutachten.wiederbeschaffungsdauer_tage, EXCLUDED.wiederbeschaffungsdauer_tage),
  ki_kalkulation                          = COALESCE(public.gutachten.ki_kalkulation, EXCLUDED.ki_kalkulation),
  ki_kalkulation_am                       = COALESCE(public.gutachten.ki_kalkulation_am, EXCLUDED.ki_kalkulation_am),
  ki_geschaetzte_kosten_min               = COALESCE(public.gutachten.ki_geschaetzte_kosten_min, EXCLUDED.ki_geschaetzte_kosten_min),
  ki_geschaetzte_kosten_max               = COALESCE(public.gutachten.ki_geschaetzte_kosten_max, EXCLUDED.ki_geschaetzte_kosten_max),
  positionen                              = COALESCE(public.gutachten.positionen, EXCLUDED.positionen);

-- ============================================================
-- Block 3: View-Repoint — alle 3 Views auf gutachten.<col>
-- Output-Spalten-Namen + Typen UNVERÄNDERT (Backward-Compat via AS-Aliase + Precision-Casts).
-- Generiert via Python aus pg_get_viewdef + Replace-Map.
-- ============================================================

-- ---- faelle_sv_view ----
CREATE OR REPLACE VIEW public.faelle_sv_view AS
SELECT f.id,
    f.status,
    c.phase AS aktuelle_phase,
    c.hergang_kunde_text AS schadens_beschreibung,
    c.schadentag AS schadens_datum,
    c.schadenort_adresse AS schadens_adresse,
    c.schadenort_plz::text AS schadens_plz,
    c.schadenort_ort AS schadens_ort,
    f.kennzeichen,
    f.fahrzeug_hersteller,
    f.fahrzeug_modell,
    f.fahrzeug_baujahr,
    g.gutachten_sv_honorar_netto AS gutachter_honorar,
    f.auszahlung_gutachter_eingegangen_am,
    f.eskalation_tag_14_ergebnis,
    f.eskalation_tag_14_ergebnis_am,
    f.eskalation_tag_21_ergebnis,
    f.eskalation_tag_21_ergebnis_am,
    f.eskalation_tag_28_ergebnis,
    f.eskalation_tag_28_ergebnis_am,
    f.technische_stellungnahme_status,
    f.technische_stellungnahme_beauftragt_am,
    f.technische_stellungnahme_hochgeladen_am,
    f.technische_stellungnahme_freigabe_am,
    f.vs_kuerzung_grund,
    f.vs_kuerzungs_typ,
    f.kuerzungs_betrag,
    f.nachbesichtigung_status,
    f.nachbesichtigung_termin_datum,
    f.nachbesichtigung_sv_konfrontation_gewuenscht,
    f.nachbesichtigung_sv_termin_vereinbart_am,
    f.vs_reaktion_typ,
    f.vs_reaktion_am,
    f.besichtigungsort_adresse,
    f.sv_id,
    f.kunde_id,
    c.claim_nummer
   FROM faelle f
     LEFT JOIN claims c ON c.id = f.claim_id
     LEFT JOIN public.gutachten g ON g.claim_id = c.id;

-- ---- v_claim_full ----
CREATE OR REPLACE VIEW public.v_claim_full AS
SELECT c.id,
    c.vehicle_id,
    c.schadentag,
    c.schadenzeit,
    c.entdeckt_am,
    c.schadenort_adresse,
    c.schadenort_plz,
    c.schadenort_ort,
    c.schadenort_land,
    c.schadenort_lat,
    c.schadenort_lng,
    c.schadenort_kategorie,
    c.hergang_kunde_text,
    c.hergang_sv_text,
    c.schadenart,
    c.fall_typ,
    c.unfall_konstellation,
    c.fahrerflucht,
    c.auslandskennzeichen,
    c.polizei_aktenzeichen,
    c.polizei_bericht_vorhanden,
    c.polizei_vor_ort,
    c.polizeibericht_status,
    c.geschaedigter_user_id,
    c.gegnerisches_vehicle_id,
    c.gegner_versicherung_id,
    c.gegner_versicherungsnummer,
    c.gegner_aktenzeichen,
    c.gegner_bekannt,
    c.anzahl_beteiligte_total,
    c.hat_personenschaden,
    c.hat_mietwagen,
    c.hat_nutzungsausfall,
    c.hat_sachschaden,
    c.hat_abschleppung,
    c.sachschaden_beschreibung,
    c.halter_ungleich_fahrer,
    c.kunden_konstellation,
    c.unfallskizze_url,
    c.unfallskizze_svg,
    c.unfallskizze_bestaetigt,
    c.unfallskizze_ablehnung_grund,
    c.unfallskizze_generiert_am,
    c.status,
    c.abgeschlossen_am,
    c.verjaehrt_am,
    c.created_at,
    c.updated_at,
    c.created_by_user_id,
    c.created_via,
    c.claim_nummer,
    c.lead_id,
    c.kundenbetreuer_id,
    c.phase,
    c.vs_ablehnungs_grund,
    c.regulierungs_betrag,
    c.endzustand_gesetzt_durch_user_id,
    c.endzustand_gesetzt_am,
    c.endzustand_grund,
    c.kanzlei_wunsch,
    c.kanzlei_wunsch_gefragt_am,
    c.kanzlei_wunsch_gefragt_in_phase,
    f.id AS fall_id,
    f.sv_id,
    c.service_typ,
    f.status AS fall_status,
    f.created_at AS fall_created_at,
    f.updated_at AS fall_updated_at,
    c.kundenbetreuer_fallback_flag,
    c.phase AS aktuelle_phase,
    c.szenario,
    c.dokumente_vollstaendig_fuer_phase,
    c.dokumente_reminder_whatsapp_letzte_sendung,
    f.no_show_gemeldet_am,
    f.re_termin_token,
    c.sa_unterschrieben_am,
    c.vollmacht_signiert_am,
    f.mandatsnummer,
    f.re_termin_token_eingelaufen_am,
    f.re_termin_eskalation_an_kb_am,
    f.storniert_am,
    f.anschlussschreiben_am,
    f.vs_eskalationsstufe,
    f.kennzeichen,
    f.fahrzeug_hersteller,
    f.fahrzeug_modell,
    f.fahrzeug_typ,
    c.sa_unterschrieben,
    f.regulierung_am,
    c.regulierungs_betrag AS regulierung_betrag,
    g.gesamt_schadensbetrag::numeric(10,2) AS gutachten_betrag,
    g.fertiggestellt_am AS gutachten_eingegangen_am,
    c.sv_zugewiesen_am,
    c.schadens_ursache,
    c.schadenort_plz::text AS schadens_plz,
    c.schadenort_ort AS schadens_ort,
    c.fall_typ AS schadens_fall_typ,
    f.gegner_anzahl_beteiligte,
    f.gegner_fahrzeugtyp,
    f.organisation_id,
    f.dispatch_id,
    f.kunde_id,
    c.ist_aktiv,
    c.deaktiviert_grund,
    f.hat_vorschaeden,
    f.vorschaden_anzahl,
    f.vorschaden_letzter_datum,
    f.vorschaden_typ_b_bericht,
    f.cardentity_abfrage_am,
    f.besichtigungsort_adresse,
    f.besichtigungsort_lat,
    f.besichtigungsort_lng,
    f.besichtigungsort_notiz,
    f.besichtigungsort_place_id,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cp.*) ORDER BY cp.reihenfolge, cp.created_at) AS jsonb_agg
           FROM claim_parties cp
          WHERE cp.claim_id = c.id), '[]'::jsonb) AS parties,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cvi.*) ORDER BY cvi.reihenfolge, cvi.created_at) AS jsonb_agg
           FROM claim_vehicle_involvements cvi
          WHERE cvi.claim_id = c.id), '[]'::jsonb) AS vehicle_involvements,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cp2.*) ORDER BY cp2.created_at) AS jsonb_agg
           FROM claim_payments cp2
          WHERE cp2.claim_id = c.id), '[]'::jsonb) AS payments,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cm.*) ORDER BY cm.created_at) AS jsonb_agg
           FROM claim_mietwagen cm
          WHERE cm.claim_id = c.id), '[]'::jsonb) AS mietwagen,
    COALESCE(( SELECT jsonb_agg(to_jsonb(vk.*) ORDER BY vk.datum) AS jsonb_agg
           FROM vs_korrespondenz vk
          WHERE vk.claim_id = c.id), '[]'::jsonb) AS vs_korrespondenz,
    COALESCE(( SELECT jsonb_agg(to_jsonb(r.*) ORDER BY r.created_at) AS jsonb_agg
           FROM repairs r
          WHERE r.claim_id = c.id), '[]'::jsonb) AS repairs
   FROM claims c
     LEFT JOIN faelle f ON f.claim_id = c.id
     LEFT JOIN public.gutachten g ON g.claim_id = c.id;

-- ---- v_faelle_mit_aktuellem_termin ----
CREATE OR REPLACE VIEW public.v_faelle_mit_aktuellem_termin AS
SELECT f.id,
    f.lead_id,
    f.kunde_id,
    f.status,
    c.betreuungspaket,
    c.hergang_kunde_text AS schadens_beschreibung,
    c.schadentag AS schadens_datum,
    c.entdeckt_am AS schadens_entdeckt_am,
    c.schadenort_adresse AS schadens_adresse,
    c.schadenort_plz::text AS schadens_plz,
    c.schadenort_ort AS schadens_ort,
    c.abtretung_pdf,
    c.vollmacht_pdf,
    c.abtretung_signiert_am,
    c.vollmacht_signiert_am,
    f.sv_id,
    c.sv_zugewiesen_am,
    g.fertiggestellt_am AS gutachten_eingegangen_am,
    g.gesamt_schadensbetrag::numeric(10,2) AS gutachten_betrag,
    c.kanzlei_uebergeben_am,
    f.anschlussschreiben_am,
    c.regulierungs_betrag AS regulierung_betrag,
    f.regulierung_am,
    f.filmcheck_ok,
    f.filmcheck_am,
    f.filmcheck_notizen,
    c.notizen,
    f.created_at,
    f.updated_at,
    c.fall_typ AS schadens_fall_typ,
    c.kunden_konstellation,
    f.kennzeichen,
    f.fahrzeug_typ,
    f.fahrzeug_hersteller,
    f.fahrzeug_modell,
    f.fahrzeug_baujahr,
    f.gegner_name,
    f.gegner_versicherung,
    f.gegner_kennzeichen,
    c.gegner_bekannt,
    c.polizei_aktenzeichen,
    c.polizei_bericht_vorhanden,
    c.hat_personenschaden AS personenschaden_flag,
    c.hat_mietwagen AS mietwagen_flag,
    c.gewerbe_flag,
    c.halter_ungleich_fahrer AS halter_ungleich_fahrer_flag,
    f.ust_id,
    f.leasinggeber_name,
    c.leasinggeber_informiert,
    f.bank_name,
    c.prioritaet,
    c.onboarding_complete,
    f.dispatch_id,
    c.kundenbetreuer_id,
    f.konvertiert_am,
    c.lead_id AS konvertiert_von_lead,
    c.status_changed_at,
    f.regulierung_angekuendigt_am,
    f.zahlung_eingegangen_am,
    c.abgeschlossen_am,
    c.google_review_gesendet,
    f.vs_eskalationsstufe,
    f.fin_quelle,
    f.fin_extrahiert_am,
    f.vorschaden_geprueft,
    f.vorschaden_anzahl,
    f.vorschaden_letzter_datum,
    f.vorschaden_typ_a_ergebnis,
    f.vorschaden_typ_b_bericht,
    f.vorschaden_typ_b_pdf_url,
    f.cardentity_abfrage_am,
    c.schadens_hoehe_netto,
    g.gutachten_nutzungsausfall_tagessatz_eur::numeric(10,2) AS nutzungsausfall_tagessatz,
    g.wiederbeschaffungsdauer_tage AS reparaturdauer_tage,
    g.gutachten_sv_honorar_netto AS gutachter_honorar,
    g.ocr_finished_at AS ocr_extrahiert_am,
    g.gutachten_ocr_raw AS ocr_rohdaten,
    g.ki_kalkulation,
    g.ki_kalkulation_am,
    g.ki_geschaetzte_kosten_min::numeric(10,2) AS ki_geschaetzte_kosten_min,
    g.ki_geschaetzte_kosten_max::numeric(10,2) AS ki_geschaetzte_kosten_max,
    c.kanzlei_ansprechpartner_name,
    c.kanzlei_ansprechpartner_email,
    c.kanzlei_ansprechpartner_telefon,
    c.kanzlei_ansprechpartner_position,
    f.mandatsnummer,
    f.losfahren_erinnerung_gesendet,
    f.termin_erinnerung_5min_gesendet,
    f.geschaetzte_fahrzeit_min,
    f.geschaetzte_fahrdistanz_km,
    f.gcal_event_id,
    (g.id IS NOT NULL) AS gutachten_vorhanden,
    g.pdf_uploaded_at AS gutachten_hochgeladen_am,
    g.positionen AS gutachten_positionen,
    g.auftragsnummer AS gutachten_nummer,
    g.reparaturkosten_netto AS reparaturkosten,
    g.minderwert AS wertminderung,
    (g.gutachten_nutzungsausfall_tagessatz_eur * g.nutzungsausfall_tage)::numeric(10,2) AS nutzungsausfall_gesamt,
    f.regulierungsweise,
    c.gegner_versicherungsnummer,
    c.sa_unterschrieben,
    c.sa_unterschrieben_am,
    c.sa_pdf_url,
    c.sa_unterschrift_url,
    c.datenschutz_akzeptiert,
    c.datenschutz_akzeptiert_am,
    c.vollmacht_status,
    c.polizei_vor_ort,
    c.hergang_kunde_text AS unfallhergang,
    c.unfallmitteilung_status,
    c.schadenort_adresse AS unfallort,
    c.schadentag AS unfalldatum,
    c.interne_notizen,
    f.anschlussschreiben_url,
    f.anschlussschreiben_sendedatum,
    f.anschlussschreiben_unterschrift,
    f.anschlussschreiben_ocr_am,
    f.besichtigungsort_adresse,
    f.besichtigungsort_lat,
    f.besichtigungsort_lng,
    f.besichtigungsort_place_id,
    c.ist_aktiv,
    c.deaktiviert_am,
    c.deaktiviert_grund,
    c.deaktiviert_notiz,
    c.szenario,
    f.ruege_erhalten_am,
    f.ruege_grund,
    f.fahrzeug_farbe,
    f.erstzulassung,
    f.kilometerstand,
    f.firma_name,
    f.marketing_quelle,
    f.marketing_provision,
    f.marketing_provision_status,
    NULL::numeric(10,2) AS gutachten_stundensatz,
    f.kanzlei_id,
    f.kanzlei_honorar,
    f.zahlung_erwartet_am,
    f.zahlung_betrag,
    f.lead_preis_netto,
    f.lead_preis_typ,
    f.lead_preis_berechnet_am,
    f.guthaben_verrechnet_netto,
    f.sv_nachzahlung_netto,
    f.abrechnung_id,
    f.storniert_am,
    f.storno_grund,
    f.storno_durch_user_id,
    f.no_show_gemeldet_am,
    c.spezifikation,
    c.schadenart AS schadens_art,
    f.organisation_id,
    c.phase AS aktuelle_phase,
    c.dokumente_vollstaendig_fuer_phase,
    c.dokumente_vollstaendig_am_phase,
    c.unfall_konstellation,
    f.gegner_anzahl_beteiligte,
    f.gegner_fahrzeugtyp,
    c.dokumente_reminder_whatsapp_letzte_sendung,
    f.fin_vin,
    f.source_channel,
    f.source_domain,
    c.schadens_ursache,
    f.kanzlei_abrechnung_id,
    f.kanzlei_provision_status,
    f.kanzlei_provision_ausgezahlt_am,
    c.service_typ,
    f.vs_reaktion_typ,
    f.vs_reaktion_am,
    c.vs_ablehnungs_grund AS vs_ablehnungsgrund,
    f.ruege_gesendet_am,
    f.ruege_betrag,
    c.kunde_no_show_count AS no_show_count,
    f.kuerzungs_betrag,
    f.vs_frist_bis,
    f.ruege_counter,
    f.schlussabrechnung_am,
    f.iban,
    f.bic,
    f.kontoinhaber,
    f.bankdaten_hinterlegt_am,
    f.ist_fahrzeughalter,
    c.finanzierung_leasing,
    c.vorsteuerabzugsberechtigt,
    c.hergang_kunde_text AS schadens_hergang,
    f.halter_vorname,
    f.halter_nachname,
    f.halter_strasse,
    f.halter_plz,
    f.halter_stadt,
    f.halter_telefon,
    f.halter_email,
    c.finanzierungsgeber_name,
    c.finanzierungsgeber_adresse,
    c.finanzierungsgeber_vertragsnr,
    f.zahlungsweg,
    f.hat_vorschaeden,
    f.vorschaeden_beschreibung,
    f.technische_stellungnahme_status,
    f.technische_stellungnahme_beauftragt_am,
    f.technische_stellungnahme_hochgeladen_am,
    f.technische_stellungnahme_freigabe_am,
    f.nachbesichtigung_status,
    f.nachbesichtigung_angefordert_am,
    f.nachbesichtigung_termin_datum,
    f.nachbesichtigung_konfrontation,
    f.as_geforderte_summe,
    f.as_frist,
    f.as_vs_reaktion_text,
    f.as_salesforce_id,
    f.as_zuletzt_synced_am,
    f.lexdrive_case_id,
    f.eskalation_tag_14_am,
    f.eskalation_tag_21_am,
    f.eskalation_tag_28_am,
    c.schadenort_kategorie AS unfallort_kategorie,
    c.unfallskizze_url,
    f.fahrzeug_ausstattung,
    f.cardentity_enriched_at,
    f.cardentity_report,
    c.vollmacht_geprueft_am,
    c.vollmacht_geprueft_von,
    c.vollmacht_pruefung_status,
    c.vollmacht_pruefung_begruendung,
    f.lexdrive_ocr_data,
    f.lexdrive_ocr_received_at,
    f.vs_kuerzung_grund,
    c.geschlossen_grund,
    f.nachbesichtigung_ergebnis,
    c.bevorzugter_kanal,
    c.gegner_versicherung_id,
    c.zeugen_kontakte,
    c.werkstatt_seit_datum,
    c.fahrzeug_fahrbereit,
    c.hat_nutzungsausfall AS nutzungsausfall,
    f.mietwagen_kanzlei_informiert,
    f.mietwagen_kanzlei_informiert_am,
    f.halter_geburtsdatum,
    c.abrechnungsart_besprochen,
    c.abrechnungsart_notiz,
    c.abrechnungsart_besprochen_am,
    f.gegner_versicherung_anfrage_datum,
    c.sprache,
    c.unfallskizze_svg,
    c.unfallskizze_bestaetigt,
    c.unfallskizze_ablehnung_grund,
    c.unfallskizze_generiert_am,
    c.zeugen_vorhanden,
    f.vorschaden_erkannt,
    f.sv_termin_dokument_reminder_gesendet_am,
    c.kundenbetreuer_fallback_flag,
    c.kundenbetreuer_zugewiesen_am,
    f.sv_briefing_text,
    f.sv_briefing_generated_at,
    f.sv_briefing_model,
    f.sv_briefing_version,
    f.sv_briefing_struktur,
    f.sv_notizen_vor_ort,
    c.makler_id,
    c.hat_sachschaden AS sachschaden_flag,
    c.sachschaden_beschreibung,
    c.gegner_aktenzeichen AS gegner_schadennummer,
    f.halter_name,
    f.wunschtermin,
    f.vs_quote_prozent,
    f.vs_quote_grund,
    f.vs_quote_akzeptiert_am,
    f.vs_quote_betrag_ausgezahlt,
    f.vs_kuerzungs_typ,
    f.auszahlung_kunde_betrag,
    f.auszahlung_kunde_eingegangen_am,
    f.auszahlung_gutachter_eingegangen_am,
    f.auszahlung_zahlungsweg,
    f.eskalation_tag_14_ergebnis,
    f.eskalation_tag_14_ergebnis_am,
    f.eskalation_tag_14_ergebnis_von,
    f.eskalation_tag_21_ergebnis,
    f.eskalation_tag_21_ergebnis_am,
    f.eskalation_tag_21_ergebnis_von,
    f.eskalation_tag_28_ergebnis,
    f.eskalation_tag_28_ergebnis_am,
    f.eskalation_tag_28_ergebnis_von,
    f.nachbesichtigung_kunde_termin_vorschlaege,
    f.nachbesichtigung_kunde_termin_eingereicht_am,
    f.nachbesichtigung_sv_konfrontation_gewuenscht,
    f.nachbesichtigung_sv_termin_vereinbart_am,
    f.auszahlung_gutachter_betrag,
    f.ruege_frist_tage,
    f.klage_uebergeben_am,
    c.fallakte_angelegt_am,
    f.kunde_vorname,
    f.kunde_nachname,
    f.kunde_telefon,
    c.kunde_email,
    f.kunde_strasse,
    f.kunde_plz,
    f.kunde_stadt,
    f.kunde_adresse,
    f.kunde_lat,
    f.kunde_lng,
    f.hsn,
    f.tsn,
    f.technische_stellungnahme_notiz_sv,
    c.fahrerflucht,
    c.auslandskennzeichen,
    c.polizeibericht_status,
    c.zb1_status,
    c.schadenzeit::text AS unfall_uhrzeit,
    c.schadenort_lat::numeric AS unfallort_lat,
    c.schadenort_lng::numeric AS unfallort_lng,
    c.bkat_unfallart,
    c.fahrzeugschaden_beschreibung,
    c.hat_mietwagen AS mietwagen_hat,
    c.mietwagen_seit_datum,
    c.mietwagen_limit_tage,
    c.mietwagen_limit_grund,
    c.mietwagen_rechnung_vorhanden,
    c.mietwagen_rechnung_url,
    c.mietwagen_argumentations_puffer,
    c.mietwagen_vermieter,
    c.vehicle_id,
    f.claim_id,
    f.lackfarbe_code,
    t.id AS aktueller_termin_id,
    t.start_zeit AS aktueller_termin_start,
    t.end_zeit AS aktueller_termin_end,
    t.status AS aktueller_termin_status,
    t.sv_id AS aktueller_termin_sv_id,
    t.kanal AS aktueller_termin_kanal,
    t.typ AS aktueller_termin_typ,
    t.final_verbindlich_ab AS aktueller_termin_final_verbindlich_ab,
    t.start_zeit AS sv_termin,
    t.status AS gutachter_termin_status,
    t.status = 'bestaetigt'::text AS gutachter_termin_bestaetigt,
    t.vorgeschlagenes_datum AS gutachter_gegenvorschlag_datum,
    t.gegenvorschlag_grund AS gutachter_gegenvorschlag_grund,
    c.claim_nummer
   FROM faelle f
     LEFT JOIN claims c ON c.id = f.claim_id
     LEFT JOIN public.gutachten g ON g.claim_id = c.id
     LEFT JOIN LATERAL ( SELECT gt.id,
            gt.sv_id,
            gt.fall_id,
            gt.start_zeit,
            gt.end_zeit,
            gt.status,
            gt.externer_kalender_id,
            gt.ablehnungsgrund,
            gt.gegenvorschlag_zeit,
            gt.created_at,
            gt.erinnerung_24h_gesendet,
            gt.erinnerung_2h_gesendet,
            gt.erinnerung_48h_docs_gesendet,
            gt.ankunft_zeit,
            gt.abschluss_zeit,
            gt.uebersprungen,
            gt.uebersprung_grund,
            gt.notizen_vor_ort,
            gt.gps_lat_ankunft,
            gt.gps_lng_ankunft,
            gt.lead_id,
            gt.ablehnen_token,
            gt.abgelehnt_am,
            gt.abgelehnt_grund,
            gt.vorgeschlagenes_datum,
            gt.gegenvorschlag_grund,
            gt.gegenvorschlag_von,
            gt.ankunft_via,
            gt.verspaetung_minuten,
            gt.losgefahren_am,
            gt.kunden_tracking_token,
            gt.notification_losgefahren_gesendet_am,
            gt.notification_5min_gesendet_am,
            gt.notification_angekommen_gesendet_am,
            gt.ablehnen_token_expires_at,
            gt.final_verbindlich_ab,
            gt.sv_ablehnung_grund,
            gt.sv_ablehnung_am,
            gt.sv_vorgeschlagene_slots,
            gt.typ,
            gt.kanal,
            gt.video_link,
            gt.kb_id,
            gt.notiz_kunde,
            gt.notiz_intern,
            gt.reminder_sent_at,
            gt.reminder_1h_sent_at,
            gt.cancelled_at,
            gt.navigation_started_at,
            gt.sv_unterwegs_seit,
            gt.sv_eta_minuten,
            gt.sv_eta_letzte_berechnung,
            gt.sv_angekommen_am,
            gt.reminder_15min_sent_at,
            gt.reminder_5min_sent_at,
            gt.durchgefuehrt_am,
            gt.kunde_tracking_aktiviert,
            gt.kunde_losgefahren_am,
            gt.kunde_eta_minuten,
            gt.kunde_eta_letzte_berechnung,
            gt.kunde_angekommen_am,
            gt.kunde_verspaetung_gemeldet_am,
            gt.bezahlt,
            gt.honorar_betrag,
            gt.google_event_id,
            gt.google_calendar_id,
            gt.google_event_synced_at,
            gt.kunde_response_token,
            gt.kunde_response_token_expires_at,
            gt.gesehen_am,
            gt.geschaetzte_fahrtzeit_min,
            gt.auftrag_id,
            gt.verlegung_quelle_id,
            gt.verlegung_grund,
            gt.verlegung_kunde_benachrichtigt_an,
            gt.verlegung_eskalation_an_kb_an,
            gt.verlegung_initiator_kunde,
            gt.besichtigung_gestartet_am,
            gt.caldav_object_url,
            gt.caldav_event_uid,
            gt.caldav_synced_at,
            gt.erinnerung_morgen_gesendet,
            gt.sv_lead_id
           FROM gutachter_termine gt
          WHERE gt.fall_id = f.id AND (gt.status = ANY (ARRAY['bestaetigt'::text, 'verlegung_pending'::text, 'reserviert'::text, 'durchgefuehrt'::text, 'gegenvorschlag'::text]))
          ORDER BY (
                CASE gt.status
                    WHEN 'bestaetigt'::text THEN 1
                    WHEN 'verlegung_pending'::text THEN 2
                    WHEN 'gegenvorschlag'::text THEN 3
                    WHEN 'reserviert'::text THEN 4
                    WHEN 'durchgefuehrt'::text THEN 5
                    ELSE 6
                END), gt.start_zeit DESC NULLS LAST
         LIMIT 1) t ON true;

COMMIT;
