-- P1 (dispatch-config-unify): Feld-Inventar-Seed der unified Flow 'lead-erfassung'.
-- 63 Felder (audience/sektion/db_target=leads), 1:1 gegen den Dispatch-Code verifiziert.
-- phase_id wird per JOIN aus phase_key aufgeloest (keine hardcoded UUIDs). Additiv.
-- Plan: docs/superpowers/plans/2026-06-01-dispatch-config-unify-p1-feld-inventar.md
INSERT INTO onboarding_felder
  (phase_id, reihenfolge, feld_key, typ, label, hint, placeholder, pflicht, optionen, db_target, conditional_on, audience, sektion)
SELECT p.id, v.reihenfolge, v.feld_key, v.typ, v.label, v.hint, v.placeholder, v.pflicht,
       v.optionen::jsonb, v.db_target::jsonb, v.conditional_on::jsonb, v.audience, v.sektion
FROM (VALUES
  ('kontakt',10,'vorname','text','Vorname',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"vorname"}',NULL,'beide'),
  ('kontakt',20,'nachname','text','Nachname',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"nachname"}',NULL,'beide'),
  ('kontakt',30,'telefon','tel','Telefon',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"telefon"}',NULL,'beide'),
  ('kontakt',40,'email','email','E-Mail',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"email"}',NULL,'beide'),
  ('kontakt',50,'bevorzugter_kanal','segmented','Bevorzugter Kanal',NULL,NULL,false,'[{"label":"WhatsApp","value":"whatsapp"},{"label":"Anruf","value":"anruf"},{"label":"E-Mail","value":"email"}]','{"tabelle":"leads","spalte":"bevorzugter_kanal"}',NULL,'beide'),
  ('kontakt',60,'whatsapp_verfuegbar','segmented','WhatsApp verfügbar?',NULL,NULL,false,'[{"label":"Ja","value":"true"},{"label":"Nein","value":"false"}]','{"tabelle":"leads","spalte":"whatsapp_verfuegbar"}',NULL,'dispatcher'),
  ('kontakt',70,'kunde_strasse','text','Straße',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"kunde_strasse"}',NULL,'beide'),
  ('kontakt',80,'kunde_plz','text','PLZ',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"kunde_plz"}',NULL,'beide'),
  ('kontakt',90,'kunde_stadt','text','Stadt',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"kunde_stadt"}',NULL,'beide'),
  ('kontakt',100,'sprache','segmented','Sprache',NULL,NULL,false,'[{"label":"Deutsch","value":"de"},{"label":"Türkisch","value":"tr"},{"label":"Arabisch","value":"ar"},{"label":"Russisch","value":"ru"},{"label":"Polnisch","value":"pl"},{"label":"Englisch","value":"en"},{"label":"Andere","value":"other"}]','{"tabelle":"leads","spalte":"sprache"}',NULL,'dispatcher'),
  ('kontakt',110,'notiz','textarea','Notiz (intern)',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"notiz"}',NULL,'dispatcher'),
  ('schaden',10,'schadentyp','toggle-cards','Schadentyp',NULL,NULL,false,'[{"label":"Spurwechsel","value":"spurwechsel"},{"label":"Auffahrunfall","value":"auffahrunfall"},{"label":"Vorfahrtsverletzung","value":"vorfahrtsverletzung"},{"label":"Parkplatz","value":"parkplatz"},{"label":"Sonstiges","value":"sonstiges"}]','{"tabelle":"leads","spalte":"schadentyp"}',NULL,'beide'),
  ('schaden',20,'schadentyp_freitext','textarea','Beschreibung',NULL,'Was genau ist passiert?',false,NULL,'{"tabelle":"leads","spalte":"schadentyp_freitext"}','{"feld":"schadentyp","equals":"sonstiges"}','beide'),
  ('schaden',30,'schaden_sichtbar','segmented','Sichtbarer Schaden?',NULL,NULL,false,'[{"label":"Ja","value":"true"},{"label":"Nein","value":"false"}]','{"tabelle":"leads","spalte":"schaden_sichtbar"}',NULL,'beide'),
  ('schaden',40,'unfallhergang','textarea','Unfallhergang',NULL,'Wie ist es passiert?',false,NULL,'{"tabelle":"leads","spalte":"unfallhergang"}',NULL,'beide'),
  ('schaden',50,'fahrzeugschaden_beschreibung','textarea','Schadenbeschreibung (Fahrzeug)',NULL,'Was ist am Auto beschädigt?',false,NULL,'{"tabelle":"leads","spalte":"fahrzeugschaden_beschreibung"}',NULL,'beide'),
  ('schaden',60,'personenschaden_flag','segmented','Personenschaden?',NULL,NULL,false,'[{"label":"Ja","value":"true"},{"label":"Nein","value":"false"}]','{"tabelle":"leads","spalte":"personenschaden_flag"}',NULL,'beide'),
  ('schaden',70,'sachschaden_flag','segmented','Sachschäden an Dritten?',NULL,NULL,false,'[{"label":"Ja","value":"true"},{"label":"Nein","value":"false"}]','{"tabelle":"leads","spalte":"sachschaden_flag"}',NULL,'beide'),
  ('schaden',80,'sachschaden_beschreibung','textarea','Was wurde beschädigt?',NULL,'z.B. Leitplanke, Handy …',false,NULL,'{"tabelle":"leads","spalte":"sachschaden_beschreibung"}','{"feld":"sachschaden_flag","equals":"true"}','beide'),
  ('schaden',90,'mietwagen_flag','segmented','Mietwagen gewünscht?',NULL,NULL,false,'[{"label":"Ja","value":"true"},{"label":"Nein","value":"false"}]','{"tabelle":"leads","spalte":"mietwagen_flag"}',NULL,'beide'),
  ('schaden',100,'nutzungsausfall','segmented','Nutzungsausfall?',NULL,NULL,false,'[{"label":"Ja","value":"true"},{"label":"Nein","value":"false"}]','{"tabelle":"leads","spalte":"nutzungsausfall"}',NULL,'beide'),
  ('schaden',110,'schadensfotos','file','Schadenfotos',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"schadensfoto_urls"}',NULL,'beide'),
  ('schaden',120,'hat_vorschaeden','segmented','Vorschäden bekannt?',NULL,NULL,false,'[{"label":"Ja","value":"true"},{"label":"Nein","value":"false"}]','{"tabelle":"leads","spalte":"hat_vorschaeden"}',NULL,'beide'),
  ('schaden',130,'vorschaeden_beschreibung','textarea','Vorschäden-Beschreibung',NULL,'Bereich / Schadenhöhe',false,NULL,'{"tabelle":"leads","spalte":"vorschaeden_beschreibung"}','{"feld":"hat_vorschaeden","equals":"true"}','beide'),
  ('unfall',10,'unfallort','text','Unfallort',NULL,'Adresse',false,NULL,'{"tabelle":"leads","spalte":"unfallort"}',NULL,'beide'),
  ('unfall',20,'unfalldatum','text','Unfalldatum',NULL,'JJJJ-MM-TT',false,NULL,'{"tabelle":"leads","spalte":"unfalldatum"}',NULL,'beide'),
  ('unfall',30,'unfall_uhrzeit','text','Unfall-Uhrzeit (ca.)',NULL,'z.B. 14:30',false,NULL,'{"tabelle":"leads","spalte":"unfall_uhrzeit"}',NULL,'beide'),
  ('unfall',40,'polizei_vor_ort','segmented','Polizei vor Ort?',NULL,NULL,false,'[{"label":"Ja","value":"true"},{"label":"Nein","value":"false"}]','{"tabelle":"leads","spalte":"polizei_vor_ort"}',NULL,'beide'),
  ('unfall',50,'polizei_aktenzeichen','text','Aktenzeichen',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"polizei_aktenzeichen"}','{"feld":"polizei_vor_ort","equals":"true"}','beide'),
  ('unfall',60,'gegner_kennzeichen','text','Gegner-Kennzeichen',NULL,'oder leer bei Fahrerflucht',false,NULL,'{"tabelle":"leads","spalte":"gegner_kennzeichen"}',NULL,'beide'),
  ('unfall',70,'gegner_versicherung','text','Gegner-Versicherung',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"gegner_versicherung"}',NULL,'beide'),
  ('unfall',80,'gegner_schadennummer','text','Schadennummer (Gegner)',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"gegner_schadennummer"}',NULL,'beide'),
  ('unfall',90,'gegner_telefon','tel','Gegner-Telefon',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"gegner_telefon"}',NULL,'beide'),
  ('unfall',100,'gegner_email','email','Gegner-E-Mail',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"gegner_email"}',NULL,'beide'),
  ('unfall',110,'zeugen','segmented','Zeugen vorhanden?',NULL,NULL,false,'[{"label":"Ja","value":"true"},{"label":"Nein","value":"false"}]','{"tabelle":"leads","spalte":"zeugen"}',NULL,'beide'),
  ('fahrzeug',10,'fahrzeugschein_foto','zb1-upload','Fahrzeugschein (ZB1) — Foto',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"kennzeichen"}',NULL,'beide'),
  ('fahrzeug',20,'kennzeichen','text','Kennzeichen',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"kennzeichen"}',NULL,'beide'),
  ('fahrzeug',30,'fahrzeug_hersteller','text','Marke',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"fahrzeug_hersteller"}',NULL,'beide'),
  ('fahrzeug',40,'fahrzeug_modell','text','Modell',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"fahrzeug_modell"}',NULL,'beide'),
  ('fahrzeug',50,'fahrzeug_baujahr','number','Baujahr',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"fahrzeug_baujahr"}',NULL,'beide'),
  ('fahrzeug',60,'fin','text','FIN',NULL,'17 Zeichen',false,NULL,'{"tabelle":"leads","spalte":"fin"}',NULL,'beide'),
  ('fahrzeug',70,'hsn','text','HSN',NULL,'4 Ziffern',false,NULL,'{"tabelle":"leads","spalte":"hsn"}',NULL,'beide'),
  ('fahrzeug',80,'tsn','text','TSN',NULL,'3 Zeichen',false,NULL,'{"tabelle":"leads","spalte":"tsn"}',NULL,'beide'),
  ('fahrzeug',90,'fahrzeug_farbe','text','Lack-Detail',NULL,'z.B. Saphirschwarz Metallic',false,NULL,'{"tabelle":"leads","spalte":"fahrzeug_farbe"}',NULL,'beide'),
  ('fahrzeug',100,'fahrzeug_fahrbereit','segmented','Fahrzeug fahrbereit?',NULL,NULL,false,'[{"label":"Ja","value":"true"},{"label":"Nein","value":"false"}]','{"tabelle":"leads","spalte":"fahrzeug_fahrbereit"}',NULL,'beide'),
  ('fahrzeug',110,'ist_fahrzeughalter','segmented','Kunde = Fahrzeughalter?',NULL,NULL,false,'[{"label":"Ja","value":"true"},{"label":"Nein","value":"false"}]','{"tabelle":"leads","spalte":"ist_fahrzeughalter"}',NULL,'beide'),
  ('fahrzeug',120,'halter_vorname','text','Halter Vorname',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"halter_vorname"}','{"feld":"ist_fahrzeughalter","equals":"false"}','beide'),
  ('fahrzeug',130,'halter_nachname','text','Halter Nachname',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"halter_nachname"}','{"feld":"ist_fahrzeughalter","equals":"false"}','beide'),
  ('fahrzeug',140,'halter_geburtsdatum','text','Halter Geburtsdatum',NULL,'JJJJ-MM-TT',false,NULL,'{"tabelle":"leads","spalte":"halter_geburtsdatum"}','{"feld":"ist_fahrzeughalter","equals":"false"}','beide'),
  ('fahrzeug',150,'halter_strasse','text','Halter Straße',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"halter_strasse"}','{"feld":"ist_fahrzeughalter","equals":"false"}','beide'),
  ('fahrzeug',160,'halter_plz','text','Halter PLZ',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"halter_plz"}','{"feld":"ist_fahrzeughalter","equals":"false"}','beide'),
  ('fahrzeug',170,'halter_stadt','text','Halter Ort',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"halter_stadt"}','{"feld":"ist_fahrzeughalter","equals":"false"}','beide'),
  ('schuld',10,'schuldfrage','segmented','Schuldfrage',NULL,NULL,false,'[{"label":"Die Gegenseite","value":"gegner"},{"label":"Noch unklar","value":"unklar"},{"label":"Ich selbst","value":"eigenverantwortung"}]','{"tabelle":"leads","spalte":"schuldfrage"}',NULL,'beide'),
  ('schuld',20,'aufklaerung_teilschuld_bestaetigt','segmented','Aufklärung Teilschuld bestätigt',NULL,NULL,false,'[{"label":"Ja","value":"true"},{"label":"Nein","value":"false"}]','{"tabelle":"leads","spalte":"aufklaerung_teilschuld_bestaetigt"}','{"feld":"schuldfrage","equals":"unklar"}','dispatcher'),
  ('service_kanzlei',10,'service_typ','toggle-cards','Service-Umfang','Bei "Komplettservice" arbeiten wir mit unserer Partnerkanzlei LexDrive zusammen — kostenlos für Sie.',NULL,false,'[{"label":"Komplettservice (empfohlen)","value":"komplett","description":"Anwalt + Vollmacht inkl. — 0 EUR, wir regeln alles fuer Sie"},{"label":"Nur Gutachten","value":"nur_gutachter","description":"Sie regulieren selbst mit der gegnerischen Versicherung"}]','{"tabelle":"leads","spalte":"service_typ"}',NULL,'beide'),
  ('service_kanzlei',20,'kanzlei_wunsch','toggle-cards','Anwalt-Wahl',NULL,NULL,false,'[{"label":"Unsere Partnerkanzlei (empfohlen)","value":"partnerkanzlei","description":"LexDrive — spezialisiert auf Kfz-Schaeden, 0 EUR fuer Sie, kuemmern sich um Vollmacht und alles weitere"},{"label":"Meine eigene Kanzlei","value":"eigene_kanzlei","description":"Sie geben uns die Kontaktdaten, wir uebergeben das Paket"},{"label":"Kein Anwalt","value":"keine_kanzlei","description":"Sie regulieren selbst — keine Anwalts-Begleitung"}]','{"tabelle":"leads","spalte":"kanzlei_wunsch"}','{"feld":"service_typ","equals":"komplett"}','beide'),
  ('termin_sv',10,'besichtigungsort_adresse','text','Besichtigungsadresse',NULL,'Wo steht das Fahrzeug?',false,NULL,'{"tabelle":"leads","spalte":"besichtigungsort_adresse"}',NULL,'beide'),
  ('termin_sv',20,'besichtigungsort_notiz','textarea','Treffpunkt-Notiz',NULL,'z.B. Hintereingang, Schlüssel bei Werkstatt',false,NULL,'{"tabelle":"leads","spalte":"besichtigungsort_notiz"}',NULL,'beide'),
  ('termin_sv',30,'wunschtermin','text','Wunschtermin',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"wunschtermin"}',NULL,'beide'),
  ('termin_sv',40,'termin','termin','SV-Besichtigungstermin',NULL,NULL,false,NULL,'{"tabelle":"_termin","spalte":"termin_id"}',NULL,'beide'),
  ('vollmacht',10,'unterschrift','signature','Schadenanzeige (SA) — Unterschrift',NULL,NULL,false,NULL,'{"tabelle":"_finalize","spalte":"unterschrift"}',NULL,'beide'),
  ('status',10,'disqualifiziert','segmented','Disqualifiziert?',NULL,NULL,false,'[{"label":"Ja","value":"true"},{"label":"Nein","value":"false"}]','{"tabelle":"leads","spalte":"disqualifiziert"}',NULL,'dispatcher'),
  ('status',20,'disqualifiziert_grund','textarea','Disqualifikations-Grund',NULL,NULL,false,NULL,'{"tabelle":"leads","spalte":"disqualifiziert_grund"}','{"feld":"disqualifiziert","equals":"true"}','dispatcher')
) AS v(sektion,reihenfolge,feld_key,typ,label,hint,placeholder,pflicht,optionen,db_target,conditional_on,audience)
JOIN onboarding_phasen p ON p.flow_key='lead-erfassung' AND p.phase_key=v.sektion;
