-- View-Kanonisierung (b): faelle_kunde_view wird duenner Layer auf v_claim_base.
-- Harness-verifiziert: 0 non-termin-Diffs ueber 89 Rows, Shape 38 Spalten identisch.
-- 2 EXEMPT-Diffs (nachbesichtigung auf 2 Claims) = Decision-a wie bei vcf.
CREATE OR REPLACE VIEW public.faelle_kunde_view AS
SELECT
  base.fall_id                                        AS id,
  base.fall_status                                    AS status,
  base.hergang_kunde_text                             AS schadens_beschreibung,
  base.schadentag                                     AS schadens_datum,
  base.schadenort_adresse                             AS schadens_adresse,
  base.schadens_plz                                   AS schadens_plz,
  base.schadens_ort                                   AS schadens_ort,
  base.kennzeichen                                    AS kennzeichen,
  base.fahrzeug_hersteller_raw                        AS fahrzeug_hersteller,
  base.fahrzeug_modell                                AS fahrzeug_modell,
  base.fahrzeug_baujahr                               AS fahrzeug_baujahr,
  NULL::numeric(10,2)                                 AS auszahlung_kunde_betrag,
  NULL::timestamptz                                   AS auszahlung_kunde_eingegangen_am,
  base.auszahlung_zahlungsweg                         AS auszahlung_zahlungsweg,
  base.eskalation_tag_14_ergebnis                     AS eskalation_tag_14_ergebnis,
  base.eskalation_tag_14_ergebnis_am                  AS eskalation_tag_14_ergebnis_am,
  base.eskalation_tag_21_ergebnis                     AS eskalation_tag_21_ergebnis,
  base.eskalation_tag_21_ergebnis_am                  AS eskalation_tag_21_ergebnis_am,
  base.eskalation_tag_28_ergebnis                     AS eskalation_tag_28_ergebnis,
  base.eskalation_tag_28_ergebnis_am                  AS eskalation_tag_28_ergebnis_am,
  base.nachbesichtigung_status                        AS nachbesichtigung_status,
  base.nachbesichtigung_termin_datum                  AS nachbesichtigung_termin_datum,
  base.nachbesichtigung_kunde_termin_vorschlaege      AS nachbesichtigung_kunde_termin_vorschlaege,
  base.nachbesichtigung_kunde_termin_eingereicht_am   AS nachbesichtigung_kunde_termin_eingereicht_am,
  base.nachbesichtigung_sv_konfrontation_gewuenscht   AS nachbesichtigung_sv_konfrontation_gewuenscht,
  base.vs_quote_prozent                               AS vs_quote_prozent,
  base.vs_quote_grund                                 AS vs_quote_grund,
  base.vs_quote_akzeptiert_am                         AS vs_quote_akzeptiert_am,
  base.vs_quote_betrag_ausgezahlt                     AS vs_quote_betrag_ausgezahlt,
  base.vs_reaktion_typ                                AS vs_reaktion_typ,
  base.vs_reaktion_am                                 AS vs_reaktion_am,
  base.besichtigungsort_adresse                       AS besichtigungsort_adresse,
  base.abgeschlossen_am                               AS abgeschlossen_am,
  base.kunde_id                                       AS kunde_id,
  base.sv_id                                          AS sv_id,
  base.claim_nummer                                   AS claim_nummer,
  base.main_phase                                     AS main_phase,
  base.sub_phase                                      AS sub_phase
FROM v_claim_base base;
