-- BUG-73: Fehlende Spalten in faelle fuer Lead-Daten-Paritaet

ALTER TABLE faelle ADD COLUMN IF NOT EXISTS fahrzeug_farbe TEXT NULL;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS erstzulassung TEXT NULL;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS kilometerstand INTEGER NULL;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS schadensursache TEXT NULL;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS firma_name TEXT NULL;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS halter_name TEXT NULL;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS polizei_vor_ort BOOLEAN NULL;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS wunschtermin TEXT NULL;
ALTER TABLE faelle ADD COLUMN IF NOT EXISTS lead_source_channel TEXT NULL;
