-- CMM-44 SP-A PR2: Drop 34 duplicate columns from public.faelle
--
-- Context: These 34 columns exist name-identically on public.claims (the SSoT).
-- They were kept in sync by the trigger pair trg_sync_faelle_to_claims /
-- trg_sync_claims_to_faelle. PR1 (merged to staging) moved all app reads/writes
-- of these 34 columns onto claims. This migration:
--   1. backfills claims from faelle (closes the AFTER-UPDATE-only sync gap for
--      INSERT-only rows that never received an UPDATE),
--   2. repoints the 3 views that still read a 34-col column from faelle,
--   3. retires the now-functionless sync trigger pair,
--   4. drops the 34 columns from faelle.
--
-- Order is mandatory: backfill -> view repoints -> trigger drop -> column drop.
-- A CREATE OR REPLACE VIEW that still references faelle.<34-col> would block
-- the DROP COLUMN, hence the views must be repointed first.
--
-- DO NOT apply before PR1 is on main/prod. Prod still reads these columns.

-- ---------------------------------------------------------------------------
-- Step 1: Backfill claims from faelle for all 34 columns.
-- COALESCE keeps any value already present on claims; only fills NULL gaps.
-- ---------------------------------------------------------------------------
UPDATE public.claims c
SET
  abgeschlossen_am               = COALESCE(c.abgeschlossen_am,               f.abgeschlossen_am),
  auslandskennzeichen            = COALESCE(c.auslandskennzeichen,            f.auslandskennzeichen),
  brn                            = COALESCE(c.brn,                            f.brn),
  fahrerflucht                   = COALESCE(c.fahrerflucht,                   f.fahrerflucht),
  finanzierung_leasing           = COALESCE(c.finanzierung_leasing,           f.finanzierung_leasing),
  finanzierungsgeber_adresse     = COALESCE(c.finanzierungsgeber_adresse,     f.finanzierungsgeber_adresse),
  finanzierungsgeber_name        = COALESCE(c.finanzierungsgeber_name,        f.finanzierungsgeber_name),
  finanzierungsgeber_vertragsnr  = COALESCE(c.finanzierungsgeber_vertragsnr,  f.finanzierungsgeber_vertragsnr),
  gegner_bekannt                 = COALESCE(c.gegner_bekannt,                 f.gegner_bekannt),
  gegner_versicherung_id         = COALESCE(c.gegner_versicherung_id,         f.gegner_versicherung_id),
  gegner_versicherungsnummer     = COALESCE(c.gegner_versicherungsnummer,     f.gegner_versicherungsnummer),
  gewerbe_flag                   = COALESCE(c.gewerbe_flag,                   f.gewerbe_flag),
  kanzlei_ansprechpartner_email  = COALESCE(c.kanzlei_ansprechpartner_email,  f.kanzlei_ansprechpartner_email),
  kanzlei_ansprechpartner_name   = COALESCE(c.kanzlei_ansprechpartner_name,   f.kanzlei_ansprechpartner_name),
  kanzlei_ansprechpartner_telefon= COALESCE(c.kanzlei_ansprechpartner_telefon,f.kanzlei_ansprechpartner_telefon),
  kanzlei_uebergeben_am          = COALESCE(c.kanzlei_uebergeben_am,          f.kanzlei_uebergeben_am),
  kunde_email                    = COALESCE(c.kunde_email,                    f.kunde_email),
  kunden_konstellation           = COALESCE(c.kunden_konstellation,           f.kunden_konstellation),
  kundenbetreuer_id              = COALESCE(c.kundenbetreuer_id,              f.kundenbetreuer_id),
  polizei_aktenzeichen           = COALESCE(c.polizei_aktenzeichen,           f.polizei_aktenzeichen),
  polizei_bericht_vorhanden      = COALESCE(c.polizei_bericht_vorhanden,      f.polizei_bericht_vorhanden),
  polizei_vor_ort                = COALESCE(c.polizei_vor_ort,                f.polizei_vor_ort),
  polizeibericht_status          = COALESCE(c.polizeibericht_status,          f.polizeibericht_status),
  sachschaden_beschreibung       = COALESCE(c.sachschaden_beschreibung,       f.sachschaden_beschreibung),
  spezifikation                  = COALESCE(c.spezifikation,                  f.spezifikation),
  unfall_konstellation           = COALESCE(c.unfall_konstellation,           f.unfall_konstellation),
  unfallskizze_ablehnung_grund   = COALESCE(c.unfallskizze_ablehnung_grund,   f.unfallskizze_ablehnung_grund),
  unfallskizze_bestaetigt        = COALESCE(c.unfallskizze_bestaetigt,        f.unfallskizze_bestaetigt),
  unfallskizze_generiert_am      = COALESCE(c.unfallskizze_generiert_am,      f.unfallskizze_generiert_am),
  unfallskizze_svg               = COALESCE(c.unfallskizze_svg,               f.unfallskizze_svg),
  unfallskizze_url               = COALESCE(c.unfallskizze_url,               f.unfallskizze_url),
  vehicle_id                     = COALESCE(c.vehicle_id,                     f.vehicle_id),
  vorsteuerabzugsberechtigt      = COALESCE(c.vorsteuerabzugsberechtigt,      f.vorsteuerabzugsberechtigt),
  zeugen_kontakte                = COALESCE(c.zeugen_kontakte,                f.zeugen_kontakte)
FROM public.faelle f
WHERE f.claim_id = c.id;

-- ---------------------------------------------------------------------------
-- Step 2: View repoints.
-- Audit result of the 6 views depending on faelle:
--   faelle_kunde_view              -> reads faelle.abgeschlossen_am          -> REPOINT
--   faelle_sv_view                 -> no 34-col read from faelle             -> ok
--   v_claim_full                   -> all 34-col read from claims (c.)       -> ok
--   v_claim_listing                -> reads faelle.kundenbetreuer_id (f.)    -> REPOINT
--   v_claim_timeline               -> faelle only joined for fall_id         -> ok
--   v_faelle_mit_aktuellem_termin  -> reads 32 of 34 from faelle (f.)        -> REPOINT
-- 3 views need a repoint. brn is not selected by any of the 6 views.
-- ---------------------------------------------------------------------------

-- 2a) faelle_kunde_view: source abgeschlossen_am from claims instead of faelle.
CREATE OR REPLACE VIEW public.faelle_kunde_view AS
SELECT
  f.id,
  f.fall_nummer,
  f.status,
  f.aktuelle_phase,
  f.schadens_beschreibung,
  f.schadens_datum,
  f.schadens_adresse,
  f.schadens_plz,
  f.schadens_ort,
  f.kennzeichen,
  f.fahrzeug_hersteller,
  f.fahrzeug_modell,
  f.fahrzeug_baujahr,
  f.auszahlung_kunde_betrag,
  f.auszahlung_kunde_eingegangen_am,
  f.auszahlung_zahlungsweg,
  f.eskalation_tag_14_ergebnis,
  f.eskalation_tag_14_ergebnis_am,
  f.eskalation_tag_21_ergebnis,
  f.eskalation_tag_21_ergebnis_am,
  f.eskalation_tag_28_ergebnis,
  f.eskalation_tag_28_ergebnis_am,
  f.nachbesichtigung_status,
  f.nachbesichtigung_termin_datum,
  f.nachbesichtigung_kunde_termin_vorschlaege,
  f.nachbesichtigung_kunde_termin_eingereicht_am,
  f.nachbesichtigung_sv_konfrontation_gewuenscht,
  f.vs_quote_prozent,
  f.vs_quote_grund,
  f.vs_quote_akzeptiert_am,
  f.vs_quote_betrag_ausgezahlt,
  f.vs_reaktion_typ,
  f.vs_reaktion_am,
  f.besichtigungsort_adresse,
  c.abgeschlossen_am,
  f.kunde_id,
  f.sv_id
FROM public.faelle f
LEFT JOIN public.claims c ON c.id = f.claim_id;

-- 2b) v_claim_listing: source kundenbetreuer_id (the faelle_kundenbetreuer_id
-- output column) from claims instead of faelle.
CREATE OR REPLACE VIEW public.v_claim_listing AS
SELECT
  c.id AS claim_id,
  c.claim_nummer,
  c.phase,
  c.status,
  c.schadentag,
  c.kunden_konstellation,
  c.created_at,
  c.updated_at,
  f.id AS fall_id,
  f.fall_nummer,
  f.sv_id,
  c.kundenbetreuer_id AS faelle_kundenbetreuer_id,
  c.kundenbetreuer_id AS claim_kundenbetreuer_id,
  f.service_typ,
  p.anzeigename AS kunde_anzeigename,
  p.vorname AS kunde_vorname,
  p.nachname AS kunde_nachname,
  v.kennzeichen_aktuell AS kennzeichen
FROM public.claims c
LEFT JOIN public.faelle f ON f.claim_id = c.id
LEFT JOIN public.profiles p ON p.id = c.geschaedigter_user_id
LEFT JOIN public.vehicles v ON v.id = c.vehicle_id;

-- 2c) v_faelle_mit_aktuellem_termin: a flat projection of faelle f plus the
-- current termin via LATERAL. 32 of the 34 columns are selected here from f.
-- A LEFT JOIN claims c ON c.id = f.claim_id is added and those 32 columns are
-- sourced from c. Column order, names and aliases are kept identical to the
-- original view so the output shape is unchanged.
CREATE OR REPLACE VIEW public.v_faelle_mit_aktuellem_termin AS
SELECT
  f.id,
  f.fall_nummer,
  f.lead_id,
  f.kunde_id,
  f.status,
  f.betreuungspaket,
  f.schadens_beschreibung,
  f.schadens_datum,
  f.schadens_entdeckt_am,
  f.schadens_adresse,
  f.schadens_plz,
  f.schadens_ort,
  f.abtretung_pdf,
  f.vollmacht_pdf,
  f.abtretung_signiert_am,
  f.vollmacht_signiert_am,
  f.sv_id,
  f.sv_zugewiesen_am,
  f.gutachten_eingegangen_am,
  f.gutachten_betrag,
  c.kanzlei_uebergeben_am,
  f.anschlussschreiben_am,
  f.regulierung_betrag,
  f.regulierung_am,
  f.filmcheck_ok,
  f.filmcheck_am,
  f.filmcheck_notizen,
  f.notizen,
  f.created_at,
  f.updated_at,
  f.schadens_fall_typ,
  c.kunden_konstellation,
  f.kennzeichen,
  f.fahrzeug_typ,
  f.fahrzeug_hersteller,
  f.fahrzeug_modell,
  f.fahrzeug_baujahr,
  f.gegner_name,
  f.gegner_versicherung,
  f.gegner_kennzeichen,
  c.gegner_bekannt,
  c.polizei_aktenzeichen,
  c.polizei_bericht_vorhanden,
  f.personenschaden_flag,
  f.mietwagen_flag,
  c.gewerbe_flag,
  f.halter_ungleich_fahrer_flag,
  f.ust_id,
  f.leasinggeber_name,
  f.leasinggeber_informiert,
  f.bank_name,
  f.prioritaet,
  f.onboarding_complete,
  f.dispatch_id,
  c.kundenbetreuer_id,
  f.konvertiert_am,
  f.konvertiert_von_lead,
  f.status_changed_at,
  f.regulierung_angekuendigt_am,
  f.zahlung_eingegangen_am,
  c.abgeschlossen_am,
  f.google_review_gesendet,
  f.vs_eskalationsstufe,
  f.fin_quelle,
  f.fin_extrahiert_am,
  f.vorschaden_geprueft,
  f.vorschaden_anzahl,
  f.vorschaden_letzter_datum,
  f.vorschaden_typ_a_ergebnis,
  f.vorschaden_typ_b_bericht,
  f.vorschaden_typ_b_pdf_url,
  f.cardentity_abfrage_am,
  f.schadens_hoehe_netto,
  f.nutzungsausfall_tagessatz,
  f.reparaturdauer_tage,
  f.gutachter_honorar,
  f.ocr_extrahiert_am,
  f.ocr_rohdaten,
  f.ki_kalkulation,
  f.ki_kalkulation_am,
  f.ki_geschaetzte_kosten_min,
  f.ki_geschaetzte_kosten_max,
  c.kanzlei_ansprechpartner_name,
  c.kanzlei_ansprechpartner_email,
  c.kanzlei_ansprechpartner_telefon,
  f.kanzlei_ansprechpartner_position,
  f.mandatsnummer,
  f.losfahren_erinnerung_gesendet,
  f.termin_erinnerung_5min_gesendet,
  f.geschaetzte_fahrzeit_min,
  f.geschaetzte_fahrdistanz_km,
  f.gcal_event_id,
  f.gutachten_vorhanden,
  f.gutachten_hochgeladen_am,
  f.gutachten_positionen,
  f.gutachten_nummer,
  f.reparaturkosten,
  f.wertminderung,
  f.nutzungsausfall_gesamt,
  f.regulierungsweise,
  c.gegner_versicherungsnummer,
  f.sa_unterschrieben,
  f.sa_unterschrieben_am,
  f.sa_pdf_url,
  f.sa_unterschrift_url,
  f.datenschutz_akzeptiert,
  f.datenschutz_akzeptiert_am,
  f.vollmacht_status,
  c.polizei_vor_ort,
  f.unfallhergang,
  f.unfallmitteilung_status,
  f.unfallort,
  f.unfalldatum,
  f.interne_notizen,
  f.anschlussschreiben_url,
  f.anschlussschreiben_sendedatum,
  f.anschlussschreiben_unterschrift,
  f.anschlussschreiben_ocr_am,
  f.besichtigungsort_adresse,
  f.besichtigungsort_lat,
  f.besichtigungsort_lng,
  f.besichtigungsort_place_id,
  f.ist_aktiv,
  f.deaktiviert_am,
  f.deaktiviert_grund,
  f.deaktiviert_notiz,
  f.szenario,
  f.ruege_erhalten_am,
  f.ruege_grund,
  f.fahrzeug_farbe,
  f.erstzulassung,
  f.kilometerstand,
  f.firma_name,
  f.marketing_quelle,
  f.marketing_provision,
  f.marketing_provision_status,
  f.gutachten_stundensatz,
  f.kanzlei_id,
  f.kanzlei_honorar,
  f.zahlung_erwartet_am,
  f.zahlung_betrag,
  f.lead_preis_netto,
  f.lead_preis_typ,
  f.lead_preis_berechnet_am,
  f.guthaben_verrechnet_netto,
  f.sv_nachzahlung_netto,
  f.abrechnung_id,
  f.storniert_am,
  f.storno_grund,
  f.storno_durch_user_id,
  f.no_show_gemeldet_am,
  c.spezifikation,
  f.schadens_art,
  f.organisation_id,
  f.aktuelle_phase,
  f.dokumente_vollstaendig_fuer_phase,
  f.dokumente_vollstaendig_am_phase,
  c.unfall_konstellation,
  f.gegner_anzahl_beteiligte,
  f.gegner_fahrzeugtyp,
  f.dokumente_reminder_whatsapp_letzte_sendung,
  f.fin_vin,
  f.source_channel,
  f.source_domain,
  f.schadens_ursache,
  f.kanzlei_abrechnung_id,
  f.kanzlei_provision_status,
  f.kanzlei_provision_ausgezahlt_am,
  f.service_typ,
  f.vs_reaktion_typ,
  f.vs_reaktion_am,
  f.vs_ablehnungsgrund,
  f.ruege_gesendet_am,
  f.ruege_betrag,
  f.no_show_count,
  f.kuerzungs_betrag,
  f.vs_frist_bis,
  f.ruege_counter,
  f.schlussabrechnung_am,
  f.iban,
  f.bic,
  f.kontoinhaber,
  f.bankdaten_hinterlegt_am,
  f.ist_fahrzeughalter,
  c.finanzierung_leasing,
  c.vorsteuerabzugsberechtigt,
  f.schadens_hergang,
  f.halter_vorname,
  f.halter_nachname,
  f.halter_strasse,
  f.halter_plz,
  f.halter_stadt,
  f.halter_telefon,
  f.halter_email,
  c.finanzierungsgeber_name,
  c.finanzierungsgeber_adresse,
  c.finanzierungsgeber_vertragsnr,
  f.zahlungsweg,
  f.hat_vorschaeden,
  f.vorschaeden_beschreibung,
  f.technische_stellungnahme_status,
  f.technische_stellungnahme_beauftragt_am,
  f.technische_stellungnahme_hochgeladen_am,
  f.technische_stellungnahme_freigabe_am,
  f.nachbesichtigung_status,
  f.nachbesichtigung_angefordert_am,
  f.nachbesichtigung_termin_datum,
  f.nachbesichtigung_konfrontation,
  f.as_geforderte_summe,
  f.as_frist,
  f.as_vs_reaktion_text,
  f.as_salesforce_id,
  f.as_zuletzt_synced_am,
  f.lexdrive_case_id,
  f.eskalation_tag_14_am,
  f.eskalation_tag_21_am,
  f.eskalation_tag_28_am,
  f.unfallort_kategorie,
  c.unfallskizze_url,
  f.fahrzeug_ausstattung,
  f.cardentity_enriched_at,
  f.cardentity_report,
  f.vollmacht_geprueft_am,
  f.vollmacht_geprueft_von,
  f.vollmacht_pruefung_status,
  f.vollmacht_pruefung_begruendung,
  f.lexdrive_ocr_data,
  f.lexdrive_ocr_received_at,
  f.vs_kuerzung_grund,
  f.geschlossen_grund,
  f.nachbesichtigung_ergebnis,
  f.bevorzugter_kanal,
  c.gegner_versicherung_id,
  c.zeugen_kontakte,
  f.werkstatt_seit_datum,
  f.fahrzeug_fahrbereit,
  f.nutzungsausfall,
  f.mietwagen_kanzlei_informiert,
  f.mietwagen_kanzlei_informiert_am,
  f.halter_geburtsdatum,
  f.abrechnungsart_besprochen,
  f.abrechnungsart_notiz,
  f.abrechnungsart_besprochen_am,
  f.gegner_versicherung_anfrage_datum,
  f.sprache,
  c.unfallskizze_svg,
  c.unfallskizze_bestaetigt,
  c.unfallskizze_ablehnung_grund,
  c.unfallskizze_generiert_am,
  f.zeugen_vorhanden,
  f.vorschaden_erkannt,
  f.sv_termin_dokument_reminder_gesendet_am,
  f.kundenbetreuer_fallback_flag,
  f.kundenbetreuer_zugewiesen_am,
  f.sv_briefing_text,
  f.sv_briefing_generated_at,
  f.sv_briefing_model,
  f.sv_briefing_version,
  f.sv_briefing_struktur,
  f.sv_notizen_vor_ort,
  f.makler_id,
  f.sachschaden_flag,
  c.sachschaden_beschreibung,
  f.gegner_schadennummer,
  f.halter_name,
  f.wunschtermin,
  f.vs_quote_prozent,
  f.vs_quote_grund,
  f.vs_quote_akzeptiert_am,
  f.vs_quote_betrag_ausgezahlt,
  f.vs_kuerzungs_typ,
  f.auszahlung_kunde_betrag,
  f.auszahlung_kunde_eingegangen_am,
  f.auszahlung_gutachter_eingegangen_am,
  f.auszahlung_zahlungsweg,
  f.eskalation_tag_14_ergebnis,
  f.eskalation_tag_14_ergebnis_am,
  f.eskalation_tag_14_ergebnis_von,
  f.eskalation_tag_21_ergebnis,
  f.eskalation_tag_21_ergebnis_am,
  f.eskalation_tag_21_ergebnis_von,
  f.eskalation_tag_28_ergebnis,
  f.eskalation_tag_28_ergebnis_am,
  f.eskalation_tag_28_ergebnis_von,
  f.nachbesichtigung_kunde_termin_vorschlaege,
  f.nachbesichtigung_kunde_termin_eingereicht_am,
  f.nachbesichtigung_sv_konfrontation_gewuenscht,
  f.nachbesichtigung_sv_termin_vereinbart_am,
  f.auszahlung_gutachter_betrag,
  f.ruege_frist_tage,
  f.klage_uebergeben_am,
  f.fallakte_angelegt_am,
  f.kunde_vorname,
  f.kunde_nachname,
  f.kunde_telefon,
  c.kunde_email,
  f.kunde_strasse,
  f.kunde_plz,
  f.kunde_stadt,
  f.kunde_adresse,
  f.kunde_lat,
  f.kunde_lng,
  f.hsn,
  f.tsn,
  f.technische_stellungnahme_notiz_sv,
  c.fahrerflucht,
  c.auslandskennzeichen,
  c.polizeibericht_status,
  f.zb1_status,
  f.unfall_uhrzeit,
  f.unfallort_lat,
  f.unfallort_lng,
  f.bkat_unfallart,
  f.fahrzeugschaden_beschreibung,
  f.mietwagen_hat,
  f.mietwagen_seit_datum,
  f.mietwagen_limit_tage,
  f.mietwagen_limit_grund,
  f.mietwagen_rechnung_vorhanden,
  f.mietwagen_rechnung_url,
  f.mietwagen_argumentations_puffer,
  f.mietwagen_vermieter,
  c.vehicle_id,
  f.claim_id,
  f.lackfarbe_code,
  t.id AS aktueller_termin_id,
  t.start_zeit AS aktueller_termin_start,
  t.end_zeit AS aktueller_termin_end,
  t.status AS aktueller_termin_status,
  t.sv_id AS aktueller_termin_sv_id,
  t.kanal AS aktueller_termin_kanal,
  t.typ AS aktueller_termin_typ,
  t.final_verbindlich_ab AS aktueller_termin_final_verbindlich_ab,
  t.start_zeit AS sv_termin,
  t.status AS gutachter_termin_status,
  (t.status = 'bestaetigt'::text) AS gutachter_termin_bestaetigt,
  t.vorgeschlagenes_datum AS gutachter_gegenvorschlag_datum,
  t.gegenvorschlag_grund AS gutachter_gegenvorschlag_grund
FROM public.faelle f
LEFT JOIN public.claims c ON c.id = f.claim_id
LEFT JOIN LATERAL (
  SELECT
    gt.id,
    gt.sv_id,
    gt.fall_id,
    gt.start_zeit,
    gt.end_zeit,
    gt.status,
    gt.externer_kalender_id,
    gt.ablehnungsgrund,
    gt.gegenvorschlag_zeit,
    gt.created_at,
    gt.erinnerung_24h_gesendet,
    gt.erinnerung_2h_gesendet,
    gt.erinnerung_48h_docs_gesendet,
    gt.ankunft_zeit,
    gt.abschluss_zeit,
    gt.uebersprungen,
    gt.uebersprung_grund,
    gt.notizen_vor_ort,
    gt.gps_lat_ankunft,
    gt.gps_lng_ankunft,
    gt.lead_id,
    gt.ablehnen_token,
    gt.abgelehnt_am,
    gt.abgelehnt_grund,
    gt.vorgeschlagenes_datum,
    gt.gegenvorschlag_grund,
    gt.gegenvorschlag_von,
    gt.ankunft_via,
    gt.verspaetung_minuten,
    gt.losgefahren_am,
    gt.kunden_tracking_token,
    gt.notification_losgefahren_gesendet_am,
    gt.notification_5min_gesendet_am,
    gt.notification_angekommen_gesendet_am,
    gt.ablehnen_token_expires_at,
    gt.final_verbindlich_ab,
    gt.sv_ablehnung_grund,
    gt.sv_ablehnung_am,
    gt.sv_vorgeschlagene_slots,
    gt.typ,
    gt.kanal,
    gt.video_link,
    gt.kb_id,
    gt.notiz_kunde,
    gt.notiz_intern,
    gt.reminder_sent_at,
    gt.reminder_1h_sent_at,
    gt.cancelled_at,
    gt.navigation_started_at,
    gt.sv_unterwegs_seit,
    gt.sv_eta_minuten,
    gt.sv_eta_letzte_berechnung,
    gt.sv_angekommen_am,
    gt.reminder_15min_sent_at,
    gt.reminder_5min_sent_at,
    gt.durchgefuehrt_am,
    gt.kunde_tracking_aktiviert,
    gt.kunde_losgefahren_am,
    gt.kunde_eta_minuten,
    gt.kunde_eta_letzte_berechnung,
    gt.kunde_angekommen_am,
    gt.kunde_verspaetung_gemeldet_am,
    gt.bezahlt,
    gt.honorar_betrag,
    gt.google_event_id,
    gt.google_calendar_id,
    gt.google_event_synced_at,
    gt.kunde_response_token,
    gt.kunde_response_token_expires_at,
    gt.gesehen_am,
    gt.geschaetzte_fahrtzeit_min,
    gt.auftrag_id,
    gt.verlegung_quelle_id,
    gt.verlegung_grund,
    gt.verlegung_kunde_benachrichtigt_an,
    gt.verlegung_eskalation_an_kb_an,
    gt.verlegung_initiator_kunde,
    gt.besichtigung_gestartet_am,
    gt.caldav_object_url,
    gt.caldav_event_uid,
    gt.caldav_synced_at,
    gt.erinnerung_morgen_gesendet,
    gt.sv_lead_id
  FROM gutachter_termine gt
  WHERE gt.fall_id = f.id
    AND gt.status = ANY (ARRAY['bestaetigt'::text, 'verlegung_pending'::text, 'reserviert'::text, 'durchgefuehrt'::text, 'gegenvorschlag'::text])
  ORDER BY
    CASE gt.status
      WHEN 'bestaetigt'::text THEN 1
      WHEN 'verlegung_pending'::text THEN 2
      WHEN 'gegenvorschlag'::text THEN 3
      WHEN 'reserviert'::text THEN 4
      WHEN 'durchgefuehrt'::text THEN 5
      ELSE 6
    END,
    gt.start_zeit DESC NULLS LAST
  LIMIT 1
) t ON true;

-- ---------------------------------------------------------------------------
-- Step 3: Retire the now-functionless sync trigger pair.
-- After PR1, no app code reads/writes the 34 columns on faelle, so the sync is
-- dead weight. Dropping the columns in Step 4 would also break the
-- faelle->claims trigger function (it references the dropped columns), so the
-- triggers and functions must be removed first.
-- ---------------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_sync_faelle_to_claims ON public.faelle;
DROP TRIGGER IF EXISTS trg_sync_claims_to_faelle ON public.claims;
DROP FUNCTION IF EXISTS public.sync_faelle_to_claims();
DROP FUNCTION IF EXISTS public.sync_claims_to_faelle();

-- ---------------------------------------------------------------------------
-- Step 4: Drop the 34 duplicate columns from faelle.
-- claims is the SSoT for all of these (backfilled in Step 1).
-- ---------------------------------------------------------------------------
ALTER TABLE public.faelle
  DROP COLUMN IF EXISTS abgeschlossen_am,
  DROP COLUMN IF EXISTS auslandskennzeichen,
  DROP COLUMN IF EXISTS brn,
  DROP COLUMN IF EXISTS fahrerflucht,
  DROP COLUMN IF EXISTS finanzierung_leasing,
  DROP COLUMN IF EXISTS finanzierungsgeber_adresse,
  DROP COLUMN IF EXISTS finanzierungsgeber_name,
  DROP COLUMN IF EXISTS finanzierungsgeber_vertragsnr,
  DROP COLUMN IF EXISTS gegner_bekannt,
  DROP COLUMN IF EXISTS gegner_versicherung_id,
  DROP COLUMN IF EXISTS gegner_versicherungsnummer,
  DROP COLUMN IF EXISTS gewerbe_flag,
  DROP COLUMN IF EXISTS kanzlei_ansprechpartner_email,
  DROP COLUMN IF EXISTS kanzlei_ansprechpartner_name,
  DROP COLUMN IF EXISTS kanzlei_ansprechpartner_telefon,
  DROP COLUMN IF EXISTS kanzlei_uebergeben_am,
  DROP COLUMN IF EXISTS kunde_email,
  DROP COLUMN IF EXISTS kunden_konstellation,
  DROP COLUMN IF EXISTS kundenbetreuer_id,
  DROP COLUMN IF EXISTS polizei_aktenzeichen,
  DROP COLUMN IF EXISTS polizei_bericht_vorhanden,
  DROP COLUMN IF EXISTS polizei_vor_ort,
  DROP COLUMN IF EXISTS polizeibericht_status,
  DROP COLUMN IF EXISTS sachschaden_beschreibung,
  DROP COLUMN IF EXISTS spezifikation,
  DROP COLUMN IF EXISTS unfall_konstellation,
  DROP COLUMN IF EXISTS unfallskizze_ablehnung_grund,
  DROP COLUMN IF EXISTS unfallskizze_bestaetigt,
  DROP COLUMN IF EXISTS unfallskizze_generiert_am,
  DROP COLUMN IF EXISTS unfallskizze_svg,
  DROP COLUMN IF EXISTS unfallskizze_url,
  DROP COLUMN IF EXISTS vehicle_id,
  DROP COLUMN IF EXISTS vorsteuerabzugsberechtigt,
  DROP COLUMN IF EXISTS zeugen_kontakte;
