-- CMM-44 SP-H PR1 — additive Migration (kein DROP)
-- Block 1: 18x ADD COLUMN auf auftraege
-- Block 2: UPDATE-Backfill auf existierende auftraege-Rows (UPDATE-only, kein INSERT)
-- Block 3: View-Repoint via LATERAL JOIN (3 Views gefunden: faelle_sv_view, v_claim_full,
--          v_faelle_mit_aktuellem_termin)
-- Nach Apply: npx supabase migration repair --status applied 20260520214419
-- Ticket: CMM-44 / Sub-Projekt SP-H
--
-- Live-Messung 2026-05-20 (scripts/cmm44-sph-measure.sql + information_schema.columns):
--   filmcheck_ok:                    bool, nullable=YES, default=false
--   filmcheck_am:                    timestamptz, nullable=YES, default=null
--   filmcheck_notizen:               text, nullable=YES, default=null
--   storniert_am:                    timestamptz, nullable=YES, default=null
--   storno_grund:                    text, nullable=YES, default=null
--   storno_durch_user_id:            uuid, nullable=YES, default=null
--   besichtigung_gestartet_am:       timestamptz, nullable=YES, default=null
--   sv_briefing_text:                text, nullable=YES, default=null
--   sv_briefing_generated_at:        timestamptz, nullable=YES, default=null
--   sv_briefing_model:               text, nullable=YES, default=null
--   sv_briefing_version:             int4, nullable=NO, default=0  (NICHT 1!)
--   sv_briefing_struktur:            jsonb, nullable=YES, default=null
--   sv_notizen_vor_ort:              text, nullable=YES, default=null
--   technische_stellungnahme_status: text, nullable=YES, default='nicht-angefordert' (mit Bindestrich!)
--   technische_stellungnahme_notiz_sv:          text, nullable=YES, default=null
--   technische_stellungnahme_beauftragt_am:     timestamptz, nullable=YES, default=null
--   technische_stellungnahme_hochgeladen_am:    timestamptz, nullable=YES, default=null
--   technische_stellungnahme_freigabe_am:       timestamptz, nullable=YES, default=null

BEGIN;

-- ============================================================
-- Block 1: ADD COLUMN — 18 neue Spalten auf public.auftraege
-- Typ/Default exakt von faelle gespiegelt (Live-Messung 2026-05-20)
-- ============================================================
ALTER TABLE public.auftraege
  ADD COLUMN filmcheck_ok                            boolean DEFAULT false,
  ADD COLUMN filmcheck_am                            timestamptz,
  ADD COLUMN filmcheck_notizen                       text,
  ADD COLUMN storniert_am                            timestamptz,
  ADD COLUMN storno_grund                            text,
  ADD COLUMN storno_durch_user_id                    uuid,
  ADD COLUMN besichtigung_gestartet_am               timestamptz,
  ADD COLUMN sv_briefing_text                        text,
  ADD COLUMN sv_briefing_generated_at                timestamptz,
  ADD COLUMN sv_briefing_model                       text,
  ADD COLUMN sv_briefing_version                     int4 NOT NULL DEFAULT 0,
  ADD COLUMN sv_briefing_struktur                    jsonb,
  ADD COLUMN sv_notizen_vor_ort                      text,
  ADD COLUMN technische_stellungnahme_status         text DEFAULT 'nicht-angefordert',
  ADD COLUMN technische_stellungnahme_notiz_sv       text,
  ADD COLUMN technische_stellungnahme_beauftragt_am  timestamptz,
  ADD COLUMN technische_stellungnahme_hochgeladen_am timestamptz,
  ADD COLUMN technische_stellungnahme_freigabe_am    timestamptz;

-- ============================================================
-- Block 2: UPDATE-Backfill auf existierende auftraege-Rows.
-- Aaron-Entscheidung Option A: nur existierende Rows updaten, keine
-- neuen Auftraege erzeugen. Pre-launch hat 1 von 42 Claims einen Auftrag.
-- Bei 1:N pro Claim schreibt das die Werte in ALLE Auftraege desselben
-- Claims — pre-launch jeweils max. 1 Row, also unkritisch.
-- sv_briefing_version: COALESCE(f.sv_briefing_version, 0) sichert NOT-NULL-Constraint.
-- (faelle.sv_briefing_version ist ebenfalls NOT NULL DEFAULT 0, cov=42/42 — kein Null-Risiko;
--  COALESCE bleibt als Sicherheitsnetz.)
-- ============================================================
UPDATE public.auftraege a SET
  filmcheck_ok                            = f.filmcheck_ok,
  filmcheck_am                            = f.filmcheck_am,
  filmcheck_notizen                       = f.filmcheck_notizen,
  storniert_am                            = f.storniert_am,
  storno_grund                            = f.storno_grund,
  storno_durch_user_id                    = f.storno_durch_user_id,
  besichtigung_gestartet_am               = f.besichtigung_gestartet_am,
  sv_briefing_text                        = f.sv_briefing_text,
  sv_briefing_generated_at                = f.sv_briefing_generated_at,
  sv_briefing_model                       = f.sv_briefing_model,
  sv_briefing_version                     = COALESCE(f.sv_briefing_version, 0),
  sv_briefing_struktur                    = f.sv_briefing_struktur,
  sv_notizen_vor_ort                      = f.sv_notizen_vor_ort,
  technische_stellungnahme_status         = f.technische_stellungnahme_status,
  technische_stellungnahme_notiz_sv       = f.technische_stellungnahme_notiz_sv,
  technische_stellungnahme_beauftragt_am  = f.technische_stellungnahme_beauftragt_am,
  technische_stellungnahme_hochgeladen_am = f.technische_stellungnahme_hochgeladen_am,
  technische_stellungnahme_freigabe_am    = f.technische_stellungnahme_freigabe_am
FROM public.faelle f
WHERE a.claim_id = f.claim_id;

-- ============================================================
-- Block 3: View-Repoint via LATERAL JOIN auf aktuellen Auftrag.
-- View-Audit-Befund 2026-05-20 (scripts/cmm44-sph-views-audit.sql):
--   faelle_sv_view              : 4 SP-H-Spalten aus f.* (technische_stellungnahme_*)
--   v_claim_full                : 1 SP-H-Spalte (f.storniert_am)
--   v_faelle_mit_aktuellem_termin: 17 SP-H-Spalten aus f.*
-- Alle drei werden via LATERAL JOIN auf den aktuellen Auftrag repointet.
-- Spaltenname via AS-Alias unveraendert fuer Backward-Compat.
-- ============================================================

-- ------------------------------------------------------------
-- 3a: faelle_sv_view repoint (4 Spalten: technische_stellungnahme_*)
-- Quelle vorher: f.technische_stellungnahme_*
-- Quelle nachher: cur_auftrag.technische_stellungnahme_*
-- ------------------------------------------------------------
CREATE OR REPLACE VIEW public.faelle_sv_view AS
SELECT f.id,
    f.status,
    c.phase AS aktuelle_phase,
    c.hergang_kunde_text AS schadens_beschreibung,
    c.schadentag AS schadens_datum,
    c.schadenort_adresse AS schadens_adresse,
    c.schadenort_plz::text AS schadens_plz,
    c.schadenort_ort AS schadens_ort,
    f.kennzeichen,
    f.fahrzeug_hersteller,
    f.fahrzeug_modell,
    f.fahrzeug_baujahr,
    g.gutachten_sv_honorar_netto AS gutachter_honorar,
    f.auszahlung_gutachter_eingegangen_am,
    f.eskalation_tag_14_ergebnis,
    f.eskalation_tag_14_ergebnis_am,
    f.eskalation_tag_21_ergebnis,
    f.eskalation_tag_21_ergebnis_am,
    f.eskalation_tag_28_ergebnis,
    f.eskalation_tag_28_ergebnis_am,
    cur_auftrag.technische_stellungnahme_status,
    cur_auftrag.technische_stellungnahme_beauftragt_am,
    cur_auftrag.technische_stellungnahme_hochgeladen_am,
    cur_auftrag.technische_stellungnahme_freigabe_am,
    f.vs_kuerzung_grund,
    f.vs_kuerzungs_typ,
    f.kuerzungs_betrag,
    f.nachbesichtigung_status,
    f.nachbesichtigung_termin_datum,
    f.nachbesichtigung_sv_konfrontation_gewuenscht,
    f.nachbesichtigung_sv_termin_vereinbart_am,
    f.vs_reaktion_typ,
    f.vs_reaktion_am,
    f.besichtigungsort_adresse,
    f.sv_id,
    f.kunde_id,
    c.claim_nummer
FROM public.faelle f
    LEFT JOIN public.claims c ON c.id = f.claim_id
    LEFT JOIN public.gutachten g ON g.claim_id = c.id
    LEFT JOIN LATERAL (
        SELECT a.technische_stellungnahme_status,
               a.technische_stellungnahme_beauftragt_am,
               a.technische_stellungnahme_hochgeladen_am,
               a.technische_stellungnahme_freigabe_am
        FROM public.auftraege a
        WHERE a.claim_id = c.id
        ORDER BY a.reihenfolge DESC
        LIMIT 1
    ) cur_auftrag ON true;

-- ------------------------------------------------------------
-- 3b: v_claim_full repoint (1 Spalte: storniert_am)
-- Quelle vorher: f.storniert_am
-- Quelle nachher: cur_auftrag.storniert_am
-- Alle anderen f.* und c.* Spalten bleiben unveraendert.
-- ------------------------------------------------------------
CREATE OR REPLACE VIEW public.v_claim_full AS
SELECT c.id,
    c.vehicle_id,
    c.schadentag,
    c.schadenzeit,
    c.entdeckt_am,
    c.schadenort_adresse,
    c.schadenort_plz,
    c.schadenort_ort,
    c.schadenort_land,
    c.schadenort_lat,
    c.schadenort_lng,
    c.schadenort_kategorie,
    c.hergang_kunde_text,
    c.hergang_sv_text,
    c.schadenart,
    c.fall_typ,
    c.unfall_konstellation,
    c.fahrerflucht,
    c.auslandskennzeichen,
    c.polizei_aktenzeichen,
    c.polizei_bericht_vorhanden,
    c.polizei_vor_ort,
    c.polizeibericht_status,
    c.geschaedigter_user_id,
    c.gegnerisches_vehicle_id,
    c.gegner_versicherung_id,
    c.gegner_versicherungsnummer,
    c.gegner_aktenzeichen,
    c.gegner_bekannt,
    c.anzahl_beteiligte_total,
    c.hat_personenschaden,
    c.hat_mietwagen,
    c.hat_nutzungsausfall,
    c.hat_sachschaden,
    c.hat_abschleppung,
    c.sachschaden_beschreibung,
    c.halter_ungleich_fahrer,
    c.kunden_konstellation,
    c.unfallskizze_url,
    c.unfallskizze_svg,
    c.unfallskizze_bestaetigt,
    c.unfallskizze_ablehnung_grund,
    c.unfallskizze_generiert_am,
    c.status,
    c.abgeschlossen_am,
    c.verjaehrt_am,
    c.created_at,
    c.updated_at,
    c.created_by_user_id,
    c.created_via,
    c.claim_nummer,
    c.lead_id,
    c.kundenbetreuer_id,
    c.phase,
    c.vs_ablehnungs_grund,
    c.regulierungs_betrag,
    c.endzustand_gesetzt_durch_user_id,
    c.endzustand_gesetzt_am,
    c.endzustand_grund,
    c.kanzlei_wunsch,
    c.kanzlei_wunsch_gefragt_am,
    c.kanzlei_wunsch_gefragt_in_phase,
    f.id AS fall_id,
    f.sv_id,
    c.service_typ,
    f.status AS fall_status,
    f.created_at AS fall_created_at,
    f.updated_at AS fall_updated_at,
    c.kundenbetreuer_fallback_flag,
    c.phase AS aktuelle_phase,
    c.szenario,
    c.dokumente_vollstaendig_fuer_phase,
    c.dokumente_reminder_whatsapp_letzte_sendung,
    f.no_show_gemeldet_am,
    f.re_termin_token,
    c.sa_unterschrieben_am,
    c.vollmacht_signiert_am,
    f.mandatsnummer,
    f.re_termin_token_eingelaufen_am,
    f.re_termin_eskalation_an_kb_am,
    cur_auftrag.storniert_am,
    f.anschlussschreiben_am,
    f.vs_eskalationsstufe,
    f.kennzeichen,
    f.fahrzeug_hersteller,
    f.fahrzeug_modell,
    f.fahrzeug_typ,
    c.sa_unterschrieben,
    f.regulierung_am,
    c.regulierungs_betrag AS regulierung_betrag,
    g.gesamt_schadensbetrag::numeric(10,2) AS gutachten_betrag,
    g.fertiggestellt_am AS gutachten_eingegangen_am,
    c.sv_zugewiesen_am,
    c.schadens_ursache,
    c.schadenort_plz::text AS schadens_plz,
    c.schadenort_ort AS schadens_ort,
    c.fall_typ AS schadens_fall_typ,
    f.gegner_anzahl_beteiligte,
    f.gegner_fahrzeugtyp,
    f.organisation_id,
    f.dispatch_id,
    f.kunde_id,
    c.ist_aktiv,
    c.deaktiviert_grund,
    f.hat_vorschaeden,
    f.vorschaden_anzahl,
    f.vorschaden_letzter_datum,
    f.vorschaden_typ_b_bericht,
    f.cardentity_abfrage_am,
    f.besichtigungsort_adresse,
    f.besichtigungsort_lat,
    f.besichtigungsort_lng,
    f.besichtigungsort_notiz,
    f.besichtigungsort_place_id,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cp.*) ORDER BY cp.reihenfolge, cp.created_at) AS jsonb_agg
           FROM public.claim_parties cp
          WHERE cp.claim_id = c.id), '[]'::jsonb) AS parties,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cvi.*) ORDER BY cvi.reihenfolge, cvi.created_at) AS jsonb_agg
           FROM public.claim_vehicle_involvements cvi
          WHERE cvi.claim_id = c.id), '[]'::jsonb) AS vehicle_involvements,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cp2.*) ORDER BY cp2.created_at) AS jsonb_agg
           FROM public.claim_payments cp2
          WHERE cp2.claim_id = c.id), '[]'::jsonb) AS payments,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cm.*) ORDER BY cm.created_at) AS jsonb_agg
           FROM public.claim_mietwagen cm
          WHERE cm.claim_id = c.id), '[]'::jsonb) AS mietwagen,
    COALESCE(( SELECT jsonb_agg(to_jsonb(vk.*) ORDER BY vk.datum) AS jsonb_agg
           FROM public.vs_korrespondenz vk
          WHERE vk.claim_id = c.id), '[]'::jsonb) AS vs_korrespondenz,
    COALESCE(( SELECT jsonb_agg(to_jsonb(r.*) ORDER BY r.created_at) AS jsonb_agg
           FROM public.repairs r
          WHERE r.claim_id = c.id), '[]'::jsonb) AS repairs
FROM public.claims c
    LEFT JOIN public.faelle f ON f.claim_id = c.id
    LEFT JOIN public.gutachten g ON g.claim_id = c.id
    LEFT JOIN LATERAL (
        SELECT a.storniert_am
        FROM public.auftraege a
        WHERE a.claim_id = c.id
        ORDER BY a.reihenfolge DESC
        LIMIT 1
    ) cur_auftrag ON true;

-- ------------------------------------------------------------
-- 3c: v_faelle_mit_aktuellem_termin repoint (17 SP-H-Spalten)
-- Quelle vorher: f.* fuer alle 17 Spalten
-- Quelle nachher: cur_auftrag.* via LATERAL JOIN auf aktuellen Auftrag
-- Hinweis: besichtigung_gestartet_am war bereits aus gutachter_termine (t.*)
-- und ist NICHT in der View-Audit-Trefferliste — es bleibt unveraendert.
-- Die 17 repointeten Spalten sind:
--   filmcheck_ok, filmcheck_am, filmcheck_notizen,
--   storniert_am, storno_grund, storno_durch_user_id,
--   sv_briefing_text, sv_briefing_generated_at, sv_briefing_model,
--   sv_briefing_version, sv_briefing_struktur, sv_notizen_vor_ort,
--   technische_stellungnahme_status, technische_stellungnahme_notiz_sv,
--   technische_stellungnahme_beauftragt_am, technische_stellungnahme_hochgeladen_am,
--   technische_stellungnahme_freigabe_am
-- ------------------------------------------------------------
CREATE OR REPLACE VIEW public.v_faelle_mit_aktuellem_termin AS
SELECT f.id,
    f.lead_id,
    f.kunde_id,
    f.status,
    c.betreuungspaket,
    c.hergang_kunde_text AS schadens_beschreibung,
    c.schadentag AS schadens_datum,
    c.entdeckt_am AS schadens_entdeckt_am,
    c.schadenort_adresse AS schadens_adresse,
    c.schadenort_plz::text AS schadens_plz,
    c.schadenort_ort AS schadens_ort,
    c.abtretung_pdf,
    c.vollmacht_pdf,
    c.abtretung_signiert_am,
    c.vollmacht_signiert_am,
    f.sv_id,
    c.sv_zugewiesen_am,
    g.fertiggestellt_am AS gutachten_eingegangen_am,
    g.gesamt_schadensbetrag::numeric(10,2) AS gutachten_betrag,
    c.kanzlei_uebergeben_am,
    f.anschlussschreiben_am,
    c.regulierungs_betrag AS regulierung_betrag,
    f.regulierung_am,
    cur_auftrag.filmcheck_ok,
    cur_auftrag.filmcheck_am,
    cur_auftrag.filmcheck_notizen,
    c.notizen,
    f.created_at,
    f.updated_at,
    c.fall_typ AS schadens_fall_typ,
    c.kunden_konstellation,
    f.kennzeichen,
    f.fahrzeug_typ,
    f.fahrzeug_hersteller,
    f.fahrzeug_modell,
    f.fahrzeug_baujahr,
    f.gegner_name,
    f.gegner_versicherung,
    f.gegner_kennzeichen,
    c.gegner_bekannt,
    c.polizei_aktenzeichen,
    c.polizei_bericht_vorhanden,
    c.hat_personenschaden AS personenschaden_flag,
    c.hat_mietwagen AS mietwagen_flag,
    c.gewerbe_flag,
    c.halter_ungleich_fahrer AS halter_ungleich_fahrer_flag,
    f.ust_id,
    f.leasinggeber_name,
    c.leasinggeber_informiert,
    f.bank_name,
    c.prioritaet,
    c.onboarding_complete,
    f.dispatch_id,
    c.kundenbetreuer_id,
    f.konvertiert_am,
    c.lead_id AS konvertiert_von_lead,
    c.status_changed_at,
    f.regulierung_angekuendigt_am,
    f.zahlung_eingegangen_am,
    c.abgeschlossen_am,
    c.google_review_gesendet,
    f.vs_eskalationsstufe,
    f.fin_quelle,
    f.fin_extrahiert_am,
    f.vorschaden_geprueft,
    f.vorschaden_anzahl,
    f.vorschaden_letzter_datum,
    f.vorschaden_typ_a_ergebnis,
    f.vorschaden_typ_b_bericht,
    f.vorschaden_typ_b_pdf_url,
    f.cardentity_abfrage_am,
    c.schadens_hoehe_netto,
    g.gutachten_nutzungsausfall_tagessatz_eur::numeric(10,2) AS nutzungsausfall_tagessatz,
    g.wiederbeschaffungsdauer_tage AS reparaturdauer_tage,
    g.gutachten_sv_honorar_netto AS gutachter_honorar,
    g.ocr_finished_at AS ocr_extrahiert_am,
    g.gutachten_ocr_raw AS ocr_rohdaten,
    g.ki_kalkulation,
    g.ki_kalkulation_am,
    g.ki_geschaetzte_kosten_min::numeric(10,2) AS ki_geschaetzte_kosten_min,
    g.ki_geschaetzte_kosten_max::numeric(10,2) AS ki_geschaetzte_kosten_max,
    c.kanzlei_ansprechpartner_name,
    c.kanzlei_ansprechpartner_email,
    c.kanzlei_ansprechpartner_telefon,
    c.kanzlei_ansprechpartner_position,
    f.mandatsnummer,
    f.losfahren_erinnerung_gesendet,
    f.termin_erinnerung_5min_gesendet,
    f.geschaetzte_fahrzeit_min,
    f.geschaetzte_fahrdistanz_km,
    f.gcal_event_id,
    g.id IS NOT NULL AS gutachten_vorhanden,
    g.pdf_uploaded_at AS gutachten_hochgeladen_am,
    g.positionen AS gutachten_positionen,
    g.auftragsnummer AS gutachten_nummer,
    g.reparaturkosten_netto AS reparaturkosten,
    g.minderwert AS wertminderung,
    (g.gutachten_nutzungsausfall_tagessatz_eur * g.nutzungsausfall_tage::numeric)::numeric(10,2) AS nutzungsausfall_gesamt,
    f.regulierungsweise,
    c.gegner_versicherungsnummer,
    c.sa_unterschrieben,
    c.sa_unterschrieben_am,
    c.sa_pdf_url,
    c.sa_unterschrift_url,
    c.datenschutz_akzeptiert,
    c.datenschutz_akzeptiert_am,
    c.vollmacht_status,
    c.polizei_vor_ort,
    c.hergang_kunde_text AS unfallhergang,
    c.unfallmitteilung_status,
    c.schadenort_adresse AS unfallort,
    c.schadentag AS unfalldatum,
    c.interne_notizen,
    f.anschlussschreiben_url,
    f.anschlussschreiben_sendedatum,
    f.anschlussschreiben_unterschrift,
    f.anschlussschreiben_ocr_am,
    f.besichtigungsort_adresse,
    f.besichtigungsort_lat,
    f.besichtigungsort_lng,
    f.besichtigungsort_place_id,
    c.ist_aktiv,
    c.deaktiviert_am,
    c.deaktiviert_grund,
    c.deaktiviert_notiz,
    c.szenario,
    f.ruege_erhalten_am,
    f.ruege_grund,
    f.fahrzeug_farbe,
    f.erstzulassung,
    f.kilometerstand,
    f.firma_name,
    f.marketing_quelle,
    f.marketing_provision,
    f.marketing_provision_status,
    NULL::numeric(10,2) AS gutachten_stundensatz,
    f.kanzlei_id,
    f.kanzlei_honorar,
    f.zahlung_erwartet_am,
    f.zahlung_betrag,
    f.lead_preis_netto,
    f.lead_preis_typ,
    f.lead_preis_berechnet_am,
    f.guthaben_verrechnet_netto,
    f.sv_nachzahlung_netto,
    f.abrechnung_id,
    cur_auftrag.storniert_am,
    cur_auftrag.storno_grund,
    cur_auftrag.storno_durch_user_id,
    f.no_show_gemeldet_am,
    c.spezifikation,
    c.schadenart AS schadens_art,
    f.organisation_id,
    c.phase AS aktuelle_phase,
    c.dokumente_vollstaendig_fuer_phase,
    c.dokumente_vollstaendig_am_phase,
    c.unfall_konstellation,
    f.gegner_anzahl_beteiligte,
    f.gegner_fahrzeugtyp,
    c.dokumente_reminder_whatsapp_letzte_sendung,
    f.fin_vin,
    f.source_channel,
    f.source_domain,
    c.schadens_ursache,
    f.kanzlei_abrechnung_id,
    f.kanzlei_provision_status,
    f.kanzlei_provision_ausgezahlt_am,
    c.service_typ,
    f.vs_reaktion_typ,
    f.vs_reaktion_am,
    c.vs_ablehnungs_grund AS vs_ablehnungsgrund,
    f.ruege_gesendet_am,
    f.ruege_betrag,
    c.kunde_no_show_count AS no_show_count,
    f.kuerzungs_betrag,
    f.vs_frist_bis,
    f.ruege_counter,
    f.schlussabrechnung_am,
    f.iban,
    f.bic,
    f.kontoinhaber,
    f.bankdaten_hinterlegt_am,
    f.ist_fahrzeughalter,
    c.finanzierung_leasing,
    c.vorsteuerabzugsberechtigt,
    c.hergang_kunde_text AS schadens_hergang,
    f.halter_vorname,
    f.halter_nachname,
    f.halter_strasse,
    f.halter_plz,
    f.halter_stadt,
    f.halter_telefon,
    f.halter_email,
    c.finanzierungsgeber_name,
    c.finanzierungsgeber_adresse,
    c.finanzierungsgeber_vertragsnr,
    f.zahlungsweg,
    f.hat_vorschaeden,
    f.vorschaeden_beschreibung,
    cur_auftrag.technische_stellungnahme_status,
    cur_auftrag.technische_stellungnahme_beauftragt_am,
    cur_auftrag.technische_stellungnahme_hochgeladen_am,
    cur_auftrag.technische_stellungnahme_freigabe_am,
    f.nachbesichtigung_status,
    f.nachbesichtigung_angefordert_am,
    f.nachbesichtigung_termin_datum,
    f.nachbesichtigung_konfrontation,
    f.as_geforderte_summe,
    f.as_frist,
    f.as_vs_reaktion_text,
    f.as_salesforce_id,
    f.as_zuletzt_synced_am,
    f.lexdrive_case_id,
    f.eskalation_tag_14_am,
    f.eskalation_tag_21_am,
    f.eskalation_tag_28_am,
    c.schadenort_kategorie AS unfallort_kategorie,
    c.unfallskizze_url,
    f.fahrzeug_ausstattung,
    f.cardentity_enriched_at,
    f.cardentity_report,
    c.vollmacht_geprueft_am,
    c.vollmacht_geprueft_von,
    c.vollmacht_pruefung_status,
    c.vollmacht_pruefung_begruendung,
    f.lexdrive_ocr_data,
    f.lexdrive_ocr_received_at,
    f.vs_kuerzung_grund,
    c.geschlossen_grund,
    f.nachbesichtigung_ergebnis,
    c.bevorzugter_kanal,
    c.gegner_versicherung_id,
    c.zeugen_kontakte,
    c.werkstatt_seit_datum,
    c.fahrzeug_fahrbereit,
    c.hat_nutzungsausfall AS nutzungsausfall,
    f.mietwagen_kanzlei_informiert,
    f.mietwagen_kanzlei_informiert_am,
    f.halter_geburtsdatum,
    c.abrechnungsart_besprochen,
    c.abrechnungsart_notiz,
    c.abrechnungsart_besprochen_am,
    f.gegner_versicherung_anfrage_datum,
    c.sprache,
    c.unfallskizze_svg,
    c.unfallskizze_bestaetigt,
    c.unfallskizze_ablehnung_grund,
    c.unfallskizze_generiert_am,
    c.zeugen_vorhanden,
    f.vorschaden_erkannt,
    f.sv_termin_dokument_reminder_gesendet_am,
    c.kundenbetreuer_fallback_flag,
    c.kundenbetreuer_zugewiesen_am,
    cur_auftrag.sv_briefing_text,
    cur_auftrag.sv_briefing_generated_at,
    cur_auftrag.sv_briefing_model,
    cur_auftrag.sv_briefing_version,
    cur_auftrag.sv_briefing_struktur,
    cur_auftrag.sv_notizen_vor_ort,
    c.makler_id,
    c.hat_sachschaden AS sachschaden_flag,
    c.sachschaden_beschreibung,
    c.gegner_aktenzeichen AS gegner_schadennummer,
    f.halter_name,
    f.wunschtermin,
    f.vs_quote_prozent,
    f.vs_quote_grund,
    f.vs_quote_akzeptiert_am,
    f.vs_quote_betrag_ausgezahlt,
    f.vs_kuerzungs_typ,
    f.auszahlung_kunde_betrag,
    f.auszahlung_kunde_eingegangen_am,
    f.auszahlung_gutachter_eingegangen_am,
    f.auszahlung_zahlungsweg,
    f.eskalation_tag_14_ergebnis,
    f.eskalation_tag_14_ergebnis_am,
    f.eskalation_tag_14_ergebnis_von,
    f.eskalation_tag_21_ergebnis,
    f.eskalation_tag_21_ergebnis_am,
    f.eskalation_tag_21_ergebnis_von,
    f.eskalation_tag_28_ergebnis,
    f.eskalation_tag_28_ergebnis_am,
    f.eskalation_tag_28_ergebnis_von,
    f.nachbesichtigung_kunde_termin_vorschlaege,
    f.nachbesichtigung_kunde_termin_eingereicht_am,
    f.nachbesichtigung_sv_konfrontation_gewuenscht,
    f.nachbesichtigung_sv_termin_vereinbart_am,
    f.auszahlung_gutachter_betrag,
    f.ruege_frist_tage,
    f.klage_uebergeben_am,
    c.fallakte_angelegt_am,
    f.kunde_vorname,
    f.kunde_nachname,
    f.kunde_telefon,
    c.kunde_email,
    f.kunde_strasse,
    f.kunde_plz,
    f.kunde_stadt,
    f.kunde_adresse,
    f.kunde_lat,
    f.kunde_lng,
    f.hsn,
    f.tsn,
    cur_auftrag.technische_stellungnahme_notiz_sv,
    c.fahrerflucht,
    c.auslandskennzeichen,
    c.polizeibericht_status,
    c.zb1_status,
    c.schadenzeit::text AS unfall_uhrzeit,
    c.schadenort_lat::numeric AS unfallort_lat,
    c.schadenort_lng::numeric AS unfallort_lng,
    c.bkat_unfallart,
    c.fahrzeugschaden_beschreibung,
    c.hat_mietwagen AS mietwagen_hat,
    c.mietwagen_seit_datum,
    c.mietwagen_limit_tage,
    c.mietwagen_limit_grund,
    c.mietwagen_rechnung_vorhanden,
    c.mietwagen_rechnung_url,
    c.mietwagen_argumentations_puffer,
    c.mietwagen_vermieter,
    c.vehicle_id,
    f.claim_id,
    f.lackfarbe_code,
    t.id AS aktueller_termin_id,
    t.start_zeit AS aktueller_termin_start,
    t.end_zeit AS aktueller_termin_end,
    t.status AS aktueller_termin_status,
    t.sv_id AS aktueller_termin_sv_id,
    t.kanal AS aktueller_termin_kanal,
    t.typ AS aktueller_termin_typ,
    t.final_verbindlich_ab AS aktueller_termin_final_verbindlich_ab,
    t.start_zeit AS sv_termin,
    t.status AS gutachter_termin_status,
    t.status = 'bestaetigt'::text AS gutachter_termin_bestaetigt,
    t.vorgeschlagenes_datum AS gutachter_gegenvorschlag_datum,
    t.gegenvorschlag_grund AS gutachter_gegenvorschlag_grund,
    c.claim_nummer
FROM public.faelle f
    LEFT JOIN public.claims c ON c.id = f.claim_id
    LEFT JOIN public.gutachten g ON g.claim_id = c.id
    LEFT JOIN LATERAL ( SELECT gt.id,
            gt.sv_id,
            gt.fall_id,
            gt.start_zeit,
            gt.end_zeit,
            gt.status,
            gt.externer_kalender_id,
            gt.ablehnungsgrund,
            gt.gegenvorschlag_zeit,
            gt.created_at,
            gt.erinnerung_24h_gesendet,
            gt.erinnerung_2h_gesendet,
            gt.erinnerung_48h_docs_gesendet,
            gt.ankunft_zeit,
            gt.abschluss_zeit,
            gt.uebersprungen,
            gt.uebersprung_grund,
            gt.notizen_vor_ort,
            gt.gps_lat_ankunft,
            gt.gps_lng_ankunft,
            gt.lead_id,
            gt.ablehnen_token,
            gt.abgelehnt_am,
            gt.abgelehnt_grund,
            gt.vorgeschlagenes_datum,
            gt.gegenvorschlag_grund,
            gt.gegenvorschlag_von,
            gt.ankunft_via,
            gt.verspaetung_minuten,
            gt.losgefahren_am,
            gt.kunden_tracking_token,
            gt.notification_losgefahren_gesendet_am,
            gt.notification_5min_gesendet_am,
            gt.notification_angekommen_gesendet_am,
            gt.ablehnen_token_expires_at,
            gt.final_verbindlich_ab,
            gt.sv_ablehnung_grund,
            gt.sv_ablehnung_am,
            gt.sv_vorgeschlagene_slots,
            gt.typ,
            gt.kanal,
            gt.video_link,
            gt.kb_id,
            gt.notiz_kunde,
            gt.notiz_intern,
            gt.reminder_sent_at,
            gt.reminder_1h_sent_at,
            gt.cancelled_at,
            gt.navigation_started_at,
            gt.sv_unterwegs_seit,
            gt.sv_eta_minuten,
            gt.sv_eta_letzte_berechnung,
            gt.sv_angekommen_am,
            gt.reminder_15min_sent_at,
            gt.reminder_5min_sent_at,
            gt.durchgefuehrt_am,
            gt.kunde_tracking_aktiviert,
            gt.kunde_losgefahren_am,
            gt.kunde_eta_minuten,
            gt.kunde_eta_letzte_berechnung,
            gt.kunde_angekommen_am,
            gt.kunde_verspaetung_gemeldet_am,
            gt.bezahlt,
            gt.honorar_betrag,
            gt.google_event_id,
            gt.google_calendar_id,
            gt.google_event_synced_at,
            gt.kunde_response_token,
            gt.kunde_response_token_expires_at,
            gt.gesehen_am,
            gt.geschaetzte_fahrtzeit_min,
            gt.auftrag_id,
            gt.verlegung_quelle_id,
            gt.verlegung_grund,
            gt.verlegung_kunde_benachrichtigt_an,
            gt.verlegung_eskalation_an_kb_an,
            gt.verlegung_initiator_kunde,
            gt.besichtigung_gestartet_am,
            gt.caldav_object_url,
            gt.caldav_event_uid,
            gt.caldav_synced_at,
            gt.erinnerung_morgen_gesendet,
            gt.sv_lead_id
           FROM public.gutachter_termine gt
          WHERE gt.fall_id = f.id AND (gt.status = ANY (ARRAY['bestaetigt'::text, 'verlegung_pending'::text, 'reserviert'::text, 'durchgefuehrt'::text, 'gegenvorschlag'::text]))
          ORDER BY (
                CASE gt.status
                    WHEN 'bestaetigt'::text THEN 1
                    WHEN 'verlegung_pending'::text THEN 2
                    WHEN 'gegenvorschlag'::text THEN 3
                    WHEN 'reserviert'::text THEN 4
                    WHEN 'durchgefuehrt'::text THEN 5
                    ELSE 6
                END), gt.start_zeit DESC NULLS LAST
         LIMIT 1) t ON true
    LEFT JOIN LATERAL (
        SELECT a.filmcheck_ok,
               a.filmcheck_am,
               a.filmcheck_notizen,
               a.storniert_am,
               a.storno_grund,
               a.storno_durch_user_id,
               a.sv_briefing_text,
               a.sv_briefing_generated_at,
               a.sv_briefing_model,
               a.sv_briefing_version,
               a.sv_briefing_struktur,
               a.sv_notizen_vor_ort,
               a.technische_stellungnahme_status,
               a.technische_stellungnahme_notiz_sv,
               a.technische_stellungnahme_beauftragt_am,
               a.technische_stellungnahme_hochgeladen_am,
               a.technische_stellungnahme_freigabe_am
        FROM public.auftraege a
        WHERE a.claim_id = c.id
        ORDER BY a.reihenfolge DESC
        LIMIT 1
    ) cur_auftrag ON true;

COMMIT;
