-- CMM-44 SP-B PR1 — additive Migration (kein DROP)
-- Legt 64 claim-globale Spalten auf public.claims an (gespiegelt von public.faelle).
-- Backfill: claims <- faelle via claim_id.
-- Block 3: View-Repoint für v_claim_full, v_claim_listing, v_faelle_mit_aktuellem_termin
--           (v_claim_parties_safe: ist_aktiv kommt aus claim_parties, kein Repoint nötig).
-- Nach Apply: npx supabase migration repair --status applied 20260518015652
-- Ticket: CMM-44 / Sub-Projekt SP-B

BEGIN;

-- ============================================================
-- Block 1: ADD COLUMN — 64 Spalten auf public.claims
-- Typ / NULL / Default 1:1 von faelle gespiegelt (Live-Messung 2026-05-18)
-- ============================================================

ALTER TABLE public.claims
  ADD COLUMN makler_id uuid,
  ADD COLUMN betreuungspaket public.betreuungspaket DEFAULT 'vollservice',
  ADD COLUMN notizen text,
  ADD COLUMN prioritaet text DEFAULT 'normal',
  ADD COLUMN onboarding_complete boolean DEFAULT false,
  ADD COLUMN status_changed_at timestamptz DEFAULT now(),
  ADD COLUMN google_review_gesendet boolean DEFAULT false,
  ADD COLUMN datenschutz_akzeptiert boolean DEFAULT false,
  ADD COLUMN datenschutz_akzeptiert_am timestamptz,
  ADD COLUMN interne_notizen text,
  ADD COLUMN ist_aktiv boolean DEFAULT true,
  ADD COLUMN deaktiviert_am timestamptz,
  ADD COLUMN deaktiviert_grund text,
  ADD COLUMN deaktiviert_notiz text,
  ADD COLUMN szenario text DEFAULT 'normalfall',
  ADD COLUMN service_typ text NOT NULL DEFAULT 'komplett',
  ADD COLUMN geschlossen_grund text,
  ADD COLUMN bevorzugter_kanal text,
  ADD COLUMN sprache text DEFAULT 'de',
  ADD COLUMN fallakte_angelegt_am timestamptz,
  ADD COLUMN google_review_prompt_gezeigt_am timestamptz,
  ADD COLUMN sv_zugewiesen_am timestamptz,
  ADD COLUMN kundenbetreuer_fallback_flag boolean NOT NULL DEFAULT false,
  ADD COLUMN kundenbetreuer_zugewiesen_am timestamptz,
  ADD COLUMN eskaliert_an_admin_id uuid,
  ADD COLUMN eskaliert_am timestamptz,
  ADD COLUMN eskaliert_grund text,
  ADD COLUMN abtretung_pdf text,
  ADD COLUMN vollmacht_pdf text,
  ADD COLUMN abtretung_signiert_am timestamptz,
  ADD COLUMN vollmacht_signiert_am timestamptz,
  ADD COLUMN sa_unterschrieben boolean DEFAULT false,
  ADD COLUMN sa_unterschrieben_am timestamptz,
  ADD COLUMN sa_pdf_url text,
  ADD COLUMN sa_unterschrift_url text,
  ADD COLUMN vollmacht_status text DEFAULT 'ausstehend',
  ADD COLUMN vollmacht_geprueft_am timestamptz,
  ADD COLUMN vollmacht_geprueft_von text,
  ADD COLUMN vollmacht_pruefung_status text,
  ADD COLUMN vollmacht_pruefung_begruendung text,
  ADD COLUMN mietwagen_seit_datum date,
  ADD COLUMN mietwagen_limit_tage integer,
  ADD COLUMN mietwagen_limit_grund text,
  ADD COLUMN mietwagen_rechnung_vorhanden boolean NOT NULL DEFAULT false,
  ADD COLUMN mietwagen_rechnung_url text,
  ADD COLUMN mietwagen_argumentations_puffer integer NOT NULL DEFAULT 3,
  ADD COLUMN mietwagen_vermieter text,
  ADD COLUMN schadens_hoehe_netto numeric(10,2),
  ADD COLUMN schadens_ursache text,
  ADD COLUMN zeugen_vorhanden boolean NOT NULL DEFAULT false,
  ADD COLUMN bkat_unfallart public.bkat_unfallart,
  ADD COLUMN werkstatt_seit_datum date,
  ADD COLUMN fahrzeug_fahrbereit boolean,
  ADD COLUMN fahrzeugschaden_beschreibung text,
  ADD COLUMN abrechnungsart_besprochen text,
  ADD COLUMN abrechnungsart_notiz text,
  ADD COLUMN abrechnungsart_besprochen_am timestamptz,
  ADD COLUMN unfallmitteilung_status text DEFAULT 'nicht_erforderlich',
  ADD COLUMN dokumente_vollstaendig_fuer_phase text,
  ADD COLUMN dokumente_vollstaendig_am_phase timestamptz,
  ADD COLUMN dokumente_reminder_whatsapp_letzte_sendung timestamptz,
  ADD COLUMN zb1_status text,
  ADD COLUMN kanzlei_ansprechpartner_position text,
  ADD COLUMN leasinggeber_informiert boolean DEFAULT false;

-- ============================================================
-- Block 2: Initial-Backfill — claims <- faelle (via claim_id)
-- Alle Bestands-Claims werden befüllt.
-- ============================================================

UPDATE public.claims c
SET
  makler_id                                    = f.makler_id,
  betreuungspaket                              = f.betreuungspaket,
  notizen                                      = f.notizen,
  prioritaet                                   = f.prioritaet,
  onboarding_complete                          = f.onboarding_complete,
  status_changed_at                            = f.status_changed_at,
  google_review_gesendet                       = f.google_review_gesendet,
  datenschutz_akzeptiert                       = f.datenschutz_akzeptiert,
  datenschutz_akzeptiert_am                    = f.datenschutz_akzeptiert_am,
  interne_notizen                              = f.interne_notizen,
  ist_aktiv                                    = f.ist_aktiv,
  deaktiviert_am                               = f.deaktiviert_am,
  deaktiviert_grund                            = f.deaktiviert_grund,
  deaktiviert_notiz                            = f.deaktiviert_notiz,
  szenario                                     = f.szenario,
  service_typ                                  = f.service_typ,
  geschlossen_grund                            = f.geschlossen_grund,
  bevorzugter_kanal                            = f.bevorzugter_kanal,
  sprache                                      = f.sprache,
  fallakte_angelegt_am                         = f.fallakte_angelegt_am,
  google_review_prompt_gezeigt_am              = f.google_review_prompt_gezeigt_am,
  sv_zugewiesen_am                             = f.sv_zugewiesen_am,
  kundenbetreuer_fallback_flag                 = f.kundenbetreuer_fallback_flag,
  kundenbetreuer_zugewiesen_am                 = f.kundenbetreuer_zugewiesen_am,
  eskaliert_an_admin_id                        = f.eskaliert_an_admin_id,
  eskaliert_am                                 = f.eskaliert_am,
  eskaliert_grund                              = f.eskaliert_grund,
  abtretung_pdf                                = f.abtretung_pdf,
  vollmacht_pdf                                = f.vollmacht_pdf,
  abtretung_signiert_am                        = f.abtretung_signiert_am,
  vollmacht_signiert_am                        = f.vollmacht_signiert_am,
  sa_unterschrieben                            = f.sa_unterschrieben,
  sa_unterschrieben_am                         = f.sa_unterschrieben_am,
  sa_pdf_url                                   = f.sa_pdf_url,
  sa_unterschrift_url                          = f.sa_unterschrift_url,
  vollmacht_status                             = f.vollmacht_status,
  vollmacht_geprueft_am                        = f.vollmacht_geprueft_am,
  vollmacht_geprueft_von                       = f.vollmacht_geprueft_von,
  vollmacht_pruefung_status                    = f.vollmacht_pruefung_status,
  vollmacht_pruefung_begruendung               = f.vollmacht_pruefung_begruendung,
  mietwagen_seit_datum                         = f.mietwagen_seit_datum,
  mietwagen_limit_tage                         = f.mietwagen_limit_tage,
  mietwagen_limit_grund                        = f.mietwagen_limit_grund,
  mietwagen_rechnung_vorhanden                 = f.mietwagen_rechnung_vorhanden,
  mietwagen_rechnung_url                       = f.mietwagen_rechnung_url,
  mietwagen_argumentations_puffer              = f.mietwagen_argumentations_puffer,
  mietwagen_vermieter                          = f.mietwagen_vermieter,
  schadens_hoehe_netto                         = f.schadens_hoehe_netto,
  schadens_ursache                             = f.schadens_ursache,
  zeugen_vorhanden                             = f.zeugen_vorhanden,
  bkat_unfallart                               = f.bkat_unfallart,
  werkstatt_seit_datum                         = f.werkstatt_seit_datum,
  fahrzeug_fahrbereit                          = f.fahrzeug_fahrbereit,
  fahrzeugschaden_beschreibung                 = f.fahrzeugschaden_beschreibung,
  abrechnungsart_besprochen                    = f.abrechnungsart_besprochen,
  abrechnungsart_notiz                         = f.abrechnungsart_notiz,
  abrechnungsart_besprochen_am                 = f.abrechnungsart_besprochen_am,
  unfallmitteilung_status                      = f.unfallmitteilung_status,
  dokumente_vollstaendig_fuer_phase            = f.dokumente_vollstaendig_fuer_phase,
  dokumente_vollstaendig_am_phase              = f.dokumente_vollstaendig_am_phase,
  dokumente_reminder_whatsapp_letzte_sendung   = f.dokumente_reminder_whatsapp_letzte_sendung,
  zb1_status                                   = f.zb1_status,
  kanzlei_ansprechpartner_position             = f.kanzlei_ansprechpartner_position,
  leasinggeber_informiert                      = f.leasinggeber_informiert
FROM public.faelle f
WHERE f.claim_id = c.id;

-- ============================================================
-- Block 3: View-Repoint
-- Betroffene Views (SP-B-Spalten kamen aus f.<col>):
--   - v_claim_full         (12 SP-B-Spalten aus f.)
--   - v_claim_listing      (1 SP-B-Spalte aus f.)
--   - v_faelle_mit_aktuellem_termin (60 SP-B-Spalten aus f.)
-- Nicht betroffen:
--   - v_claim_parties_safe: ist_aktiv kommt aus claim_parties (false positive im IS-Audit)
-- ============================================================

-- ---- v_claim_full ----
-- Repoint: f.service_typ, f.kundenbetreuer_fallback_flag, f.szenario,
--   f.dokumente_vollstaendig_fuer_phase, f.dokumente_reminder_whatsapp_letzte_sendung,
--   f.sa_unterschrieben_am, f.vollmacht_signiert_am, f.sa_unterschrieben,
--   f.sv_zugewiesen_am, f.schadens_ursache, f.deaktiviert_grund, f.ist_aktiv
--   => alle auf c.<col> (claims alias c: FROM claims c LEFT JOIN faelle f)

CREATE OR REPLACE VIEW public.v_claim_full AS
 SELECT c.id,
    c.vehicle_id,
    c.schadentag,
    c.schadenzeit,
    c.entdeckt_am,
    c.schadenort_adresse,
    c.schadenort_plz,
    c.schadenort_ort,
    c.schadenort_land,
    c.schadenort_lat,
    c.schadenort_lng,
    c.schadenort_kategorie,
    c.hergang_kunde_text,
    c.hergang_sv_text,
    c.schadenart,
    c.fall_typ,
    c.unfall_konstellation,
    c.fahrerflucht,
    c.auslandskennzeichen,
    c.polizei_aktenzeichen,
    c.polizei_bericht_vorhanden,
    c.polizei_vor_ort,
    c.polizeibericht_status,
    c.geschaedigter_user_id,
    c.gegnerisches_vehicle_id,
    c.gegner_versicherung_id,
    c.gegner_versicherungsnummer,
    c.gegner_aktenzeichen,
    c.gegner_bekannt,
    c.anzahl_beteiligte_total,
    c.hat_personenschaden,
    c.hat_mietwagen,
    c.hat_nutzungsausfall,
    c.hat_sachschaden,
    c.hat_abschleppung,
    c.sachschaden_beschreibung,
    c.halter_ungleich_fahrer,
    c.kunden_konstellation,
    c.unfallskizze_url,
    c.unfallskizze_svg,
    c.unfallskizze_bestaetigt,
    c.unfallskizze_ablehnung_grund,
    c.unfallskizze_generiert_am,
    c.status,
    c.abgeschlossen_am,
    c.verjaehrt_am,
    c.created_at,
    c.updated_at,
    c.created_by_user_id,
    c.created_via,
    c.claim_nummer,
    c.lead_id,
    c.kundenbetreuer_id,
    c.phase,
    c.vs_ablehnungs_grund,
    c.regulierungs_betrag,
    c.endzustand_gesetzt_durch_user_id,
    c.endzustand_gesetzt_am,
    c.endzustand_grund,
    c.kanzlei_wunsch,
    c.kanzlei_wunsch_gefragt_am,
    c.kanzlei_wunsch_gefragt_in_phase,
    f.id AS fall_id,
    f.sv_id,
    c.service_typ,
    f.status AS fall_status,
    f.created_at AS fall_created_at,
    f.updated_at AS fall_updated_at,
    c.kundenbetreuer_fallback_flag,
    c.phase AS aktuelle_phase,
    c.szenario,
    c.dokumente_vollstaendig_fuer_phase,
    c.dokumente_reminder_whatsapp_letzte_sendung,
    f.no_show_gemeldet_am,
    f.re_termin_token,
    c.sa_unterschrieben_am,
    c.vollmacht_signiert_am,
    f.mandatsnummer,
    f.re_termin_token_eingelaufen_am,
    f.re_termin_eskalation_an_kb_am,
    f.storniert_am,
    f.anschlussschreiben_am,
    f.vs_eskalationsstufe,
    f.kennzeichen,
    f.fahrzeug_hersteller,
    f.fahrzeug_modell,
    f.fahrzeug_typ,
    c.sa_unterschrieben,
    f.regulierung_am,
    c.regulierungs_betrag AS regulierung_betrag,
    f.gutachten_betrag,
    f.gutachten_eingegangen_am,
    c.sv_zugewiesen_am,
    c.schadens_ursache,
    c.schadenort_plz::text AS schadens_plz,
    c.schadenort_ort AS schadens_ort,
    c.fall_typ AS schadens_fall_typ,
    f.gegner_anzahl_beteiligte,
    f.gegner_fahrzeugtyp,
    f.organisation_id,
    f.dispatch_id,
    f.kunde_id,
    c.ist_aktiv,
    c.deaktiviert_grund,
    f.hat_vorschaeden,
    f.vorschaden_anzahl,
    f.vorschaden_letzter_datum,
    f.vorschaden_typ_b_bericht,
    f.cardentity_abfrage_am,
    f.besichtigungsort_adresse,
    f.besichtigungsort_lat,
    f.besichtigungsort_lng,
    f.besichtigungsort_notiz,
    f.besichtigungsort_place_id,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cp.*) ORDER BY cp.reihenfolge, cp.created_at) AS jsonb_agg
           FROM claim_parties cp
          WHERE cp.claim_id = c.id), '[]'::jsonb) AS parties,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cvi.*) ORDER BY cvi.reihenfolge, cvi.created_at) AS jsonb_agg
           FROM claim_vehicle_involvements cvi
          WHERE cvi.claim_id = c.id), '[]'::jsonb) AS vehicle_involvements,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cp2.*) ORDER BY cp2.created_at) AS jsonb_agg
           FROM claim_payments cp2
          WHERE cp2.claim_id = c.id), '[]'::jsonb) AS payments,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cm.*) ORDER BY cm.created_at) AS jsonb_agg
           FROM claim_mietwagen cm
          WHERE cm.claim_id = c.id), '[]'::jsonb) AS mietwagen,
    COALESCE(( SELECT jsonb_agg(to_jsonb(vk.*) ORDER BY vk.datum) AS jsonb_agg
           FROM vs_korrespondenz vk
          WHERE vk.claim_id = c.id), '[]'::jsonb) AS vs_korrespondenz,
    COALESCE(( SELECT jsonb_agg(to_jsonb(r.*) ORDER BY r.created_at) AS jsonb_agg
           FROM repairs r
          WHERE r.claim_id = c.id), '[]'::jsonb) AS repairs
   FROM claims c
     LEFT JOIN faelle f ON f.claim_id = c.id;

-- ---- v_claim_listing ----
-- Repoint: f.service_typ => c.service_typ

CREATE OR REPLACE VIEW public.v_claim_listing AS
 SELECT c.id AS claim_id,
    c.claim_nummer,
    c.phase,
    c.status,
    c.schadentag,
    c.kunden_konstellation,
    c.created_at,
    c.updated_at,
    f.id AS fall_id,
    f.sv_id,
    c.kundenbetreuer_id AS faelle_kundenbetreuer_id,
    c.kundenbetreuer_id AS claim_kundenbetreuer_id,
    c.service_typ,
    p.anzeigename AS kunde_anzeigename,
    p.vorname AS kunde_vorname,
    p.nachname AS kunde_nachname,
    v.kennzeichen_aktuell AS kennzeichen
   FROM claims c
     LEFT JOIN faelle f ON f.claim_id = c.id
     LEFT JOIN profiles p ON p.id = c.geschaedigter_user_id
     LEFT JOIN vehicles v ON v.id = c.vehicle_id;

-- ---- v_faelle_mit_aktuellem_termin ----
-- Repoint: alle 60 SP-B-Spalten die aus f.<col> kamen => c.<col>
-- (f.-Alias bleibt für rein-faelle-Spalten; Basis: FROM faelle f LEFT JOIN claims c)

CREATE OR REPLACE VIEW public.v_faelle_mit_aktuellem_termin AS
 SELECT f.id,
    f.lead_id,
    f.kunde_id,
    f.status,
    c.betreuungspaket,
    c.hergang_kunde_text AS schadens_beschreibung,
    c.schadentag AS schadens_datum,
    c.entdeckt_am AS schadens_entdeckt_am,
    c.schadenort_adresse AS schadens_adresse,
    c.schadenort_plz::text AS schadens_plz,
    c.schadenort_ort AS schadens_ort,
    c.abtretung_pdf,
    c.vollmacht_pdf,
    c.abtretung_signiert_am,
    c.vollmacht_signiert_am,
    f.sv_id,
    c.sv_zugewiesen_am,
    f.gutachten_eingegangen_am,
    f.gutachten_betrag,
    c.kanzlei_uebergeben_am,
    f.anschlussschreiben_am,
    c.regulierungs_betrag AS regulierung_betrag,
    f.regulierung_am,
    f.filmcheck_ok,
    f.filmcheck_am,
    f.filmcheck_notizen,
    c.notizen,
    f.created_at,
    f.updated_at,
    c.fall_typ AS schadens_fall_typ,
    c.kunden_konstellation,
    f.kennzeichen,
    f.fahrzeug_typ,
    f.fahrzeug_hersteller,
    f.fahrzeug_modell,
    f.fahrzeug_baujahr,
    f.gegner_name,
    f.gegner_versicherung,
    f.gegner_kennzeichen,
    c.gegner_bekannt,
    c.polizei_aktenzeichen,
    c.polizei_bericht_vorhanden,
    c.hat_personenschaden AS personenschaden_flag,
    c.hat_mietwagen AS mietwagen_flag,
    c.gewerbe_flag,
    c.halter_ungleich_fahrer AS halter_ungleich_fahrer_flag,
    f.ust_id,
    f.leasinggeber_name,
    c.leasinggeber_informiert,
    f.bank_name,
    c.prioritaet,
    c.onboarding_complete,
    f.dispatch_id,
    c.kundenbetreuer_id,
    f.konvertiert_am,
    c.lead_id AS konvertiert_von_lead,
    c.status_changed_at,
    f.regulierung_angekuendigt_am,
    f.zahlung_eingegangen_am,
    c.abgeschlossen_am,
    c.google_review_gesendet,
    f.vs_eskalationsstufe,
    f.fin_quelle,
    f.fin_extrahiert_am,
    f.vorschaden_geprueft,
    f.vorschaden_anzahl,
    f.vorschaden_letzter_datum,
    f.vorschaden_typ_a_ergebnis,
    f.vorschaden_typ_b_bericht,
    f.vorschaden_typ_b_pdf_url,
    f.cardentity_abfrage_am,
    c.schadens_hoehe_netto,
    f.nutzungsausfall_tagessatz,
    f.reparaturdauer_tage,
    f.gutachter_honorar,
    f.ocr_extrahiert_am,
    f.ocr_rohdaten,
    f.ki_kalkulation,
    f.ki_kalkulation_am,
    f.ki_geschaetzte_kosten_min,
    f.ki_geschaetzte_kosten_max,
    c.kanzlei_ansprechpartner_name,
    c.kanzlei_ansprechpartner_email,
    c.kanzlei_ansprechpartner_telefon,
    c.kanzlei_ansprechpartner_position,
    f.mandatsnummer,
    f.losfahren_erinnerung_gesendet,
    f.termin_erinnerung_5min_gesendet,
    f.geschaetzte_fahrzeit_min,
    f.geschaetzte_fahrdistanz_km,
    f.gcal_event_id,
    f.gutachten_vorhanden,
    f.gutachten_hochgeladen_am,
    f.gutachten_positionen,
    f.gutachten_nummer,
    f.reparaturkosten,
    f.wertminderung,
    f.nutzungsausfall_gesamt,
    f.regulierungsweise,
    c.gegner_versicherungsnummer,
    c.sa_unterschrieben,
    c.sa_unterschrieben_am,
    c.sa_pdf_url,
    c.sa_unterschrift_url,
    c.datenschutz_akzeptiert,
    c.datenschutz_akzeptiert_am,
    c.vollmacht_status,
    c.polizei_vor_ort,
    c.hergang_kunde_text AS unfallhergang,
    c.unfallmitteilung_status,
    c.schadenort_adresse AS unfallort,
    c.schadentag AS unfalldatum,
    c.interne_notizen,
    f.anschlussschreiben_url,
    f.anschlussschreiben_sendedatum,
    f.anschlussschreiben_unterschrift,
    f.anschlussschreiben_ocr_am,
    f.besichtigungsort_adresse,
    f.besichtigungsort_lat,
    f.besichtigungsort_lng,
    f.besichtigungsort_place_id,
    c.ist_aktiv,
    c.deaktiviert_am,
    c.deaktiviert_grund,
    c.deaktiviert_notiz,
    c.szenario,
    f.ruege_erhalten_am,
    f.ruege_grund,
    f.fahrzeug_farbe,
    f.erstzulassung,
    f.kilometerstand,
    f.firma_name,
    f.marketing_quelle,
    f.marketing_provision,
    f.marketing_provision_status,
    f.gutachten_stundensatz,
    f.kanzlei_id,
    f.kanzlei_honorar,
    f.zahlung_erwartet_am,
    f.zahlung_betrag,
    f.lead_preis_netto,
    f.lead_preis_typ,
    f.lead_preis_berechnet_am,
    f.guthaben_verrechnet_netto,
    f.sv_nachzahlung_netto,
    f.abrechnung_id,
    f.storniert_am,
    f.storno_grund,
    f.storno_durch_user_id,
    f.no_show_gemeldet_am,
    c.spezifikation,
    c.schadenart AS schadens_art,
    f.organisation_id,
    c.phase AS aktuelle_phase,
    c.dokumente_vollstaendig_fuer_phase,
    c.dokumente_vollstaendig_am_phase,
    c.unfall_konstellation,
    f.gegner_anzahl_beteiligte,
    f.gegner_fahrzeugtyp,
    c.dokumente_reminder_whatsapp_letzte_sendung,
    f.fin_vin,
    f.source_channel,
    f.source_domain,
    c.schadens_ursache,
    f.kanzlei_abrechnung_id,
    f.kanzlei_provision_status,
    f.kanzlei_provision_ausgezahlt_am,
    c.service_typ,
    f.vs_reaktion_typ,
    f.vs_reaktion_am,
    c.vs_ablehnungs_grund AS vs_ablehnungsgrund,
    f.ruege_gesendet_am,
    f.ruege_betrag,
    c.kunde_no_show_count AS no_show_count,
    f.kuerzungs_betrag,
    f.vs_frist_bis,
    f.ruege_counter,
    f.schlussabrechnung_am,
    f.iban,
    f.bic,
    f.kontoinhaber,
    f.bankdaten_hinterlegt_am,
    f.ist_fahrzeughalter,
    c.finanzierung_leasing,
    c.vorsteuerabzugsberechtigt,
    c.hergang_kunde_text AS schadens_hergang,
    f.halter_vorname,
    f.halter_nachname,
    f.halter_strasse,
    f.halter_plz,
    f.halter_stadt,
    f.halter_telefon,
    f.halter_email,
    c.finanzierungsgeber_name,
    c.finanzierungsgeber_adresse,
    c.finanzierungsgeber_vertragsnr,
    f.zahlungsweg,
    f.hat_vorschaeden,
    f.vorschaeden_beschreibung,
    f.technische_stellungnahme_status,
    f.technische_stellungnahme_beauftragt_am,
    f.technische_stellungnahme_hochgeladen_am,
    f.technische_stellungnahme_freigabe_am,
    f.nachbesichtigung_status,
    f.nachbesichtigung_angefordert_am,
    f.nachbesichtigung_termin_datum,
    f.nachbesichtigung_konfrontation,
    f.as_geforderte_summe,
    f.as_frist,
    f.as_vs_reaktion_text,
    f.as_salesforce_id,
    f.as_zuletzt_synced_am,
    f.lexdrive_case_id,
    f.eskalation_tag_14_am,
    f.eskalation_tag_21_am,
    f.eskalation_tag_28_am,
    c.schadenort_kategorie AS unfallort_kategorie,
    c.unfallskizze_url,
    f.fahrzeug_ausstattung,
    f.cardentity_enriched_at,
    f.cardentity_report,
    c.vollmacht_geprueft_am,
    c.vollmacht_geprueft_von,
    c.vollmacht_pruefung_status,
    c.vollmacht_pruefung_begruendung,
    f.lexdrive_ocr_data,
    f.lexdrive_ocr_received_at,
    f.vs_kuerzung_grund,
    c.geschlossen_grund,
    f.nachbesichtigung_ergebnis,
    c.bevorzugter_kanal,
    c.gegner_versicherung_id,
    c.zeugen_kontakte,
    c.werkstatt_seit_datum,
    c.fahrzeug_fahrbereit,
    c.hat_nutzungsausfall AS nutzungsausfall,
    f.mietwagen_kanzlei_informiert,
    f.mietwagen_kanzlei_informiert_am,
    f.halter_geburtsdatum,
    c.abrechnungsart_besprochen,
    c.abrechnungsart_notiz,
    c.abrechnungsart_besprochen_am,
    f.gegner_versicherung_anfrage_datum,
    c.sprache,
    c.unfallskizze_svg,
    c.unfallskizze_bestaetigt,
    c.unfallskizze_ablehnung_grund,
    c.unfallskizze_generiert_am,
    c.zeugen_vorhanden,
    f.vorschaden_erkannt,
    f.sv_termin_dokument_reminder_gesendet_am,
    c.kundenbetreuer_fallback_flag,
    c.kundenbetreuer_zugewiesen_am,
    f.sv_briefing_text,
    f.sv_briefing_generated_at,
    f.sv_briefing_model,
    f.sv_briefing_version,
    f.sv_briefing_struktur,
    f.sv_notizen_vor_ort,
    c.makler_id,
    c.hat_sachschaden AS sachschaden_flag,
    c.sachschaden_beschreibung,
    c.gegner_aktenzeichen AS gegner_schadennummer,
    f.halter_name,
    f.wunschtermin,
    f.vs_quote_prozent,
    f.vs_quote_grund,
    f.vs_quote_akzeptiert_am,
    f.vs_quote_betrag_ausgezahlt,
    f.vs_kuerzungs_typ,
    f.auszahlung_kunde_betrag,
    f.auszahlung_kunde_eingegangen_am,
    f.auszahlung_gutachter_eingegangen_am,
    f.auszahlung_zahlungsweg,
    f.eskalation_tag_14_ergebnis,
    f.eskalation_tag_14_ergebnis_am,
    f.eskalation_tag_14_ergebnis_von,
    f.eskalation_tag_21_ergebnis,
    f.eskalation_tag_21_ergebnis_am,
    f.eskalation_tag_21_ergebnis_von,
    f.eskalation_tag_28_ergebnis,
    f.eskalation_tag_28_ergebnis_am,
    f.eskalation_tag_28_ergebnis_von,
    f.nachbesichtigung_kunde_termin_vorschlaege,
    f.nachbesichtigung_kunde_termin_eingereicht_am,
    f.nachbesichtigung_sv_konfrontation_gewuenscht,
    f.nachbesichtigung_sv_termin_vereinbart_am,
    f.auszahlung_gutachter_betrag,
    f.ruege_frist_tage,
    f.klage_uebergeben_am,
    c.fallakte_angelegt_am,
    f.kunde_vorname,
    f.kunde_nachname,
    f.kunde_telefon,
    c.kunde_email,
    f.kunde_strasse,
    f.kunde_plz,
    f.kunde_stadt,
    f.kunde_adresse,
    f.kunde_lat,
    f.kunde_lng,
    f.hsn,
    f.tsn,
    f.technische_stellungnahme_notiz_sv,
    c.fahrerflucht,
    c.auslandskennzeichen,
    c.polizeibericht_status,
    c.zb1_status,
    c.schadenzeit::text AS unfall_uhrzeit,
    c.schadenort_lat::numeric AS unfallort_lat,
    c.schadenort_lng::numeric AS unfallort_lng,
    c.bkat_unfallart,
    c.fahrzeugschaden_beschreibung,
    c.hat_mietwagen AS mietwagen_hat,
    c.mietwagen_seit_datum,
    c.mietwagen_limit_tage,
    c.mietwagen_limit_grund,
    c.mietwagen_rechnung_vorhanden,
    c.mietwagen_rechnung_url,
    c.mietwagen_argumentations_puffer,
    c.mietwagen_vermieter,
    c.vehicle_id,
    f.claim_id,
    f.lackfarbe_code,
    t.id AS aktueller_termin_id,
    t.start_zeit AS aktueller_termin_start,
    t.end_zeit AS aktueller_termin_end,
    t.status AS aktueller_termin_status,
    t.sv_id AS aktueller_termin_sv_id,
    t.kanal AS aktueller_termin_kanal,
    t.typ AS aktueller_termin_typ,
    t.final_verbindlich_ab AS aktueller_termin_final_verbindlich_ab,
    t.start_zeit AS sv_termin,
    t.status AS gutachter_termin_status,
    t.status = 'bestaetigt'::text AS gutachter_termin_bestaetigt,
    t.vorgeschlagenes_datum AS gutachter_gegenvorschlag_datum,
    t.gegenvorschlag_grund AS gutachter_gegenvorschlag_grund,
    c.claim_nummer
   FROM faelle f
     LEFT JOIN claims c ON c.id = f.claim_id
     LEFT JOIN LATERAL ( SELECT gt.id,
            gt.sv_id,
            gt.fall_id,
            gt.start_zeit,
            gt.end_zeit,
            gt.status,
            gt.externer_kalender_id,
            gt.ablehnungsgrund,
            gt.gegenvorschlag_zeit,
            gt.created_at,
            gt.erinnerung_24h_gesendet,
            gt.erinnerung_2h_gesendet,
            gt.erinnerung_48h_docs_gesendet,
            gt.ankunft_zeit,
            gt.abschluss_zeit,
            gt.uebersprungen,
            gt.uebersprung_grund,
            gt.notizen_vor_ort,
            gt.gps_lat_ankunft,
            gt.gps_lng_ankunft,
            gt.lead_id,
            gt.ablehnen_token,
            gt.abgelehnt_am,
            gt.abgelehnt_grund,
            gt.vorgeschlagenes_datum,
            gt.gegenvorschlag_grund,
            gt.gegenvorschlag_von,
            gt.ankunft_via,
            gt.verspaetung_minuten,
            gt.losgefahren_am,
            gt.kunden_tracking_token,
            gt.notification_losgefahren_gesendet_am,
            gt.notification_5min_gesendet_am,
            gt.notification_angekommen_gesendet_am,
            gt.ablehnen_token_expires_at,
            gt.final_verbindlich_ab,
            gt.sv_ablehnung_grund,
            gt.sv_ablehnung_am,
            gt.sv_vorgeschlagene_slots,
            gt.typ,
            gt.kanal,
            gt.video_link,
            gt.kb_id,
            gt.notiz_kunde,
            gt.notiz_intern,
            gt.reminder_sent_at,
            gt.reminder_1h_sent_at,
            gt.cancelled_at,
            gt.navigation_started_at,
            gt.sv_unterwegs_seit,
            gt.sv_eta_minuten,
            gt.sv_eta_letzte_berechnung,
            gt.sv_angekommen_am,
            gt.reminder_15min_sent_at,
            gt.reminder_5min_sent_at,
            gt.durchgefuehrt_am,
            gt.kunde_tracking_aktiviert,
            gt.kunde_losgefahren_am,
            gt.kunde_eta_minuten,
            gt.kunde_eta_letzte_berechnung,
            gt.kunde_angekommen_am,
            gt.kunde_verspaetung_gemeldet_am,
            gt.bezahlt,
            gt.honorar_betrag,
            gt.google_event_id,
            gt.google_calendar_id,
            gt.google_event_synced_at,
            gt.kunde_response_token,
            gt.kunde_response_token_expires_at,
            gt.gesehen_am,
            gt.geschaetzte_fahrtzeit_min,
            gt.auftrag_id,
            gt.verlegung_quelle_id,
            gt.verlegung_grund,
            gt.verlegung_kunde_benachrichtigt_an,
            gt.verlegung_eskalation_an_kb_an,
            gt.verlegung_initiator_kunde,
            gt.besichtigung_gestartet_am,
            gt.caldav_object_url,
            gt.caldav_event_uid,
            gt.caldav_synced_at,
            gt.erinnerung_morgen_gesendet,
            gt.sv_lead_id
           FROM gutachter_termine gt
          WHERE gt.fall_id = f.id AND (gt.status = ANY (ARRAY['bestaetigt'::text, 'verlegung_pending'::text, 'reserviert'::text, 'durchgefuehrt'::text, 'gegenvorschlag'::text]))
          ORDER BY (
                CASE gt.status
                    WHEN 'bestaetigt'::text THEN 1
                    WHEN 'verlegung_pending'::text THEN 2
                    WHEN 'gegenvorschlag'::text THEN 3
                    WHEN 'reserviert'::text THEN 4
                    WHEN 'durchgefuehrt'::text THEN 5
                    ELSE 6
                END), gt.start_zeit DESC NULLS LAST
         LIMIT 1) t ON true;

COMMIT;
