-- CMM-49: letzter pg_depend-Blocker an gutachter_termine.sv_id = v_faelle_mit_aktuellem_termin
-- (LATERAL-Subquery selektierte gt.sv_id -> aktueller_termin_sv_id). ab96fed4-Entscheid:
-- aktueller_termin_sv_id -> NULL (totes Output-Feld, 0 Consumer in src). Change = 1 Token in der
-- Subquery: gt.sv_id -> NULL::uuid AS sv_id. sv_id (claims) + sv_termin (start_zeit) bleiben.
-- Verifikation: 199-Spalten-MD5 (ohne aktueller_termin_sv_id) before==after (cef68690...), n=79;
-- aktueller_termin_sv_id danach NULL fuer alle Rows; pg_depend@gt.sv_id ohne v_faelle.
-- Bereits via apply_migration appliziert (recorded 20260611131431).
CREATE OR REPLACE VIEW v_faelle_mit_aktuellem_termin AS
 SELECT fcb.fall_id AS id,
    c.lead_id,
    c.geschaedigter_user_id AS kunde_id,
    c.operative_status::fall_status AS status,
    c.betreuungspaket,
    c.hergang_kunde_text AS schadens_beschreibung,
    c.schadentag AS schadens_datum,
    c.entdeckt_am AS schadens_entdeckt_am,
    c.schadenort_adresse AS schadens_adresse,
    c.schadenort_plz::text AS schadens_plz,
    c.schadenort_ort AS schadens_ort,
    c.abtretung_pdf,
    c.vollmacht_pdf,
    c.abtretung_signiert_am,
    c.vollmacht_signiert_am,
    c.sv_id,
    c.sv_zugewiesen_am,
    g.fertiggestellt_am AS gutachten_eingegangen_am,
    g.gesamt_schadensbetrag::numeric(10,2) AS gutachten_betrag,
    c.kanzlei_uebergeben_am,
    kf.anschlussschreiben_am,
    c.regulierungs_betrag AS regulierung_betrag,
    kf.regulierung_am,
    cur_auftrag.filmcheck_ok,
    cur_auftrag.filmcheck_am,
    cur_auftrag.filmcheck_notizen,
    c.notizen,
    c.created_at,
    COALESCE(( SELECT cr.last_activity_at
           FROM claim_recency cr
          WHERE cr.claim_id = c.id), c.created_at) AS updated_at,
    c.fall_typ AS schadens_fall_typ,
    c.kunden_konstellation,
    veh.kennzeichen_aktuell::text AS kennzeichen,
    veh.bauart AS fahrzeug_typ,
    veh.hersteller AS fahrzeug_hersteller,
    veh.modell_haupttyp AS fahrzeug_modell,
    EXTRACT(year FROM veh.baujahr_monat)::integer AS fahrzeug_baujahr,
    NULL::text AS gegner_name,
    NULL::text AS gegner_versicherung,
    NULL::text AS gegner_kennzeichen,
    c.gegner_bekannt,
    c.polizei_aktenzeichen,
    c.polizei_bericht_vorhanden,
    c.hat_personenschaden AS personenschaden_flag,
    c.hat_mietwagen AS mietwagen_flag,
    c.gewerbe_flag,
    c.halter_ungleich_fahrer AS halter_ungleich_fahrer_flag,
    NULL::text AS ust_id,
    c.leasinggeber_name,
    c.leasinggeber_informiert,
    NULL::text AS bank_name,
    c.prioritaet,
    c.onboarding_complete,
    NULL::uuid AS dispatch_id,
    c.kundenbetreuer_id,
    c.konvertiert_am,
    c.lead_id AS konvertiert_von_lead,
    c.status_changed_at,
    kf.regulierung_angekuendigt_am,
    NULL::timestamp with time zone AS zahlung_eingegangen_am,
    c.abgeschlossen_am,
    c.google_review_gesendet,
    COALESCE(kf.vs_eskalationsstufe, 'vs-01'::text) AS vs_eskalationsstufe,
    veh.fin_quelle,
    veh.fin_extrahiert_am,
    c.vorschaden_geprueft,
    vv.anzahl AS vorschaden_anzahl,
    vv.letzter_datum AS vorschaden_letzter_datum,
    veh.cardentity_report -> 'typA'::text AS vorschaden_typ_a_ergebnis,
    veh.cardentity_report -> 'typB'::text AS vorschaden_typ_b_bericht,
    veh.cardentity_report ->> 'pdfUrl'::text AS vorschaden_typ_b_pdf_url,
    veh.cardentity_letzter_pull AS cardentity_abfrage_am,
    c.schadens_hoehe_netto,
    g.gutachten_nutzungsausfall_tagessatz_eur::numeric(10,2) AS nutzungsausfall_tagessatz,
    g.wiederbeschaffungsdauer_tage AS reparaturdauer_tage,
    g.gutachten_sv_honorar_netto AS gutachter_honorar,
    g.ocr_finished_at AS ocr_extrahiert_am,
    g.gutachten_ocr_raw AS ocr_rohdaten,
    g.ki_kalkulation,
    g.ki_kalkulation_am,
    g.ki_geschaetzte_kosten_min::numeric(10,2) AS ki_geschaetzte_kosten_min,
    g.ki_geschaetzte_kosten_max::numeric(10,2) AS ki_geschaetzte_kosten_max,
    c.kanzlei_ansprechpartner_name,
    c.kanzlei_ansprechpartner_email,
    c.kanzlei_ansprechpartner_telefon,
    c.kanzlei_ansprechpartner_position,
    kf.mandatsnummer,
    t.losfahren_erinnerung_gesendet,
    t.termin_erinnerung_5min_gesendet,
    t.geschaetzte_fahrtzeit_min AS geschaetzte_fahrzeit_min,
    t.geschaetzte_fahrdistanz_km,
    t.google_event_id AS gcal_event_id,
    g.id IS NOT NULL AS gutachten_vorhanden,
    g.pdf_uploaded_at AS gutachten_hochgeladen_am,
    g.positionen AS gutachten_positionen,
    g.auftragsnummer AS gutachten_nummer,
    g.reparaturkosten_netto AS reparaturkosten,
    g.minderwert AS wertminderung,
    (g.gutachten_nutzungsausfall_tagessatz_eur * g.nutzungsausfall_tage::numeric)::numeric(10,2) AS nutzungsausfall_gesamt,
    kf.regulierungsweise,
    c.gegner_versicherungsnummer,
    c.sa_unterschrieben,
    c.sa_unterschrieben_am,
    c.sa_pdf_url,
    c.sa_unterschrift_url,
    c.datenschutz_akzeptiert,
    c.datenschutz_akzeptiert_am,
    c.vollmacht_status,
    c.polizei_vor_ort,
    c.hergang_kunde_text AS unfallhergang,
    c.unfallmitteilung_status,
    c.schadenort_adresse AS unfallort,
    c.schadentag AS unfalldatum,
    c.interne_notizen,
    kf.anschlussschreiben_url,
    kf.anschlussschreiben_sendedatum,
    COALESCE(kf.anschlussschreiben_unterschrift, false) AS anschlussschreiben_unterschrift,
    kf.anschlussschreiben_ocr_am,
    t.besichtigungsort_adresse,
    t.besichtigungsort_lat,
    t.besichtigungsort_lng,
    t.besichtigungsort_place_id,
    c.ist_aktiv,
    c.deaktiviert_am,
    c.deaktiviert_grund,
    c.deaktiviert_notiz,
    c.szenario,
    kf.ruege_erhalten_am,
    kf.ruege_grund,
    veh.farbe_klartext AS fahrzeug_farbe,
    veh.erstzulassung::text AS erstzulassung,
    veh.aktueller_kilometerstand AS kilometerstand,
    NULL::text AS firma_name,
    c.marketing_quelle,
    c.marketing_provision,
    c.marketing_provision_status,
    NULL::numeric(10,2) AS gutachten_stundensatz,
    kf.kanzlei_id,
    c.kanzlei_honorar,
    NULL::date AS zahlung_erwartet_am,
    NULL::numeric(10,2) AS zahlung_betrag,
    c.lead_preis_netto,
    c.lead_preis_typ,
    c.lead_preis_berechnet_am,
    c.guthaben_verrechnet_netto,
    c.sv_nachzahlung_netto,
    c.abrechnung_id,
    cur_auftrag.storniert_am,
    cur_auftrag.storno_grund,
    cur_auftrag.storno_durch_user_id,
    t.no_show_gemeldet_am,
    c.spezifikation,
    c.schadenart AS schadens_art,
    NULL::uuid AS organisation_id,
    c.dokumente_vollstaendig_fuer_phase,
    c.dokumente_vollstaendig_am_phase,
    c.unfall_konstellation,
    NULL::integer AS gegner_anzahl_beteiligte,
    NULL::text AS gegner_fahrzeugtyp,
    c.dokumente_reminder_whatsapp_letzte_sendung,
    veh.fin::text AS fin_vin,
    NULL::text AS source_channel,
    NULL::text AS source_domain,
    c.schadens_ursache,
    c.kanzlei_abrechnung_id,
    c.kanzlei_provision_status,
    c.kanzlei_provision_ausgezahlt_am,
    c.service_typ,
    kf.vs_reaktion_typ,
    kf.vs_reaktion_am,
    c.vs_ablehnungs_grund AS vs_ablehnungsgrund,
    kf.ruege_gesendet_am,
    kf.ruege_betrag,
    c.kunde_no_show_count AS no_show_count,
    kf.kuerzungs_betrag,
    kf.vs_frist_bis,
    COALESCE(kf.ruege_counter, 0) AS ruege_counter,
    c.schlussabrechnung_am,
    c.iban,
    c.bic,
    c.kontoinhaber,
    c.bankdaten_hinterlegt_am,
    NULL::boolean AS ist_fahrzeughalter,
    c.finanzierung_leasing,
    c.vorsteuerabzugsberechtigt,
    c.hergang_kunde_text AS schadens_hergang,
    NULL::text AS halter_vorname,
    NULL::text AS halter_nachname,
    NULL::text AS halter_strasse,
    NULL::text AS halter_plz,
    NULL::text AS halter_stadt,
    NULL::text AS halter_telefon,
    NULL::text AS halter_email,
    c.finanzierungsgeber_name,
    c.finanzierungsgeber_adresse,
    c.finanzierungsgeber_vertragsnr,
    c.zahlungsweg,
    c.hat_vorschaeden,
    c.vorschaeden_beschreibung,
    cur_auftrag.technische_stellungnahme_status,
    cur_auftrag.technische_stellungnahme_beauftragt_am,
    cur_auftrag.technische_stellungnahme_hochgeladen_am,
    cur_auftrag.technische_stellungnahme_freigabe_am,
    t.nachbesichtigung_status,
    t.nachbesichtigung_angefordert_am,
    t.nachbesichtigung_termin_datum,
    t.nachbesichtigung_konfrontation,
    kf.as_geforderte_summe,
    kf.as_frist,
    kf.as_vs_reaktion_text,
    kf.as_salesforce_id,
    kf.as_zuletzt_synced_am,
    kf.lexdrive_case_id,
    kf.eskalation_tag_14_am,
    kf.eskalation_tag_21_am,
    kf.eskalation_tag_28_am,
    c.schadenort_kategorie AS unfallort_kategorie,
    c.unfallskizze_url,
    veh.fahrzeug_ausstattung,
    veh.cardentity_letzter_pull AS cardentity_enriched_at,
    veh.cardentity_report,
    c.vollmacht_geprueft_am,
    c.vollmacht_geprueft_von,
    c.vollmacht_pruefung_status,
    c.vollmacht_pruefung_begruendung,
    kf.lexdrive_ocr_data,
    kf.lexdrive_ocr_received_at,
    kf.vs_kuerzung_grund,
    c.geschlossen_grund,
    t.nachbesichtigung_ergebnis,
    c.bevorzugter_kanal,
    c.gegner_versicherung_id,
    c.zeugen_kontakte,
    c.werkstatt_seit_datum,
    c.fahrzeug_fahrbereit,
    c.hat_nutzungsausfall AS nutzungsausfall,
    c.mietwagen_kanzlei_informiert,
    c.mietwagen_kanzlei_informiert_am,
    NULL::date AS halter_geburtsdatum,
    c.abrechnungsart_besprochen,
    c.abrechnungsart_notiz,
    c.abrechnungsart_besprochen_am,
    NULL::date AS gegner_versicherung_anfrage_datum,
    c.sprache,
    c.unfallskizze_svg,
    c.unfallskizze_bestaetigt,
    c.unfallskizze_ablehnung_grund,
    c.unfallskizze_generiert_am,
    c.zeugen_vorhanden,
    c.vorschaden_erkannt,
    t.sv_termin_dokument_reminder_gesendet_am,
    c.kundenbetreuer_fallback_flag,
    c.kundenbetreuer_zugewiesen_am,
    cur_auftrag.sv_briefing_text,
    cur_auftrag.sv_briefing_generated_at,
    cur_auftrag.sv_briefing_model,
    cur_auftrag.sv_briefing_version,
    cur_auftrag.sv_briefing_struktur,
    cur_auftrag.sv_notizen_vor_ort,
    c.makler_id,
    c.hat_sachschaden AS sachschaden_flag,
    c.sachschaden_beschreibung,
    c.gegner_aktenzeichen AS gegner_schadennummer,
    NULL::text AS halter_name,
    t.wunschtermin,
    kf.vs_quote_prozent,
    kf.vs_quote_grund,
    kf.vs_quote_akzeptiert_am,
    kf.vs_quote_betrag_ausgezahlt,
    kf.vs_kuerzungs_typ,
    NULL::numeric(10,2) AS auszahlung_kunde_betrag,
    NULL::timestamp with time zone AS auszahlung_kunde_eingegangen_am,
    c.auszahlung_gutachter_eingegangen_am,
    c.auszahlung_zahlungsweg,
    kf.eskalation_tag_14_ergebnis,
    kf.eskalation_tag_14_ergebnis_am,
    kf.eskalation_tag_14_ergebnis_von,
    kf.eskalation_tag_21_ergebnis,
    kf.eskalation_tag_21_ergebnis_am,
    kf.eskalation_tag_21_ergebnis_von,
    kf.eskalation_tag_28_ergebnis,
    kf.eskalation_tag_28_ergebnis_am,
    kf.eskalation_tag_28_ergebnis_von,
    t.nachbesichtigung_kunde_termin_vorschlaege,
    t.nachbesichtigung_kunde_termin_eingereicht_am,
    t.nachbesichtigung_sv_konfrontation_gewuenscht,
    t.nachbesichtigung_sv_termin_vereinbart_am,
    c.auszahlung_gutachter_betrag,
    COALESCE(kf.ruege_frist_tage, 14) AS ruege_frist_tage,
    kf.klage_uebergeben_am,
    c.fallakte_angelegt_am,
    cp_g.vorname AS kunde_vorname,
    cp_g.nachname AS kunde_nachname,
    cp_g.telefon AS kunde_telefon,
    c.kunde_email,
    cp_g.adresse_strasse AS kunde_strasse,
    cp_g.adresse_plz::text AS kunde_plz,
    cp_g.adresse_ort AS kunde_stadt,
    cp_g.adresse_strasse AS kunde_adresse,
    c.kunde_lat,
    c.kunde_lng,
    veh.hsn::text AS hsn,
    veh.tsn::text AS tsn,
    cur_auftrag.technische_stellungnahme_notiz_sv,
    c.fahrerflucht,
    c.auslandskennzeichen,
    c.polizeibericht_status,
    c.zb1_status,
    c.schadenzeit::text AS unfall_uhrzeit,
    c.schadenort_lat::numeric AS unfallort_lat,
    c.schadenort_lng::numeric AS unfallort_lng,
    c.bkat_unfallart,
    c.fahrzeugschaden_beschreibung,
    c.hat_mietwagen AS mietwagen_hat,
    c.mietwagen_seit_datum,
    c.mietwagen_limit_tage,
    c.mietwagen_limit_grund,
    c.mietwagen_rechnung_vorhanden,
    c.mietwagen_rechnung_url,
    c.mietwagen_argumentations_puffer,
    c.mietwagen_vermieter,
    c.vehicle_id,
    c.id AS claim_id,
    veh.farbcode AS lackfarbe_code,
    t.id AS aktueller_termin_id,
    t.start_zeit AS aktueller_termin_start,
    t.end_zeit AS aktueller_termin_end,
    t.status AS aktueller_termin_status,
    t.sv_id AS aktueller_termin_sv_id,
    t.kanal AS aktueller_termin_kanal,
    t.typ AS aktueller_termin_typ,
    t.final_verbindlich_ab AS aktueller_termin_final_verbindlich_ab,
    t.start_zeit AS sv_termin,
    t.status AS gutachter_termin_status,
    t.status = 'bestaetigt'::text AS gutachter_termin_bestaetigt,
    t.vorgeschlagenes_datum AS gutachter_gegenvorschlag_datum,
    t.gegenvorschlag_grund AS gutachter_gegenvorschlag_grund,
    c.claim_nummer,
    vcp.main_phase,
    vcp.sub_phase
   FROM claims c
     LEFT JOIN faelle_claim_bridge fcb ON fcb.claim_id = c.id
     LEFT JOIN vehicles veh ON veh.id = c.vehicle_id
     LEFT JOIN gutachten g ON g.claim_id = c.id
     LEFT JOIN kanzlei_faelle kf ON kf.claim_id = c.id
     LEFT JOIN LATERAL ( SELECT gt.id,
            NULL::uuid AS sv_id,
            gt.fall_id,
            gt.start_zeit,
            gt.end_zeit,
            gt.status,
            gt.externer_kalender_id,
            gt.ablehnungsgrund,
            gt.gegenvorschlag_zeit,
            gt.created_at,
            gt.erinnerung_24h_gesendet,
            gt.erinnerung_2h_gesendet,
            gt.erinnerung_48h_docs_gesendet,
            gt.ankunft_zeit,
            gt.abschluss_zeit,
            gt.uebersprungen,
            gt.uebersprung_grund,
            gt.notizen_vor_ort,
            gt.gps_lat_ankunft,
            gt.gps_lng_ankunft,
            gt.lead_id,
            gt.ablehnen_token,
            gt.abgelehnt_am,
            gt.abgelehnt_grund,
            gt.vorgeschlagenes_datum,
            gt.gegenvorschlag_grund,
            gt.gegenvorschlag_von,
            gt.ankunft_via,
            gt.verspaetung_minuten,
            gt.losgefahren_am,
            gt.kunden_tracking_token,
            gt.notification_losgefahren_gesendet_am,
            gt.notification_5min_gesendet_am,
            gt.notification_angekommen_gesendet_am,
            gt.ablehnen_token_expires_at,
            gt.final_verbindlich_ab,
            gt.sv_ablehnung_grund,
            gt.sv_ablehnung_am,
            gt.sv_vorgeschlagene_slots,
            gt.typ,
            gt.kanal,
            gt.video_link,
            gt.kb_id,
            gt.notiz_kunde,
            gt.notiz_intern,
            gt.reminder_sent_at,
            gt.reminder_1h_sent_at,
            gt.cancelled_at,
            gt.navigation_started_at,
            gt.sv_unterwegs_seit,
            gt.sv_eta_minuten,
            gt.sv_eta_letzte_berechnung,
            gt.sv_angekommen_am,
            gt.reminder_15min_sent_at,
            gt.reminder_5min_sent_at,
            gt.durchgefuehrt_am,
            gt.kunde_tracking_aktiviert,
            gt.kunde_losgefahren_am,
            gt.kunde_eta_minuten,
            gt.kunde_eta_letzte_berechnung,
            gt.kunde_angekommen_am,
            gt.kunde_verspaetung_gemeldet_am,
            gt.bezahlt,
            gt.honorar_betrag,
            gt.google_event_id,
            gt.google_calendar_id,
            gt.google_event_synced_at,
            gt.kunde_response_token,
            gt.kunde_response_token_expires_at,
            gt.gesehen_am,
            gt.geschaetzte_fahrtzeit_min,
            gt.auftrag_id,
            gt.verlegung_quelle_id,
            gt.verlegung_grund,
            gt.verlegung_kunde_benachrichtigt_an,
            gt.verlegung_eskalation_an_kb_an,
            gt.verlegung_initiator_kunde,
            gt.besichtigung_gestartet_am,
            gt.caldav_object_url,
            gt.caldav_event_uid,
            gt.caldav_synced_at,
            gt.erinnerung_morgen_gesendet,
            gt.sv_lead_id,
            gt.besichtigungsort_adresse,
            gt.besichtigungsort_lat,
            gt.besichtigungsort_lng,
            gt.besichtigungsort_place_id,
            gt.geschaetzte_fahrdistanz_km,
            gt.termin_erinnerung_5min_gesendet,
            gt.sv_termin_dokument_reminder_gesendet_am,
            gt.losfahren_erinnerung_gesendet,
            gt.wunschtermin,
            gt.no_show_gemeldet_am,
            gt.nachbesichtigung_status,
            gt.nachbesichtigung_angefordert_am,
            gt.nachbesichtigung_termin_datum,
            gt.nachbesichtigung_konfrontation,
            gt.nachbesichtigung_ergebnis,
            gt.nachbesichtigung_kunde_termin_vorschlaege,
            gt.nachbesichtigung_kunde_termin_eingereicht_am,
            gt.nachbesichtigung_sv_konfrontation_gewuenscht,
            gt.nachbesichtigung_sv_termin_vereinbart_am
           FROM gutachter_termine gt
          WHERE gt.claim_id = c.id AND (gt.status = ANY (ARRAY['bestaetigt'::text, 'verlegung_pending'::text, 'reserviert'::text, 'durchgefuehrt'::text, 'gegenvorschlag'::text]))
          ORDER BY (
                CASE gt.status
                    WHEN 'bestaetigt'::text THEN 1
                    WHEN 'verlegung_pending'::text THEN 2
                    WHEN 'gegenvorschlag'::text THEN 3
                    WHEN 'reserviert'::text THEN 4
                    WHEN 'durchgefuehrt'::text THEN 5
                    ELSE 6
                END), gt.start_zeit DESC NULLS LAST
         LIMIT 1) t ON true
     LEFT JOIN LATERAL ( SELECT a.filmcheck_ok,
            a.filmcheck_am,
            a.filmcheck_notizen,
            a.storniert_am,
            a.storno_grund,
            a.storno_durch_user_id,
            a.sv_briefing_text,
            a.sv_briefing_generated_at,
            a.sv_briefing_model,
            a.sv_briefing_version,
            a.sv_briefing_struktur,
            a.sv_notizen_vor_ort,
            a.technische_stellungnahme_status,
            a.technische_stellungnahme_notiz_sv,
            a.technische_stellungnahme_beauftragt_am,
            a.technische_stellungnahme_hochgeladen_am,
            a.technische_stellungnahme_freigabe_am
           FROM auftraege a
          WHERE a.claim_id = c.id
          ORDER BY a.reihenfolge DESC
         LIMIT 1) cur_auftrag ON true
     LEFT JOIN LATERAL ( SELECT cp.vorname,
            cp.nachname,
            cp.telefon,
            cp.adresse_strasse,
            cp.adresse_plz,
            cp.adresse_ort
           FROM claim_parties cp
          WHERE cp.claim_id = c.id AND cp.rolle = 'geschaedigter'::text
          ORDER BY cp.created_at, cp.id
         LIMIT 1) cp_g ON true
     LEFT JOIN LATERAL ( SELECT NULLIF(count(*), 0)::integer AS anzahl,
            max(vv0.schaden_datum) AS letzter_datum
           FROM vehicle_vorschaeden vv0
          WHERE vv0.vehicle_id = c.vehicle_id) vv ON true
     LEFT JOIN v_claim_phase vcp ON vcp.claim_id = c.id;
