-- View-Kanonisierung (b): faelle_sv_view wird duenner Layer auf v_claim_base.
-- Harness-verifiziert: 0 non-termin-Diffs ueber 89 Rows, Shape 42 Spalten identisch.
-- 2 EXEMPT-Diffs (nachbesichtigung_status/_kunde_termin_vorschlaege auf 2 Claims) =
-- Decision-a (base nutzt get_aktueller_gt_termin_id statt neuester-Termin) wie bei vcf.
CREATE OR REPLACE VIEW public.faelle_sv_view AS
SELECT
  base.fall_id                                        AS id,
  base.fall_status                                    AS status,
  base.hergang_kunde_text                             AS schadens_beschreibung,
  base.schadentag                                     AS schadens_datum,
  base.schadenort_adresse                             AS schadens_adresse,
  base.schadens_plz                                   AS schadens_plz,
  base.schadens_ort                                   AS schadens_ort,
  base.kennzeichen                                    AS kennzeichen,
  base.fahrzeug_hersteller_raw                        AS fahrzeug_hersteller,
  base.fahrzeug_modell                                AS fahrzeug_modell,
  base.fahrzeug_baujahr                               AS fahrzeug_baujahr,
  base.gutachter_honorar                              AS gutachter_honorar,
  base.auszahlung_gutachter_eingegangen_am            AS auszahlung_gutachter_eingegangen_am,
  base.eskalation_tag_14_ergebnis                     AS eskalation_tag_14_ergebnis,
  base.eskalation_tag_14_ergebnis_am                  AS eskalation_tag_14_ergebnis_am,
  base.eskalation_tag_21_ergebnis                     AS eskalation_tag_21_ergebnis,
  base.eskalation_tag_21_ergebnis_am                  AS eskalation_tag_21_ergebnis_am,
  base.eskalation_tag_28_ergebnis                     AS eskalation_tag_28_ergebnis,
  base.eskalation_tag_28_ergebnis_am                  AS eskalation_tag_28_ergebnis_am,
  base.technische_stellungnahme_status                AS technische_stellungnahme_status,
  base.technische_stellungnahme_beauftragt_am         AS technische_stellungnahme_beauftragt_am,
  base.technische_stellungnahme_hochgeladen_am        AS technische_stellungnahme_hochgeladen_am,
  base.technische_stellungnahme_freigabe_am           AS technische_stellungnahme_freigabe_am,
  base.vs_kuerzung_grund                              AS vs_kuerzung_grund,
  base.vs_kuerzungs_typ                               AS vs_kuerzungs_typ,
  base.kuerzungs_betrag                               AS kuerzungs_betrag,
  base.nachbesichtigung_status                        AS nachbesichtigung_status,
  base.nachbesichtigung_termin_datum                  AS nachbesichtigung_termin_datum,
  base.nachbesichtigung_sv_konfrontation_gewuenscht   AS nachbesichtigung_sv_konfrontation_gewuenscht,
  base.nachbesichtigung_sv_termin_vereinbart_am       AS nachbesichtigung_sv_termin_vereinbart_am,
  base.vs_reaktion_typ                                AS vs_reaktion_typ,
  base.vs_reaktion_am                                 AS vs_reaktion_am,
  base.besichtigungsort_adresse                       AS besichtigungsort_adresse,
  base.sv_id                                          AS sv_id,
  base.kunde_id                                       AS kunde_id,
  base.claim_nummer                                   AS claim_nummer,
  base.mandatsnummer                                  AS mandatsnummer,
  base.lexdrive_case_id                               AS lexdrive_case_id,
  base.main_phase                                     AS main_phase,
  base.sub_phase                                      AS sub_phase,
  base.auszahlung_gutachter_betrag                    AS auszahlung_gutachter_betrag,
  base.nachbesichtigung_kunde_termin_vorschlaege      AS nachbesichtigung_kunde_termin_vorschlaege
FROM v_claim_base base;
