-- AAR-747 Follow-up: View + FK-Constraint sauber umbenennen.
--
-- ALTER TABLE ... RENAME COLUMN in Migration #1 hat intern die View-
-- Definition angepasst (f.dispatch_id), ABER die Output-Column der View
-- blieb als `leadbearbeiter_id` — PostgreSQL behält per Default die
-- Alt-Aliase (f.dispatch_id AS leadbearbeiter_id) um rückwärtskompatibel
-- zu bleiben. Wir wollen aber die View-Column auch umbenennen.
--
-- Zudem heißt der FK-Constraint noch faelle_leadbearbeiter_id_fkey.

-- ─── 1. FK-Constraint umbenennen ───────────────────────────────────────
ALTER TABLE public.faelle
  RENAME CONSTRAINT faelle_leadbearbeiter_id_fkey TO faelle_dispatch_id_fkey;

-- ─── 2. View neu erstellen mit dispatch_id als Output-Column ──────────
DROP VIEW IF EXISTS public.v_faelle_mit_aktuellem_termin;

CREATE VIEW public.v_faelle_mit_aktuellem_termin AS
 SELECT f.id,
    f.fall_nummer,
    f.lead_id,
    f.kunde_id,
    f.status,
    f.betreuungspaket,
    f.schadens_beschreibung,
    f.schadens_datum,
    f.schadens_entdeckt_am,
    f.schadens_adresse,
    f.schadens_plz,
    f.schadens_ort,
    f.abtretung_pdf,
    f.vollmacht_pdf,
    f.abtretung_signiert_am,
    f.vollmacht_signiert_am,
    f.sv_id,
    f.sv_zugewiesen_am,
    f.gutachten_eingegangen_am,
    f.gutachten_betrag,
    f.kanzlei_uebergeben_am,
    f.anschlussschreiben_am,
    f.regulierung_betrag,
    f.regulierung_am,
    f.filmcheck_ok,
    f.filmcheck_am,
    f.filmcheck_notizen,
    f.notizen,
    f.created_at,
    f.updated_at,
    f.schadens_fall_typ,
    f.kunden_konstellation,
    f.kennzeichen,
    f.fahrzeug_typ,
    f.fahrzeug_hersteller,
    f.fahrzeug_modell,
    f.fahrzeug_baujahr,
    f.gegner_name,
    f.gegner_versicherung,
    f.gegner_kennzeichen,
    f.gegner_bekannt,
    f.polizei_aktenzeichen,
    f.polizei_bericht_vorhanden,
    f.personenschaden_flag,
    f.mietwagen_flag,
    f.gewerbe_flag,
    f.halter_ungleich_fahrer_flag,
    f.ust_id,
    f.leasinggeber_name,
    f.leasinggeber_informiert,
    f.bank_name,
    f.prioritaet,
    f.onboarding_complete,
    f.dispatch_id,
    f.kundenbetreuer_id,
    f.konvertiert_am,
    f.konvertiert_von_lead,
    f.status_changed_at,
    f.regulierung_angekuendigt_am,
    f.zahlung_eingegangen_am,
    f.abgeschlossen_am,
    f.google_review_gesendet,
    f.vs_eskalationsstufe,
    f.fin_quelle,
    f.fin_extrahiert_am,
    f.vorschaden_geprueft,
    f.vorschaden_anzahl,
    f.vorschaden_letzter_datum,
    f.vorschaden_typ_a_ergebnis,
    f.vorschaden_typ_b_bericht,
    f.vorschaden_typ_b_pdf_url,
    f.cardentity_abfrage_am,
    f.schadens_hoehe_netto,
    f.wiederbeschaffungswert,
    f.restwert,
    f.nutzungsausfall_tage,
    f.nutzungsausfall_tagessatz,
    f.reparaturdauer_tage,
    f.totalschaden,
    f.gutachter_honorar,
    f.ocr_extrahiert_am,
    f.ocr_rohdaten,
    f.ki_kalkulation,
    f.ki_kalkulation_am,
    f.ki_geschaetzte_kosten_min,
    f.ki_geschaetzte_kosten_max,
    f.kanzlei_ansprechpartner_name,
    f.kanzlei_ansprechpartner_email,
    f.kanzlei_ansprechpartner_telefon,
    f.kanzlei_ansprechpartner_position,
    f.mandatsnummer,
    f.losfahren_erinnerung_gesendet,
    f.termin_erinnerung_5min_gesendet,
    f.geschaetzte_fahrzeit_min,
    f.geschaetzte_fahrdistanz_km,
    f.gcal_event_id,
    f.gutachten_vorhanden,
    f.gutachten_hochgeladen_am,
    f.gutachten_positionen,
    f.gutachten_nummer,
    f.reparaturkosten,
    f.wertminderung,
    f.nutzungsausfall_gesamt,
    f.regulierungsweise,
    f.gegner_versicherungsnummer,
    f.sa_unterschrieben,
    f.sa_unterschrieben_am,
    f.sa_pdf_url,
    f.sa_unterschrift_url,
    f.datenschutz_akzeptiert,
    f.datenschutz_akzeptiert_am,
    f.vollmacht_status,
    f.polizei_vor_ort,
    f.unfallhergang,
    f.unfallmitteilung_status,
    f.unfallort,
    f.unfalldatum,
    f.interne_notizen,
    f.anschlussschreiben_url,
    f.anschlussschreiben_sendedatum,
    f.anschlussschreiben_unterschrift,
    f.anschlussschreiben_ocr_am,
    f.besichtigungsort_adresse,
    f.besichtigungsort_lat,
    f.besichtigungsort_lng,
    f.besichtigungsort_place_id,
    f.ist_aktiv,
    f.deaktiviert_am,
    f.deaktiviert_grund,
    f.deaktiviert_notiz,
    f.szenario,
    f.ruege_erhalten_am,
    f.ruege_grund,
    f.fahrzeug_farbe,
    f.erstzulassung,
    f.kilometerstand,
    f.firma_name,
    f.marketing_quelle,
    f.marketing_provision,
    f.marketing_provision_status,
    f.gutachten_stundensatz,
    f.kanzlei_id,
    f.kanzlei_honorar,
    f.zahlung_erwartet_am,
    f.zahlung_betrag,
    f.lead_preis_netto,
    f.lead_preis_typ,
    f.lead_preis_berechnet_am,
    f.guthaben_verrechnet_netto,
    f.sv_nachzahlung_netto,
    f.abrechnung_id,
    f.storniert_am,
    f.storno_grund,
    f.storno_durch_user_id,
    f.no_show_gemeldet_am,
    f.spezifikation,
    f.schadens_art,
    f.organisation_id,
    f.aktuelle_phase,
    f.dokumente_vollstaendig_fuer_phase,
    f.dokumente_vollstaendig_am_phase,
    f.unfall_konstellation,
    f.gegner_anzahl_beteiligte,
    f.gegner_fahrzeugtyp,
    f.dokumente_reminder_whatsapp_letzte_sendung,
    f.fin_vin,
    f.source_channel,
    f.source_domain,
    f.schadens_ursache,
    f.kanzlei_abrechnung_id,
    f.kanzlei_provision_status,
    f.kanzlei_provision_ausgezahlt_am,
    f.service_typ,
    f.vs_reaktion_typ,
    f.vs_reaktion_am,
    f.vs_ablehnungsgrund,
    f.ruege_gesendet_am,
    f.ruege_betrag,
    f.no_show_count,
    f.kuerzungs_betrag,
    f.vs_frist_bis,
    f.ruege_counter,
    f.schlussabrechnung_am,
    f.iban,
    f.bic,
    f.kontoinhaber,
    f.bankdaten_hinterlegt_am,
    f.ist_fahrzeughalter,
    f.finanzierung_leasing,
    f.vorsteuerabzugsberechtigt,
    f.schadens_hergang,
    f.halter_vorname,
    f.halter_nachname,
    f.halter_strasse,
    f.halter_plz,
    f.halter_stadt,
    f.halter_telefon,
    f.halter_email,
    f.finanzierungsgeber_name,
    f.finanzierungsgeber_adresse,
    f.finanzierungsgeber_vertragsnr,
    f.zahlungsweg,
    f.hat_vorschaeden,
    f.vorschaeden_beschreibung,
    f.technische_stellungnahme_status,
    f.technische_stellungnahme_beauftragt_am,
    f.technische_stellungnahme_hochgeladen_am,
    f.technische_stellungnahme_freigabe_am,
    f.nachbesichtigung_status,
    f.nachbesichtigung_angefordert_am,
    f.nachbesichtigung_termin_datum,
    f.nachbesichtigung_konfrontation,
    f.as_geforderte_summe,
    f.as_frist,
    f.as_vs_reaktion_text,
    f.as_salesforce_id,
    f.as_zuletzt_synced_am,
    f.lexdrive_case_id,
    f.eskalation_tag_14_am,
    f.eskalation_tag_21_am,
    f.eskalation_tag_28_am,
    f.unfallort_kategorie,
    f.unfallskizze_url,
    f.fahrzeug_ausstattung,
    f.cardentity_enriched_at,
    f.cardentity_report,
    f.vollmacht_geprueft_am,
    f.vollmacht_geprueft_von,
    f.vollmacht_pruefung_status,
    f.vollmacht_pruefung_begruendung,
    f.lexdrive_ocr_data,
    f.lexdrive_ocr_received_at,
    f.vs_kuerzung_grund,
    f.geschlossen_grund,
    f.nachbesichtigung_ergebnis,
    f.bevorzugter_kanal,
    f.gegner_versicherung_id,
    f.zeugen_kontakte,
    f.werkstatt_seit_datum,
    f.fahrzeug_fahrbereit,
    f.nutzungsausfall,
    f.mietwagen_kanzlei_informiert,
    f.mietwagen_kanzlei_informiert_am,
    f.halter_geburtsdatum,
    f.abrechnungsart_besprochen,
    f.abrechnungsart_notiz,
    f.abrechnungsart_besprochen_am,
    f.gegner_versicherung_anfrage_datum,
    f.sprache,
    f.unfallskizze_svg,
    f.unfallskizze_bestaetigt,
    f.unfallskizze_ablehnung_grund,
    f.unfallskizze_generiert_am,
    f.zeugen_vorhanden,
    f.vorschaden_erkannt,
    f.sv_termin_dokument_reminder_gesendet_am,
    f.kundenbetreuer_fallback_flag,
    f.kundenbetreuer_zugewiesen_am,
    f.sv_briefing_text,
    f.sv_briefing_generated_at,
    f.sv_briefing_model,
    f.sv_briefing_version,
    f.sv_briefing_struktur,
    f.sv_notizen_vor_ort,
    f.makler_id,
    f.sachschaden_flag,
    f.sachschaden_beschreibung,
    f.gegner_schadennummer,
    f.halter_name,
    f.wunschtermin,
    t.id AS aktueller_termin_id,
    t.start_zeit AS aktueller_termin_start,
    t.end_zeit AS aktueller_termin_end,
    t.status AS aktueller_termin_status,
    t.sv_id AS aktueller_termin_sv_id,
    t.kanal AS aktueller_termin_kanal,
    t.typ AS aktueller_termin_typ,
    t.final_verbindlich_ab AS aktueller_termin_final_verbindlich_ab,
    t.start_zeit AS sv_termin,
    t.status AS gutachter_termin_status,
    t.status = 'bestaetigt'::text AS gutachter_termin_bestaetigt,
    t.vorgeschlagenes_datum AS gutachter_gegenvorschlag_datum,
    t.gegenvorschlag_grund AS gutachter_gegenvorschlag_grund
   FROM faelle f
     LEFT JOIN LATERAL (
       SELECT gt.id, gt.sv_id, gt.fall_id, gt.start_zeit, gt.end_zeit,
              gt.status, gt.externer_kalender_id, gt.ablehnungsgrund,
              gt.gegenvorschlag_zeit, gt.created_at,
              gt.erinnerung_24h_gesendet, gt.erinnerung_2h_gesendet,
              gt.erinnerung_48h_docs_gesendet, gt.ankunft_zeit,
              gt.abschluss_zeit, gt.uebersprungen, gt.uebersprung_grund,
              gt.notizen_vor_ort, gt.gps_lat_ankunft, gt.gps_lng_ankunft,
              gt.lead_id, gt.ablehnen_token, gt.abgelehnt_am,
              gt.abgelehnt_grund, gt.vorgeschlagenes_datum,
              gt.gegenvorschlag_grund, gt.gegenvorschlag_von,
              gt.ankunft_via, gt.verspaetung_minuten, gt.losgefahren_am,
              gt.kunden_tracking_token, gt.notification_losgefahren_gesendet_am,
              gt.notification_5min_gesendet_am, gt.notification_angekommen_gesendet_am,
              gt.ablehnen_token_expires_at, gt.final_verbindlich_ab,
              gt.sv_ablehnung_grund, gt.sv_ablehnung_am,
              gt.sv_vorgeschlagene_slots, gt.typ, gt.kanal, gt.video_link,
              gt.kb_id, gt.notiz_kunde, gt.notiz_intern, gt.reminder_sent_at,
              gt.reminder_1h_sent_at, gt.cancelled_at,
              gt.navigation_started_at, gt.sv_unterwegs_seit,
              gt.sv_eta_minuten, gt.sv_eta_letzte_berechnung,
              gt.sv_angekommen_am, gt.reminder_15min_sent_at,
              gt.reminder_5min_sent_at, gt.durchgefuehrt_am,
              gt.kunde_tracking_aktiviert, gt.kunde_losgefahren_am,
              gt.kunde_eta_minuten, gt.kunde_eta_letzte_berechnung,
              gt.kunde_angekommen_am, gt.kunde_verspaetung_gemeldet_am
         FROM gutachter_termine gt
        WHERE gt.fall_id = f.id
          AND gt.status = ANY (ARRAY['bestaetigt'::text, 'reserviert'::text, 'durchgefuehrt'::text, 'gegenvorschlag'::text])
        ORDER BY (
          CASE gt.status
            WHEN 'bestaetigt'::text THEN 1
            WHEN 'gegenvorschlag'::text THEN 2
            WHEN 'reserviert'::text THEN 3
            WHEN 'durchgefuehrt'::text THEN 4
            ELSE 5
          END), gt.start_zeit DESC NULLS LAST
        LIMIT 1) t ON true;
