-- Portal-i18n Config-Seed (Delta 2/3): onboarding_felder.i18n fuer 64
-- customer-facing Wizard-Felder (audience beide/kunde) in en/tr/pl/ru/ar.
-- de bleibt Basis-Fallback (Spalten label/hint/placeholder/optionen). Subagent-uebersetzt + validiert.
-- Guarded (nur wo i18n noch leer) -> idempotent, kollidiert nicht mit Parallel-Seeds.

UPDATE onboarding_felder SET i18n = '{"en":{"label":"TSN","placeholder":"3 characters"},"tr":{"label":"TSN","placeholder":"3 karakter"},"pl":{"label":"TSN","placeholder":"3 znaki"},"ru":{"label":"TSN","placeholder":"3 символа"},"ar":{"label":"TSN","placeholder":"3 أحرف"}}'::jsonb
  WHERE id = 'afea0f11-f3f1-4782-bcff-6fe73c6fe050' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Paint detail","placeholder":"e.g. Sapphire Black Metallic"},"tr":{"label":"Renk Detayı","placeholder":"örn. Safir Siyahı Metalik"},"pl":{"label":"Kolor lakieru","placeholder":"np. Szafirowa czerń metalik"},"ru":{"label":"Цвет кузова","placeholder":"напр. сапфирово-чёрный металлик"},"ar":{"label":"تفاصيل اللون","placeholder":"مثال: أسود صفيري معدني"}}'::jsonb
  WHERE id = '94c79b6c-52e9-4d12-8f5a-156413d4e861' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Vehicle drivable?","optionen":{"true":{"label":"Yes"},"false":{"label":"No"}}},"tr":{"label":"Araç sürülebilir mi?","optionen":{"true":{"label":"Evet"},"false":{"label":"Hayır"}}},"pl":{"label":"Pojazd sprawny?","optionen":{"true":{"label":"Tak"},"false":{"label":"Nie"}}},"ru":{"label":"Автомобиль на ходу?","optionen":{"true":{"label":"Да"},"false":{"label":"Нет"}}},"ar":{"label":"هل السيارة صالحة للقيادة؟","optionen":{"true":{"label":"نعم"},"false":{"label":"لا"}}}}'::jsonb
  WHERE id = '9d41a0fd-daac-49b3-a3a3-3698a10b1fd6' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Customer = registered keeper?","optionen":{"true":{"label":"Yes"},"false":{"label":"No"}}},"tr":{"label":"Müşteri = Araç sahibi mi?","optionen":{"true":{"label":"Evet"},"false":{"label":"Hayır"}}},"pl":{"label":"Klient = właściciel pojazdu?","optionen":{"true":{"label":"Tak"},"false":{"label":"Nie"}}},"ru":{"label":"Клиент = владелец ТС?","optionen":{"true":{"label":"Да"},"false":{"label":"Нет"}}},"ar":{"label":"هل العميل هو مالك السيارة؟","optionen":{"true":{"label":"نعم"},"false":{"label":"لا"}}}}'::jsonb
  WHERE id = '0a86490f-28ed-49fb-acf7-43d9f199a31d' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Keeper first name"},"tr":{"label":"Araç Sahibi Adı"},"pl":{"label":"Imię właściciela"},"ru":{"label":"Имя владельца"},"ar":{"label":"الاسم الأول للمالك"}}'::jsonb
  WHERE id = '52cf3caa-34bb-41a7-a39a-c90d6c38a36e' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Keeper last name"},"tr":{"label":"Araç Sahibi Soyadı"},"pl":{"label":"Nazwisko właściciela"},"ru":{"label":"Фамилия владельца"},"ar":{"label":"اسم العائلة للمالك"}}'::jsonb
  WHERE id = '01aeb6b2-b6e5-45e3-b99d-b6e8c59c2833' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Keeper date of birth","placeholder":"YYYY-MM-DD"},"tr":{"label":"Araç Sahibi Doğum Tarihi","placeholder":"YYYY-AA-GG"},"pl":{"label":"Data urodzenia właściciela","placeholder":"RRRR-MM-DD"},"ru":{"label":"Дата рождения владельца","placeholder":"ГГГГ-ММ-ДД"},"ar":{"label":"تاريخ ميلاد المالك","placeholder":"YYYY-MM-DD"}}'::jsonb
  WHERE id = 'cf51b69e-1936-4599-9f89-d40a41a0bcf1' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Keeper street address"},"tr":{"label":"Araç Sahibi Sokak"},"pl":{"label":"Ulica właściciela"},"ru":{"label":"Улица владельца"},"ar":{"label":"شارع المالك"}}'::jsonb
  WHERE id = '60602b72-ec61-4870-b829-26dcf12e47a1' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Keeper postal code"},"tr":{"label":"Araç Sahibi Posta Kodu"},"pl":{"label":"Kod pocztowy właściciela"},"ru":{"label":"Индекс владельца"},"ar":{"label":"الرمز البريدي للمالك"}}'::jsonb
  WHERE id = '5faa664f-71a5-4f5b-bc96-c21067460bde' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Keeper city"},"tr":{"label":"Araç Sahibi Şehir"},"pl":{"label":"Miejscowość właściciela"},"ru":{"label":"Город владельца"},"ar":{"label":"مدينة المالك"}}'::jsonb
  WHERE id = '3d8606a1-7ea7-4815-9560-37cb82c83a83' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Fault","optionen":{"gegner":{"label":"The other party"},"unklar":{"label":"Not yet clear"},"eigenverantwortung":{"label":"Myself"}}},"tr":{"label":"Kusur Durumu","optionen":{"gegner":{"label":"Karşı taraf"},"unklar":{"label":"Henüz belirsiz"},"eigenverantwortung":{"label":"Ben kendim"}}},"pl":{"label":"Wina","optionen":{"gegner":{"label":"Druga strona"},"unklar":{"label":"Niejasne"},"eigenverantwortung":{"label":"Ja sam/sama"}}},"ru":{"label":"Виновник ДТП","optionen":{"gegner":{"label":"Другая сторона"},"unklar":{"label":"Пока неясно"},"eigenverantwortung":{"label":"Я сам"}}},"ar":{"label":"مسؤولية الحادث","optionen":{"gegner":{"label":"الطرف الآخر"},"unklar":{"label":"غير محدد"},"eigenverantwortung":{"label":"أنا المسؤول"}}}}'::jsonb
  WHERE id = 'd4f92530-c6c4-4782-bb83-a12a5f664202' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Service scope","hint":"With \"Full service\" we work together with our partner law firm LexDrive — free of charge for you.","optionen":{"komplett":{"label":"Full service (recommended)","description":"Lawyer + power of attorney included — €0, we handle everything for you"},"nur_gutachter":{"label":"Expert report only","description":"You settle directly with the opposing insurance yourself"}}},"tr":{"label":"Hizmet Kapsamı","hint":"\"Tam hizmet\" seçeneğinde LexDrive ortak hukuk bürosuyla çalışırız — sizin için ücretsizdir.","optionen":{"komplett":{"label":"Tam hizmet (önerilir)","description":"Avukat + vekâletname dahil — 0 EUR, her şeyi sizin için hallederiz"},"nur_gutachter":{"label":"Yalnızca bilirkişi raporu","description":"Karşı tarafın sigortasıyla kendiniz tazminat talep edersiniz"}}},"pl":{"label":"Zakres usługi","hint":"Przy wyborze „Kompleksowej obsługi” współpracujemy z naszą kancelarią partnerską LexDrive — bezpłatnie dla Państwa.","optionen":{"komplett":{"label":"Obsługa kompleksowa (zalecana)","description":"Adwokat + pełnomocnictwo w cenie — 0 EUR, załatwiamy wszystko za Państwa"},"nur_gutachter":{"label":"Tylko ekspertyza","description":"Państwo samodzielnie regulują szkodę z ubezpieczeniem sprawcy"}}},"ru":{"label":"Объём услуг","hint":"При выборе «Полный сервис» мы работаем с нашей партнёрской юридической фирмой LexDrive — бесплатно для Вас.","optionen":{"komplett":{"label":"Полный сервис (рекомендуется)","description":"Юрист + доверенность включены — 0 EUR, мы берём всё на себя"},"nur_gutachter":{"label":"Только заключение","description":"Вы самостоятельно урегулируете ущерб со страховой виновника"}}},"ar":{"label":"نطاق الخدمة","hint":"عند اختيار «الخدمة الشاملة» نتعاون مع شركة المحاماة الشريكة LexDrive — مجاناً بالنسبة لك.","optionen":{"komplett":{"label":"خدمة شاملة (موصى بها)","description":"محامي + توكيل مشمول — 0 يورو، نتولى كل شيء نيابةً عنك"},"nur_gutachter":{"label":"تقرير خبير فقط","description":"تتولى التسوية بنفسك مع شركة تأمين الطرف الآخر"}}}}'::jsonb
  WHERE id = '10ded825-fdf7-47d1-9779-841d2c519bec' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Lawyer choice","optionen":{"partnerkanzlei":{"label":"Our partner law firm (recommended)","description":"LexDrive — specialised in car damage claims, €0 for you, they handle the power of attorney and everything else"},"eigene_kanzlei":{"label":"My own law firm","description":"You provide the contact details and we hand over the file"},"keine_kanzlei":{"label":"No lawyer","description":"You settle yourself — no legal support"}}},"tr":{"label":"Avukat Seçimi","optionen":{"partnerkanzlei":{"label":"Ortak hukuk büromuz (önerilir)","description":"LexDrive — araç hasarlarında uzman, sizin için 0 EUR, vekâletname ve diğer tüm işlemleri üstlenir"},"eigene_kanzlei":{"label":"Kendi hukuk bürom","description":"İletişim bilgilerini bize verin, dosyayı biz iletiyoruz"},"keine_kanzlei":{"label":"Avukat istemiyorum","description":"Kendiniz tazminat talep edersiniz — avukatsız"}}},"pl":{"label":"Wybór adwokata","optionen":{"partnerkanzlei":{"label":"Nasza kancelaria partnerska (zalecana)","description":"LexDrive — specjalizacja w szkodach komunikacyjnych, 0 EUR dla Państwa, zajmują się pełnomocnictwem i wszystkim innym"},"eigene_kanzlei":{"label":"Moja własna kancelaria","description":"Proszę podać dane kontaktowe, my przekazujemy dokumentację"},"keine_kanzlei":{"label":"Bez adwokata","description":"Państwo regulują szkodę samodzielnie — bez obsługi prawnej"}}},"ru":{"label":"Выбор юриста","optionen":{"partnerkanzlei":{"label":"Наша партнёрская фирма (рекомендуется)","description":"LexDrive — специализация на Kfz-ущербе, 0 EUR для Вас, занимаются доверенностью и всем остальным"},"eigene_kanzlei":{"label":"Моя собственная юридическая фирма","description":"Вы предоставляете контактные данные, мы передаём пакет документов"},"keine_kanzlei":{"label":"Без юриста","description":"Вы урегулируете самостоятельно — без юридического сопровождения"}}},"ar":{"label":"اختيار المحامي","optionen":{"partnerkanzlei":{"label":"مكتبنا الشريك (موصى به)","description":"LexDrive — متخصص في أضرار السيارات، 0 يورو لك، يتولى التوكيل وكل الإجراءات"},"eigene_kanzlei":{"label":"مكتبي الخاص","description":"أعطنا بيانات التواصل وسنسلّم الملف"},"keine_kanzlei":{"label":"بدون محامي","description":"تتولى التسوية بنفسك — دون مرافقة قانونية"}}}}'::jsonb
  WHERE id = '43ba0f07-a163-45a8-b13c-80442c925ec6' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Inspection address","placeholder":"Where is the vehicle located?"},"tr":{"label":"Ekspertiz Adresi","placeholder":"Araç nerede bulunuyor?"},"pl":{"label":"Adres oględzin","placeholder":"Gdzie stoi pojazd?"},"ru":{"label":"Адрес осмотра","placeholder":"Где находится автомобиль?"},"ar":{"label":"عنوان المعاينة","placeholder":"أين توجد السيارة؟"}}'::jsonb
  WHERE id = '79585c4a-d721-4cee-b584-2eefe025015b' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Meeting point note","placeholder":"e.g. rear entrance, key at workshop"},"tr":{"label":"Buluşma Notu","placeholder":"örn. Arka giriş, anahtar tamirhanede"},"pl":{"label":"Uwaga do miejsca spotkania","placeholder":"np. Wejście tylne, klucz w warsztacie"},"ru":{"label":"Заметка о месте встречи","placeholder":"напр. задний вход, ключ на СТО"},"ar":{"label":"ملاحظة موضع اللقاء","placeholder":"مثال: المدخل الخلفي، المفتاح في الورشة"}}'::jsonb
  WHERE id = '191014de-d4c7-43db-aada-44771d40b3e8' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Preferred appointment"},"tr":{"label":"Tercih Edilen Tarih"},"pl":{"label":"Preferowany termin"},"ru":{"label":"Желаемая дата"},"ar":{"label":"الموعد المفضل"}}'::jsonb
  WHERE id = '457a5c53-62fd-4600-83fe-54937330a422' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Appraiser inspection appointment"},"tr":{"label":"Bilirkişi Ekspertiz Randevusu"},"pl":{"label":"Termin oględzin rzeczoznawcy"},"ru":{"label":"Дата осмотра экспертом-оценщиком"},"ar":{"label":"موعد معاينة خبير التقييم"}}'::jsonb
  WHERE id = 'f2430924-1589-48c7-a891-7c6dd66c635f' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Damage report (SA) — Signature"},"tr":{"label":"Hasar Bildirimi (SA) — İmza"},"pl":{"label":"Zgłoszenie szkody (SA) — podpis"},"ru":{"label":"Уведомление об ущербе (SA) — подпись"},"ar":{"label":"إشعار الضرر (SA) — التوقيع"}}'::jsonb
  WHERE id = '3dbe5fa1-930f-452d-a3ca-04923faf1e18' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Vehicle registration document (ZB1) — Photo"},"tr":{"label":"Araç Ruhsatı (ZB1) — Fotoğraf"},"pl":{"label":"Dowód rejestracyjny (ZB1) — zdjęcie"},"ru":{"label":"Свидетельство о регистрации ТС (ZB1) — фото"},"ar":{"label":"رخصة السيارة (ZB1) — صورة"}}'::jsonb
  WHERE id = 'd398abd9-8987-452b-bdbd-ff9453c920ac' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Postal code"},"tr":{"label":"Posta Kodu"},"pl":{"label":"Kod pocztowy"},"ru":{"label":"Индекс"},"ar":{"label":"الرمز البريدي"}}'::jsonb
  WHERE id = 'c9a8200c-2737-4792-8939-254997ab6342' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"City"},"tr":{"label":"Şehir"},"pl":{"label":"Miejscowość"},"ru":{"label":"Город"},"ar":{"label":"المدينة"}}'::jsonb
  WHERE id = '52098329-79bd-40bf-ac8c-bb5c68b1ff5e' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"First name"},"tr":{"label":"Ad"},"pl":{"label":"Imię"},"ru":{"label":"Имя"},"ar":{"label":"الاسم الأول"}}'::jsonb
  WHERE id = '2df9b5a9-19aa-4dcb-ae22-6865b482efc8' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Last name"},"tr":{"label":"Soyad"},"pl":{"label":"Nazwisko"},"ru":{"label":"Фамилия"},"ar":{"label":"اسم العائلة"}}'::jsonb
  WHERE id = '6568f566-765a-4fba-84e7-49c81aa77e62' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Phone"},"tr":{"label":"Telefon"},"pl":{"label":"Telefon"},"ru":{"label":"Телефон"},"ar":{"label":"الهاتف"}}'::jsonb
  WHERE id = 'efbcd823-cdc3-4838-9850-3d2c8399d4b6' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Email"},"tr":{"label":"E-posta"},"pl":{"label":"E-mail"},"ru":{"label":"Эл. почта"},"ar":{"label":"البريد الإلكتروني"}}'::jsonb
  WHERE id = '3c8cf312-e9cb-400d-8c8a-6a48ef2eaac2' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Street address"},"tr":{"label":"Sokak"},"pl":{"label":"Ulica"},"ru":{"label":"Улица"},"ar":{"label":"الشارع"}}'::jsonb
  WHERE id = '00c13c3e-d760-4681-aad1-656b3307f580' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Preferred channel","optionen":{"whatsapp":{"label":"WhatsApp"},"sms":{"label":"SMS"},"email":{"label":"Email"}}},"tr":{"label":"Tercih Edilen İletişim Kanalı","optionen":{"whatsapp":{"label":"WhatsApp"},"sms":{"label":"SMS"},"email":{"label":"E-posta"}}},"pl":{"label":"Preferowany kanał kontaktu","optionen":{"whatsapp":{"label":"WhatsApp"},"sms":{"label":"SMS"},"email":{"label":"E-mail"}}},"ru":{"label":"Предпочтительный канал","optionen":{"whatsapp":{"label":"WhatsApp"},"sms":{"label":"SMS"},"email":{"label":"Эл. почта"}}},"ar":{"label":"قناة التواصل المفضلة","optionen":{"whatsapp":{"label":"WhatsApp"},"sms":{"label":"SMS"},"email":{"label":"البريد الإلكتروني"}}}}'::jsonb
  WHERE id = '3896b0d3-16e6-45e4-b7a8-f24303ea313c' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Damage type","optionen":{"spurwechsel":{"label":"Lane change"},"auffahrunfall":{"label":"Rear-end collision"},"vorfahrtsverletzung":{"label":"Failure to yield"},"parkplatz":{"label":"Car park"},"sonstiges":{"label":"Other"}}},"tr":{"label":"Hasar Türü","optionen":{"spurwechsel":{"label":"Şerit değiştirme"},"auffahrunfall":{"label":"Arkadan çarpma"},"vorfahrtsverletzung":{"label":"Öncelik ihlali"},"parkplatz":{"label":"Otopark"},"sonstiges":{"label":"Diğer"}}},"pl":{"label":"Rodzaj szkody","optionen":{"spurwechsel":{"label":"Zmiana pasa ruchu"},"auffahrunfall":{"label":"Najechanie na tył"},"vorfahrtsverletzung":{"label":"Naruszenie pierwszeństwa"},"parkplatz":{"label":"Parking"},"sonstiges":{"label":"Inne"}}},"ru":{"label":"Тип ДТП","optionen":{"spurwechsel":{"label":"Смена полосы"},"auffahrunfall":{"label":"Наезд сзади"},"vorfahrtsverletzung":{"label":"Нарушение приоритета проезда"},"parkplatz":{"label":"На парковке"},"sonstiges":{"label":"Прочее"}}},"ar":{"label":"نوع الحادث","optionen":{"spurwechsel":{"label":"تغيير المسار"},"auffahrunfall":{"label":"اصطدام من الخلف"},"vorfahrtsverletzung":{"label":"عدم احترام الأولوية"},"parkplatz":{"label":"موقف السيارات"},"sonstiges":{"label":"أخرى"}}}}'::jsonb
  WHERE id = '89964d78-5a5c-460d-85e4-443feab8ce86' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Description","placeholder":"What exactly happened?"},"tr":{"label":"Açıklama","placeholder":"Tam olarak ne oldu?"},"pl":{"label":"Opis","placeholder":"Co dokładnie się wydarzyło?"},"ru":{"label":"Описание","placeholder":"Что именно произошло?"},"ar":{"label":"الوصف","placeholder":"ماذا حدث بالضبط؟"}}'::jsonb
  WHERE id = 'c1e43a20-a38f-4676-8ea3-b365d2e0972a' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Visible damage?","optionen":{"true":{"label":"Yes"},"false":{"label":"No"}}},"tr":{"label":"Görünür hasar var mı?","optionen":{"true":{"label":"Evet"},"false":{"label":"Hayır"}}},"pl":{"label":"Widoczna szkoda?","optionen":{"true":{"label":"Tak"},"false":{"label":"Nie"}}},"ru":{"label":"Видимые повреждения?","optionen":{"true":{"label":"Да"},"false":{"label":"Нет"}}},"ar":{"label":"ضرر مرئي؟","optionen":{"true":{"label":"نعم"},"false":{"label":"لا"}}}}'::jsonb
  WHERE id = '46d4a43e-7866-417e-927a-716543ad88ab' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Course of the accident","placeholder":"How did it happen?"},"tr":{"label":"Kaza Seyri","placeholder":"Nasıl oldu?"},"pl":{"label":"Przebieg wypadku","placeholder":"Jak doszło do zdarzenia?"},"ru":{"label":"Обстоятельства ДТП","placeholder":"Как это произошло?"},"ar":{"label":"مجريات الحادث","placeholder":"كيف حدث ذلك؟"}}'::jsonb
  WHERE id = '1966c077-5774-493d-a8ce-e9a980e89471' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Damage description (vehicle)","placeholder":"What is damaged on the vehicle?"},"tr":{"label":"Hasar Açıklaması (Araç)","placeholder":"Araçta ne hasar gördü?"},"pl":{"label":"Opis uszkodzeń pojazdu","placeholder":"Co zostało uszkodzone w samochodzie?"},"ru":{"label":"Описание повреждений (автомобиль)","placeholder":"Что повреждено на автомобиле?"},"ar":{"label":"وصف الأضرار (السيارة)","placeholder":"ما الذي تضرر في السيارة؟"}}'::jsonb
  WHERE id = '581ee1f5-009e-40ac-9765-f2dfe5c05b08' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Personal injury?","optionen":{"true":{"label":"Yes"},"false":{"label":"No"}}},"tr":{"label":"Kişisel yaralanma var mı?","optionen":{"true":{"label":"Evet"},"false":{"label":"Hayır"}}},"pl":{"label":"Obrażenia osób?","optionen":{"true":{"label":"Tak"},"false":{"label":"Nie"}}},"ru":{"label":"Пострадавшие люди?","optionen":{"true":{"label":"Да"},"false":{"label":"Нет"}}},"ar":{"label":"إصابات بشرية؟","optionen":{"true":{"label":"نعم"},"false":{"label":"لا"}}}}'::jsonb
  WHERE id = '73a4568a-bb36-49a5-b28a-08d6e288e49a' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Third-party property damage?","optionen":{"true":{"label":"Yes"},"false":{"label":"No"}}},"tr":{"label":"Üçüncü şahıslarda maddi hasar?","optionen":{"true":{"label":"Evet"},"false":{"label":"Hayır"}}},"pl":{"label":"Szkody rzeczowe u osób trzecich?","optionen":{"true":{"label":"Tak"},"false":{"label":"Nie"}}},"ru":{"label":"Имущественный ущерб третьим лицам?","optionen":{"true":{"label":"Да"},"false":{"label":"Нет"}}},"ar":{"label":"أضرار مادية لأطراف أخرى؟","optionen":{"true":{"label":"نعم"},"false":{"label":"لا"}}}}'::jsonb
  WHERE id = 'cdd77618-f7ba-4dbb-9aa5-df4114dedc4a' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"What was damaged?","placeholder":"e.g. crash barrier, phone …"},"tr":{"label":"Ne hasar gördü?","placeholder":"örn. Bariyerler, telefon …"},"pl":{"label":"Co zostało uszkodzone?","placeholder":"np. Bariera, telefon …"},"ru":{"label":"Что повреждено?","placeholder":"напр. ограждение, телефон …"},"ar":{"label":"ما الذي تضرر؟","placeholder":"مثال: حاجز أمان، هاتف …"}}'::jsonb
  WHERE id = '0966bae1-fd87-4cd2-b0b3-2b088799707c' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Rental car requested?","optionen":{"true":{"label":"Yes"},"false":{"label":"No"}}},"tr":{"label":"Kiralık araç isteniyor mu?","optionen":{"true":{"label":"Evet"},"false":{"label":"Hayır"}}},"pl":{"label":"Wynajem auta?","optionen":{"true":{"label":"Tak"},"false":{"label":"Nie"}}},"ru":{"label":"Нужен прокатный автомобиль?","optionen":{"true":{"label":"Да"},"false":{"label":"Нет"}}},"ar":{"label":"هل تريد سيارة بديلة؟","optionen":{"true":{"label":"نعم"},"false":{"label":"لا"}}}}'::jsonb
  WHERE id = '523ffb44-5e33-4a0f-ae60-979aac7d3c24' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Loss of use?","optionen":{"true":{"label":"Yes"},"false":{"label":"No"}}},"tr":{"label":"Kullanım kaybı?","optionen":{"true":{"label":"Evet"},"false":{"label":"Hayır"}}},"pl":{"label":"Utrata możliwości użytkowania?","optionen":{"true":{"label":"Tak"},"false":{"label":"Nie"}}},"ru":{"label":"Потеря пользования?","optionen":{"true":{"label":"Да"},"false":{"label":"Нет"}}},"ar":{"label":"فقدان الاستخدام؟","optionen":{"true":{"label":"نعم"},"false":{"label":"لا"}}}}'::jsonb
  WHERE id = '6b3406ad-7d35-4c37-b1c5-06f6816cf986' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Damage photos"},"tr":{"label":"Hasar Fotoğrafları"},"pl":{"label":"Zdjęcia szkód"},"ru":{"label":"Фотографии повреждений"},"ar":{"label":"صور الأضرار"}}'::jsonb
  WHERE id = '2395203f-ef1c-407a-b350-babfdd4283b2' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Pre-existing damage known?","optionen":{"true":{"label":"Yes"},"false":{"label":"No"}}},"tr":{"label":"Önceki hasar biliniyor mu?","optionen":{"true":{"label":"Evet"},"false":{"label":"Hayır"}}},"pl":{"label":"Znane szkody poprzednie?","optionen":{"true":{"label":"Tak"},"false":{"label":"Nie"}}},"ru":{"label":"Известны предыдущие повреждения?","optionen":{"true":{"label":"Да"},"false":{"label":"Нет"}}},"ar":{"label":"أضرار سابقة معروفة؟","optionen":{"true":{"label":"نعم"},"false":{"label":"لا"}}}}'::jsonb
  WHERE id = 'b010a14e-f4be-452c-b5d8-623d805b47ad' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Pre-existing damage description","placeholder":"Area / damage extent"},"tr":{"label":"Önceki Hasar Açıklaması","placeholder":"Bölge / Hasar miktarı"},"pl":{"label":"Opis szkód poprzednich","placeholder":"Miejsce / wysokość szkody"},"ru":{"label":"Описание предыдущих повреждений","placeholder":"Зона / сумма ущерба"},"ar":{"label":"وصف الأضرار السابقة","placeholder":"المنطقة / حجم الضرر"}}'::jsonb
  WHERE id = '52138078-1520-4f50-88b6-601a10ae8568' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Accident location","placeholder":"Address"},"tr":{"label":"Kaza Yeri","placeholder":"Adres"},"pl":{"label":"Miejsce wypadku","placeholder":"Adres"},"ru":{"label":"Место ДТП","placeholder":"Адрес"},"ar":{"label":"موقع الحادث","placeholder":"العنوان"}}'::jsonb
  WHERE id = '1266ce03-f974-4d2c-83d8-a1ebb8672246' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Accident date","placeholder":"YYYY-MM-DD"},"tr":{"label":"Kaza Tarihi","placeholder":"YYYY-AA-GG"},"pl":{"label":"Data wypadku","placeholder":"RRRR-MM-DD"},"ru":{"label":"Дата ДТП","placeholder":"ГГГГ-ММ-ДД"},"ar":{"label":"تاريخ الحادث","placeholder":"YYYY-MM-DD"}}'::jsonb
  WHERE id = 'ddf0b44e-d125-4c71-b148-d553fdc0d69f' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Accident time (approx.)","placeholder":"e.g. 14:30"},"tr":{"label":"Kaza Saati (yaklaşık)","placeholder":"örn. 14:30"},"pl":{"label":"Godzina wypadku (ok.)","placeholder":"np. 14:30"},"ru":{"label":"Время ДТП (прибл.)","placeholder":"напр. 14:30"},"ar":{"label":"وقت الحادث (تقريباً)","placeholder":"مثال: 14:30"}}'::jsonb
  WHERE id = 'e2b69efb-3d83-429a-a510-40e9625109bd' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Police on scene?","optionen":{"true":{"label":"Yes"},"false":{"label":"No"}}},"tr":{"label":"Polis olay yerinde miydi?","optionen":{"true":{"label":"Evet"},"false":{"label":"Hayır"}}},"pl":{"label":"Policja na miejscu?","optionen":{"true":{"label":"Tak"},"false":{"label":"Nie"}}},"ru":{"label":"Полиция на месте?","optionen":{"true":{"label":"Да"},"false":{"label":"Нет"}}},"ar":{"label":"هل كانت الشرطة في الموقع؟","optionen":{"true":{"label":"نعم"},"false":{"label":"لا"}}}}'::jsonb
  WHERE id = 'daa70804-f5ae-44cc-acf6-b32a48032e26' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Police reference number"},"tr":{"label":"Polis Dosya Numarası"},"pl":{"label":"Numer akt"},"ru":{"label":"Номер дела"},"ar":{"label":"رقم المحضر"}}'::jsonb
  WHERE id = '87f51e35-d0b9-4bb9-9ad5-dbfbed85a382' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Other party''s license plate","placeholder":"or leave blank for hit-and-run"},"tr":{"label":"Karşı Taraf Plakası","placeholder":"veya olay yeri terk edilmişse boş bırakın"},"pl":{"label":"Tablica rejestracyjna sprawcy","placeholder":"lub puste przy ucieczce z miejsca wypadku"},"ru":{"label":"Номерной знак виновника","placeholder":"или оставьте пустым при скрытии с места ДТП"},"ar":{"label":"لوحة الطرف الآخر","placeholder":"أو اتركه فارغاً في حالة الفرار"}}'::jsonb
  WHERE id = 'fa0ab15a-e8c2-4777-86fa-f8c3bd24e2ed' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Other party''s insurance"},"tr":{"label":"Karşı Taraf Sigortası"},"pl":{"label":"Ubezpieczenie sprawcy"},"ru":{"label":"Страховая виновника"},"ar":{"label":"تأمين الطرف الآخر"}}'::jsonb
  WHERE id = '18d73db3-04aa-45d1-a374-f10a42a816f3' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Claim number (other party)"},"tr":{"label":"Hasar Numarası (Karşı Taraf)"},"pl":{"label":"Numer szkody (sprawca)"},"ru":{"label":"Номер страхового случая (виновник)"},"ar":{"label":"رقم الضرر (الطرف الآخر)"}}'::jsonb
  WHERE id = '6a541a09-af89-43fa-aee7-73f0a3c71855' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Other party''s phone"},"tr":{"label":"Karşı Taraf Telefonu"},"pl":{"label":"Telefon sprawcy"},"ru":{"label":"Телефон виновника"},"ar":{"label":"هاتف الطرف الآخر"}}'::jsonb
  WHERE id = '81c7da8e-8549-4be9-bed0-42ad79d30126' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Other party''s email"},"tr":{"label":"Karşı Taraf E-postası"},"pl":{"label":"E-mail sprawcy"},"ru":{"label":"Эл. почта виновника"},"ar":{"label":"بريد الطرف الآخر الإلكتروني"}}'::jsonb
  WHERE id = '53d67e18-10a5-4d61-b84e-0c12384c4004' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Witnesses present?","optionen":{"true":{"label":"Yes"},"false":{"label":"No"}}},"tr":{"label":"Tanık var mı?","optionen":{"true":{"label":"Evet"},"false":{"label":"Hayır"}}},"pl":{"label":"Świadkowie?","optionen":{"true":{"label":"Tak"},"false":{"label":"Nie"}}},"ru":{"label":"Есть свидетели?","optionen":{"true":{"label":"Да"},"false":{"label":"Нет"}}},"ar":{"label":"هل يوجد شهود؟","optionen":{"true":{"label":"نعم"},"false":{"label":"لا"}}}}'::jsonb
  WHERE id = '80e7f9ce-d671-46e7-b17f-ce3481286839' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"License plate"},"tr":{"label":"Plaka"},"pl":{"label":"Tablica rejestracyjna"},"ru":{"label":"Номерной знак"},"ar":{"label":"لوحة الترخيص"}}'::jsonb
  WHERE id = 'b5d1c0cf-8477-46ff-bab9-abe57d0dec8c' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Make"},"tr":{"label":"Marka"},"pl":{"label":"Marka"},"ru":{"label":"Марка"},"ar":{"label":"الماركة"}}'::jsonb
  WHERE id = 'ff43de4e-5a3b-4a0b-a91a-597a16f4e096' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Model"},"tr":{"label":"Model"},"pl":{"label":"Model"},"ru":{"label":"Модель"},"ar":{"label":"الموديل"}}'::jsonb
  WHERE id = 'ff24ba73-6fea-412c-8e80-d95856b5c1af' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Year of manufacture"},"tr":{"label":"Üretim Yılı"},"pl":{"label":"Rok produkcji"},"ru":{"label":"Год выпуска"},"ar":{"label":"سنة الصنع"}}'::jsonb
  WHERE id = '5f4678b5-3e64-4466-a38a-aaa750ac6e40' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"FIN","placeholder":"17 characters"},"tr":{"label":"FIN","placeholder":"17 karakter"},"pl":{"label":"FIN","placeholder":"17 znaków"},"ru":{"label":"FIN","placeholder":"17 символов"},"ar":{"label":"FIN","placeholder":"17 حرفاً"}}'::jsonb
  WHERE id = 'd294d08b-fb3c-42cb-87da-6b97819a5dce' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"HSN","placeholder":"4 digits"},"tr":{"label":"HSN","placeholder":"4 rakam"},"pl":{"label":"HSN","placeholder":"4 cyfry"},"ru":{"label":"HSN","placeholder":"4 цифры"},"ar":{"label":"HSN","placeholder":"4 أرقام"}}'::jsonb
  WHERE id = 'de5cb462-ee79-4181-855b-806152e2ab8d' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Phone number","hint":"You will receive a code by SMS."},"tr":{"label":"Telefon Numarası","hint":"SMS ile bir doğrulama kodu alacaksınız."},"pl":{"label":"Numer telefonu","hint":"Otrzymają Państwo kod weryfikacyjny SMS-em."},"ru":{"label":"Номер телефона","hint":"Вы получите код по SMS."},"ar":{"label":"رقم الهاتف","hint":"ستتلقى رمز تحقق عبر SMS."}}'::jsonb
  WHERE id = '81641ce2-8fa8-488d-bf28-4b2a929a1055' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Address","placeholder":"1 Example St, 42103 Wuppertal"},"tr":{"label":"Adres","placeholder":"Musterstraße 1, 42103 Wuppertal"},"pl":{"label":"Adres","placeholder":"Musterstraße 1, 42103 Wuppertal"},"ru":{"label":"Адрес","placeholder":"Musterstraße 1, 42103 Wuppertal"},"ar":{"label":"العنوان","placeholder":"Musterstraße 1, 42103 Wuppertal"}}'::jsonb
  WHERE id = '1f05bc23-9992-4ea6-b20a-90fb460f8555' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Profile photo","hint":"Optional, but recommended."},"tr":{"label":"Profil Fotoğrafı","hint":"İsteğe bağlı, ancak önerilir."},"pl":{"label":"Zdjęcie profilowe","hint":"Opcjonalne, ale zalecane."},"ru":{"label":"Фото профиля","hint":"Необязательно, но рекомендуется."},"ar":{"label":"صورة الملف الشخصي","hint":"اختياري، لكن موصى به."}}'::jsonb
  WHERE id = '0e3d0a6b-306e-4594-9736-d478017d4e4f' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Short description","placeholder":"What are you specialised in?"},"tr":{"label":"Kısa Tanıtım","placeholder":"Uzmanlık alanınız nedir?"},"pl":{"label":"Krótki opis","placeholder":"W czym się Państwo specjalizują?"},"ru":{"label":"Краткое описание","placeholder":"На чём Вы специализируетесь?"},"ar":{"label":"نبذة مختصرة","placeholder":"ما هي تخصصاتك؟"}}'::jsonb
  WHERE id = 'a523c77f-d0bc-4bde-a028-23173a134c7b' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Calendar","hint":"Connect Google Calendar or CalDAV."},"tr":{"label":"Takvim","hint":"Google Takvim veya CalDAV bağlayın."},"pl":{"label":"Kalendarz","hint":"Podłącz Kalendarz Google lub CalDAV."},"ru":{"label":"Календарь","hint":"Подключите Google Календарь или CalDAV."},"ar":{"label":"التقويم","hint":"ربط Google Calendar أو CalDAV."}}'::jsonb
  WHERE id = 'f59c1766-f1b1-4c4a-b69b-1605d10bac58' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Signature"},"tr":{"label":"İmza"},"pl":{"label":"Podpis"},"ru":{"label":"Подпись"},"ar":{"label":"التوقيع"}}'::jsonb
  WHERE id = '9e2698d3-c845-4238-8679-224368879979' AND (i18n IS NULL OR i18n = '{}'::jsonb);
UPDATE onboarding_felder SET i18n = '{"en":{"label":"Foreign license plate (other party)?","optionen":{"true":{"label":"Yes"},"false":{"label":"No"}}},"tr":{"label":"Karşı tarafın yabancı plakası var mı?","optionen":{"true":{"label":"Evet"},"false":{"label":"Hayır"}}},"pl":{"label":"Zagraniczna tablica rejestracyjna sprawcy?","optionen":{"true":{"label":"Tak"},"false":{"label":"Nie"}}},"ru":{"label":"Иностранный номерной знак виновника?","optionen":{"true":{"label":"Да"},"false":{"label":"Нет"}}},"ar":{"label":"هل للطرف الآخر لوحة أجنبية؟","optionen":{"true":{"label":"نعم"},"false":{"label":"لا"}}}}'::jsonb
  WHERE id = '5384eb8c-ba9d-4c0e-b3a1-6ede52749c1d' AND (i18n IS NULL OR i18n = '{}'::jsonb);
