-- CMM-44 SP-A2 PR2 — 28 semantik-gleiche Duplikat-Spalten von faelle droppen.
-- claims ist SSoT. PR1a/b/c (Reader-Rename) sind auf main/prod -> kein App-Code
-- liest die 28 faelle-Spalten mehr. Reihenfolge: Backfill -> View-Repoint ->
-- DROP TRIGGER -> DROP COLUMN x28.
-- Spec:  docs/superpowers/specs/2026-05-17-cmm44-spa2-semantik-duplikate-design.md
-- Plan:  docs/superpowers/plans/2026-05-17-cmm44-spa2-semantik-duplikate.md

BEGIN;

-- ============================================================
-- BLOCK 1: Gap-Backfill — claims gewinnt, nur NULL-Luecken fuellen.
-- Kollisionsgruppen mit fester Quell-Prioritaet (erst-Spalte hat Vorrang).
-- ============================================================
UPDATE public.claims c SET schadenort_adresse = COALESCE(c.schadenort_adresse, f.schadens_adresse, f.unfallort)
  FROM public.faelle f WHERE f.claim_id = c.id AND c.schadenort_adresse IS NULL;
UPDATE public.claims c SET schadenort_plz = f.schadens_plz
  FROM public.faelle f WHERE f.claim_id = c.id AND c.schadenort_plz IS NULL AND f.schadens_plz IS NOT NULL;
UPDATE public.claims c SET schadenort_ort = f.schadens_ort
  FROM public.faelle f WHERE f.claim_id = c.id AND c.schadenort_ort IS NULL AND f.schadens_ort IS NOT NULL;
UPDATE public.claims c SET schadenort_kategorie = f.unfallort_kategorie
  FROM public.faelle f WHERE f.claim_id = c.id AND c.schadenort_kategorie IS NULL AND f.unfallort_kategorie IS NOT NULL;
UPDATE public.claims c SET schadenort_lat = f.unfallort_lat
  FROM public.faelle f WHERE f.claim_id = c.id AND c.schadenort_lat IS NULL AND f.unfallort_lat IS NOT NULL;
UPDATE public.claims c SET schadenort_lng = f.unfallort_lng
  FROM public.faelle f WHERE f.claim_id = c.id AND c.schadenort_lng IS NULL AND f.unfallort_lng IS NOT NULL;
UPDATE public.claims c SET schadentag = COALESCE(c.schadentag, f.schadens_datum, f.unfalldatum)
  FROM public.faelle f WHERE f.claim_id = c.id AND c.schadentag IS NULL;
UPDATE public.claims c SET entdeckt_am = f.schadens_entdeckt_am
  FROM public.faelle f WHERE f.claim_id = c.id AND c.entdeckt_am IS NULL AND f.schadens_entdeckt_am IS NOT NULL;
-- unfall_uhrzeit ist text, schadenzeit ist time -> expliziter Cast (heute beide 0 Zeilen).
UPDATE public.claims c SET schadenzeit = f.unfall_uhrzeit::time without time zone
  FROM public.faelle f WHERE f.claim_id = c.id AND c.schadenzeit IS NULL AND f.unfall_uhrzeit IS NOT NULL;
UPDATE public.claims c SET hergang_kunde_text = COALESCE(c.hergang_kunde_text, f.schadens_beschreibung, f.unfallhergang, f.schadens_hergang)
  FROM public.faelle f WHERE f.claim_id = c.id AND c.hergang_kunde_text IS NULL;
UPDATE public.claims c SET schadenart = f.schadens_art
  FROM public.faelle f WHERE f.claim_id = c.id AND c.schadenart IS NULL AND f.schadens_art IS NOT NULL;
UPDATE public.claims c SET fall_typ = f.schadens_fall_typ
  FROM public.faelle f WHERE f.claim_id = c.id AND c.fall_typ IS NULL AND f.schadens_fall_typ IS NOT NULL;
UPDATE public.claims c SET hat_personenschaden = f.personenschaden_flag
  FROM public.faelle f WHERE f.claim_id = c.id AND c.hat_personenschaden IS NULL AND f.personenschaden_flag IS NOT NULL;
UPDATE public.claims c SET halter_ungleich_fahrer = f.halter_ungleich_fahrer_flag
  FROM public.faelle f WHERE f.claim_id = c.id AND c.halter_ungleich_fahrer IS NULL AND f.halter_ungleich_fahrer_flag IS NOT NULL;
UPDATE public.claims c SET hat_sachschaden = f.sachschaden_flag
  FROM public.faelle f WHERE f.claim_id = c.id AND c.hat_sachschaden IS NULL AND f.sachschaden_flag IS NOT NULL;
UPDATE public.claims c SET hat_mietwagen = COALESCE(c.hat_mietwagen, f.mietwagen_flag, f.mietwagen_hat)
  FROM public.faelle f WHERE f.claim_id = c.id AND c.hat_mietwagen IS NULL;
UPDATE public.claims c SET hat_nutzungsausfall = f.nutzungsausfall
  FROM public.faelle f WHERE f.claim_id = c.id AND c.hat_nutzungsausfall IS NULL AND f.nutzungsausfall IS NOT NULL;
UPDATE public.claims c SET gegner_aktenzeichen = f.gegner_schadennummer
  FROM public.faelle f WHERE f.claim_id = c.id AND c.gegner_aktenzeichen IS NULL AND f.gegner_schadennummer IS NOT NULL;
UPDATE public.claims c SET kunde_no_show_count = f.no_show_count
  FROM public.faelle f WHERE f.claim_id = c.id AND c.kunde_no_show_count IS NULL AND f.no_show_count IS NOT NULL;
UPDATE public.claims c SET phase = f.aktuelle_phase
  FROM public.faelle f WHERE f.claim_id = c.id AND c.phase IS NULL AND f.aktuelle_phase IS NOT NULL;
UPDATE public.claims c SET lead_id = f.konvertiert_von_lead
  FROM public.faelle f WHERE f.claim_id = c.id AND c.lead_id IS NULL AND f.konvertiert_von_lead IS NOT NULL;
UPDATE public.claims c SET regulierungs_betrag = f.regulierung_betrag
  FROM public.faelle f WHERE f.claim_id = c.id AND c.regulierungs_betrag IS NULL AND f.regulierung_betrag IS NOT NULL;
UPDATE public.claims c SET vs_ablehnungs_grund = f.vs_ablehnungsgrund
  FROM public.faelle f WHERE f.claim_id = c.id AND c.vs_ablehnungs_grund IS NULL AND f.vs_ablehnungsgrund IS NOT NULL;

-- ============================================================
-- BLOCK 2: blockierende Views/Trigger anpassen.
-- Audit (scripts/probe-cmm44-spa2-deps.sql, 2026-05-17):
--   4 Views referenzieren die 28 Spalten -> CREATE OR REPLACE mit Repoint
--   auf claims; Ausgabe-Aliasnamen BLEIBEN (Tech-Debt bis View-Cleanup SP-K/L).
--   v_claim_listing + v_claim_timeline: 0 Treffer -> unveraendert.
--   Trigger faelle_phase_transition_trigger (UPDATE OF aktuelle_phase) blockt
--   den DROP -> wird hier entfernt.
--   Verwaiste Funktions-Stubs bleiben (late-bound, DB-weit von KEINEM Trigger
--   gerufen -> harmlos; verifiziert pg_trigger 2026-05-17):
--     log_phase_transition, trg_fn_sync_claims_to_faelle,
--     trg_fn_sync_kanzlei_paket_to_faelle, map_claim_phase_to_faelle_phase.
--   Aufraeumen dieser Stubs ist CMM-44-Cleanup-Backlog, kein SP-A2-Scope.
-- ============================================================
DROP TRIGGER IF EXISTS faelle_phase_transition_trigger ON public.faelle;

CREATE OR REPLACE VIEW public.faelle_kunde_view AS
 SELECT f.id,
    f.fall_nummer,
    f.status,
    c.phase::text AS aktuelle_phase,
    c.hergang_kunde_text::text AS schadens_beschreibung,
    c.schadentag::date AS schadens_datum,
    c.schadenort_adresse::text AS schadens_adresse,
    c.schadenort_plz::text AS schadens_plz,
    c.schadenort_ort::text AS schadens_ort,
    f.kennzeichen,
    f.fahrzeug_hersteller,
    f.fahrzeug_modell,
    f.fahrzeug_baujahr,
    f.auszahlung_kunde_betrag,
    f.auszahlung_kunde_eingegangen_am,
    f.auszahlung_zahlungsweg,
    f.eskalation_tag_14_ergebnis,
    f.eskalation_tag_14_ergebnis_am,
    f.eskalation_tag_21_ergebnis,
    f.eskalation_tag_21_ergebnis_am,
    f.eskalation_tag_28_ergebnis,
    f.eskalation_tag_28_ergebnis_am,
    f.nachbesichtigung_status,
    f.nachbesichtigung_termin_datum,
    f.nachbesichtigung_kunde_termin_vorschlaege,
    f.nachbesichtigung_kunde_termin_eingereicht_am,
    f.nachbesichtigung_sv_konfrontation_gewuenscht,
    f.vs_quote_prozent,
    f.vs_quote_grund,
    f.vs_quote_akzeptiert_am,
    f.vs_quote_betrag_ausgezahlt,
    f.vs_reaktion_typ,
    f.vs_reaktion_am,
    f.besichtigungsort_adresse,
    c.abgeschlossen_am,
    f.kunde_id,
    f.sv_id
   FROM faelle f
     LEFT JOIN claims c ON c.id = f.claim_id;

CREATE OR REPLACE VIEW public.faelle_sv_view AS
 SELECT f.id,
    f.fall_nummer,
    f.status,
    c.phase::text AS aktuelle_phase,
    c.hergang_kunde_text::text AS schadens_beschreibung,
    c.schadentag::date AS schadens_datum,
    c.schadenort_adresse::text AS schadens_adresse,
    c.schadenort_plz::text AS schadens_plz,
    c.schadenort_ort::text AS schadens_ort,
    f.kennzeichen,
    f.fahrzeug_hersteller,
    f.fahrzeug_modell,
    f.fahrzeug_baujahr,
    f.gutachter_honorar,
    f.auszahlung_gutachter_eingegangen_am,
    f.eskalation_tag_14_ergebnis,
    f.eskalation_tag_14_ergebnis_am,
    f.eskalation_tag_21_ergebnis,
    f.eskalation_tag_21_ergebnis_am,
    f.eskalation_tag_28_ergebnis,
    f.eskalation_tag_28_ergebnis_am,
    f.technische_stellungnahme_status,
    f.technische_stellungnahme_beauftragt_am,
    f.technische_stellungnahme_hochgeladen_am,
    f.technische_stellungnahme_freigabe_am,
    f.vs_kuerzung_grund,
    f.vs_kuerzungs_typ,
    f.kuerzungs_betrag,
    f.nachbesichtigung_status,
    f.nachbesichtigung_termin_datum,
    f.nachbesichtigung_sv_konfrontation_gewuenscht,
    f.nachbesichtigung_sv_termin_vereinbart_am,
    f.vs_reaktion_typ,
    f.vs_reaktion_am,
    f.besichtigungsort_adresse,
    f.sv_id,
    f.kunde_id
   FROM faelle f
     LEFT JOIN claims c ON c.id = f.claim_id;

CREATE OR REPLACE VIEW public.v_claim_full AS
 SELECT c.id,
    c.vehicle_id,
    c.schadentag,
    c.schadenzeit,
    c.entdeckt_am,
    c.schadenort_adresse,
    c.schadenort_plz,
    c.schadenort_ort,
    c.schadenort_land,
    c.schadenort_lat,
    c.schadenort_lng,
    c.schadenort_kategorie,
    c.hergang_kunde_text,
    c.hergang_sv_text,
    c.schadenart,
    c.fall_typ,
    c.unfall_konstellation,
    c.fahrerflucht,
    c.auslandskennzeichen,
    c.polizei_aktenzeichen,
    c.polizei_bericht_vorhanden,
    c.polizei_vor_ort,
    c.polizeibericht_status,
    c.geschaedigter_user_id,
    c.gegnerisches_vehicle_id,
    c.gegner_versicherung_id,
    c.gegner_versicherungsnummer,
    c.gegner_aktenzeichen,
    c.gegner_bekannt,
    c.anzahl_beteiligte_total,
    c.hat_personenschaden,
    c.hat_mietwagen,
    c.hat_nutzungsausfall,
    c.hat_sachschaden,
    c.hat_abschleppung,
    c.sachschaden_beschreibung,
    c.halter_ungleich_fahrer,
    c.kunden_konstellation,
    c.unfallskizze_url,
    c.unfallskizze_svg,
    c.unfallskizze_bestaetigt,
    c.unfallskizze_ablehnung_grund,
    c.unfallskizze_generiert_am,
    c.status,
    c.abgeschlossen_am,
    c.verjaehrt_am,
    c.created_at,
    c.updated_at,
    c.created_by_user_id,
    c.created_via,
    c.claim_nummer,
    c.lead_id,
    c.kundenbetreuer_id,
    c.phase,
    c.vs_ablehnungs_grund,
    c.regulierungs_betrag,
    c.endzustand_gesetzt_durch_user_id,
    c.endzustand_gesetzt_am,
    c.endzustand_grund,
    c.kanzlei_wunsch,
    c.kanzlei_wunsch_gefragt_am,
    c.kanzlei_wunsch_gefragt_in_phase,
    f.id AS fall_id,
    f.fall_nummer,
    f.sv_id,
    f.service_typ,
    f.status AS fall_status,
    f.created_at AS fall_created_at,
    f.updated_at AS fall_updated_at,
    f.kundenbetreuer_fallback_flag,
    c.phase::text AS aktuelle_phase,
    f.szenario,
    f.dokumente_vollstaendig_fuer_phase,
    f.dokumente_reminder_whatsapp_letzte_sendung,
    f.no_show_gemeldet_am,
    f.re_termin_token,
    f.sa_unterschrieben_am,
    f.vollmacht_signiert_am,
    f.mandatsnummer,
    f.re_termin_token_eingelaufen_am,
    f.re_termin_eskalation_an_kb_am,
    f.storniert_am,
    f.anschlussschreiben_am,
    f.vs_eskalationsstufe,
    f.kennzeichen,
    f.fahrzeug_hersteller,
    f.fahrzeug_modell,
    f.fahrzeug_typ,
    f.sa_unterschrieben,
    f.regulierung_am,
    c.regulierungs_betrag::numeric(10,2) AS regulierung_betrag,
    f.gutachten_betrag,
    f.gutachten_eingegangen_am,
    f.sv_zugewiesen_am,
    f.schadens_ursache,
    c.schadenort_plz::text AS schadens_plz,
    c.schadenort_ort::text AS schadens_ort,
    c.fall_typ::text AS schadens_fall_typ,
    f.gegner_anzahl_beteiligte,
    f.gegner_fahrzeugtyp,
    f.organisation_id,
    f.dispatch_id,
    f.kunde_id,
    f.ist_aktiv,
    f.deaktiviert_grund,
    f.hat_vorschaeden,
    f.vorschaden_anzahl,
    f.vorschaden_letzter_datum,
    f.vorschaden_typ_b_bericht,
    f.cardentity_abfrage_am,
    f.besichtigungsort_adresse,
    f.besichtigungsort_lat,
    f.besichtigungsort_lng,
    f.besichtigungsort_notiz,
    f.besichtigungsort_place_id,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cp.*) ORDER BY cp.reihenfolge, cp.created_at) AS jsonb_agg
           FROM claim_parties cp
          WHERE cp.claim_id = c.id), '[]'::jsonb) AS parties,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cvi.*) ORDER BY cvi.reihenfolge, cvi.created_at) AS jsonb_agg
           FROM claim_vehicle_involvements cvi
          WHERE cvi.claim_id = c.id), '[]'::jsonb) AS vehicle_involvements,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cp2.*) ORDER BY cp2.created_at) AS jsonb_agg
           FROM claim_payments cp2
          WHERE cp2.claim_id = c.id), '[]'::jsonb) AS payments,
    COALESCE(( SELECT jsonb_agg(to_jsonb(cm.*) ORDER BY cm.created_at) AS jsonb_agg
           FROM claim_mietwagen cm
          WHERE cm.claim_id = c.id), '[]'::jsonb) AS mietwagen,
    COALESCE(( SELECT jsonb_agg(to_jsonb(vk.*) ORDER BY vk.datum) AS jsonb_agg
           FROM vs_korrespondenz vk
          WHERE vk.claim_id = c.id), '[]'::jsonb) AS vs_korrespondenz,
    COALESCE(( SELECT jsonb_agg(to_jsonb(r.*) ORDER BY r.created_at) AS jsonb_agg
           FROM repairs r
          WHERE r.claim_id = c.id), '[]'::jsonb) AS repairs
   FROM claims c
     LEFT JOIN faelle f ON f.claim_id = c.id;

CREATE OR REPLACE VIEW public.v_faelle_mit_aktuellem_termin AS
 SELECT f.id,
    f.fall_nummer,
    f.lead_id,
    f.kunde_id,
    f.status,
    f.betreuungspaket,
    c.hergang_kunde_text::text AS schadens_beschreibung,
    c.schadentag::date AS schadens_datum,
    c.entdeckt_am::date AS schadens_entdeckt_am,
    c.schadenort_adresse::text AS schadens_adresse,
    c.schadenort_plz::text AS schadens_plz,
    c.schadenort_ort::text AS schadens_ort,
    f.abtretung_pdf,
    f.vollmacht_pdf,
    f.abtretung_signiert_am,
    f.vollmacht_signiert_am,
    f.sv_id,
    f.sv_zugewiesen_am,
    f.gutachten_eingegangen_am,
    f.gutachten_betrag,
    c.kanzlei_uebergeben_am,
    f.anschlussschreiben_am,
    c.regulierungs_betrag::numeric(10,2) AS regulierung_betrag,
    f.regulierung_am,
    f.filmcheck_ok,
    f.filmcheck_am,
    f.filmcheck_notizen,
    f.notizen,
    f.created_at,
    f.updated_at,
    c.fall_typ::text AS schadens_fall_typ,
    c.kunden_konstellation,
    f.kennzeichen,
    f.fahrzeug_typ,
    f.fahrzeug_hersteller,
    f.fahrzeug_modell,
    f.fahrzeug_baujahr,
    f.gegner_name,
    f.gegner_versicherung,
    f.gegner_kennzeichen,
    c.gegner_bekannt,
    c.polizei_aktenzeichen,
    c.polizei_bericht_vorhanden,
    c.hat_personenschaden::boolean AS personenschaden_flag,
    c.hat_mietwagen::boolean AS mietwagen_flag,
    c.gewerbe_flag,
    c.halter_ungleich_fahrer::boolean AS halter_ungleich_fahrer_flag,
    f.ust_id,
    f.leasinggeber_name,
    f.leasinggeber_informiert,
    f.bank_name,
    f.prioritaet,
    f.onboarding_complete,
    f.dispatch_id,
    c.kundenbetreuer_id,
    f.konvertiert_am,
    c.lead_id::uuid AS konvertiert_von_lead,
    f.status_changed_at,
    f.regulierung_angekuendigt_am,
    f.zahlung_eingegangen_am,
    c.abgeschlossen_am,
    f.google_review_gesendet,
    f.vs_eskalationsstufe,
    f.fin_quelle,
    f.fin_extrahiert_am,
    f.vorschaden_geprueft,
    f.vorschaden_anzahl,
    f.vorschaden_letzter_datum,
    f.vorschaden_typ_a_ergebnis,
    f.vorschaden_typ_b_bericht,
    f.vorschaden_typ_b_pdf_url,
    f.cardentity_abfrage_am,
    f.schadens_hoehe_netto,
    f.nutzungsausfall_tagessatz,
    f.reparaturdauer_tage,
    f.gutachter_honorar,
    f.ocr_extrahiert_am,
    f.ocr_rohdaten,
    f.ki_kalkulation,
    f.ki_kalkulation_am,
    f.ki_geschaetzte_kosten_min,
    f.ki_geschaetzte_kosten_max,
    c.kanzlei_ansprechpartner_name,
    c.kanzlei_ansprechpartner_email,
    c.kanzlei_ansprechpartner_telefon,
    f.kanzlei_ansprechpartner_position,
    f.mandatsnummer,
    f.losfahren_erinnerung_gesendet,
    f.termin_erinnerung_5min_gesendet,
    f.geschaetzte_fahrzeit_min,
    f.geschaetzte_fahrdistanz_km,
    f.gcal_event_id,
    f.gutachten_vorhanden,
    f.gutachten_hochgeladen_am,
    f.gutachten_positionen,
    f.gutachten_nummer,
    f.reparaturkosten,
    f.wertminderung,
    f.nutzungsausfall_gesamt,
    f.regulierungsweise,
    c.gegner_versicherungsnummer,
    f.sa_unterschrieben,
    f.sa_unterschrieben_am,
    f.sa_pdf_url,
    f.sa_unterschrift_url,
    f.datenschutz_akzeptiert,
    f.datenschutz_akzeptiert_am,
    f.vollmacht_status,
    c.polizei_vor_ort,
    c.hergang_kunde_text::text AS unfallhergang,
    f.unfallmitteilung_status,
    c.schadenort_adresse::text AS unfallort,
    c.schadentag::date AS unfalldatum,
    f.interne_notizen,
    f.anschlussschreiben_url,
    f.anschlussschreiben_sendedatum,
    f.anschlussschreiben_unterschrift,
    f.anschlussschreiben_ocr_am,
    f.besichtigungsort_adresse,
    f.besichtigungsort_lat,
    f.besichtigungsort_lng,
    f.besichtigungsort_place_id,
    f.ist_aktiv,
    f.deaktiviert_am,
    f.deaktiviert_grund,
    f.deaktiviert_notiz,
    f.szenario,
    f.ruege_erhalten_am,
    f.ruege_grund,
    f.fahrzeug_farbe,
    f.erstzulassung,
    f.kilometerstand,
    f.firma_name,
    f.marketing_quelle,
    f.marketing_provision,
    f.marketing_provision_status,
    f.gutachten_stundensatz,
    f.kanzlei_id,
    f.kanzlei_honorar,
    f.zahlung_erwartet_am,
    f.zahlung_betrag,
    f.lead_preis_netto,
    f.lead_preis_typ,
    f.lead_preis_berechnet_am,
    f.guthaben_verrechnet_netto,
    f.sv_nachzahlung_netto,
    f.abrechnung_id,
    f.storniert_am,
    f.storno_grund,
    f.storno_durch_user_id,
    f.no_show_gemeldet_am,
    c.spezifikation,
    c.schadenart::text AS schadens_art,
    f.organisation_id,
    c.phase::text AS aktuelle_phase,
    f.dokumente_vollstaendig_fuer_phase,
    f.dokumente_vollstaendig_am_phase,
    c.unfall_konstellation,
    f.gegner_anzahl_beteiligte,
    f.gegner_fahrzeugtyp,
    f.dokumente_reminder_whatsapp_letzte_sendung,
    f.fin_vin,
    f.source_channel,
    f.source_domain,
    f.schadens_ursache,
    f.kanzlei_abrechnung_id,
    f.kanzlei_provision_status,
    f.kanzlei_provision_ausgezahlt_am,
    f.service_typ,
    f.vs_reaktion_typ,
    f.vs_reaktion_am,
    c.vs_ablehnungs_grund::text AS vs_ablehnungsgrund,
    f.ruege_gesendet_am,
    f.ruege_betrag,
    c.kunde_no_show_count::integer AS no_show_count,
    f.kuerzungs_betrag,
    f.vs_frist_bis,
    f.ruege_counter,
    f.schlussabrechnung_am,
    f.iban,
    f.bic,
    f.kontoinhaber,
    f.bankdaten_hinterlegt_am,
    f.ist_fahrzeughalter,
    c.finanzierung_leasing,
    c.vorsteuerabzugsberechtigt,
    c.hergang_kunde_text::text AS schadens_hergang,
    f.halter_vorname,
    f.halter_nachname,
    f.halter_strasse,
    f.halter_plz,
    f.halter_stadt,
    f.halter_telefon,
    f.halter_email,
    c.finanzierungsgeber_name,
    c.finanzierungsgeber_adresse,
    c.finanzierungsgeber_vertragsnr,
    f.zahlungsweg,
    f.hat_vorschaeden,
    f.vorschaeden_beschreibung,
    f.technische_stellungnahme_status,
    f.technische_stellungnahme_beauftragt_am,
    f.technische_stellungnahme_hochgeladen_am,
    f.technische_stellungnahme_freigabe_am,
    f.nachbesichtigung_status,
    f.nachbesichtigung_angefordert_am,
    f.nachbesichtigung_termin_datum,
    f.nachbesichtigung_konfrontation,
    f.as_geforderte_summe,
    f.as_frist,
    f.as_vs_reaktion_text,
    f.as_salesforce_id,
    f.as_zuletzt_synced_am,
    f.lexdrive_case_id,
    f.eskalation_tag_14_am,
    f.eskalation_tag_21_am,
    f.eskalation_tag_28_am,
    c.schadenort_kategorie::text AS unfallort_kategorie,
    c.unfallskizze_url,
    f.fahrzeug_ausstattung,
    f.cardentity_enriched_at,
    f.cardentity_report,
    f.vollmacht_geprueft_am,
    f.vollmacht_geprueft_von,
    f.vollmacht_pruefung_status,
    f.vollmacht_pruefung_begruendung,
    f.lexdrive_ocr_data,
    f.lexdrive_ocr_received_at,
    f.vs_kuerzung_grund,
    f.geschlossen_grund,
    f.nachbesichtigung_ergebnis,
    f.bevorzugter_kanal,
    c.gegner_versicherung_id,
    c.zeugen_kontakte,
    f.werkstatt_seit_datum,
    f.fahrzeug_fahrbereit,
    c.hat_nutzungsausfall::boolean AS nutzungsausfall,
    f.mietwagen_kanzlei_informiert,
    f.mietwagen_kanzlei_informiert_am,
    f.halter_geburtsdatum,
    f.abrechnungsart_besprochen,
    f.abrechnungsart_notiz,
    f.abrechnungsart_besprochen_am,
    f.gegner_versicherung_anfrage_datum,
    f.sprache,
    c.unfallskizze_svg,
    c.unfallskizze_bestaetigt,
    c.unfallskizze_ablehnung_grund,
    c.unfallskizze_generiert_am,
    f.zeugen_vorhanden,
    f.vorschaden_erkannt,
    f.sv_termin_dokument_reminder_gesendet_am,
    f.kundenbetreuer_fallback_flag,
    f.kundenbetreuer_zugewiesen_am,
    f.sv_briefing_text,
    f.sv_briefing_generated_at,
    f.sv_briefing_model,
    f.sv_briefing_version,
    f.sv_briefing_struktur,
    f.sv_notizen_vor_ort,
    f.makler_id,
    c.hat_sachschaden::boolean AS sachschaden_flag,
    c.sachschaden_beschreibung,
    c.gegner_aktenzeichen::text AS gegner_schadennummer,
    f.halter_name,
    f.wunschtermin,
    f.vs_quote_prozent,
    f.vs_quote_grund,
    f.vs_quote_akzeptiert_am,
    f.vs_quote_betrag_ausgezahlt,
    f.vs_kuerzungs_typ,
    f.auszahlung_kunde_betrag,
    f.auszahlung_kunde_eingegangen_am,
    f.auszahlung_gutachter_eingegangen_am,
    f.auszahlung_zahlungsweg,
    f.eskalation_tag_14_ergebnis,
    f.eskalation_tag_14_ergebnis_am,
    f.eskalation_tag_14_ergebnis_von,
    f.eskalation_tag_21_ergebnis,
    f.eskalation_tag_21_ergebnis_am,
    f.eskalation_tag_21_ergebnis_von,
    f.eskalation_tag_28_ergebnis,
    f.eskalation_tag_28_ergebnis_am,
    f.eskalation_tag_28_ergebnis_von,
    f.nachbesichtigung_kunde_termin_vorschlaege,
    f.nachbesichtigung_kunde_termin_eingereicht_am,
    f.nachbesichtigung_sv_konfrontation_gewuenscht,
    f.nachbesichtigung_sv_termin_vereinbart_am,
    f.auszahlung_gutachter_betrag,
    f.ruege_frist_tage,
    f.klage_uebergeben_am,
    f.fallakte_angelegt_am,
    f.kunde_vorname,
    f.kunde_nachname,
    f.kunde_telefon,
    c.kunde_email,
    f.kunde_strasse,
    f.kunde_plz,
    f.kunde_stadt,
    f.kunde_adresse,
    f.kunde_lat,
    f.kunde_lng,
    f.hsn,
    f.tsn,
    f.technische_stellungnahme_notiz_sv,
    c.fahrerflucht,
    c.auslandskennzeichen,
    c.polizeibericht_status,
    f.zb1_status,
    c.schadenzeit::text AS unfall_uhrzeit,
    c.schadenort_lat::numeric AS unfallort_lat,
    c.schadenort_lng::numeric AS unfallort_lng,
    f.bkat_unfallart,
    f.fahrzeugschaden_beschreibung,
    c.hat_mietwagen::boolean AS mietwagen_hat,
    f.mietwagen_seit_datum,
    f.mietwagen_limit_tage,
    f.mietwagen_limit_grund,
    f.mietwagen_rechnung_vorhanden,
    f.mietwagen_rechnung_url,
    f.mietwagen_argumentations_puffer,
    f.mietwagen_vermieter,
    c.vehicle_id,
    f.claim_id,
    f.lackfarbe_code,
    t.id AS aktueller_termin_id,
    t.start_zeit AS aktueller_termin_start,
    t.end_zeit AS aktueller_termin_end,
    t.status AS aktueller_termin_status,
    t.sv_id AS aktueller_termin_sv_id,
    t.kanal AS aktueller_termin_kanal,
    t.typ AS aktueller_termin_typ,
    t.final_verbindlich_ab AS aktueller_termin_final_verbindlich_ab,
    t.start_zeit AS sv_termin,
    t.status AS gutachter_termin_status,
    t.status = 'bestaetigt'::text AS gutachter_termin_bestaetigt,
    t.vorgeschlagenes_datum AS gutachter_gegenvorschlag_datum,
    t.gegenvorschlag_grund AS gutachter_gegenvorschlag_grund
   FROM faelle f
     LEFT JOIN claims c ON c.id = f.claim_id
     LEFT JOIN LATERAL ( SELECT gt.id,
            gt.sv_id,
            gt.fall_id,
            gt.start_zeit,
            gt.end_zeit,
            gt.status,
            gt.externer_kalender_id,
            gt.ablehnungsgrund,
            gt.gegenvorschlag_zeit,
            gt.created_at,
            gt.erinnerung_24h_gesendet,
            gt.erinnerung_2h_gesendet,
            gt.erinnerung_48h_docs_gesendet,
            gt.ankunft_zeit,
            gt.abschluss_zeit,
            gt.uebersprungen,
            gt.uebersprung_grund,
            gt.notizen_vor_ort,
            gt.gps_lat_ankunft,
            gt.gps_lng_ankunft,
            gt.lead_id,
            gt.ablehnen_token,
            gt.abgelehnt_am,
            gt.abgelehnt_grund,
            gt.vorgeschlagenes_datum,
            gt.gegenvorschlag_grund,
            gt.gegenvorschlag_von,
            gt.ankunft_via,
            gt.verspaetung_minuten,
            gt.losgefahren_am,
            gt.kunden_tracking_token,
            gt.notification_losgefahren_gesendet_am,
            gt.notification_5min_gesendet_am,
            gt.notification_angekommen_gesendet_am,
            gt.ablehnen_token_expires_at,
            gt.final_verbindlich_ab,
            gt.sv_ablehnung_grund,
            gt.sv_ablehnung_am,
            gt.sv_vorgeschlagene_slots,
            gt.typ,
            gt.kanal,
            gt.video_link,
            gt.kb_id,
            gt.notiz_kunde,
            gt.notiz_intern,
            gt.reminder_sent_at,
            gt.reminder_1h_sent_at,
            gt.cancelled_at,
            gt.navigation_started_at,
            gt.sv_unterwegs_seit,
            gt.sv_eta_minuten,
            gt.sv_eta_letzte_berechnung,
            gt.sv_angekommen_am,
            gt.reminder_15min_sent_at,
            gt.reminder_5min_sent_at,
            gt.durchgefuehrt_am,
            gt.kunde_tracking_aktiviert,
            gt.kunde_losgefahren_am,
            gt.kunde_eta_minuten,
            gt.kunde_eta_letzte_berechnung,
            gt.kunde_angekommen_am,
            gt.kunde_verspaetung_gemeldet_am,
            gt.bezahlt,
            gt.honorar_betrag,
            gt.google_event_id,
            gt.google_calendar_id,
            gt.google_event_synced_at,
            gt.kunde_response_token,
            gt.kunde_response_token_expires_at,
            gt.gesehen_am,
            gt.geschaetzte_fahrtzeit_min,
            gt.auftrag_id,
            gt.verlegung_quelle_id,
            gt.verlegung_grund,
            gt.verlegung_kunde_benachrichtigt_an,
            gt.verlegung_eskalation_an_kb_an,
            gt.verlegung_initiator_kunde,
            gt.besichtigung_gestartet_am,
            gt.caldav_object_url,
            gt.caldav_event_uid,
            gt.caldav_synced_at,
            gt.erinnerung_morgen_gesendet,
            gt.sv_lead_id
           FROM gutachter_termine gt
          WHERE gt.fall_id = f.id AND (gt.status = ANY (ARRAY['bestaetigt'::text, 'verlegung_pending'::text, 'reserviert'::text, 'durchgefuehrt'::text, 'gegenvorschlag'::text]))
          ORDER BY (
                CASE gt.status
                    WHEN 'bestaetigt'::text THEN 1
                    WHEN 'verlegung_pending'::text THEN 2
                    WHEN 'gegenvorschlag'::text THEN 3
                    WHEN 'reserviert'::text THEN 4
                    WHEN 'durchgefuehrt'::text THEN 5
                    ELSE 6
                END), gt.start_zeit DESC NULLS LAST
         LIMIT 1) t ON true;


-- ============================================================
-- BLOCK 3: DROP COLUMN x28 auf faelle.
-- ============================================================
ALTER TABLE public.faelle
  DROP COLUMN schadens_adresse,
  DROP COLUMN unfallort,
  DROP COLUMN schadens_plz,
  DROP COLUMN schadens_ort,
  DROP COLUMN unfallort_kategorie,
  DROP COLUMN unfallort_lat,
  DROP COLUMN unfallort_lng,
  DROP COLUMN schadens_datum,
  DROP COLUMN unfalldatum,
  DROP COLUMN schadens_entdeckt_am,
  DROP COLUMN unfall_uhrzeit,
  DROP COLUMN schadens_beschreibung,
  DROP COLUMN unfallhergang,
  DROP COLUMN schadens_hergang,
  DROP COLUMN schadens_art,
  DROP COLUMN schadens_fall_typ,
  DROP COLUMN personenschaden_flag,
  DROP COLUMN halter_ungleich_fahrer_flag,
  DROP COLUMN sachschaden_flag,
  DROP COLUMN mietwagen_flag,
  DROP COLUMN mietwagen_hat,
  DROP COLUMN nutzungsausfall,
  DROP COLUMN gegner_schadennummer,
  DROP COLUMN no_show_count,
  DROP COLUMN aktuelle_phase,
  DROP COLUMN konvertiert_von_lead,
  DROP COLUMN regulierung_betrag,
  DROP COLUMN vs_ablehnungsgrund;

COMMIT;
