-- Placeholder: Migration 20260415220429 wurde vor Einführung des lokalen Migration-Trackings
-- direkt auf die DB angewendet. Inhalt ist in der DB — diese Datei dient nur
-- als lokaler Marker damit supabase CLI nicht abbricht.
